---
title: "clinical TG adjustment"
output: pdf_document
---

```{r load library}
require(openxlsx)
library(factoextra)
library(cluster)
require(nlme) # directly provides p-values, unlike lme4
require(splines)
require(dplyr)
library(fgsea)
library(knitr)
library(kableExtra)
library(tidyverse)
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
source(paste0(codebase_path,"/codebase_subtype.R"))

organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")

intermediate_results_outdir_DR = "/scratch/data-integration/molecular_subtyping/DimensionReduction/"
mcia_results = readRDS(paste0(intermediate_results_outdir_DR,"MCIA_phase123_20230726.rds"))

data_path <- "/scratch/data-integration/pipelines/processedData/"
data_env0 <- readRDS(paste0(data_path, "data_env_ravi_20220513.RDS"))
```

# Load preliminary results
```{r load subtype assignment and clinical data}
# load subtype assignment and clinical data
nclust_tree_all = 6
subtype_hcl = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/subtype_hcl.rds")
clin_data_aligned = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/clin_data_aligned.rds")
extended_data = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/extended_data.rds")
```

# Clinical names correspondence
```{r clinical names correspondence}
clin_names <- c("sex" = "Sex (Female)",
                "ethnicity" = "Ethnicity (Hispanic or Latino)",
                "admit_age" = "Admission age",
                "discretized_admit_age_quantile" = "Admission age quantile",
                "raceAmerican Indian / Alaska Native" = "American Indian/Alaska Native",
                "raceAsian" = "Asian",
                "raceBlack / African American" = "Black/African American",
                "raceBlack...African.American" = "Black/African American",
                "raceMultiple" = "Multiple Races",
                "raceNative Hawaiian / Pacific Islander" = "Native Hawaiian/Pacific Islander",
                "raceWhite" = "White",
                "bmicat" = "BMI category",
                "comorb_htn" = "Hypertension",
                "comorb_isaric_dm" = "Diabetes",
                "comorb_anyresp_noasthma" = "Pulmonary (excludes asthma)",
                "comorb_isaric_asthma" = "Asthma",
                "comorb_isaric_cardiac" = "Chronic cardiac disease",
                "comorb_isaric_ckd" = "Chronic kidney disease",
                "comorb_isaric_neoplasm" = "Malignant neoplasm",
                "comorb_neuro" = "Chronic neurological disorder",
                "comorb_isaric_liver" = "Liver disease",
                "comorb_hxtrans" = "History of solid organ or bone marrow transplant",
                "comorb_hiv2" = "HIV",
                "comorb_eversmkvape" = "Current or former smoking and/or vaping",
                "comorb_anysubstance" = "Drug or alcohol abuse or cannabis use",
                "comp_seizure" = "Seizures",
                "comp_meningitis" = "Meningitis/encephalitis",
                "comp_stroke" = "Stroke/CVA",
                "comp_afib" = "Atrial fibrillation",
                "comp_ventricular_arr" = "Ventricular arrhythmia",
                "comp_endo" = "Endocarditis",
                "comp_myocard" = "Myocarditis/pericarditis",
                "comp_cardarrest" = "Cardiac arrest",
                "comp_stemi" = "ST-elevation MI (STEMI)",
                "comp_nstemi" = "Non-ST elevation MI (NSTEMI) or other cardiac ischemia",
                "comp_chf" = "CHF/cardiomyopathy",
                "comp_pneumonia" = "Pneumonia",
                "comp_bronch" = "Bronchiolitis",
                "comp_pneumo" = "Pneumothorax",
                "comp_pneumomed" = "Pneumomediastinum",
                "comp_aat" = "Acute arterial thromboembolism excluding stroke/CVA or myocardial infarction",
                "comp_avthromb" = "Acute venous thromboembolism",
                "comp_shock" = "Shock (use of vasopressors)",
                "comp_bac" = "Bacteremia",
                "comp_coag" = "Coagulation disorder/disseminated intravascular coagulation",
                "comp_hypogly" = "Symptomatic hypoglycemia",
                "comp_bleed" = "Bleeding",
                "comp_anemia" = "Anemia",
                "comp_pancreas" = "Pancreatitis",
                "comp_renal" = "Acute renal injury/failure",
                "comp_liver" = "Liver dysfunction/failure",
                "comp_othlab" = "Other lab abnormality",
                "comp_electrolyte" = "Electrolyte abnormality",
                "comp_othinf" = "Other infection (non-pulmonary)",
                "comp_othpulm" = "Other pulmonary complication",
                "comp_unddisease" = "Exacerbation of underlying disease",
                "comp_enceph" = "Encephalopathy",
                "comp_othneuro" = "Other neurologic complication",
                "comp_hypergly" = "Hyperglycemia",
                "comp_psych" = "Psychiatric complication",
                "comp_mis" = "Multisystem inflammatory syndrome (MIS)",
                "comp_gastroent" = "Gastroenteritis",
                "comp_pulmvas" = "Pulmonary vascular disease",
                "ever_azithro" = "Azithromycin",
                "ever_icu" = "Ever in ICU",
                "ever_otherabx" = "Other Antibiotics",
                "ever_remdes" = "Remdesivir",
                "ever_steroids" = "Steroids",
                "ever_ever_esc" = "Ever required escalation of care",
                "ever_immsupp" = "Immunosuppressives",
                "baseline_anyimg" = "Any chest imaging at baseline",
                "baseline_img_infil" = "Radiographic findings on chest imaging",
                "baseline_lymph_abn" = "Abnormal Lymphocyte count",
                "baseline_platelets_abn" = "Abnormal Platelets",
                "baseline_alt_abn" = "Abnormal ALT",
                "baseline_cr_abn" = "Abnormal Creatinine",
                "baseline_crp_abn" = "Abnormal CRP",
                "baseline_ddimer_abn" = "Abnormal D-dimer",
                "baseline_trop_abn" = "Abnormal Troponin")
```

# Clinical heatmap adjusted for TG (Extended Data Fig2A)
```{r clinical heatmap, fig.height=8, fig.width=14, warning=FALSE}
interest_clin_feature = c(
  "comorb_htn", "comorb_anyresp_noasthma", "comorb_isaric_cardiac", 
  "comorb_isaric_ckd", "comorb_hxtrans", "comp_stroke", "comp_afib",
  "comp_ventricular_arr", "comp_cardarrest", "comp_chf", "comp_pneumonia", 
  "comp_avthromb", "comp_shock", "comp_bac", "comp_bleed", "comp_anemia", 
  "comp_renal", "ever_icu", "ever_ever_esc", "sex", "ethnicity", 
  "raceBlack / African American", "raceWhite", "baseline_lymph_abn", 
  "baseline_platelets_abn", "baseline_alt_abn", "baseline_cr_abn", 
  "baseline_crp_abn", "baseline_ddimer_abn", "baseline_trop_abn", 
  "bmicat", "discretized_admit_age_quantile", "baseline_img_infil")

clin_data_patient <- clin_data_aligned[clin_data_aligned$event_type == "Visit 1",]
demo_data <- clin_data_patient[, c("admit_age", "sex", "ethnicity",
                                   "discretized_admit_age_quantile",
                                   "bmicat", "enrollment_site", "race")]
demo_data$ethnicity[demo_data$ethnicity == "Not Specified"] <- NA
demo_data$bmicat[demo_data$bmicat == 999] <- NA
demo_data$bmicat_test <- demo_data$bmicat
# group obesity together
demo_data$bmicat_test[demo_data$bmicat_test == 5] <- 4
demo_data$race <- as.factor(demo_data$race)
race_one_hot <- model.matrix(~ race-1, data = demo_data)
race_one_hot <- race_one_hot[, !(colnames(race_one_hot) %in%
                                   c("raceOther / Declined", 
                                     "raceUnknown / Unavailable"))]
demo_data_adjust <- demo_data[, c("discretized_admit_age_quantile", "sex")]
TG_adjust <- data.frame(TG = subtype_hcl$TG)

clin_data_logit <- clin_data_patient %>%
  dplyr::select(matches("^(comorb|comp)"), ever_icu, ever_ever_esc) %>%
  dplyr::select(-comorb_count, -comorb_countcat) %>%
  select_if(~sum(.x, na.rm = TRUE) > 0)
clin_data_demo_logit <- cbind(demo_data[, c("sex", "ethnicity")], race_one_hot)
clin_data_demo_logit$sex <- ifelse(clin_data_demo_logit$sex == "Female", 1, 0)
clin_data_demo_logit$ethnicity <- ifelse(clin_data_demo_logit$ethnicity == 
                                           "Hispanic or Latino", 1, 0)

clin_data_baseline <- clin_data_patient %>%
  dplyr::select(matches("^baseline")) %>%
  dplyr::select(-baseline_anyimg) %>%
  mutate(across(everything(), ~replace(., . == 999, NA)))
clin_data_baseline_logit <- clin_data_baseline %>%
  dplyr::select(ends_with("_abn"))

sub_idx <- which(subtype_hcl$label != "D")
clin_test_logit <- test_clinical_logit_demo(
  subtype_hcl$label[sub_idx],
  clin_data_logit[sub_idx,],
  cbind(demo_data_adjust[sub_idx,],
        TG_adjust[sub_idx, ]))
demo_test_logit <- test_clinical_logit_demo(
  subtype_hcl$label[sub_idx],
  clin_data_demo_logit[sub_idx,],
  as.data.frame(TG_adjust[sub_idx, ]))
baseline_test_logit <- test_clinical_logit_demo(
  subtype_hcl$label[sub_idx],
  clin_data_baseline_logit[sub_idx,],
  cbind(demo_data_adjust[sub_idx,],
        TG_adjust[sub_idx, ]))
bmi_test_ordinal <- test_ordinal_demo(
  subtype_hcl$label[sub_idx],
  demo_data$bmicat_test[sub_idx],
  as.data.frame(TG_adjust[sub_idx, ]))
age_test_ordinal <- test_ordinal_demo(
  subtype_hcl$label[sub_idx],
  demo_data$discretized_admit_age_quantile[sub_idx],
  as.data.frame(TG_adjust[sub_idx, ]))
baseline_test_ordinal <- test_ordinal_demo(
  subtype_hcl$label[sub_idx],
  clin_data_baseline$baseline_img_infil[sub_idx],
  cbind(demo_data_adjust[sub_idx,],
        TG_adjust[sub_idx, ]))

clin_test_logit$p_lr_adj <- p.adjust(clin_test_logit$p_lr, method = "BH")

# clinical test featuring variables of interest
clin_test <- clin_test_logit
clin_test$est_logit <- cbind(clin_test_logit$est_logit, 
                             demo_test_logit$est_logit,
                             baseline_test_logit$est_logit,
                             bmi_test_ordinal$est_ordinal,
                             age_test_ordinal$est_ordinal,
                             baseline_test_ordinal$est_ordinal)
colnames(clin_test$est_logit)[ncol(clin_test$est_logit)-2] <- "bmicat"
colnames(clin_test$est_logit)[ncol(clin_test$est_logit)-1] <- 
  "discretized_admit_age_quantile"
colnames(clin_test$est_logit)[ncol(clin_test$est_logit)] <- "baseline_img_infil"
clin_test$est_logit = clin_test$est_logit[,interest_clin_feature]

clin_test$p_logit <- cbind(clin_test_logit$p_logit, 
                           demo_test_logit$p_logit,
                           baseline_test_logit$p_logit,
                           bmi_test_ordinal$p_ordinal,
                           age_test_ordinal$p_ordinal,
                           baseline_test_ordinal$p_ordinal)
colnames(clin_test$p_logit)[ncol(clin_test$p_logit)-2] <- "bmicat"
colnames(clin_test$p_logit)[ncol(clin_test$p_logit)-1] <- 
  "discretized_admit_age_quantile"
colnames(clin_test$p_logit)[ncol(clin_test$p_logit)] <- "baseline_img_infil"

pvec <- as.vector(as.matrix(clin_test$p_logit))
pvec_bh <- p.adjust(pvec, method = "BH")
clin_test$p_adj <- matrix(pvec_bh, nrow = nrow(clin_test$p_logit), 
                          ncol = ncol(clin_test$p_logit),
                          dimnames = list(rownames(clin_test$p_logit),
                                          colnames(clin_test$p_logit)))

clin_test$p_logit = clin_test$p_logit[,interest_clin_feature]
clin_test$p_adj = clin_test$p_adj[,interest_clin_feature]

heatmap_clinical(clin_test, clin_names, adjust_p = TRUE)
```




