---
title: "Other Clustering Method"
output: html_notebook
---

```{r load library}
library(ade4) #used in mcia
library(mogsa)
library(factoextra)
library(cluster)
library(nnet)
library(survival)
library(ordinal)
library(ggeffects)
library(openxlsx)
library(network)
library(GGally)
library(ggalt)
library(metafor)
library(cowplot)
library(survminer)
require(nlme) # directly provides p-values, unlike lme4
require(splines)
require(dplyr)
library(fgsea)
library(mclust)
library(aricode)
library(clue)
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
source(paste0(codebase_path,"/codebase_subtype.R"))

organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")

intermediate_results_outdir_DR = "/scratch/data-integration/molecular_subtyping/DimensionReduction/"
mcia_results = readRDS(paste0(intermediate_results_outdir_DR,"MCIA_phase123_20230726.rds"))

data_path <- "/scratch/data-integration/pipelines/processedData/"
data_env0 <- readRDS(paste0(data_path, "data_env_ravi_20220513.RDS"))

PACS_group = list(physical = c(2), cognitive = c(5), multiple = c(6))
clin_data_all = organized_data$clinical_data[,setdiff(colnames(organized_data$clinical_data), c("sample_id","sample_type", "phase1_2","samples_collected","phase"))]
clin_data_all = unique(clin_data_all)
clin_data_aligned = data_frame(event_id=rownames(organized_data$datasets$plasma_proteomics_targeted))
clin_data_aligned <- clin_data_aligned %>% left_join(clin_data_all, by = c("event_id"))
ll = which(clin_data_aligned$event_type %in% paste0("Visit ",1:6))
clin_data_aligned =clin_data_aligned[ll,]
mcia_factors= mcia_results$mcia_factors[ll,]
clin_data_aligned$conv_cluster6[is.na(clin_data_aligned$conv_cluster6)] = 999
clin_data_aligned$conv_physical_deficit = ifelse(clin_data_aligned$conv_cluster6%in%PACS_group$physical,1,0)
clin_data_aligned$conv_cognitive_deficit = ifelse(clin_data_aligned$conv_cluster6%in%PACS_group$cognitive,1,0)
clin_data_aligned$conv_global_deficit = ifelse(clin_data_aligned$conv_cluster6%in%PACS_group$multiple,1,0)
```

# Clustering data preparation
```{r data preparation}
n_factor = 40
factor_scores = mcia_factors[,1:n_factor]
# normalize factor scores
factor_scores = apply(factor_scores, 2, function(z) qqnorm(z, plot.it = F)$x)
# update factors that explain more consistent variation across assays
aa = (apply(sqrt(mcia_results$mcia_factor_evaluation$ave_variance_explained[1:n_factor,]),
            1, sum))^2
factor_scores = t(apply(factor_scores, 1, function(z) z*sqrt(aa)))
# flip the sign of factor1
factor_scores[,1] = -factor_scores[,1]

visit_max = 6
extended_data = make_data_long(factor_scores, sample_meta = clin_data_aligned, 
                               visit_max = visit_max, mean_removal = F)
X = extended_data$X
# upweight samples with convalesent outcomes
ll0 = which(clin_data_aligned$conv_cluster6 != 999)
extended_data_conv = make_data_long(factor_scores[ll0,], 
                                    sample_meta = clin_data_aligned[ll0,], 
                                    visit_max = visit_max, mean_removal = F)

participant_ids = rownames(extended_data$X)
other_features = colnames(clin_data_aligned)[grepl("comorb",colnames(clin_data_aligned)) |grepl("ever",colnames(clin_data_aligned))|grepl("comp",colnames(clin_data_aligned))]
clin_vars <- c("participant_id", "conv_cluster3", "conv_cluster6", 
               "conv_cognitive_deficit", "conv_physical_deficit", 
               "conv_global_deficit", "ethnicity", other_features)
clin_mat_use = data.frame(unique(clin_data_aligned[, clin_vars]))
rownames(clin_mat_use) = clin_mat_use$participant_id
clin_mat_use = clin_mat_use[participant_ids,]
tmp1 = extended_data$sample_meta_participant_level
tmp1$participant_id = NULL
clin_mat_use = cbind(clin_mat_use, tmp1)

id_PASC = (clin_mat_use$conv_cluster6 != 999)
PASCs = rep(NA, nrow(clin_mat_use))
PASCs[id_PASC] = ifelse(
  clin_mat_use$conv_cluster6[id_PASC]%in%PACS_group$physical, "physical",
  ifelse(clin_mat_use$conv_cluster6[id_PASC]%in%PACS_group$cognitive, "cognitive",
         ifelse(clin_mat_use$conv_cluster6[id_PASC]%in%PACS_group$multiple, "multiple",
                "minimal")))
PASCs = factor(PASCs, c("minimal", "physical", "cognitive", "multiple"))
clin_data_pasc = data.frame("participant_id" = clin_mat_use$participant_id,
                            "PASC_group" = PASCs)
clin_data_aligned = left_join(clin_data_aligned, clin_data_pasc, 
                              by = "participant_id")
```

# Hierarchical clustering
```{r hierarchical clustering}
dist_mat_all <- calculate_distance_matrix(X, n_factor, visit_max = visit_max)
dist_mat_conv <- calculate_distance_matrix(extended_data_conv$X, n_factor, 
                                           visit_max = visit_max)
participant_id_conv = rownames(extended_data_conv$X)
# Clustering using all participants
hcl_all <- hclust(d = dist_mat_all, method = "ward.D2")
# Clustering using convalesent participants
hcl_conv <- hclust(d = dist_mat_conv, method = "ward.D2")

Kmin = 5; Kmax= 10
k.values <- Kmin:Kmax
sil_values <- c()
avg_sil <- function(dist_obj, cluster) {
  ss <- silhouette(cluster, dist_obj)
  mean(ss[, 3])
}
for (k in k.values) {
  cluster_cut <- cutree(hcl_all, k)
  sil_values[k - Kmin+1] <- avg_sil(dist_obj  = dist(x = X[,1:n_factor]), 
                                    cluster_cut)
}

nclust_tree_conv = nclust_tree_all = k.values[which.max(sil_values)]

subtype_hcl_all = cutree(hcl_all, k = nclust_tree_all)
subtype_hcl_conv =  cutree(hcl_conv, k = nclust_tree_conv)
subtype_hcl = data.frame(full = subtype_hcl_all)
subtype_hcl$conv = NA
rownames(subtype_hcl) = names(subtype_hcl_all)
subtype_hcl[names(subtype_hcl_conv),]$conv = subtype_hcl_conv
subtype_hcl$PASC = PASCs
subtype_hcl$TG = factor(clin_mat_use$trajectory_group)

# S8 S3 S4 S5 S7 S1 S6 S2
# rename: SD, SC1, SC2, SE, SF, SA, SB1, SB2
# merge: SD, SC, SC, SE, SF, SA, SB, SB
mapping_label <- c("1" = "A", "2" = "B", "3" = "C", "4" = "C", 
                   "5" = "E", "6" = "B", "7" = "F", "8" = "D")
subtype_hcl$label <- mapping_label[as.character(subtype_hcl$full)]
# table(subtype_hcl$label, subtype_hcl$full)
nclust_tree_all = 6
```

# Hierarchical clustering - visit 1
```{r}
idx_ABC = which(subtype_hcl$label %in% c("A", "B", "C"))
dist_mat_V1_ABC = dist(X[idx_ABC, 1:n_factor], method = "euclidean")
hcl_V1_ABC = hclust(d = dist_mat_V1_ABC, method = "ward.D2")
cut_ABC = cutree(hcl_V1_ABC, k = 3)

idx_EF = which(subtype_hcl$label %in% c("E", "F"))
dist_mat_V1_EF = dist(X[idx_EF, 1:n_factor], method = "euclidean")
hcl_V1_EF = hclust(d = dist_mat_V1_EF, method = "ward.D2")
cut_EF = cutree(hcl_V1_EF, k = 2)
cut_EF = cut_EF + 3

idx_exclD = which(subtype_hcl$label != "D")
label_subD = array(6, sum(subtype_hcl$label == "D"))
names(label_subD) = rownames(subtype_hcl)[subtype_hcl$label == "D"]
merged_label = c(cut_ABC, cut_EF, label_subD)
merged_label = factor(merged_label)
levels(merged_label) = 1:6
label_V1 = merged_label[order(names(merged_label))]

# adjustedRandIndex(subtype_hcl$label, label_V1)
# NMI(subtype_hcl$label, label_V1)

contingency = table(subtype_hcl$label, label_V1)
assignment = clue::solve_LSAP(contingency, maximum = TRUE)
mapping = setNames(LETTERS[seq_along(assignment)],
                     as.character(assignment))
label_V1 = mapping[as.character(label_V1)]
```

# TG barplot - V1 hcl
```{r TG barplot - V1 hcl, fig.height=6, fig.width=8}
df_summary = data.frame(Subtype = label_V1,
                        TG = subtype_hcl$TG)
df_summary$Subtype = factor(df_summary$Subtype)
df_summary2 <- df_summary %>%
  dplyr::group_by(Subtype, TG) %>%
  dplyr::summarise(Count = n(), .groups = "drop")
total_counts2 <- df_summary2 %>%
  group_by(Subtype) %>%
  summarise(Total = sum(Count))
df_summary2 <- df_summary2 %>%
  dplyr::group_by(Subtype) %>% 
  mutate(percent = Count/sum(Count)*100)
df_summary2$Subtype <- factor(df_summary2$Subtype, 
                              levels = rev(levels(df_summary2$Subtype)))

ggplot(df_summary2, aes(y = Subtype, x = percent, fill = TG)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
    geom_text(data = total_counts2,
              aes(y = Subtype, x = -6, label = sprintf(" %d", Total)),
            position = position_dodge(width = 0.9),
            inherit.aes = FALSE, size = 7)+
  labs(y = "Subtype",
       x = "Percent") +
  theme(axis.title.x = element_text(size = 15),
        axis.title.y = element_blank(),
        axis.text.x = element_text(color = "black", size = 15),
        axis.text.y = element_blank(),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.key.size = unit(2, "lines"),
        plot.margin = margin(b = 55, t = 5)) +
  scale_fill_manual(values = c("1" = "#639A21", "2" = "#39828C", 
                               "3" = "#6371AD", "4" = "#BD7D31", 
                               "5" = "#9C3418"))
```

# TG test - V1 hcl
```{r TG test - V1 hcl, fig.height=6, fig.width=2.3}
clin_data_patient = clin_data_aligned[clin_data_aligned$event_type == "Visit 1", ]
demo_data_adjust = clin_data_patient[, c("discretized_admit_age_quantile", "sex")]
V1_clust_test = list(); V1_clust_test[["TG"]] = list()
V1_clust_test[["TG"]][["ordinal_demo"]] = test_ordinal_demo(
  subtype = label_V1,
  response = subtype_hcl$TG,
  demo_data = demo_data_adjust)

heatmap_ordinal(V1_clust_test[["TG"]][["ordinal_demo"]])
```

# Factor trajectory - V1 hcl
```{r factor trajectory - V1 hcl, fig.height=6, fig.width=24, warning=FALSE}
df_label = data.frame(label = label_V1)
rownames(df_label) = rownames(subtype_hcl)

mod_ids = c(1, 2, 3, 10)
negation = c(-1, 1, 1, 1)
# negate factors
factors = t(t(mcia_results$mcia_factors[,mod_ids]) * negation)
factors = apply(factors,2, function(z) qqnorm(z, plot.it = F)$x)
factors = data.frame(factors,row.names = rownames(organized_data$datasets$plasma_proteomics_targeted))
factors = factors[clin_data_aligned$event_id,]
colnames(factors) = paste0("Factor", mod_ids)

assay_mat = factors
assay_mat$event_id = rownames(assay_mat)
assay_mat = cytof_mat_preprocess(cytof_mat = assay_mat, 
                                 subtype_hcl = df_label,
                                 clin_data = clin_data_aligned)
clin_colnames_select = setdiff(colnames(assay_mat), colnames(factors))

factor_trajectory_analysis_results = helper_trajectory_data_smooth_spline(
  assay_mat = assay_mat, clin_colnames_select = clin_colnames_select,
  endpoint = "label", use_endpoint_levels = c("A", "B", "C", "E", "F"),
  max_date = 40, text_position = 2)
ggarrange(plotlist = factor_trajectory_analysis_results$test_fig_list, 
          nrow = 1, common.legend = T, legend = "bottom")
```

# Clinical names correspondence
```{r clinical names correspondence}
clin_names <- c("sex" = "Sex (Female)",
                "ethnicity" = "Ethnicity (Hispanic or Latino)",
                "admit_age" = "Admission age",
                "discretized_admit_age_quantile" = "Admission age quantile",
                "raceAmerican Indian / Alaska Native" = "American Indian/Alaska Native",
                "raceAsian" = "Asian",
                "raceBlack / African American" = "Black/African American",
                "raceBlack...African.American" = "Black/African American",
                "raceMultiple" = "Multiple Races",
                "raceNative Hawaiian / Pacific Islander" = "Native Hawaiian/Pacific Islander",
                "raceWhite" = "White",
                "bmicat" = "BMI category",
                "comorb_htn" = "Hypertension",
                "comorb_isaric_dm" = "Diabetes",
                "comorb_anyresp_noasthma" = "Pulmonary (excludes asthma)",
                "comorb_isaric_asthma" = "Asthma",
                "comorb_isaric_cardiac" = "Chronic cardiac disease",
                "comorb_isaric_ckd" = "Chronic kidney disease",
                "comorb_isaric_neoplasm" = "Malignant neoplasm",
                "comorb_neuro" = "Chronic neurological disorder",
                "comorb_isaric_liver" = "Liver disease",
                "comorb_hxtrans" = "History of solid organ or bone marrow transplant",
                "comorb_hiv2" = "HIV",
                "comorb_eversmkvape" = "Current or former smoking and/or vaping",
                "comorb_anysubstance" = "Drug or alcohol abuse or cannabis use",
                "comp_seizure" = "Seizures",
                "comp_meningitis" = "Meningitis/encephalitis",
                "comp_stroke" = "Stroke/CVA",
                "comp_afib" = "Atrial fibrillation",
                "comp_ventricular_arr" = "Ventricular arrhythmia",
                "comp_endo" = "Endocarditis",
                "comp_myocard" = "Myocarditis/pericarditis",
                "comp_cardarrest" = "Cardiac arrest",
                "comp_stemi" = "ST-elevation MI (STEMI)",
                "comp_nstemi" = "Non-ST elevation MI (NSTEMI) or other cardiac ischemia",
                "comp_chf" = "CHF/cardiomyopathy",
                "comp_pneumonia" = "Pneumonia",
                "comp_bronch" = "Bronchiolitis",
                "comp_pneumo" = "Pneumothorax",
                "comp_pneumomed" = "Pneumomediastinum",
                "comp_aat" = "Acute arterial thromboembolism excluding stroke/CVA or myocardial infarction",
                "comp_avthromb" = "Acute venous thromboembolism",
                "comp_shock" = "Shock (use of vasopressors)",
                "comp_bac" = "Bacteremia",
                "comp_coag" = "Coagulation disorder/disseminated intravascular coagulation",
                "comp_hypogly" = "Symptomatic hypoglycemia",
                "comp_bleed" = "Bleeding",
                "comp_anemia" = "Anemia",
                "comp_pancreas" = "Pancreatitis",
                "comp_renal" = "Acute renal injury/failure",
                "comp_liver" = "Liver dysfunction/failure",
                "comp_othlab" = "Other lab abnormality",
                "comp_electrolyte" = "Electrolyte abnormality",
                "comp_othinf" = "Other infection (non-pulmonary)",
                "comp_othpulm" = "Other pulmonary complication",
                "comp_unddisease" = "Exacerbation of underlying disease",
                "comp_enceph" = "Encephalopathy",
                "comp_othneuro" = "Other neurologic complication",
                "comp_hypergly" = "Hyperglycemia",
                "comp_psych" = "Psychiatric complication",
                "comp_mis" = "Multisystem inflammatory syndrome (MIS)",
                "comp_gastroent" = "Gastroenteritis",
                "comp_pulmvas" = "Pulmonary vascular disease",
                "ever_azithro" = "Azithromycin",
                "ever_icu" = "Ever in ICU",
                "ever_otherabx" = "Other Antibiotics",
                "ever_remdes" = "Remdesivir",
                "ever_steroids" = "Steroids",
                "ever_ever_esc" = "Ever required escalation of care",
                "ever_immsupp" = "Immunosuppressives",
                "baseline_anyimg" = "Any chest imaging at baseline",
                "baseline_img_infil" = "Radiographic findings on chest imaging",
                "baseline_lymph_abn" = "Abnormal Lymphocyte count",
                "baseline_platelets_abn" = "Abnormal Platelets",
                "baseline_alt_abn" = "Abnormal ALT",
                "baseline_cr_abn" = "Abnormal Creatinine",
                "baseline_crp_abn" = "Abnormal CRP",
                "baseline_ddimer_abn" = "Abnormal D-dimer",
                "baseline_trop_abn" = "Abnormal Troponin")
```

```{r}
interest_clin_feature = c(
  "comorb_htn", "comorb_anyresp_noasthma", "comorb_isaric_cardiac", 
  "comorb_isaric_ckd", "comorb_hxtrans", "comp_stroke", "comp_afib",
  "comp_ventricular_arr", "comp_cardarrest", "comp_chf", "comp_pneumonia", 
  "comp_avthromb", "comp_shock", "comp_bac", "comp_bleed", "comp_anemia", 
  "comp_renal", "ever_icu", "ever_ever_esc", "sex", "ethnicity", 
  "raceBlack / African American", "raceWhite", "baseline_lymph_abn", 
  "baseline_platelets_abn", "baseline_alt_abn", "baseline_cr_abn", 
  "baseline_crp_abn", "baseline_ddimer_abn", "baseline_trop_abn", 
  "bmicat", "discretized_admit_age_quantile", "baseline_img_infil")
```

# Demographic, comorbidity, baseline, and complication - V1 hcl
```{r clinical heatmap - V1 hcl, fig.height=8, fig.width=14, warning=FALSE}
clin_data_patient <- clin_data_aligned[clin_data_aligned$event_type == "Visit 1",]
demo_data <- clin_data_patient[, c("admit_age", "sex", "ethnicity",
                                   "discretized_admit_age_quantile",
                                   "bmicat", "enrollment_site", "race")]
demo_data$ethnicity[demo_data$ethnicity == "Not Specified"] <- NA
demo_data$bmicat[demo_data$bmicat == 999] <- NA
demo_data$bmicat_test <- demo_data$bmicat
# group obesity together
demo_data$bmicat_test[demo_data$bmicat_test == 5] <- 4
demo_data$race <- as.factor(demo_data$race)
race_one_hot <- model.matrix(~ race-1, data = demo_data)
race_one_hot <- race_one_hot[, !(colnames(race_one_hot) %in%
                                   c("raceOther / Declined", 
                                     "raceUnknown / Unavailable"))]
demo_data_adjust <- demo_data[, c("discretized_admit_age_quantile", "sex")]

clin_data_logit <- clin_data_patient %>%
  dplyr::select(matches("^(comorb|comp)"), ever_icu, ever_ever_esc) %>%
  dplyr::select(-comorb_count, -comorb_countcat, -comp_other2) %>%
  select_if(~sum(.x, na.rm = TRUE) > 0)
clin_data_demo_logit <- cbind(demo_data[, c("sex", "ethnicity")], race_one_hot)
clin_data_demo_logit$sex <- ifelse(clin_data_demo_logit$sex == "Female", 1, 0)
clin_data_demo_logit$ethnicity <- ifelse(clin_data_demo_logit$ethnicity == 
                                           "Hispanic or Latino", 1, 0)

clin_data_baseline <- clin_data_patient %>%
  dplyr::select(matches("^baseline")) %>%
  dplyr::select(-baseline_anyimg) %>%
  mutate(across(everything(), ~replace(., . == 999, NA)))
clin_data_baseline_logit <- clin_data_baseline %>%
  dplyr::select(ends_with("_abn"))

sub_idx <- which(label_V1 != "D")
clin_test_logit <- test_clinical_logit_demo(
  label_V1[sub_idx],
  clin_data_logit[sub_idx,],
  demo_data_adjust[sub_idx,])
demo_test_logit <- test_clinical_logit(
  label_V1[sub_idx],
  clin_data_demo_logit[sub_idx,])
baseline_test_logit <- test_clinical_logit_demo(
  label_V1[sub_idx],
  clin_data_baseline_logit[sub_idx,],
  demo_data_adjust[sub_idx,])
bmi_test_ordinal <- test_ordinal(
  label_V1[sub_idx],
  demo_data$bmicat_test[sub_idx])
age_test_ordinal <- test_ordinal(
  label_V1[sub_idx],
  demo_data$discretized_admit_age_quantile[sub_idx])
baseline_test_ordinal <- test_ordinal_demo(
  label_V1[sub_idx],
  clin_data_baseline$baseline_img_infil[sub_idx],
  demo_data_adjust[sub_idx,])

clin_test_logit$p_lr_adj <- p.adjust(clin_test_logit$p_lr, method = "BH")
demo_test_logit$p_lr_adj <- p.adjust(demo_test_logit$p_lr, method = "BH")

# clinical test featuring variables of interest
clin_test <- clin_test_logit
# interest_clin_idx <- which(clin_test_logit$p_lr_adj < 0.001)
# interest_demo_idx <- which(demo_test_logit$p_lr_adj < 0.001)
clin_test$est_logit <- cbind(clin_test_logit$est_logit, 
                             demo_test_logit$est_logit,
                             baseline_test_logit$est_logit,
                             bmi_test_ordinal$est_ordinal,
                             age_test_ordinal$est_ordinal,
                             baseline_test_ordinal$est_ordinal)
colnames(clin_test$est_logit)[ncol(clin_test$est_logit)-2] <- "bmicat"
colnames(clin_test$est_logit)[ncol(clin_test$est_logit)-1] <- 
  "discretized_admit_age_quantile"
colnames(clin_test$est_logit)[ncol(clin_test$est_logit)] <- "baseline_img_infil"
clin_test$est_logit = clin_test$est_logit[,interest_clin_feature]

clin_test$p_logit <- cbind(clin_test_logit$p_logit, 
                           demo_test_logit$p_logit,
                           baseline_test_logit$p_logit,
                           bmi_test_ordinal$p_ordinal,
                           age_test_ordinal$p_ordinal,
                           baseline_test_ordinal$p_ordinal)
colnames(clin_test$p_logit)[ncol(clin_test$p_logit)-2] <- "bmicat"
colnames(clin_test$p_logit)[ncol(clin_test$p_logit)-1] <- 
  "discretized_admit_age_quantile"
colnames(clin_test$p_logit)[ncol(clin_test$p_logit)] <- "baseline_img_infil"
clin_test$p_logit = clin_test$p_logit[,interest_clin_feature]

clin_test$p_adj <- apply(clin_test$p_logit, 2,
                         function(p) p.adjust(p, method = "BH"))

heatmap_clinical(clin_test, clin_names, adjust_p = TRUE)
```

# Barplot colored by PASC
```{r barplot colored by PASC, fig.height=6, fig.width=8}
df_summary <- data.frame(Subtype = label_V1,
                         PASC =subtype_hcl$PASC,
                         TG = subtype_hcl$TG)
df_summary <- df_summary[df_summary$Subtype != "D", ]
df_summary1 <- df_summary %>%
  dplyr::group_by(Subtype, PASC) %>%
  dplyr::summarise(Count = n(), .groups = "drop")
df_summary1 <- df_summary1[!is.na(df_summary1$PASC),]
total_counts1 <- df_summary1 %>%
  group_by(Subtype) %>%
  summarise(Total = sum(Count))
df_summary1 <- df_summary1 %>%
  dplyr::group_by(Subtype) %>%
  mutate(percent = Count/sum(Count)*100)

df_summary1$Subtype <- factor(as.character(df_summary1$Subtype))
df_summary1$PASC <- factor(df_summary1$PASC, labels = c("Minimal", "Physical", 
                                                        "Cognitive", "Multiple"))
df_summary1$Subtype <- factor(df_summary1$Subtype, 
                              levels = rev(levels(df_summary1$Subtype)))

ggplot(df_summary1, aes(y = Subtype, x = percent, fill = PASC)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  geom_text(data = total_counts1,
            aes(y = Subtype, x = -6, label = sprintf(" %d", Total)),
            position = position_dodge(width = 0.9),
            inherit.aes = FALSE, size = 7)+
  labs(y = "Subtype", x = "Percent") +
  theme(axis.title.x = element_text(size = 15),
        axis.title.y = element_blank(),
        axis.text.x = element_text(color = "black", size = 15),
        axis.text.y = element_blank(),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.key.size = unit(2, "lines"),
        plot.margin = margin(b = 55, t = 5)) +
  scale_fill_manual(values = c("Minimal" = "#999999", "Physical" = "#58B5EA", 
                               "Cognitive" = "#EAAE2A", "Multiple" = "#FF1820"))
```

# PASC test - V1 hcl
```{r PASC test - V1 hcl, fig.height=6, fig.width=5}
id = which(!is.na(subtype_hcl$PASC) & label_V1 != "D")
full_clust_test= list(); full_clust_test[["PASC"]] = list()
ww = ifelse(subtype_hcl$PASC[id] == "minimal", 0, 1)
clin_data_patient = clin_data_aligned[clin_data_aligned$event_type == "Visit 1", ]
demo_data_adjust = clin_data_patient[, c("discretized_admit_age_quantile", "sex")]

full_clust_test[["PASC"]][["fisher"]] = test_clinical_fisher_exact(
  subtype = label_V1[id],
  response = subtype_hcl$PASC[id],
  response_binary = ww, seed = 123)

heatmap_fisher(full_clust_test[["PASC"]][["fisher"]])
```

# PASC global - V1 hcl
```{r PASC global - V1 hcl, fig.height=6, fig.width=2}
heatmap_fisher_global(full_clust_test[["PASC"]][["fisher"]])
```

