---
title: "Additional Check"
output: html_notebook
---

```{r load library}
require(openxlsx)
library(factoextra)
library(cluster)
require(nlme) # directly provides p-values, unlike lme4
require(splines)
require(dplyr)
library(fgsea)
library(knitr)
library(kableExtra)
library(tidyverse)
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
source(paste0(codebase_path,"/codebase_subtype.R"))

organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")

intermediate_results_outdir_DR = "/scratch/data-integration/molecular_subtyping/DimensionReduction/"
mcia_results = readRDS(paste0(intermediate_results_outdir_DR,"MCIA_phase123_20230726.rds"))

data_path <- "/scratch/data-integration/pipelines/processedData/"
data_env0 <- readRDS(paste0(data_path, "data_env_ravi_20220513.RDS"))

base_obj = readRDS(file ="/scratch/data-integration/cleanedup/mod1_interpretation_base.rds")
```

# Load preliminary results
```{r load subtype assignment and clinical data}
# load subtype assignment and clinical data
nclust_tree_all = 6
subtype_hcl = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/subtype_hcl.rds")
clin_data_aligned = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/clin_data_aligned.rds")
extended_data = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/extended_data.rds")
```

# MCIA factor average variance
```{r MCIA factor average variance, fig.height=6, fig.width=6}
omics_name_mapping = c(
  "plasma_proteomics_targeted" = "PPT",
  "plasma_proteomics_global_dda" = "PPG",
  "serum_olink" = "SPT",
  "plasma_metabolomics_global" = "PMG",
  "nasal_transcriptomics" = "NGX",
  "pbmc_transcriptomics" = "PGX")

# average variance_explained
variance_explained = as.data.frame(mcia_results$mcia_factor_evaluation$ave_variance_explained)
colnames(variance_explained) = names(organized_data$datasets_imputed)
colnames(variance_explained) = omics_name_mapping[colnames(variance_explained)]
variance_explained$factor = 1:nrow(variance_explained)
variance_explained = pivot_longer(
  variance_explained, cols = -factor, names_to = "omics", 
  values_to = "variance")

ggplot(variance_explained, aes(x = factor, y = variance, color = omics)) +
  geom_line(linewidth = 0.65) +
  geom_vline(xintercept = 40, linetype = "dashed", 
             color = "grey40", linewidth = 0.65) +
  theme_classic() +
  labs(x = "Factor",
       y = "Average Variance Explained",
       color = "") +
  theme(panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line.x = element_line(linewidth = 1),
    axis.line.y = element_line(linewidth = 1),
    axis.ticks = element_line(linewidth = 1),
    axis.text.x = element_text(color = "black", size = 15),  
    axis.text.y = element_text(color = "black", size = 15),
    axis.title.x = element_text(color = "black", size = 15),
    axis.title.y = element_text(color = "black", size = 15),
    strip.text = element_text(color = "black", size = 15),
    axis.ticks.length = unit(0.15, "cm"),
    legend.position = "bottom",
    legend.text = element_text(size = 15),
    legend.title = element_text(size = 15),
    legend.key.size = unit(2.5, "lines"),
    aspect.ratio = 0.85)
```

# MCIA factor accumulated average variance
```{r MCIA factor accumulated average variance, fig.height=6, fig.width=6}
omics_name_mapping = c(
  "plasma_proteomics_targeted" = "PPT",
  "plasma_proteomics_global_dda" = "PPG",
  "serum_olink" = "SPT",
  "plasma_metabolomics_global" = "PMG",
  "nasal_transcriptomics" = "NGX",
  "pbmc_transcriptomics" = "PGX")

# accumulated average variance_explained
variance_explained = as.data.frame(mcia_results$mcia_factor_evaluation$ave_variance_explained)
colnames(variance_explained) = names(organized_data$datasets_imputed)
colnames(variance_explained) = omics_name_mapping[colnames(variance_explained)]
accum_variance_explained = apply(variance_explained, 2, cumsum)
accum_variance_explained = as.data.frame(accum_variance_explained)
accum_variance_explained$factor = 1:nrow(accum_variance_explained)

accum_variance_explained = pivot_longer(
  accum_variance_explained, cols = -factor, names_to = "omics", 
  values_to = "variance")

ggplot(accum_variance_explained, aes(x = factor, y = variance, color = omics)) +
  geom_line(linewidth = 0.65) +
  geom_vline(xintercept = 40, linetype = "dashed", 
             color = "grey40", linewidth = 0.65) +
  theme_classic() +
  labs(x = "Factor",
       y = "Cumulative Average Variance Explained",
       color = "") +
  theme(panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line.x = element_line(linewidth = 1),
    axis.line.y = element_line(linewidth = 1),
    axis.ticks = element_line(linewidth = 1),
    axis.text.x = element_text(color = "black", size = 15),  
    axis.text.y = element_text(color = "black", size = 15),
    axis.title.x = element_text(color = "black", size = 15),
    axis.title.y = element_text(color = "black", size = 15),
    strip.text = element_text(color = "black", size = 15),
    axis.ticks.length = unit(0.15, "cm"),
    legend.position = "bottom",
    legend.text = element_text(size = 15),
    legend.title = element_text(size = 15),
    legend.key.size = unit(2.5, "lines"),
    aspect.ratio = 0.85)
```

# Correlation between subtype factors and integration factors
```{r correlation between subtype factors and integration factors, fig.height=6, fig.width=7}
n_factor = 40
factor_subtype = as.data.frame(mcia_results$mcia_factors[, 1:n_factor])
rownames(factor_subtype) = rownames(organized_data$datasets$plasma_proteomics_targeted)

factor_train = base_obj$mcia.factors.train
rownames(factor_train) = rownames(base_obj$clin.train)
factor_test = base_obj$mcia.factors.test
rownames(factor_test) = rownames(base_obj$clin.test)
factor_integration = rbind(factor_train, factor_test)

shared_sample = intersect(rownames(factor_subtype), rownames(factor_integration))
shared_sample = sort(shared_sample)

factor_subtype = factor_subtype[shared_sample,]
factor_subtype = apply(factor_subtype, 2, function(z) qqnorm(z, plot.it = F)$x)
factor_integration = factor_integration[shared_sample,]
factor_integration = apply(factor_integration, 2, function(z) qqnorm(z, plot.it = F)$x)

cor_mat = matrix(NA, nrow = n_factor, ncol = n_factor)
for (i in 1:n_factor) {
  for (j in 1:n_factor) {
    cor_mat[i, j] = cor(factor_subtype[,i], factor_integration[,j])
  }
}
cor_mat = abs(cor_mat)
rownames(cor_mat) = paste0("F", 1:40)
colnames(cor_mat) = paste0("F", 1:40)

df_cor = as.data.frame(cor_mat)
df_cor = df_cor %>%
  rownames_to_column(var = "factor_subtype") %>%
  pivot_longer(-factor_subtype, names_to = "factor_integration", 
               values_to = "correlation")
df_cor$factor_subtype = factor(df_cor$factor_subtype)
levels(df_cor$factor_subtype) = paste0("F", 1:40)
df_cor$factor_integration = factor(df_cor$factor_integration)
levels(df_cor$factor_integration) = paste0("F", 1:40)

ggplot(df_cor, aes(x = factor_subtype, y = factor_integration, 
                   fill = correlation)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "#284AA0", mid = "white", high = "#BC4A4A", 
                       midpoint = 0, name = expression("Absolute\nCorrelation"),
                       limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  theme_minimal() +
  labs(x = "Factor (Molecular Subtyping)", y = "Factor (Integration)") +
  theme(axis.ticks = element_line(linewidth = 0.5),  
        axis.line.x = element_line(linewidth = 1),
        axis.line.y = element_line(linewidth = 1),
        axis.text.y = element_text(size = 9, color = "black"),
        axis.text.x = element_text(size = 9, color = "black", angle = 90,
                                   vjust = 0.5),
        legend.title = element_text(size = 15, margin = margin(b = 20)),
        legend.text = element_text(size = 15),
        legend.spacing.y = unit(20, "pt"),
        axis.title.x = element_text(color = "black", size = 15,
                                    margin = margin(t = 10)),
        axis.title.y = element_text(color = "black", size = 15,
                                    margin = margin(r = 10)))
```





