---
title: "Code_Yutong"
output: html_document
date: "2024-01-23"
---

```{r}
library(dplyr)
library(pROC)
library(caret)
```

```{r}
# factor scores
mcia_results <- readRDS("/scratch/data-integration/molecular_subtyping/DimensionReduction/MCIA_phase123_20230726.rds")
organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")
extended_data = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/extended_data.rds")


clin_data_all = organized_data$clinical_data[,setdiff(colnames(organized_data$clinical_data), c("sample_id","sample_type", "phase1_2","samples_collected","phase","enrollment_site"))]
clin_data_all = unique(clin_data_all)
clin_data_aligned = data_frame(event_id=rownames(organized_data$datasets$plasma_proteomics_targeted))
clin_data_aligned <- clin_data_aligned %>% left_join(clin_data_all, by = c("event_id"))
ll = which(clin_data_aligned$event_type %in% paste0("Visit ",1:6))
clin_data_aligned <- clin_data_aligned[ll,]
mcia_factors = mcia_results$mcia_factors
rownames(mcia_factors) <- gsub('-([0-9])$', '-0\\1', rownames(organized_data$datasets_imputed[[1]]))
mcia_factors = mcia_factors[ll,]
n_factor = 40
factor_scores = mcia_factors[,1:n_factor]
factor_scores = apply(factor_scores, 2,function(z) qqnorm(z, plot.it = F)$x)
# update factors that explain more consistent variation across assays
aa = (apply(sqrt(mcia_results$mcia_factor_evaluation$ave_variance_explained[1:n_factor,]),1,sum))^2
factor_scores = t(apply(factor_scores,1,function(z) z*sqrt(aa)))
rownames(factor_scores) <- rownames(mcia_factors)
factor_scores <- as.data.frame(factor_scores)
factor_scores$participant_id <- substr(rownames(factor_scores), start = 1, stop = 8)

# ema of factor scores
mov_ave <- function(a){
  mu <- 1 - 2/(length(a)+2)
  res <- a[1]
  for (k in 1:length(a))  res <- mu*a[k] + (1-mu)*res
  return(res)
}
factor_scores_ema <- aggregate(. ~ participant_id, data = factor_scores, FUN = mov_ave)
rownames(factor_scores_ema) <- factor_scores_ema$participant_id
factor_scores_ema$participant_id <- NULL

# V1 of factor scores
factor_scores_v1 <- factor_scores[!duplicated(factor_scores$participant_id),]
# factor_scores_v1 <- factor_scores[substr(rownames(factor_scores), start = 10, stop = 11)=="01",]
rownames(factor_scores_v1) <- factor_scores_v1$participant_id
factor_scores_v1$participant_id <- NULL
```

```{r}
# subtype assignments
subtype_labels <- readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/subtype_hcl.rds")
subtype_labels$merged_labels <- subtype_labels$label
label_map <- c(A = 1, B = 2, C = 3, D = 4, E = 5, F = 6)
subtype_labels$merged_labels <- label_map[subtype_labels$merged_labels]

# probability vector
factor_scores$visit <- clin_data_aligned$event_type
factor_scores$subtype <- subtype_labels[factor_scores$participant_id,]$merged_labels
factor_scores <- na.omit(factor_scores)
subtype_centers <- list()
for (i in 1:6){
  tmp <- factor_scores[factor_scores$subtype ==i,]
  visits <- unique(tmp$visit)
  subtype_centers[[i]] <- 1:40
  for (v in visits){
    subtype_centers[[i]] <- rbind(subtype_centers[[i]], colMeans(tmp[tmp$visit == v, 1:40]))
  }
  subtype_centers[[i]] <- as.data.frame(subtype_centers[[i]][-1,])
  rownames(subtype_centers[[i]]) <- visits
}
copy <- factor_scores
copy$dist <- rowSums((copy[,1:40]-subtype_centers[[1]][copy$visit,])^2)
copy <- na.omit(copy)
dist_to_subtype <- aggregate(dist ~ participant_id, data = copy, FUN = mean)
rownames(dist_to_subtype) <- dist_to_subtype$participant_id
dist_to_subtype$participant_id <- NULL
colnames(dist_to_subtype) <- c("S1")
for (i in 2:6){
  copy <- factor_scores
  copy$dist <- rowSums((copy[,1:40]-subtype_centers[[i]][copy$visit,])^2)
  copy <- na.omit(copy)
  dist <- aggregate(dist ~ participant_id, data = copy, FUN = mean)
  dist_to_subtype[dist$participant_id, paste0("S",i)] <- dist$dist
}
softmax <- function(x) {
  exp_x <- exp(x - max(x))
  return(exp_x / sum(exp_x))
}
probs <- as.data.frame(t(apply(-dist_to_subtype, FUN = softmax, MARGIN = 1)))
colnames(probs) <- c("p1","p2","p3","p4","p5","p6")
log_probs <- log(probs)

# check assignment accuracy
print(sum(apply(probs,1,which.max)==subtype_labels$merged_labels)/dim(probs)[1])
```

```{r}
# clinical data
clinical_data <- clin_data_aligned[!duplicated(clin_data_aligned$participant_id),]
clinical_data <- as.data.frame(clinical_data)
rownames(clinical_data) <- clinical_data$participant_id
clinical_data <- clinical_data %>% dplyr::select(participant_id, admit_age, sex,  
                                                  bmicat, los, ncomp, 
                                                  baseline_sofa_score_new, 
                                                  matches("comorb"))
clinical_data$comorb_countcat <- NULL
clinical_data[clinical_data$sex=='Female',]$sex <- 1
clinical_data[clinical_data$sex=='Male',]$sex <- 0
clinical_data$sex <- as.numeric(clinical_data$sex)
base_obj <- readRDS('/scratch/data-integration/cleanedup/mod1_interpretation_base.rds')
spike_IgG <- rbind(base_obj$others$serum_rbd_abtiters$train$serum_rbd_abtiters_counts,
                   base_obj$others$serum_rbd_abtiters$test$serum_rbd_abtiters_counts)

spike_IgG$N1_CT <- rbind(base_obj$others$nasal_viralload$train$nasal_viralload_counts,
                         base_obj$others$nasal_viralload$test$nasal_viralload_counts)$N1_CT
spike_IgG <- spike_IgG[,c('AUC Spike IgG','N1_CT')]
spike_IgG <- na.omit(spike_IgG)
spike_IgG$participant_id <- substr(rownames(spike_IgG), start = 1, stop = 8)

# ema of viral loads and antibody
spike_IgG_ema <- aggregate(. ~ participant_id, data = spike_IgG, FUN=mov_ave)
rownames(spike_IgG_ema) <- spike_IgG_ema$participant_id

# V1 of viral loads and antibody
spike_IgG_v1 <- spike_IgG[!duplicated(spike_IgG$participant_id),]
# spike_IgG_v1 <- spike_IgG[substr(rownames(spike_IgG), start = 10, stop = 11)=="01",]
rownames(spike_IgG_v1) <- spike_IgG_v1$participant_id

clinical_data_ema <- merge(clinical_data, spike_IgG_ema, by='participant_id')
rownames(clinical_data_ema) <- clinical_data_ema$participant_id
clinical_data_ema$participant_id <- NULL
clinical_data_ema <- na.omit(clinical_data_ema)
clinical_data_ema <- clinical_data_ema[clinical_data_ema$bmicat!=999,]

clinical_data_v1 <- merge(clinical_data, spike_IgG_v1, by='participant_id')
rownames(clinical_data_v1) <- clinical_data_v1$participant_id
clinical_data_v1$participant_id <- NULL
clinical_data_v1 <- na.omit(clinical_data_v1)
clinical_data_v1 <- clinical_data_v1[clinical_data_v1$bmicat!=999,]
```

```{r}
# post-acute assignment
sample_meta_participant = extended_data$sample_meta_participant_level
sample_meta_participant$death_date[sample_meta_participant$death_date<0] = 999
censoring_date_death = 200
death_surv = cbind(sample_meta_participant$death_date,sample_meta_participant$death_date)
death_surv[death_surv[,2]>censoring_date_death,2] = censoring_date_death+1
death_surv[,1] = ifelse(death_surv[,2]<=censoring_date_death,1,0)
death_surv = data.frame(death_surv)
colnames(death_surv) = c("state", "time")
```

```{r}
# PASC
conval_raw <- organized_data$clinical_data$conv_cluster6
names(conval_raw) <- organized_data$clinical_data$event_id
# conval_raw <- na.omit(conval_raw)
conval_raw[conval_raw == 3 | conval_raw == 4] = 1
conval_raw[conval_raw == 5] = 3
conval_raw[conval_raw == 6] = 4
conval_raw <- conval_raw[!duplicated(gsub('-[0-9]+$', '', names(conval_raw)))]
names(conval_raw) <- gsub('-[0-9]+$', '', names(conval_raw))
conval_raw <- conval_raw[sort(names(conval_raw))]

conval_raw <- conval_raw[sample_meta_participant$participant_id]
id_post_acute_death <- which((death_surv$time > 28 & 
                                death_surv$time < censoring_date_death) | 
                               !is.na(conval_raw))
conval_raw <- conval_raw[id_post_acute_death]
conval_raw[is.na(conval_raw)] <- 0
```

```{r}
# data for prediction
# ema data
id <- Reduce(intersect, list(rownames(clinical_data_ema), 
                             rownames(factor_scores_ema), 
                             rownames(log_probs),
                             names(conval_raw)))
data_pred_ema <- list()
data_pred_ema[['conval']] <- conval_raw[id]
data_pred_ema[['clinical']] <- clinical_data_ema[id,]
data_pred_ema[['subtype']] <- log_probs[id,]
data_pred_ema[['factor']] <- factor_scores_ema[id,]

# V1 data
id_v1 <- Reduce(intersect, list(rownames(clinical_data_v1), 
                             rownames(factor_scores_v1), 
                             rownames(log_probs),
                             names(conval_raw)))
data_pred_v1 <- list()
data_pred_v1[['conval']] <- conval_raw[id_v1]
data_pred_v1[['clinical']] <- clinical_data_v1[id_v1,]
data_pred_v1[['subtype']] <- log_probs[id_v1,]
data_pred_v1[['factor']] <- factor_scores_v1[id_v1,]
```

```{r}
prediction <- function(data, pred_model) { 
  models <- list()
  test_sets <- list()
  conval <- data$conval
  repeats <- 10
  rocs <- vector("list", repeats)
  prcs <- vector("list", repeats)
  aucs <- rep(0, repeats)
  auprcs <- rep(0, repeats)
  train_accs <- rep(0, repeats)
  test_accs <- rep(0, repeats) 
  set.seed(3261) 
  for (s in 1:repeats) {
    # split data
    ind_train <- sample(1:length(conval), floor(length(conval)*0.7))
    conval_train <- conval[ind_train]
    conval_test <- conval[-ind_train]

    # binary response
    conval01_train <- conval_train
    conval01_train[conval01_train != 1] <- 0
    conval01_test <- conval_test
    conval01_test[conval01_test != 1] <- 0

    d_train <- data.frame(Column1 = 1:length(conval01_train))
    d_test <- data.frame(Column1 = 1:length(conval01_test))
    rownames(d_train) <- names(conval01_train)
    rownames(d_test) <- names(conval01_test)
    # clinical
    d_train <- cbind(d_train, data$clinical[rownames(d_train),])
    d_test <- cbind(d_test, data$clinical[rownames(d_test),])
    # subtype
    if (pred_model != "CLINICAL") {
      d_train <- cbind(d_train, data$subtype[rownames(d_train),])
      d_test <- cbind(d_test, data$subtype[rownames(d_test),])
    }
    # factor scores
    if (pred_model == "CLINICAL-SUBTYPE+") {
      d_train <- cbind(d_train, data$factor[rownames(d_train),])
      d_test <- cbind(d_test, data$factor[rownames(d_test),])
    }
    
    d_train$Column1 <- NULL
    d_test$Column1 <- NULL

    d_train$conval <- conval01_train
    d_train$conval[d_train$conval == 0] <- "level0"
    d_train$conval[d_train$conval == 1] <- "level1"
    d_train$conval <- factor(d_train$conval)
    d_test$conval <- conval01_test
    d_test$conval[d_test$conval == 0] <- "level0"
    d_test$conval[d_test$conval == 1] <- "level1"
    d_test$conval <- factor(d_test$conval)

    control <- trainControl(method = "cv", number = 5, summaryFunction = twoClassSummary, classProbs = TRUE)
    model = train(conval ~ ., data = d_train, trControl = control, method = "svmRadial", metric = "ROC")
    
    # in-sample training accuracy
    pred_train <- predict(model, d_train)
    train_accs[s] <- mean(pred_train == d_train$conval)
    print(paste0("Training accuracy: ", train_accs[s]))
    
    
    # test accuracy
    pred_test <- predict(model, d_test)
    test_accs[s] <- mean(pred_test == d_test$conval)
    print(paste("Test accuracy:", test_accs[s]))
    
    # auc and auprc
    pred <- predict(model, d_test, type = 'prob')[,2]
    
    rocs[[s]] <- pROC::roc(d_test$conval, pred)
    aucs[s] <- rocs[[s]]$auc
    print(paste0("auc: ", aucs[s]))
    
    prcs[[s]] <- PRROC::pr.curve(scores.class0 = 1-pred, weights.class0 = 1-conval01_test, curve = TRUE)
    auprcs[s] <- prcs[[s]]$auc.integral
    print(paste0("auprc: ", auprcs[s]))
    
    models[[s]] <- model
    test_sets[[s]] <- d_test
  }
  print("---Summary---")
  print(paste0("auc mean: ", mean(aucs)))
  print(paste0("auc std: ", sd(aucs)))
  print(paste0("auprc mean: ", mean(auprcs)))
  print(paste0("auprc std: ", sd(auprcs)))
  print(paste0("training accuracy mean: ", mean(train_accs)))
  print(paste0("test accuracy mean: ", mean(test_accs)))
  res <- list(aucs, rocs, auprcs, prcs, models, test_sets)
  names(res) <- c("aucs", "rocs", "auprcs", "prcs", "models", "test_sets")
  return(res)
}
```

```{r}
res <- prediction(data_pred_ema, "CLINICAL")
aucs_clinical <- res$aucs
rocs_clinical <- res$rocs
auprcs_clinical <- res$auprcs
prcs_clinical <- res$prcs
models_clinical <- res$models
test_sets_clinical <- res$test_sets

res <- prediction(data_pred_ema, "CLINICAL-SUBTYPE")
aucs_clinical_prob <- res$aucs
rocs_clinical_prob <- res$rocs
auprcs_clinical_prob <- res$auprcs
prcs_clinical_prob <- res$prcs
models_clinical_prob <- res$models
test_sets_clinical_prob <- res$test_sets

res <- prediction(data_pred_ema, "CLINICAL-SUBTYPE+")
aucs_clinical_factor_prob <- res$aucs
rocs_clinical_factor_prob <- res$rocs
auprcs_clinical_factor_prob <- res$auprcs
prcs_clinical_factor_prob <- res$prcs
models_clinical_factor_prob <- res$models
test_sets_clinical_factor_prob <- res$test_sets
```

# Visualization
# ROC plots
```{r}
library(cutpointr)
library(tidyverse)

# prepare data
fig_names <- c('CLINICAL', 'CLINICAL-SUBTYPE', 'CLINICAL-SUBTYPE+')

aucs <- list(aucs_clinical, aucs_clinical_prob, aucs_clinical_factor_prob)
rocs <- list(rocs_clinical, rocs_clinical_prob, rocs_clinical_factor_prob)
roc_data <- NULL
ci_data <- NULL
for (i in 1:length(fig_names)){
  fig_name <- fig_names[i]
  rocs_svm <- rocs[[i]]
  aucs_svm <- aucs[[i]]
  
  # compute average roc curves
  predictions <- rocs_svm[[1]]$predictor
  for (j in 2:10){
    predictions <- rbind(predictions, rocs_svm[[j]]$predictor)
  }
  
  responses <- rocs_svm[[1]]$response
  for (j in 2:10){
    responses <- rbind(responses, rocs_svm[[j]]$response)
  }
  
  predictions_10_samples <- data.frame(
      Sample = rep(c(1:10), times = length(rocs_svm[[1]]$predictor)),
      PredictionValues = as.numeric(predictions),
      RealClass = as.numeric(responses)
  )
  
  mean_roc <- function(data, cutoffs = seq(from = -1, to = 2, by = 0.01)) {
      map_df(cutoffs, function(cp) {
          out <- cutpointr(data = data, x = PredictionValues, class = RealClass,
                           subgroup = Sample, method = oc_manual, cutpoint = cp,
                           pos_class = 2, direction = ">=")
          data.frame(cutoff = cp,
                     sensitivity = mean(out$sensitivity),
                     specificity = mean(out$specificity))
      })
  }
  mr <- mean_roc(predictions_10_samples)
  
  df <- data.frame(
    CI_low = pmax(rev(mr$sensitivity) - sd(aucs_svm), 0),
    CI_high = pmin(rev(mr$sensitivity) + sd(aucs_svm), 1),
    FPR = rev(1 - mr$specificity),
    Model = fig_name
  )
  ci_data <- rbind(ci_data, df)
  
  df <- data.frame(
    TPR = rev(mr$sensitivity),
    FPR = rev(1 - mr$specificity),
    Label = "average",
    Model = fig_name
  )
  roc_data <- rbind(roc_data, df)
  
  df <- data.frame(
    TPR = seq(0, 1, 0.01),
    FPR = seq(0, 1, 0.01),
    Label = "chance",
    Model = fig_name
  )
  roc_data <- rbind(roc_data, df)
  
  for (j in 1:10){
    df <- data.frame(
      TPR = rev(rocs_svm[[j]]$sensitivities),
      FPR = rev(1 - rocs_svm[[j]]$specificities),
      Label = toString(j),
      Model = fig_name
    )
    roc_data <- rbind(roc_data, df)
  }
}
```

```{r fig.height=6, fig.width=18}
# ROC plots
mycol_purple <- rgb(171, 130, 255, max = 255, alpha = 70)
mycol_red <- rgb(233, 150, 122, max = 255, alpha = 70)
custom_colors <- c("1" = "mistyrose", "2" = "antiquewhite2", "3" = "paleturquoise",
                   "4" = "darkseagreen2", "5" = mycol_red, "6" = "peachpuff",
                   "7" = "honeydew3", "8" = "khaki1", "9" = "thistle1",
                   "10" = mycol_purple, "average" = "black", "chance" = "red")

custom_line_types <- c("1" = "solid", "2" = "solid", "3" = "solid", "4" = "solid", "5" = "solid",
                       "6" = "solid", "7" = "solid", "8" = "solid", "9" = "solid", "10" = "solid",
                       "average" = "solid", "chance" = "dashed")

custom_line_width <- c("1" = 0.8, "2" = 0.8, "3" = 0.8, "4" = 0.8, "5" = 0.8,
                       "6" = 0.8, "7" = 0.8, "8" = 0.8, "9" = 0.8, "10" = 0.8,
                       "average" = 1, "chance" = 0.8)

aucs <- list(aucs_clinical, aucs_clinical_prob, aucs_clinical_factor_prob)
texts <- c()
for (i in 1:length(aucs)){
  aucs_svm <- aucs[[i]]
  M <- mean(aucs_svm)
  SD <- sd(aucs_svm)
  texts[i] <- paste0("AUROC: ", sprintf("%.3f",round(M,3)), " (SD ", sprintf("%.3f",round(SD,3)), ")")
}

facet_labels <- data.frame(
  Model = c("CLINICAL", "CLINICAL-SUBTYPE", "CLINICAL-SUBTYPE+"),
  Text = texts,
  xPos = rep(0.7, 3), 
  yPos = rep(0.4, 3)  
)

ggplot() +
geom_line(data = roc_data, aes(x = FPR, y = TPR, color = Label, linewidth = Label, linetype = Label)) + 
scale_color_manual(values = custom_colors, breaks = c("chance", "average"),
                   labels = c("Chance (random classifier)        ", "Average testing AUROC        ")) +
scale_linewidth_manual(values = custom_line_width, breaks = c("chance", "average"), 
                       labels = c("Chance (random classifier)        ", "Average testing AUROC        ")) +  
scale_linetype_manual(values = custom_line_types, breaks = c("chance", "average"), 
                      labels = c("Chance (random classifier)        ", "Average testing AUROC        ")) + 
# Add the confidence intervals
geom_ribbon(data = ci_data, aes(x = FPR, ymin = CI_low, ymax = CI_high, fill = "CI"), alpha = 0.4) +
scale_fill_manual(values = c("CI" = "darkgray"), labels = "±1 SD") +
facet_wrap(~ Model, scales = "free_y") +
labs(x = "False positive rate", y = "True positive rate") +
scale_x_continuous(expand = c(0, 0), limits = c(0, 1), breaks = seq(0, 1, by = 0.2)) +
scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = seq(0, 1, by = 0.2)) +
# Customize the theme 
theme_minimal() +
theme(panel.spacing = unit(2, "lines"),
      panel.grid.major = element_blank(),  # Remove major grid lines
      panel.grid.minor = element_blank(),  # Remove minor grid lines
      panel.border = element_blank(),  # Remove panel border
      axis.line.x = element_line(linewidth = 1),  # Add x axis line
      axis.line.y = element_line(linewidth = 1),  # Add y axis line
      axis.ticks = element_line(linewidth = 1),  # axis ticks
      axis.text.x = element_text(color = "black", size = 15),  # axis text
      axis.text.y = element_text(color = "black", size = 15),  # axis text
      axis.title = element_text(color = "black", size = 15),  # axis titles 
      axis.ticks.length = unit(0.15, "cm"),  # Adjust the length of axis ticks
      strip.text = element_text(color = "black", size = 15, margin = margin(b = 20)),
      legend.position = "top",  # Position the legend at the top
      legend.justification = "left",  # Justify the legend to the left
      legend.title = element_blank(),
      legend.text = element_text(color = "black", size = 15),
      legend.margin = margin(t = 5, b = 10),
      legend.spacing.x = unit(1, "mm"),
      legend.key.width = unit(2, "cm"),
      plot.margin = margin(t = 10, r = 25, b = 10, l = 15),
      aspect.ratio = 0.85
    ) + 
guides(color = guide_legend(order = 1), linewidth = guide_legend(order = 1),
       linetype = guide_legend(order = 1), fill = guide_legend(order = 2)) + 
geom_text(color = "black", data = facet_labels, aes(x = xPos, y = yPos, label = Text), inherit.aes = FALSE, size = 5)
```


# PRC plots
```{r}
library(cutpointr)
library(tidyverse)

# prepare data
fig_names <- c('CLINICAL', 'CLINICAL-SUBTYPE', 'CLINICAL-SUBTYPE+')

auprcs <- list(auprcs_clinical, auprcs_clinical_prob, auprcs_clinical_factor_prob)
prcs <- list(prcs_clinical, prcs_clinical_prob, prcs_clinical_factor_prob)
rocs <- list(rocs_clinical, rocs_clinical_prob, rocs_clinical_factor_prob)
test_sets <- list(test_sets_clinical, test_sets_clinical_prob, test_sets_clinical_factor_prob)
prc_data <- NULL
ci_data <- NULL

for (i in 1:length(fig_names)){
  fig_name <- fig_names[i]
  rocs_svm <- rocs[[i]]
  prcs_svm <- prcs[[i]]
  auprcs_svm <- auprcs[[i]]
  test_sets_svm <- test_sets[[i]]
  
  # compute average prc
  predictions_10_samples <- list()
  for (j in 1:10){
    predictions_10_samples[[j]] <- data.frame(predictions = 1-rocs_svm[[j]]$predictor,
                                              responses = ifelse(rocs_svm[[j]]$response=="level0", 1, 0)
                                             )
  }
  
  cutoffs <- seq(from = 0, to = 1, by = 0.01)
  # Function to calculate precision and recall
  calculate_metrics <- function(data, cutoff) {
    predicted_labels <- ifelse(data$predictions >= cutoff, 1, 0)
    labels <- data$responses
    true_positives <- sum(predicted_labels == 1 & labels == 1)
    false_positives <- sum(predicted_labels == 1 & labels == 0)
    false_negatives <- sum(predicted_labels == 0 & labels == 1)
    
    precision <- ifelse((true_positives + false_positives) > 0, true_positives / (true_positives + false_positives), 1)
    recall <- true_positives / max((true_positives + false_negatives),1)
    
    return(data.frame(precision=precision, recall=recall))
  }

  # Initialize a data frame to store average precision and recall for each cutoff
  mr <- data.frame(cutoff = numeric(), precision = numeric(), recall = numeric())
  
  # Calculate average precision and recall for each cutoff
  for (cutoff in cutoffs) {
    metrics_list <- t(sapply(predictions_10_samples, calculate_metrics, cutoff = cutoff))
    mr <- rbind(mr, data.frame(cutoff = cutoff, precision = mean(unlist(metrics_list[,1])), 
                               recall = mean(unlist(metrics_list[,2]))))
  }
  
  df <- data.frame(
    CI_low = pmax(rev(mr$precision) - sd(auprcs_svm), 0),
    CI_high = pmin(rev(mr$precision) + sd(auprcs_svm), 1),
    recall = rev(mr$recall),
    Model = fig_name
  )
  ci_data <- rbind(ci_data, df)
  
  df <- data.frame(
    precision = rev(mr$precision),
    recall = rev(mr$recall),
    Label = "average",
    Model = fig_name
  )
  prc_data <- rbind(prc_data, df)
  
  baseline = 0
  for (j in 1:10) {
    baseline = baseline + table(test_sets_svm[[j]]$conval)[1]/length(test_sets_svm[[j]]$conval)
  }
  baseline = baseline/10
  df <- data.frame(
    precision = rep(baseline, 101),
    recall = seq(0, 1, 0.01),
    Label = "chance",
    Model = fig_name
  )
  prc_data <- rbind(prc_data, df)
  
  for (j in 1:10){
    df <- data.frame(
      precision = rev(prcs_svm[[j]]$curve[,2]),
      recall = rev(prcs_svm[[j]]$curve[,1]),
      Label = toString(j),
      Model = fig_name
    )
    prc_data <- rbind(prc_data, df)
  }
}
```

```{r fig.height=6, fig.width=18}
# PRC plots
mycol_purple <- rgb(171, 130, 255, max = 255, alpha = 70)
mycol_red <- rgb(233, 150, 122, max = 255, alpha = 70)
custom_colors <- c("1" = "mistyrose", "2" = "antiquewhite2", "3" = "paleturquoise",
                   "4" = "darkseagreen2", "5" = mycol_red, "6" = "peachpuff",
                   "7" = "honeydew3", "8" = "khaki1", "9" = "thistle1",
                   "10" = mycol_purple, "average" = "black", "chance" = "red")

custom_line_types <- c("1" = "solid", "2" = "solid", "3" = "solid", "4" = "solid", "5" = "solid",
                       "6" = "solid", "7" = "solid", "8" = "solid", "9" = "solid", "10" = "solid",
                       "average" = "solid", "chance" = "dashed")

custom_line_width <- c("1" = 0.8, "2" = 0.8, "3" = 0.8, "4" = 0.8, "5" = 0.8,
                       "6" = 0.8, "7" = 0.8, "8" = 0.8, "9" = 0.8, "10" = 0.8,
                       "average" = 1, "chance" = 0.8)

auprcs <- list(auprcs_clinical, auprcs_clinical_prob, auprcs_clinical_factor_prob)
texts <- c()
for (i in 1:length(auprcs)){
  auprcs_svm <- auprcs[[i]]
  M <- mean(auprcs_svm)
  SD <- sd(auprcs_svm)
  texts[i] <- paste0("AUPRC: ", sprintf("%.3f",round(M,3)), " (SD ", sprintf("%.3f",round(SD,3)), ")")
}

facet_labels <- data.frame(
  Model = c("CLINICAL", "CLINICAL-SUBTYPE", "CLINICAL-SUBTYPE+"),
  Text = texts,
  xPos = rep(0.5, 3), 
  yPos = rep(0.2, 3)  
)

ggplot() +
geom_line(data = prc_data, aes(x = recall, y = precision, color = Label, linewidth = Label, linetype = Label)) + 
scale_color_manual(values = custom_colors, breaks = c("chance", "average"),
                   labels = c("Chance (random classifier)        ", "Average testing AUPRC        ")) +
scale_linewidth_manual(values = custom_line_width, breaks = c("chance", "average"), 
                       labels = c("Chance (random classifier)        ", "Average testing AUPRC        ")) +  
scale_linetype_manual(values = custom_line_types, breaks = c("chance", "average"), 
                      labels = c("Chance (random classifier)        ", "Average testing AUPRC        ")) + 
# Add the confidence intervals
geom_ribbon(data = ci_data, aes(x = recall, ymin = CI_low, ymax = CI_high, fill = "CI"), alpha = 0.4) +
scale_fill_manual(values = c("CI" = "darkgray"), labels = "±1 SD") +
facet_wrap(~ Model, scales = "free_y") +
labs(x = "Recall", y = "Precision") +
scale_x_continuous(expand = c(0, 0), limits = c(0, 1), breaks = seq(0, 1, by = 0.2)) +
scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = seq(0, 1, by = 0.2)) +
# Customize the theme 
theme_minimal() +
theme(panel.spacing = unit(2, "lines"),
      panel.grid.major = element_blank(),  # Remove major grid lines
      panel.grid.minor = element_blank(),  # Remove minor grid lines
      panel.border = element_blank(),  # Remove panel border
      axis.line.x = element_line(linewidth = 1),  # Add x axis line
      axis.line.y = element_line(linewidth = 1),  # Add y axis line
      axis.ticks = element_line(linewidth = 1),  # axis ticks
      axis.text.x = element_text(color = "black", size = 15),  # axis text
      axis.text.y = element_text(color = "black", size = 15),  # axis text
      axis.title = element_text(color = "black", size = 15),  # axis titles 
      axis.ticks.length = unit(0.15, "cm"),  # Adjust the length of axis ticks
      strip.text = element_text(color = "black", size = 15, margin = margin(b = 20)),
      legend.position = "top",  # Position the legend at the top
      legend.justification = "left",  # Justify the legend to the left
      legend.title = element_blank(),
      legend.text = element_text(color = "black", size = 15),
      legend.margin = margin(t = 5, b = 10),
      legend.spacing.x = unit(1, "mm"),
      legend.key.width = unit(2, "cm"),
      plot.margin = margin(t = 10, r = 25, b = 10, l = 15),
      aspect.ratio = 0.85
    ) + 
guides(color = guide_legend(order = 1), linewidth = guide_legend(order = 1),
       linetype = guide_legend(order = 1), fill = guide_legend(order = 2)) + 
geom_text(color = "black", data = facet_labels, aes(x = xPos, y = yPos, label = Text), inherit.aes = FALSE, size = 5)
```


# barplot of AUROC, AUPRC
```{r fig.height=6, fig.width=6}
df <- data.frame(
  category = c("Average AUROC", "Average AUPRC"),
  value1 = c(mean(aucs_clinical), mean(auprcs_clinical)),
  value2 = c(mean(aucs_clinical_prob), mean(auprcs_clinical_prob)),
  value3 = c(mean(aucs_clinical_factor_prob), mean(auprcs_clinical_factor_prob)),
  value4 = c(0.5, prc_data$precision[prc_data$Label == "chance"][1])
)

df <- tidyr::pivot_longer(df, cols = c(value1, value2, value3, value4), 
                          names_to = "model", values_to = "value")
# df$category <- factor(df$category, levels = c("Average AUROC", "Average AUPRC"))

aucs <- list(aucs_clinical, aucs_clinical_prob, aucs_clinical_factor_prob,
             auprcs_clinical, auprcs_clinical_prob, auprcs_clinical_factor_prob)
texts <- c()
for (i in 1:length(aucs)){
  aucs_svm <- aucs[[i]]
  M <- mean(aucs_svm)
  SD <- sd(aucs_svm)
  texts[i] <- paste0(sprintf("%.3f",round(M,3)), "\n(SD ", sprintf("%.3f",round(SD,3)), ")")
}
texts <- c(texts[1:3], "0.500", texts[4:6], 
           round(prc_data$precision[prc_data$Label == "chance"][1], 3))
df$text <- texts

# Create the bar plot
ggplot(df, aes(x = category, y = value, fill = model)) +
  geom_bar(data = subset(df, model != "value4"), 
           stat = "identity", position = "dodge") +
  geom_bar(data = subset(df, model == "value4"),
           stat = "identity", position = "dodge", alpha = 0.8) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.9), breaks = seq(0, 0.9, by = 0.2)) +
  scale_fill_manual(values = c(value1="#F8766D",value2="#7CAE00",value3="#00BFC4",value4="darkgray"),
                    labels = c("CLINICAL","CLINICAL-SUBTYPE","CLINICAL-SUBTYPE+","Chance (random classifier)")) +
  guides(fill = guide_legend(ncol = 2)) + 
  labs(x = "", y = "", fill = "") +
  theme_minimal() +
  theme(
        panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        panel.border = element_blank(),  
        axis.line.x = element_line(linewidth = 1),  
        axis.line.y = element_line(linewidth = 1),  
        axis.ticks = element_line(linewidth = 1),  
        axis.text.x = element_text(color = "black", size = 15),  
        axis.text.y = element_text(color = "black", size = 15),  
        axis.title = element_text(color = "black", size = 15),  
        axis.ticks.length = unit(0.15, "cm"),  
        legend.position = "top", 
        legend.justification = "left",
        legend.direction = "vertical",
        legend.text = element_text(size = 15),
        plot.margin = margin(r = 20, l = 10),
        aspect.ratio = 0.85
  ) +
  geom_text(data = subset(df, model != "value4"),
            aes(label = text), position = position_dodge(width = 0.9),  
            vjust = -0.5, size = 3) +
  geom_text(data = subset(df, model == "value4"),
            aes(label = text), position = position_dodge(width = 0.9),  
            vjust = -0.5, size = 3)
```

# boxplot of AUROC and AUPRC increment
```{r fig.height=6, fig.width=6}
# Categories
categories <- rep(c("AUROC", "AUPRC"), each = 10)

# Values for the first box
values1 <- c(aucs_clinical_prob-aucs_clinical, auprcs_clinical_prob-auprcs_clinical)

# Values for the second box
values2 <- c(aucs_clinical_factor_prob-aucs_clinical, auprcs_clinical_factor_prob-auprcs_clinical)

# Combine into a data frame
df <- data.frame(category = rep(categories, 2),
                 value = c(values1, values2),
                 group = rep(c("CLINICAL-SUBTYPE", "CLINICAL-SUBTYPE+"), each = 20))

# add p-values
p.val <- function(x){
  return(wilcox.test(rep(0,10), x, paired = TRUE, alternative = "less")$p.value)
}
p_values <- aggregate(value ~ category + group, data = df, FUN = p.val)
p_values$value <- c("0.065", "0.080", "0.348", "0.065")

ggplot(df, aes(x = category, y = value, color = group)) +
  geom_boxplot(position = position_dodge(width = 0.8), size = 1, width = 0.7, outlier.shape = NA) +
  geom_jitter(aes(color = group), position = position_dodge(width = 0.8), size = 2.5, alpha = 0.5) +
  scale_y_continuous(limits = c(-0.015, 0.1), breaks = seq(0, 0.1, by = 0.02)) + 
  labs(x = "", y = "Increment over CLINICAL", color = NULL) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        panel.border = element_blank(),  
        axis.line.x = element_line(linewidth = 1),  
        axis.line.y = element_line(linewidth = 1),  
        axis.ticks = element_line(linewidth = 1),  
        axis.text.x = element_text(color = "black", size = 15),  
        axis.text.y = element_text(color = "black", size = 15),  
        axis.title = element_text(color = "black", size = 15),  
        axis.ticks.length = unit(0.15, "cm"),  
        legend.position = "top",  
        # legend.justification = "left",
        # legend.direction = "vertical",
        legend.text = element_text(size = 15),
        plot.margin = margin(r = 20, l = 10),
        aspect.ratio = 0.85
  ) + 
  geom_text(data = p_values, aes(label = value, y = 0.1, x=c(0.8,1.82,1.22,2.22)), size = 5, vjust = 0, 
            position = position_dodge(width = 0.8), color = "black") +
  coord_cartesian(clip = "off")
```

