---
title: "Figure7"
format: html
editor: visual
---

## Figure 7

### Boot-up

```{r}
library(tidyr)
library(readr)
library(dplyr)
library(tibble)
library(ggplot2)
library(data.table)
library(viridis)
library(rstatix)
library(ggpubr)
out_dir <- "../output/"
TrajGrpCol <- c("1" = "#639A21", "2" = "#39828C", "3" = "#6371AD", "4" = "#BD7D31", "5" = "#9C3418")
PROGrpCol <- c("minimal" = "#999999", "physical" = "#58B5EA", "cognitive" = "#EAAE2A", "global" = "#FF1820")
comb_data <- read_csv("/scratch/metagenomics/viral_reactivation/full_comb_data.csv") %>% select(-1) %>%
  select(-starts_with("Human betaherpesvirus 6"),
         -starts_with("Human gammaherpesvirus 8"),
         -starts_with("Human betaherpesvirus 7"),
         -starts_with("Respiratory syncytial virus"),
         -starts_with("Human immunodeficiency virus 1"),
         -starts_with("SARS-CoV-2.pbmc"),
         -starts_with("Enterovirus.ea"),
         -starts_with("Enterovirus.pbmc"),
         -starts_with("Anelloviridae.ea"),
         -starts_with("Anelloviridae.nasal"),
         -starts_with("Human alphaherpesvirus 1 (HSV1).pbmc"),
         -starts_with("Human alphaherpesvirus 2 (HSV2).pbmc"),
         -ends_with(".ea")) %>%
  dplyr::rename("Betacoronavirus.nasal" = "SARS-CoV-2.nasal")


data_env <- readRDS("/scratch/metagenomics/viral_reactivation/2024-02-02_obj.RDS")
clinical_data <- data_env$clinical_data
rm(data_env)

clinical_data_ext <- read_csv("/data/clinical/current/2023-01-01-locked/2023-01-01-impacc-clin-individ-supp-locked.csv")
```

### PASC Survey Responses

```{r}
## Load in necessary data
pro_symptoms <- read_csv("~/git_clones/impacc-public-code/convalescent_manuscript/impacc-convalescent.csv") %>%
  mutate(conv_cluster6 = ifelse(is.na(conv_cluster6), "non-PRO", ifelse(conv_cluster6 %in% c(1,3,4),
                                "minimal",
                                ifelse(conv_cluster6 %in% c(2), "physical", ifelse(conv_cluster6 == 5, "cognitive",
                                                                                   ifelse(conv_cluster6 == 6, "global", "Error")))))) %>%
  mutate(PASC_status = ifelse(conv_cluster6 == "minimal", "PRO Minimal", "PRO PASC Group"))
pro_grouped_symptoms <- read_csv("~/git_clones/impacc-public-code/convalescent_manuscript/impacc_conv_symptoms.csv")

pro_df <- pro_symptoms %>%
  left_join(pro_grouped_symptoms) %>%
  select(-2)

```

## Panel A

```{r}
library(aplot)
library(rstatix)
library(ordinal)

ever_reactivate <- comb_data %>%
  pivot_longer(cols = -event_id) %>%
  left_join(clinical_data %>% select(event_id, participant_id,
                                     event_type, event_date)) %>%
  group_by(participant_id, name) %>%
  ## Acute samples only
  filter(event_type %in% paste0("Visit ", 1:6)) %>%
  filter(event_date <= 40) %>%
  dplyr::summarize(max = max(value, na.rm = TRUE)) %>%
  filter(max != -Inf) %>%
  mutate(binary = ifelse(max > 0, 1, 0)) %>%
  filter(!grepl("Betaco", name)) 

ever_reactivate_neg <- ever_reactivate %>%
  group_by(participant_id) %>%
  dplyr::summarize(binary = sum(binary)) %>%
  filter(binary == 0) %>%
  mutate(binary = 1, max = 1) %>%
  mutate(name = "Virus Negative")

graph_data <- plyr::rbind.fill(ever_reactivate, ever_reactivate_neg) %>%
  left_join(clinical_data %>% distinct(participant_id, trajectory_group)) %>%
  left_join(pro_symptoms %>% distinct(participant_id,conv_cluster6)) %>%
  filter(binary == 1) %>%
  filter(!grepl(".ea", name)) %>%
  filter(!name %in% c("Simplexvirus.pbmc",
                      "Human betaherpesvirus 5 (CMV).nasal",
                      "CMV.nasal")) %>%
  group_by(name, conv_cluster6) %>%
  filter(!is.na(conv_cluster6)) %>%
  dplyr::summarize(count = n()) %>%
  mutate(freq = count / sum(count) * 100) %>%
  mutate(conv_cluster6 = factor(conv_cluster6)) %>%
   mutate(name = gsub(".*\\(", "", gsub("\\)", "", name))) %>%
  ungroup()
order <- c("Virus Negative","Enterovirus.nasal", "HSV1.nasal", "HSV2.nasal", "EBV.nasal",
           "EBV.pbmc", "CMV.pbmc", "Anelloviridae.pbmc")
gga <- graph_data %>%
  mutate(conv_cluster6 = factor(conv_cluster6, c("minimal", "cognitive", "physical", "global"))) %>%
  mutate(label = paste0("n=", count, "\n(", round(freq, 1), "%)")) %>%
  ggplot(aes(y=freq, x=name, fill = conv_cluster6)) +
  geom_bar(stat = "identity", position = "stack", aes()) +
  geom_text(aes(label = label), position = position_stack(vjust = 0.5, reverse = FALSE), size = 2) +
  theme_classic() + scale_x_discrete(limits = order) +
  #scale_fill_manual(values = TrajGrpCol, name = "Trajectory Group") +
  xlab("Virus and Compartment") +
  ylab("Percent of Participants (%)") +
  theme(axis.text = element_text(color="black"),
        legend.position = "top", #legend.direction = "horizontal",
        legend.direction = "horizontal",
        axis.ticks = element_line(color = "black")) +
  scale_fill_manual(values = PROGrpCol, name = "PRO Groups",
                     guide = guide_legend(reverse = TRUE)) +
  coord_flip()  +
  geom_hline(yintercept = 38.7, linetype = "dashed", alpha = 0.3)
## 5x3
gga
ggsave(paste0(out_dir, "Figure7A.pdf"), width = 5, height = 3)
write_csv(gga$data, paste0(out_dir, "source_data_Figure7A.csv"))
```

```{r}

ever_reactivate <- comb_data %>%
  pivot_longer(cols = -event_id) %>%
  left_join(clinical_data %>% select(event_id, participant_id,
                                     event_type, event_date)) %>%
  group_by(participant_id, name) %>%
  filter(event_date <= 40) %>%
  filter(event_type %in% paste0('Visit ', 1:6)) %>%
  dplyr::summarize(max = max(value, na.rm = TRUE)) %>%
  filter(max != -Inf) %>%
  mutate(binary = ifelse(max > 0, 1, 0)) %>%
  filter(!grepl("Betaco", name)) 

ever_reactivate_neg <- ever_reactivate %>%
  group_by(participant_id) %>%
  dplyr::summarize(binary = sum(binary)) %>%
  filter(binary == 0) %>%
  mutate(binary = 1, max = 1) %>%
  mutate(name = "Virus Negative")

graph_data <- plyr::rbind.fill(ever_reactivate, ever_reactivate_neg) %>%
  left_join(clinical_data %>% distinct(participant_id, trajectory_group)) %>%
  left_join(pro_symptoms %>% distinct(participant_id,conv_cluster6)) %>%
  mutate(conv_cluster6 = ifelse(conv_cluster6 != "minimal", "PASC", conv_cluster6)) %>%
  filter(binary == 1) %>%
  filter(!grepl(".ea", name)) %>%
  filter(!name %in% c("Simplexvirus.pbmc",
                      "Human betaherpesvirus 5 (CMV).nasal",
                      "CMV.nasal")) %>%
  group_by(name, conv_cluster6) %>%
  filter(!is.na(conv_cluster6)) %>%
  dplyr::summarize(count = n()) %>%
  mutate(freq = count / sum(count) * 100,
         total = sum(count)) %>%
  mutate(conv_cluster6 = factor(conv_cluster6)) %>%
   mutate(name = gsub(".*\\(", "", gsub("\\)", "", name))) %>%
  ungroup()

## Association Testing
stat.df <- data.frame()
for(active_virus in unique(graph_data$name)[-8]){
  tmp.chi <- graph_data %>%
    filter(!is.na(conv_cluster6)) %>%
    filter(name %in% c(active_virus, "Virus Negative")) %>%
    ungroup() %>%
    pivot_wider(names_from = conv_cluster6, values_from = count,
                id_cols = name) %>%
    column_to_rownames("name")

  stat.df <- rbind.data.frame(stat.df, chisq_test(tmp.chi) %>% mutate(name = active_virus))
}
stat.df <- stat.df %>%
  ungroup() %>%
  mutate(p.value = p) %>%
  mutate(p.adj = p.adjust(p.value, "fdr")) %>%
  add_significance("p.adj")

write_csv(stat.df, paste0(out_dir, "Supplemental_Data_6_part1.csv"))
```

## Panel B

```{r, fig.width = 5.5, fig.height = 2.5}
library(lme4)
ever_reactivate <- comb_data %>%
  pivot_longer(cols = -event_id) %>%
  left_join(clinical_data %>% select(event_id, participant_id, event_date)) %>%
  filter(event_date > 60) %>%
  group_by(participant_id, name) %>%
  dplyr::summarize(max = max(value, na.rm = TRUE)) %>%
  filter(max != -Inf) %>%
  mutate(binary = ifelse(max > 0, 1, 0)) %>%
  filter(!grepl("Betaco|CMV).nasal|Simplexvirus.pbmc|CMV).pbmc", name)) %>%
  filter(grepl("Anelloviridae.pbmc|Enterovirus.nasal", name))


graph_data <- ever_reactivate %>%
  filter(!grepl(".ea", name)) %>%
  left_join(clinical_data %>% distinct(participant_id, trajectory_group)) %>%
   left_join(pro_symptoms %>% distinct(participant_id,conv_cluster6)) %>%
  group_by(conv_cluster6, name) %>%
  dplyr::summarize(freq = mean(binary) * 100,
                   count = n()) %>%
  filter(count > 10) %>%
  mutate(conv_cluster6 = factor(conv_cluster6)) %>%
   mutate(name = gsub(".*\\(", "", gsub("\\)", "", name))) %>%
  ungroup() %>%
  complete(conv_cluster6, name) %>%
  mutate(freq = ifelse(is.na(freq), 0, freq),
         count = ifelse(is.na(count), 0, count)) %>%
  mutate(positive = freq * count / 100) %>%
  group_by(name) %>%
  mutate(pos_freq = positive / sum(positive) *100)

## Association Testing
stat.df <- data.frame()
stat.df.glm <- data.frame()
for(active_virus in unique(graph_data$name)){
  tmp.chi <- graph_data %>%
    filter(!is.na(conv_cluster6)) %>%
    filter(name == active_virus) %>%
    ungroup() %>%
    mutate(negative = count - positive) %>%
    select(conv_cluster6, positive, negative) %>%
    column_to_rownames("conv_cluster6")

  stat.df <- rbind.data.frame(stat.df, chisq_test(tmp.chi) %>% mutate(name = active_virus))
  
  model_df <- ever_reactivate %>%
  filter(!grepl(".ea", name)) %>%
  left_join(clinical_data %>% distinct(participant_id, trajectory_group,
                                       discretized_admit_age_quantile, sex,
                                       enrollment_site)) %>%
   left_join(pro_symptoms %>% distinct(participant_id,conv_cluster6)) %>%
  filter(name == active_virus )

  ## Now fit a glmer to also regress trajectory group, sex, admit age, and whether on immunosupressive therapies
fit <- glmer(conv_cluster6 ~ ever_immsupp + binary + trajectory_group + sex + discretized_admit_age_quantile + (1|enrollment_site),
           data = model_df %>%
      left_join(clinical_data_ext %>% distinct(participant_id, ever_immsupp)) %>%
        mutate(conv_cluster6 = factor(conv_cluster6),
               ever_immsupp = factor(ever_immsupp),
               binary = factor(binary)) %>%
        filter(!is.na(binary)) %>%
        filter(!is.na(ever_immsupp)) %>%
        filter(!is.na(conv_cluster6)) %>% as.data.frame(), family = "binomial")

stat.df.glm <- rbind.data.frame(stat.df.glm,
                                as.data.frame(car::Anova(fit, type = "III")) %>%
                                  rownames_to_column("feature") %>%
                                  mutate(virus = active_virus))
}

stat.df <- stat.df %>%
  mutate(p.value = p) %>%
  mutate(p.adj = p.adjust(p.value, "fdr")) %>%
  add_significance("p.adj") %>%
  mutate(xpos = 2:1) %>%
  mutate(group1 = "filler_text", group2 = "variable") %>%
  mutate(y.position = 40)
write.csv(stat.df, paste0(out_dir, "Supplemental_Data_6_part2.csv"))

stat.df.glm
write.csv(stat.df.glm, paste0(out_dir, "Supplemental_Data_6_part3.csv"))

stat.df.glm.adj <- stat.df.glm %>%
  filter(feature == "binary") %>%
  mutate(p.value = `Pr(>Chisq)`) %>%
  mutate(p.adj = p.adjust(p.value, "fdr")) %>%
  add_significance("p.adj") %>%
  mutate(xpos = 2:1) %>%
  mutate(group1 = "filler_text", group2 = "variable") %>%
  mutate(y.position = 40)
write.csv(stat.df.glm.adj, paste0(out_dir, "Supplemental_Data_6_part4.csv"))

## Add star manually
ggb <- graph_data %>%
  filter(!is.na(conv_cluster6)) %>%
  mutate(label = paste0(positive, "/", count,"  ", round(freq, 1), "%")) %>%
  mutate(conv_cluster6 = factor(conv_cluster6, levels = c("minimal", "cognitive", "physical", "global"))) %>%
  ggplot(aes(x=name, y=freq)) +
  geom_bar(stat = "identity", position = position_dodge(preserve = "single"), aes(fill = conv_cluster6)) +
  geom_text(aes(label = label, fill = conv_cluster6), position = position_dodge(width = .9), hjust = 0.45, size = 3) +
  theme_classic() + scale_x_discrete(limits = rev(unique(graph_data$name))) +
  scale_fill_manual(values = TrajGrpCol, name = "Trajectory Group") +
  xlab("Virus and Compartment") +
  ylab("Percent of participants with\nVirus Detected in at Least One Convalescent Sample") +
    coord_flip(ylim = c(0, 35)) +
  scale_fill_manual(values = PROGrpCol, name = "PRO Groups") +
  theme(
        axis.text = element_text(color="black"),
        axis.ticks = element_line(color = "black")) 
ggb
ggsave(paste0(out_dir, "Figure7B.pdf"), width = 5, height = 3)
write_csv(ggb$data, paste0(out_dir, "source_data_Figure7B.csv"))
```

## Supplemental Figure 11

### Panel S11A

```{r}
library(aplot)
library(rstatix)
library(ordinal)

ever_reactivate <- comb_data %>%
  pivot_longer(cols = -event_id) %>%
  left_join(clinical_data %>% select(event_id, participant_id,
                                     event_type, event_date)) %>%
  group_by(participant_id, name) %>%
  filter(event_date <= 40) %>%
  filter(event_type %in% paste0("Visit ", 1:6)) %>%
  dplyr::summarize(max = max(value, na.rm = TRUE)) %>%
  filter(max != -Inf) %>%
  mutate(binary = ifelse(max > 0, 1, 0)) %>%
  filter(!grepl("Betaco", name)) 

ever_reactivate_neg <- ever_reactivate %>%
  group_by(participant_id) %>%
  dplyr::summarize(binary = sum(binary)) %>%
  filter(binary == 0) %>%
  mutate(binary = 1, max = 1) %>%
  mutate(name = "Virus Negative")

graph_data <- rbind.data.frame(ever_reactivate, ever_reactivate_neg) %>%
  left_join(clinical_data %>% distinct(participant_id, trajectory_group,
                                       diedever, death_date)) %>%
  left_join(pro_symptoms %>% distinct(participant_id,PASC_status)) %>%
  filter(binary == 1) %>%
  filter(!grepl(".ea", name)) %>%
  filter(!name %in% c("Simplexvirus.pbmc",
                      "Anelloviridae.nasal",
                      "Human betaherpesvirus 5 (CMV).nasal",
                      "CMV.nasal")) %>%
  mutate(PASC_status = ifelse(is.na(PASC_status),
                              ifelse(!is.na(death_date),
                                "Died", "Non-responders"), PASC_status)) %>%
  group_by(name, PASC_status) %>%
  filter(!is.na(PASC_status)) %>%
  dplyr::summarize(count = n()) %>%
  mutate(freq = count / sum(count) * 100) %>%
  mutate(PASC_status = factor(PASC_status)) %>%
   mutate(name = gsub(".*\\(", "", gsub("\\)", "", name))) %>%
  ungroup()


p_values <- c()
for(i in unique(graph_data$name)[c(-4,-8)]){
  tmp <- graph_data %>% filter(name %in% c(i, "Virus Negative"))
  tmp_table <- matrix(unlist(c(tmp[3,3]+tmp[4,3], tmp[2,3],
                        tmp[7,3]+tmp[8,3], tmp[6,3])), nrow = 2, ncol = 2)
  rownames(tmp_table) <- c("Responders", "Non-Responders")
  colnames(tmp_table) <- c("Virus Pos", "Virus Neg")
  p_values <- c(p_values, chisq.test((tmp_table))$p.value)
  names(p_values)[length(p_values)] <- i
}
print(p.adjust(p_values, "fdr"))
p_df <- as.data.frame(p_values) %>%
  mutate(p.adj = p.adjust(p_values, "fdr")) %>%
              rownames_to_column("name") %>%
              mutate(p_values = formatC(p_values, format = "e", digits = 2))
write_csv(p_df, paste0(out_dir, "Supplemental_Data_6_part5.csv"))                     
ggS11A <- graph_data %>%
  mutate(PASC_status = factor(PASC_status, levels = c("PRO Minimal", "PRO PASC Group", "Non-responders", "Died"))) %>%
  mutate(label = paste0("n=", count, "\n(", round(freq, 1), "%)")) %>%
  group_by(name) %>%
  mutate(total = sum(count),
         freq_dec = freq / 100) %>%
  rowwise() %>%
  mutate(margin = qnorm(0.975)*sqrt(freq_dec*(1-freq_dec)/total)) %>%
  mutate(lowerCI = freq - (margin * 100)) %>%
  mutate(upperCI = freq + (margin * 100)) %>%
  ggplot(aes(y=freq, x=name, fill = PASC_status)) +
  geom_bar(stat = "identity", position = "stack", aes()) +
  geom_text(aes(label = label), position = position_stack(vjust = 0.5, reverse = FALSE),
            size = 3) +
  theme_classic() + scale_x_discrete(limits = rev(unique(graph_data$name))) +
  xlab("Virus and Compartment") +
  ylab("Percent of Participants (%)") +
  theme(axis.text = element_text(color="black"),
        legend.position = "top",
        legend.direction = "vertical",
        axis.ticks = element_line(color = "black")) +
  scale_fill_manual(values = c("lightgray","dodgerblue",  "#737272", "#fc5e5e"), "PRO") +
  # geom_text(inherit.aes = F, data = p_df,
  #           aes(x=name, label = p_values), y= 107, size = 3) +
  # geom_text(label = "Response Bias\np.adj", y=107, x=9, size = 3) +
  coord_flip(clip = "off",ylim = c(0,110)) +
  scale_y_continuous(breaks = seq(0,100,by=20))

```

### Panel S11B

```{r}

ever_reactivate <- comb_data %>%
  pivot_longer(cols = -event_id) %>%
  left_join(clinical_data %>% select(event_id, participant_id, event_type,
                                     event_date)) %>%
  filter(event_date <= 40) %>%
  filter(event_type %in% paste0("Visit ", 1:6)) %>%
  group_by(participant_id, name) %>%
  dplyr::summarize(max = max(value, na.rm = TRUE)) %>%
  filter(max != -Inf) %>%
  mutate(binary = ifelse(max > 0, 1, 0)) %>%
  filter(!grepl("Betaco|CMV).nasal|Simplexvirus.pbmc|CMV).pbmc|Anelloviridae.nasal", name)) 


graph_data <- ever_reactivate %>%
  filter(!grepl(".ea", name)) %>%
  left_join(clinical_data %>% distinct(participant_id, trajectory_group)) %>%
   left_join(pro_symptoms %>% distinct(participant_id,conv_cluster6)) %>%
  group_by(conv_cluster6, name) %>%
  dplyr::summarize(freq = mean(binary) * 100,
                   count = n()) %>%
  filter(count > 10) %>%
  mutate(conv_cluster6 = factor(conv_cluster6)) %>%
   mutate(name = gsub(".*\\(", "", gsub("\\)", "", name))) %>%
  ungroup() %>%
  complete(conv_cluster6, name) %>%
  mutate(freq = ifelse(is.na(freq), 0, freq),
         count = ifelse(is.na(count), 0, count)) %>%
  mutate(positive = freq * count / 100) %>%
  group_by(name) %>%
  mutate(pos_freq = positive / sum(positive) *100)

## Acute Chronic Virus with PRO Group Association
stat.df <- data.frame()
for(active_virus in unique(graph_data$name)){
  tmp.chi <- graph_data %>%
    filter(!is.na(conv_cluster6)) %>%
    filter(name == active_virus) %>%
    ungroup() %>%
    mutate(negative = count - positive) %>%
    select(conv_cluster6, positive, negative) %>%
    column_to_rownames("conv_cluster6")

  stat.df <- rbind.data.frame(stat.df, chisq_test(tmp.chi) %>% mutate(name = active_virus))
}

stat.df <- stat.df %>%
  mutate(p.value = p) %>%
  mutate(p.adj = p.adjust(p.value, "fdr")) %>%
  add_significance("p.adj") %>%
  mutate(xpos = 6:1) %>%
  mutate(group1 = "filler_text", group2 = "variable") %>%
  mutate(y.position = 40)
write.csv(stat.df, paste0(out_dir, "Supplemental_data_6_part6.csv"))


ggS11B <- graph_data %>%
  mutate(conv_cluster6 = as.character(conv_cluster6)) %>%
  mutate(conv_cluster6 = ifelse(is.na(conv_cluster6), "non-responder", conv_cluster6)) %>%
  mutate(label1 = paste0(positive, "/", count)) %>%
  mutate(label2 = paste0(round(freq, 1), "%")) %>%
  mutate(conv_cluster6 = factor(conv_cluster6, levels = c("non-responder", "minimal", "cognitive", "physical", "global"))) %>%
  ggplot(aes(x=name, y=freq)) +
  geom_bar(stat = "identity", position = position_dodge(preserve = "single"), aes(fill = conv_cluster6)) +
  geom_text(aes(label = label1, fill = conv_cluster6),
            position = position_dodge(width = .9), hjust = 1.3, size = 3) +
  geom_text(aes(label = label2, fill = conv_cluster6),
            position = position_dodge(width = .9), hjust = -0.10, size = 3) +
  theme_classic() + scale_x_discrete(limits = rev(unique(graph_data$name))) +
  xlab("Virus and Compartment") +
  ylab("Percent of Participants (%)") +
    coord_flip(ylim = c(0,35)) +
  scale_fill_manual(values = c("non-responder" = "#737272", PROGrpCol), name = "PRO Groups") +
  theme(
        axis.text = element_text(color="black"),
        axis.ticks = element_line(color = "black"))
```

### Panel S11C

```{r}

graph_data <- comb_data %>%
  pivot_longer(cols = -event_id) %>%
  filter(name == "Anelloviridae.pbmc") %>%
  filter(!is.na(value)) %>%
  left_join(clinical_data %>% distinct(event_id, participant_id, event_type)) %>%
  mutate(binary = ifelse(value > 0, 1, 0)) %>%
  distinct() %>%
  filter(event_type %in% paste0("Visit ", 7:10)) %>%
  left_join(pro_symptoms %>% distinct(participant_id,conv_cluster6)) %>%
  group_by(event_type, conv_cluster6, name) %>%
  dplyr::summarize(freq = mean(binary) * 100,
                   count = n()) %>%
  filter(count > 10) %>%
  mutate(conv_cluster6 = factor(conv_cluster6)) %>%
   mutate(name = gsub(".*\\(", "", gsub("\\)", "", name))) %>%
  ungroup() %>%
  complete(event_type, conv_cluster6, name) %>%
  mutate(freq = ifelse(is.na(freq), 0, freq),
         count = ifelse(is.na(count), 0, count)) %>%
  mutate(positive = freq * count / 100) %>%
  group_by(name) %>%
  mutate(pos_freq = positive / sum(positive) *100)

ggS11C <- graph_data %>%
  filter(name == "Anelloviridae.pbmc") %>%
  mutate(conv_cluster6 = factor(conv_cluster6)) %>%
  filter(!is.na(conv_cluster6)) %>%
  mutate(label = paste0(positive, "/", count, "  ", round(freq, 1), "%")) %>%
  mutate(label1 = paste0(positive, "/", count)) %>%
  mutate(label2 = paste0(round(freq, 1), "%")) %>%
  ggplot(aes(x=event_type, y=freq)) +
  geom_bar(stat = "identity", position = position_dodge(preserve = "single"), aes(fill = conv_cluster6)) +
  geom_text(aes(label = label1, fill = conv_cluster6), position = position_dodge(width = .9), hjust = 1.3, size = 3) +
  geom_text(aes(label = label2, fill = conv_cluster6), position = position_dodge(width = .9), hjust = -0.10, size = 3) +
  theme_classic() + scale_x_discrete(limits = rev(paste0("Visit ", 7:10))) +
  scale_fill_manual(values = TrajGrpCol, name = "Trajectory Group") +
  xlab("Visit") +
  ylab(" ") +
    coord_flip() +
  scale_fill_manual(values = PROGrpCol, name = "PRO Groups") +
  theme(
        axis.text = element_text(color="black"),
        axis.ticks = element_line(color = "black")) +
  ggtitle("Anelloviridae.PBMC") +
  labs(subtitle = "By Convalescent Visit Number") +
  ylab("Percent of PBMC Samples Positive\nfor Anelloviridae (%)")

```

### Panel S11D

```{r}
ggS11D <- comb_data %>%
  pivot_longer(cols = -event_id) %>%
  filter(name == "Anelloviridae.pbmc") %>%
  filter(!is.na(value)) %>%
  left_join(clinical_data %>% distinct(event_id, participant_id, event_type)) %>%
  left_join(pro_symptoms) %>%
  filter(event_type %in% paste0("Visit ", 7:10)) %>%
  distinct(conv_cluster6, participant_id, event_type) %>%
  group_by(participant_id, conv_cluster6) %>%
  dplyr::summarize(count = n()) %>% ungroup() %>%
  group_by(conv_cluster6, count) %>%
  dplyr::summarise(count2 = n()) %>%
  mutate(freq = count2 / sum(count2) *100) %>%
  filter(!is.na(conv_cluster6)) %>%
  mutate(conv_cluster6 = stringr::str_to_title(conv_cluster6)) %>%
  mutate(count = factor(count)) %>%
  ggplot(aes(x=conv_cluster6, y=freq, fill = count)) +
  geom_bar(stat = "identity") +
  theme_classic() +
  ylab("Percent of Participants (%)") +
  xlab("PRO Groups") +
  scale_fill_manual(values = c("#D3CA79", "#EA7300", "#E83F25", "#A62C2C"),
                    name = "Number of Convalescent Samples") +
  theme(axis.text = element_text(color = "black"),
        axis.ticks = element_line(color = "black"))
ggS11D
```

### Panel S11E

```{r, fig.width = 9, fig.height = 2.5}

ggS11E <- comb_data %>%
  pivot_longer(cols = -event_id) %>%
  filter(name == "Anelloviridae.pbmc") %>%
  filter(!is.na(value)) %>%
  left_join(clinical_data %>% distinct(event_id, participant_id, event_type)) %>%
  left_join(pro_symptoms) %>%
  filter(event_type %in% paste0("Visit ", 7:10)) %>%
  distinct(conv_cluster6, participant_id, event_type, value) %>%
  group_by(participant_id, conv_cluster6)  %>%
  mutate(event_type = factor(event_type, levels = paste0("Visit ", 7:10))) %>%
  filter(!is.na(conv_cluster6)) %>%
  mutate(conv_cluster6 = stringr::str_to_title(conv_cluster6)) %>%
  ggplot(aes(x=event_type, y=value, color = conv_cluster6)) +
  geom_point() +
  geom_line(aes(group = participant_id), alpha = 0.3) +
  theme_classic() +
  ylab("Reads per Million of Anelloviridae (RPM)") +
  scale_y_continuous(trans='log10') +
  xlab("PRO Groups") +
  scale_color_manual(values = unname(PROGrpCol)[c(3,4,1,2)],
                    name = "Convalescent Visit") +
  theme(axis.text = element_text(color = "black"),
        axis.ticks = element_line(color = "black")) +
  facet_grid(~conv_cluster6)
ggS11E
ggsave(paste0(out_dir, "FigureS11E.pdf"), width =9, height = 2.5)
write.csv(ggS11E$data %>%
            select(-participant_id) %>%
            mutate(participant_id = .group), paste0(out_dir, "source_data_FigureS11E.csv"))

```

### Figure arrangement

```{r, fig.width = 11, fig.height = 8}

ggarrange(ggS11A, ggS11B, ggS11C, ggS11D, nrow = 2, ncol =2, labels = "AUTO",font.label = list(size = 18), heights = c(1.3, 1))
ggsave(paste0(out_dir, "FigureS11.pdf"), width = 11, height = 8)

write_csv(ggS11A$data, paste0(out_dir, "source_data_FigureS11A.csv"))
write_csv(ggS11B$data, paste0(out_dir, "source_data_FigureS11B.csv"))
write_csv(ggS11C$data, paste0(out_dir, "source_data_FigureS11C.csv"))
write_csv(ggS11D$data, paste0(out_dir, "source_data_FigureS11D.csv"))
```

# Session Info

```{r}
sessionInfo()
```
