---
title: "Transplant CyTOF"
output: html_document
date: "2024-01-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(patchwork)
library(gamm4)


my.theme <- theme_classic() + 
  theme(
    plot.title = element_text(hjust = 0.5, size=12, face="plain"),
    axis.text = element_text(size=12, color="black"),
    text = element_text(size=12, family="Arial"),
    plot.margin = unit(c(0,1,1,0), "cm")
  )

```

# Data import

## Clinical metadata

```{r}
# Patient metadata
clin.individ <- read.csv(
  "/data/clinical/current/2023-01-01-locked/2023-01-01-impacc-clin-individ-locked.csv",
  header = TRUE)

# Sample
clin.sample <- read.csv(
  "/data/clinical/current/2023-01-01-locked/2023-01-01-impacc-clin-sample-locked.csv",
  header = TRUE)

# Event
clin.event <- read.csv(
  "/data/clinical/current/2023-01-01-locked/2023-01-01-impacc-clin-event-locked.csv",
  header = TRUE)
```

Merge metadata

```{r}
# Combine sample and event metadata
clin.sample.event <- merge(
  clin.sample, clin.event,
  by = "event_id",
  all.x = TRUE, all.y = FALSE,
  suffixes = c("",".y"),
  sort = FALSE
)

# Add patient metadata
clin.sample.event.individ <- merge(
  clin.sample.event, clin.individ,
  by = "participant_id", all = FALSE, sort = FALSE
)
```

Manually correct some typos.

```{r}
# Correct the symptom_date of patient 008-0103: change from -376 to -13 (confirmed with data management team)
clin.sample.event.individ[clin.sample.event.individ$participant_id=="008-0103","symptom_date"] <- -13

# Correct event_date of 004-0012-8: change from 2 to 32 (it's 32 in 2021-11-11-frozen data)
clin.sample.event.individ[clin.sample.event.individ$event_id=="004-0012-8","event_date"] <- 32
```

## Transplant metadata 

264 patients included in transplant study (use new metadata table that Harry will share)

```{r}
transplant <- read.delim(
  "/scratch/immunosuppression/2023.03.09_txcasecontrol.txt",
  header = TRUE)
newTG <- read.delim(
  "/scratch/immunosuppression/2023.10.03_new_tgroups.txt",
  header = TRUE)

# Merge new TG assignment
transplant <- merge(
  transplant, newTG,
  by="studyid", all=FALSE
)

# Format factor
transplant$transplant_final <- as.factor(transplant$transplant_final)

```

Remove BMT patients and their controls.

```{r}
transplant <- transplant %>%
  subset(!(studyid %in% c("002-0022","007-0008","001-0013","010-0009","004-0041","005-0047")))

```

Only keep transplant patients in the clinical metadata

```{r}
clin.sample.event.individ <- merge(
  clin.sample.event.individ[,c("participant_id","event_id","sample_id","event_date","event_type","event_location","respiratory_status")], 
  transplant,
  by.x="participant_id", by.y="studyid",
  all=FALSE
)

```

## Import
```{r}
#CyTOF data
cytof <- read.csv("/data/bld-cytof/current/bld-cytof-Counts.csv",
  header = TRUE, row.names = 1
)
#metadata
cytof.metadata <- read.csv("/data/bld-cytof/current/bld-cytof-Metadata.csv",
  header = TRUE, row.names = 1
)

# Only keep samples that pass QC
cytof.metadata <- subset(cytof.metadata, sample_status=="IMPACC sample assayed and passed QC")
clin.sample.event.individ <- clin.sample.event.individ %>%
  subset(sample_id %in% rownames(cytof.metadata))
```

```{r}
# Filter cytof data to samples of interest
cytof <- cytof[clin.sample.event.individ$sample_id,]
```

## Import viral load data

```{r}
# mNGS metadata
mngs.metadata <- read.csv(
  # "/data/nasal-metagenomics/current/nasal-metagenomics-Metadata.csv",
  "/data/nasal-metagenomics/legacy/2022-09-03/nasal-metagenomics-Metadata.csv",
  header = TRUE, row.names = NULL,
  check.names = FALSE
)

mngs.metadata <- mngs.metadata %>%
  filter(!is.na(sc2_rpm))

# mNGS QC
mngs.metadata <- mngs.metadata %>%
  filter(sample_status == "IMPACC sample assayed and passed QC")
```

```{r}
# Reformat visit_num: decapitalize "VISIT"
mngs.metadata$visit_num <- gsub(
  "^VISIT", "Visit", mngs.metadata$visit_num
)

# Merge with sample metadata
clin.sample.event.individ <- merge(
  clin.sample.event.individ, mngs.metadata[,c("participant_id","visit_num","sc2_rpm")],
  by.x=c("participant_id","event_type"), by.y=c("participant_id","visit_num"),
  all.x=TRUE, all.y=FALSE # keep samples that don't pass SARS-CoV-2 metatranscriptomics QC
  # all=FALSE # discard samples that don't pass SARS-CoV-2 metatranscriptomics QC <<< do NOT do this
)

# log-transform viral load
clin.sample.event.individ$sc2_rpm_log10 <- log10(clin.sample.event.individ$sc2_rpm+1)
```

# Analysis: Visit 1 only
```{r}
# Sample metadata
clin.sample.event.individ.visit1 <- clin.sample.event.individ %>%
  subset(event_type == "Visit 1")

# Subset cytof data
cytof.visit1 <- cytof[clin.sample.event.individ.visit1$sample_id,]

#remove debris and multiplets
cytof.visit1.sub=cytof.visit1[,-c(32:34,54:63,65,66,41:46)]

#convert count to %
cytof.visit1.sub.pct=cytof.visit1.sub/rowSums(cytof.visit1.sub,na.rm=T)*100

#add minimum per cell-type and log-transform
cytof.visit1.final=cytof.visit1.sub.pct
for(i in 1:ncol(cytof.visit1.sub.pct)){
  cytof.visit1.final[,i]=log2(cytof.visit1.sub.pct[,i]+min(cytof.visit1.sub.pct[which(cytof.visit1.sub.pct[,i]>0),i]))
}

```

```{r}
#run regression
res.cytof <- data.frame(matrix(NA, nrow=ncol(cytof.visit1.final), ncol=4))
colnames(res.cytof) <- c("variable","slope","PVal","adj.PVal")
rownames(res.cytof) <- colnames(cytof.visit1.final)
res.cytof$variable <- rownames(res.cytof)
for (i in rownames(res.cytof)) {
temp <- data.frame(conc=cytof.visit1.final[,i],
tx=clin.sample.event.individ.visit1$transplant_final) %>%
subset(!is.na(conc))
my.lm <- lm(conc ~ tx, data=temp)
res.cytof[i,"slope"] <- summary(my.lm)$coefficients["tx1",1]
res.cytof[i,"PVal"] <- summary(my.lm)$coefficients["tx1",4]
remove(temp, my.lm)
}
res.cytof$adj.PVal <- p.adjust(res.cytof$PVal, method = "BH")


#read-in uncorrected CyTOF population names and add to table
tmp <- read.csv("/data/bld-cytof/current/bld-cytof-Counts.csv",
  header = TRUE, row.names = 1,check.names = F
)
res.cytof$nam=colnames(tmp)[-c(32:34,54:63,65,66,41:46)]

#subset to unadjusted significant results
res.cytof.sub=res.cytof[res.cytof$PVal<0.05,]

#plot as barplot/Figure 3A
ggplot(data=res.cytof.sub, 
             aes(x=slope, y=reorder(nam, slope, FUN = function(x) x[1]))) +
  geom_col(aes(color=as.factor(slope>0)), fill=NA, width=0.7) +
  geom_col(
    data=. %>% subset(adj.PVal<0.05),
    aes(fill=as.factor(slope>0)), width=0.7) +
  geom_vline(xintercept = 0, size = 0.4, color = "black") +
  #geom_text(
    #data=. %>% subset(slope>0),
    #aes(x=0,label=sprintf("P = %.1e", adj.PVal)), 
    #hjust=1.06, size=2.8) +
  #geom_text(
   # data=. %>% subset(slope<0),
    #aes(x=0, label=sprintf("P = %.1e", adj.PVal)),
    #hjust=-0.06, size=2.8) +
  labs(x="Increase in frequency (z-score)", y="",
       title="Differential CyTOF populations at Visit 1") +
  scale_x_continuous(
    limits=c(-2.5,2.5), expand=c(0,0)) +
  scale_color_manual(values=c("TRUE"="orange","FALSE"="cornflowerblue"),
                     guide="none") +
  scale_fill_manual(values=c("TRUE"="orange","FALSE"="cornflowerblue"),
                    guide="none") +
  #facet_wrap(~ control) + # separate into 2 panels: Yes/No w.r.t. controlling for viral load
  theme_bw() + theme(
    plot.title = element_text(hjust = 0.5, size=12, face="plain"),
    axis.text.x = element_text(size=11, color="black"),
    axis.text.y = element_text(size=11, color="black"),
    text = element_text(size=12, family="Arial"),
    plot.margin = unit(c(0,1,1,0), "cm"),
    panel.grid.minor=element_blank(),
    panel.spacing = unit(0.9, "cm"),
  )

```

```{r}
#example boxplots/Figure 3B
for(i in which(res.cytof$adj.PVal<0.05)){
par(mar=c(5.1,5.1,4.1,2.1))
boxplot(cytof.visit1.final[,i]~clin.sample.event.individ.visit1$transplant_final,yaxt='n',xaxt='n',border=c("cornflowerblue","orange"),xlab="",ylab="Frequency (%)",las=2,main=res.cytof$nam[i],cex.lab=1.5,cex.main=1.5,cex.axis=1.2,font.main=1,pch="",ylim=c(-9.71,4.28),col="white")
axis(1,at=1:2,labels=c("Control","Transplant"),cex.axis=1.2)
axis(2,at=log2(c(0.001,0.002,0.005,0.01,0.02,0.05,0.1,0.2,0.5,1,2,5,10,20,50)),labels=c(0.001,0.002,0.005,0.01,0.02,0.05,0.1,0.2,0.5,1,2,5,10,20,50),las=2)
stripchart(cytof.visit1.final[clin.sample.event.individ.visit1$transplant_final==0,i]~factor(clin.sample.event.individ.visit1$transplant_final[clin.sample.event.individ.visit1$transplant_final==0]),add=T,vertical=T,method="jitter",pch=20,col="cornflowerblue",at=1)
stripchart(cytof.visit1.final[clin.sample.event.individ.visit1$transplant_final==1,i]~factor(clin.sample.event.individ.visit1$transplant_final[clin.sample.event.individ.visit1$transplant_final==1]),add=T,vertical=T,method="jitter",pch=20,col="orange",at=2)
text(x=1.5,y=0.9*max(cytof.visit1.final[,28],na.rm=T),label=paste0("P=",round(res.cytof$adj.PVal[i],4)),cex=1.5)
}

```

```{r}
#repeat with viral load adjustment
#run regression
res.cytof.vrld <- data.frame(matrix(NA, nrow=ncol(cytof.visit1.final), ncol=4))
colnames(res.cytof.vrld) <- c("variable","slope","PVal","adj.PVal")
rownames(res.cytof.vrld) <- colnames(cytof.visit1.final)
res.cytof.vrld$variable <- rownames(res.cytof.vrld)
for (i in rownames(res.cytof.vrld)) {
temp <- data.frame(conc=cytof.visit1.final[,i],
tx=clin.sample.event.individ.visit1$transplant_final,
vrld=clin.sample.event.individ.visit1$sc2_rpm) %>%
subset(!is.na(conc)|is.na(vrld))
my.lm <- lm(conc ~ tx+vrld, data=temp)
res.cytof.vrld[i,"slope"] <- summary(my.lm)$coefficients["tx1",1]
res.cytof.vrld[i,"PVal"] <- summary(my.lm)$coefficients["tx1",4]
remove(temp, my.lm)
}
res.cytof.vrld$adj.PVal <- p.adjust(res.cytof.vrld$PVal, method = "BH")

#add uncorrected CyTOF population names to table
res.cytof.vrld$nam=colnames(tmp)[-c(32:34,54:63,65,66,41:46)]

#subset to unadjusted significant results
res.cytof.vrld.sub=res.cytof.vrld[res.cytof$PVal<0.05,]

#plot as barplot/Supp. Figure 3
ggplot(data=res.cytof.vrld.sub, 
             aes(x=slope, y=reorder(nam, slope, FUN = function(x) x[1]))) +
  geom_col(aes(color=as.factor(slope>0)), fill=NA, width=0.7) +
  geom_col(
    data=. %>% subset(adj.PVal<0.05),
    aes(fill=as.factor(slope>0)), width=0.7) +
  geom_vline(xintercept = 0, size = 0.4, color = "black") +
  #geom_text(
    #data=. %>% subset(slope>0),
    #aes(x=0,label=sprintf("P = %.1e", adj.PVal)), 
    #hjust=1.06, size=2.8) +
  #geom_text(
   # data=. %>% subset(slope<0),
    #aes(x=0, label=sprintf("P = %.1e", adj.PVal)),
    #hjust=-0.06, size=2.8) +
  labs(x="Increase in frequency (z-score)", y="",
       title="Differential CyTOF populations at Visit 1") +
  scale_x_continuous(
    limits=c(-2.5,2.5), expand=c(0,0)) +
  scale_color_manual(values=c("TRUE"="orange","FALSE"="cornflowerblue"),
                     guide="none") +
  scale_fill_manual(values=c("TRUE"="orange","FALSE"="cornflowerblue"),
                    guide="none") +
  #facet_wrap(~ control) + # separate into 2 panels: Yes/No w.r.t. controlling for viral load
  theme_bw() + theme(
    plot.title = element_text(hjust = 0.5, size=12, face="plain"),
    axis.text.x = element_text(size=11, color="black"),
    axis.text.y = element_text(size=11, color="black"),
    text = element_text(size=12, family="Arial"),
    plot.margin = unit(c(0,1,1,0), "cm"),
    panel.grid.minor=element_blank(),
    panel.spacing = unit(0.9, "cm"),
  )

```

```{r}
##compare CyTOF populations by trajectory group

#make split TG variable
clin.sample.event.individ.visit1$TG45=clin.sample.event.individ.visit1$trajectory_group>3

#run regression for control and tx separately
res.cytof.ctrl <- data.frame(matrix(NA, nrow=ncol(cytof.visit1.final), ncol=4))
colnames(res.cytof.ctrl) <- c("variable","slope","PVal","adj.PVal")
rownames(res.cytof.ctrl) <- colnames(cytof.visit1.final)
res.cytof.ctrl$variable <- rownames(res.cytof.ctrl)
for (i in rownames(res.cytof.ctrl)) {
temp <- data.frame(conc=cytof.visit1.final[,i],
tx=clin.sample.event.individ.visit1$transplant_final,
tg=clin.sample.event.individ.visit1$TG45) %>%
subset(!is.na(conc)&tx==0)
my.lm <- lm(conc ~ tg, data=temp)
res.cytof.ctrl[i,"slope"] <- summary(my.lm)$coefficients["tgTRUE",1]
res.cytof.ctrl[i,"PVal"] <- summary(my.lm)$coefficients["tgTRUE",4]
remove(temp, my.lm)
}
res.cytof.ctrl$adj.PVal <- p.adjust(res.cytof.ctrl$PVal, method = "BH")

res.cytof.tx <- data.frame(matrix(NA, nrow=ncol(cytof.visit1.final), ncol=4))
colnames(res.cytof.tx) <- c("variable","slope","PVal","adj.PVal")
rownames(res.cytof.tx) <- colnames(cytof.visit1.final)
res.cytof.tx$variable <- rownames(res.cytof.tx)
for (i in rownames(res.cytof.tx)) {
temp <- data.frame(conc=cytof.visit1.final[,i],
tx=clin.sample.event.individ.visit1$transplant_final,
tg=clin.sample.event.individ.visit1$TG45) %>%
subset(!is.na(conc)&tx==1)
my.lm <- lm(conc ~ tg, data=temp)
res.cytof.tx[i,"slope"] <- summary(my.lm)$coefficients["tgTRUE",1]
res.cytof.tx[i,"PVal"] <- summary(my.lm)$coefficients["tgTRUE",4]
remove(temp, my.lm)
}
res.cytof.tx$adj.PVal <- p.adjust(res.cytof.tx$PVal, method = "BH")

#combine
res.cytof.ctrl$group="Control"
res.cytof.tx$group="Transplant"
res.cytof.ctrl$nam=colnames(tmp)[-c(32:34,54:63,65,66,41:46)]
res.cytof.tx$nam=colnames(tmp)[-c(32:34,54:63,65,66,41:46)]

res.cytof.merge=rbind(res.cytof.ctrl,res.cytof.tx)
res.cytof.merge.sub=res.cytof.merge[res.cytof.merge$variable%in%res.cytof.ctrl$variable[which(res.cytof.ctrl$adj.PVal<0.05|res.cytof.tx$adj.PVal<0.05)],]

#plot as barplot/Figure 7A
ggplot(data=res.cytof.merge.sub,
aes(x=group, y=reorder(nam,slope,FUN=function(x) x[1]))) +
geom_point(aes(color=slope), shape=1, size=2.2, stroke=1.2) +
geom_point(data=. %>% subset(adj.PVal < 0.05),
aes(color=slope),
shape=19, size=2.2) +
geom_hline(yintercept=seq.int(2,nrow(res.cytof.merge.sub))-0.5,
size=0.4, linetype="dotted", color="grey") + # my.cytokines: vector of cytokines in res.toplot
scale_color_gradientn(
colors=c("limegreen","#f7f7f7","coral2"),
limits=c(-4.11,4.11),
breaks=c(-4,-2,0,2,4),
name="") +
labs(x="", y="", title="CyTOF populations associated\nwith severity at Visit 1") + # temporary title, will change to "Cytokines associated with severity at Visit 1"
theme_bw() +
theme(
plot.title = element_text(hjust = 0.5, size=12, face="plain"),
axis.text.x = element_text(size=12, color="black", angle=35, hjust=1),
axis.text.y = element_text(size=11, color="black"),
text = element_text(size=12, family="Arial"),
axis.ticks.y=element_blank(),
plot.margin = unit(c(0,1,1,0), "cm"),
panel.grid=element_blank(),
)
```