---
title: "cytotoxic functions"
output: pdf_document
---

```{r load library}
library(ade4) #used in mcia
library(mogsa)
library(factoextra)
library(cluster)
library(nnet)
library(survival)
library(ordinal)
library(ggeffects)
library(openxlsx)
library(network)
library(GGally)
library(ggalt)
library(metafor)
library(cowplot)
library(survminer)
require(nlme) # directly provides p-values, unlike lme4
require(splines)
require(dplyr)
library(fgsea)
library(circlize)
require(rio)
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
source(paste0(codebase_path,"/codebase_subtype.R"))

organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")

intermediate_results_outdir_DR = "/scratch/data-integration/molecular_subtyping/DimensionReduction/"
mcia_results = readRDS(paste0(intermediate_results_outdir_DR,"MCIA_phase123_20230726.rds"))

data_path <- "/scratch/data-integration/pipelines/processedData/"
data_env0 <- readRDS(paste0(data_path, "data_env_ravi_20220513.RDS"))

base_obj = readRDS(file = "/scratch/data-integration/cleanedup/mod1_interpretation_base.rds")
```

# Load subtype assignment and data preprocessing
```{r load subtype assignment and data preprocessing}
visit_max = 6
nclust_tree_all = 6
subtype_hcl = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/subtype_hcl.rds")
clin_data_aligned = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/clin_data_aligned.rds")
extended_data = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/extended_data.rds")
# viral load
ct_train = data.frame(
  "event_id" = rownames(base_obj$others$nasal_viralload$train$nasal_viralload_counts),
  "N1_CT" = base_obj$others$nasal_viralload$train$nasal_viralload_counts$N1_CT,
  "RP_CT" = base_obj$others$nasal_viralload$train$nasal_viralload_counts$RP_CT)
ct_test = data.frame(
  "event_id" = rownames(base_obj$others$nasal_viralload$test$nasal_viralload_counts),
  "N1_CT" = base_obj$others$nasal_viralload$test$nasal_viralload_counts$N1_CT,
  "RP_CT" = base_obj$others$nasal_viralload$test$nasal_viralload_counts$RP_CT)
ct_df = rbind(ct_train, ct_test)
ct_df = ct_df[order(ct_df$event_id),]
rownames(ct_df) = ct_df$event_id
# remove samples with undetected RP_CT values
ct_df = ct_df[!is.na(ct_df$RP_CT), ]
# replace NA (undetermined) in N1_CT to 40
ct_df$N1_CT[is.na(ct_df$N1_CT)] = 40
# replace values > 40 to 40
ct_df$N1_CT[ct_df$N1_CT > 40] = 40
# flip the sign of N1_CT
ct_df$N1_CT <- -ct_df$N1_CT
ct_df = subset(ct_df, select = -c(event_id, RP_CT))
ct_df = as.data.frame(quantileNormalizeNoTies(ct_df))
ct_df$event_id = rownames(ct_df)
colnames(ct_df) <- c("negative N1-CT", "event_id")
# antibody
auc_train = data.frame(
  "event_id" = rownames(base_obj$others$serum_rbd_abtiters$train$serum_rbd_abtiters_counts),
  "log2_AUC" = base_obj$others$serum_rbd_abtiters$train$serum_rbd_abtiters_counts$`AUC RBD IgG`)
auc_test = data.frame(
  "event_id" = rownames(base_obj$others$serum_rbd_abtiters$test$serum_rbd_abtiters_counts),
  "log2_AUC" = base_obj$others$serum_rbd_abtiters$test$serum_rbd_abtiters_counts$`AUC RBD IgG`)
auc_df = rbind(auc_train, auc_test)
auc_df = auc_df[order(auc_df$event_id),]
rownames(auc_df) = auc_df$event_id
auc_df = subset(auc_df, select = -event_id)
auc_df = as.data.frame(quantileNormalizeNoTies(auc_df))
auc_df$event_id = rownames(auc_df)
colnames(auc_df) <- c("AUC RBD IgG", "event_id")

# cytof parent preprocess
cytof_parent_mat_train = base_obj$others$bld_cytof$train$bld_cytof_counts
cytof_parent_mat_train = base_obj$others$bld_cytof$preprocess_bld_cytof_parent_granulo_separate(counts = cytof_parent_mat_train, rowfeature = base_obj$others$bld_cytof$train$bld_cytof_rowfeatures)
cytof_parent_mat_test = base_obj$others$bld_cytof$test$bld_cytof_counts
cytof_parent_mat_test = base_obj$others$bld_cytof$preprocess_bld_cytof_parent_granulo_separate(counts = cytof_parent_mat_test, rowfeature = base_obj$others$bld_cytof$test$bld_cytof_rowfeatures)

cytof_parent_mat = rbind(cytof_parent_mat_train, cytof_parent_mat_test)
cytof_parent_mat$event_id = rownames(cytof_parent_mat)
cytof_parent_mat <- cytof_parent_mat %>%
  left_join(ct_df %>% left_join(auc_df, by = "event_id"), by = "event_id") %>%
  dplyr::select(-event_id, everything(), event_id)
cytof_parent_feature_names = setdiff(colnames(cytof_parent_mat), "event_id")

cytof_parent_mat = cytof_mat_preprocess(
  cytof_parent_mat, subtype_hcl, clin_data_aligned)

# cytof child preprocess
cytof_child_mat_train = base_obj$others$bld_cytof$train$bld_cytof_counts
cytof_child_mat_train = preprocess_bld_cytof_child_seperate_granulo(counts = cytof_child_mat_train)
cytof_child_mat_test = base_obj$others$bld_cytof$test$bld_cytof_counts
cytof_child_mat_test = preprocess_bld_cytof_child_seperate_granulo(counts = cytof_child_mat_test)

cytof_child_mat = rbind(cytof_child_mat_train, cytof_child_mat_test)
cytof_child_feature_names = colnames(cytof_child_mat)
cytof_child_mat$event_id = rownames(cytof_child_mat)

cytof_child_mat = cytof_mat_preprocess(
  cytof_child_mat, subtype_hcl, clin_data_aligned)

# cytokine preprocess
cytokine_mat = organized_data$datasets$serum_olink
cytokine_feature_names = colnames(cytokine_mat)
cytokine_mat$event_id = rownames(cytokine_mat)
cytokine_mat = cytof_mat_preprocess(
  cytokine_mat, subtype_hcl, clin_data_aligned)

# T-cell Cytotoxic preprocess
pbmc_feature_names = c("PRF1","IFNG","GNLY","NKG7","GZMB","GZMA","GZMH",
                       "KLRK1","KLRB1","KLRD1","CTSW","GZMK","GZMM")
pbmc_raw <- as.data.frame(read_csv("/data/pbmc-transcriptomics/current/pbmc-transcriptomics-RowFeature.csv", skip = 1))
pbmc = organized_data$datasets_imputed[[6]]
pbmc_raw = pbmc_raw[pbmc_raw$gene_name %in% pbmc_feature_names,]
pbmc = pbmc[, pbmc_raw$gene_id]
colnames(pbmc) = pbmc_feature_names
pbmc$event_id = rownames(pbmc)
pbmc = cytof_mat_preprocess(pbmc, subtype_hcl, clin_data_aligned)
```

# Hierarchical clustering on Serum Olink
```{r hierarchical clustering on Serum Olink}
serum_olink_core <- organized_data$datasets_imputed$serum_olink
serum_olink_core$event_id <- rownames(serum_olink_core)
serum_olink_core <- cytof_mat_preprocess(serum_olink_core, subtype_hcl, 
                                         clin_data_aligned)
serum_olink_core <- serum_olink_core_dist_preprocess(serum_olink_core, 1:92, 
                                                     visit_max)
n_participant <- nrow(extended_data$X)
dist_mat_so <- calculate_distance_matrix(serum_olink_core, n_participant, visit_max)
hcl_so <- hclust(d = dist_mat_so, method = "ward.D2")
Kmin <- 5; Kmax <- 10
k.values <- Kmin:Kmax
sil_values_so <- c()
avg_sil <- function(dist_obj, cluster) {
  ss <- silhouette(cluster, dist_obj)
  mean(ss[, 3])
}
for (k in k.values) {
  cluster_cut <- cutree(hcl_so, k)
  sil_values_so[k - Kmin+1] <- avg_sil(dist_obj = dist(
    x = serum_olink_core[,1:n_participant]), cluster_cut)
}
nclust_tree_so <- k.values[which.max(sil_values_so)]
olink_cluster <- cutree(hcl_so, k = nclust_tree_so)
olink_cluster <- data.frame(feature = names(olink_cluster), 
                            category = olink_cluster)
cytokine_cls <- olink_cluster[order(olink_cluster$category), ]
```

# Baseline neutrophil & lymphocyte (Extended Data Fig3B)
```{r baseline neutrophil & lymphocyte, fig.height=6, fig.width=10, warning=FALSE}
data_baseline <- read.csv("/scratch/data-integration/impacc-baseline-labs.csv")
df_anc <- subtype_hcl
df_anc$studyid <- rownames(subtype_hcl)
df_anc <- left_join(df_anc, data_baseline, by = "studyid")
anc_norm <- cbind(df_anc$baseline_lab_anc,
                  df_anc$baseline_lab_lymph)
anc_norm <- quantileNormalizeNoTies(anc_norm)
anc_norm <- as.data.frame(anc_norm)
colnames(anc_norm) <- c("norm_anc", "norm_lymph")
df_anc <- data.frame(Subtype = factor(subtype_hcl$label),
                     norm_anc = anc_norm$norm_anc,
                     norm_lymph = anc_norm$norm_lymph)
df_anc <- df_anc[df_anc$Subtype != "D", ]

clin_data_patient <- clin_data_aligned[clin_data_aligned$event_type == "Visit 1",]
demo_data_adjust <- clin_data_patient[, c("discretized_admit_age_quantile", "sex")]
test_ExtendedData3D <- baseline_comparison(anc_norm, demo_data_adjust,
                                           subtype_hcl$label)
colnames(test_ExtendedData3D$est_lm) = c("Normalized Baseline Absolute Neutrophil Count",
                                         "Normalized Baseline Lymphocyte")
colnames(test_ExtendedData3D$p_lm) = c("Normalized Baseline Absolute Neutrophil Count",
                                       "Normalized Baseline Lymphocyte")
pval_all <- baseline_comparison(anc_norm, demo_data_adjust, 
                                subtype_hcl$label)$p_lm
pvec <- as.vector(as.matrix(pval_all))
pvec_bh <- p.adjust(pvec, method = "BH")
pval_all <- matrix(pvec_bh, nrow = nrow(pval_all),
                   ncol = ncol(pval_all),
                   dimnames = list(rownames(pval_all),
                                   colnames(pval_all)))
p_val1 <- data.frame(
  label_group = c("EF vs ABC", "F vs E", "A vs BC", "B vs AC", "C vs AB"),
  p_val = pval_all[, "norm_anc"],
  y_pos = c(max(anc_norm$norm_anc, na.rm = TRUE)*1.1,
            max(anc_norm$norm_anc[subtype_hcl$label == "E" |
                                    subtype_hcl$label == "F"],
                na.rm = TRUE)*1.1,
            rep(max(anc_norm$norm_lymph[subtype_hcl$label == "A" |
                                          subtype_hcl$label == "B" |
                                          subtype_hcl$label == "C"],
                    na.rm = TRUE)*1.1, 3)))
p_val1 <- p_val1 %>%
  mutate(sig = ifelse(p_val <= 0.001, "***",
                       ifelse(p_val <= 0.01, "**",
                              ifelse(p_val <= 0.05, " * ", ""))),
         segment = sig != "")

p_val2 <- data.frame(
  label_group = c("EF vs ABC", "F vs E", "A vs BC", "B vs AC", "C vs AB"),
  p_val = pval_all[, "norm_lymph"],
  y_pos = c(max(anc_norm$norm_lymph,
                na.rm = TRUE)*1.1,
            max(anc_norm$norm_lymph[subtype_hcl$label == "E" |
                                      subtype_hcl$label == "F"],
                na.rm = TRUE)*1.1,
            rep(max(anc_norm$norm_lymph[subtype_hcl$label == "A" |
                                          subtype_hcl$label == "B" |
                                          subtype_hcl$label == "C"],
                    na.rm = TRUE)*1.1, 3)))
p_val2 <- p_val2 %>%
  mutate(sig = ifelse(p_val <= 0.001, "***",
                       ifelse(p_val <= 0.01, "**",
                              ifelse(p_val <= 0.05, " * ", ""))),
         segment = sig != "")

plot_anc <- ggplot(df_anc, aes(x = Subtype, y = norm_anc, color = Subtype)) + 
  geom_boxplot(outlier.size = 0.6, size = 1.2) +
  geom_jitter(width = 0.2, size = 0.3, alpha = 0.8)+
  theme_classic() +
  scale_fill_manual(values = c("#20854EB2", "#0072B5B2", "#E18727B2",
                               "#EE4C97B2", "#BC3C29B2")) +
  scale_color_manual(values = c("#20854EB2", "#0072B5B2", "#E18727B2",
                                "#EE4C97B2", "#BC3C29B2")) +
  theme(axis.line.x = element_line(linewidth = 1),
       axis.line.y = element_line(linewidth = 1),
       axis.ticks = element_line(linewidth = 1),
       axis.text.x = element_text(color = "black", size = 15),  
       axis.text.y = element_text(color = "black", size = 15),
       axis.title.x = element_text(color = "black", size = 15),
       axis.title.y = element_text(color = "black", size = 15),
       axis.ticks.length = unit(0.15, "cm"),
       legend.position = "top",
       legend.text = element_text(size = 15),
       legend.title = element_text(size = 15),
       legend.key.size = unit(2.5, "lines")) +
  labs(y = "Normalized Baseline Absolute Neutrophil Count") +
  geom_text(data = p_val1[p_val1$label_group == "EF vs ABC",], 
              aes(x = 3, y = y_pos, label = sig),
              position = position_dodge(0.9), hjust = 0.5, 
              color = "grey40", size = 8) +
  geom_segment(data = filter(p_val1, label_group == "EF vs ABC" & segment), 
               aes(x = 1, xend = 5, y = y_pos-0.08, yend = y_pos-0.08), 
               color = "grey40", size = 0.7) +
  geom_text(data = p_val1[p_val1$label_group == "A vs BC",], 
              aes(x = 2, y = y_pos+0.5, label = sig),
              position = position_dodge(0.9), hjust = 0.5, 
              color = "#20854EB2", size = 8) +
  geom_segment(data = filter(p_val1, label_group == "A vs BC" & segment), 
               aes(x = 1, xend = 3, y = y_pos-0.08+0.5, yend = y_pos-0.08+0.5), 
               color = "#20854EB2", size = 0.7) +
  geom_text(data = p_val1[p_val1$label_group == "C vs AB",], 
              aes(x = 2, y = y_pos+1, label = sig),
              position = position_dodge(0.9), hjust = 0.5, 
              color = "#E18727B2", size = 8) +
  geom_segment(data = filter(p_val1, label_group == "C vs AB" & segment), 
               aes(x = 1, xend = 3, y = y_pos-0.08+1, yend = y_pos-0.08+1), 
               color = "#E18727B2", size = 0.7)

plot_lymph <- ggplot(df_anc, aes(x = Subtype, y = norm_lymph, color = Subtype)) + 
  geom_boxplot(outlier.size = 0.6, size = 1.2) +
  geom_jitter(width = 0.2, size = 0.3, alpha = 0.8)+
  theme_classic() +
  scale_fill_manual(values = c("#20854EB2", "#0072B5B2", "#E18727B2",
                               "#EE4C97B2", "#BC3C29B2")) +
  scale_color_manual(values = c("#20854EB2", "#0072B5B2", "#E18727B2",
                                "#EE4C97B2", "#BC3C29B2")) +
  theme(axis.line.x = element_line(linewidth = 1),
       axis.line.y = element_line(linewidth = 1),
       axis.ticks = element_line(linewidth = 1),
       axis.text.x = element_text(color = "black", size = 15),  
       axis.text.y = element_text(color = "black", size = 15),
       axis.title.x = element_text(color = "black", size = 15),
       axis.title.y = element_text(color = "black", size = 15),
       axis.ticks.length = unit(0.15, "cm"),
       legend.position = "top",
       legend.text = element_text(size = 15),
       legend.title = element_text(size = 15),
       legend.key.size = unit(2.5, "lines")) +
  labs(y = "Normalized Baseline Lymphocyte") +
  geom_text(data = p_val2[p_val2$label_group == "EF vs ABC",], 
              aes(x = 3, y = y_pos, label = sig),
              position = position_dodge(0.9), hjust = 0.5, 
              color = "grey40", size = 8) +
  geom_segment(data = filter(p_val2, label_group == "EF vs ABC" & segment), 
               aes(x = 1, xend = 5, y = y_pos-0.08, yend = y_pos-0.08), 
               color = "grey40", size = 0.7)

ggarrange(plotlist = list(plot_anc, plot_lymph),
          nrow = 1, ncol = 2, common.legend = T, legend = "top")
```

# Cytotoxic comparison heatmap (Extended Data Fig3C)
```{r cytotoxic comparison heatmap, fig.height=6, fig.width=10.8}
plotDF = cytotoxic_test$effect_size

plotDF = as.matrix(plotDF)
test_types = rep(unique_group, each = length(unique_visit))
test_types = factor(test_types, levels = unique_group)
colnames(plotDF) = rep(unique_visit, length(unique_group))

cytotoxic_comparison = ComplexHeatmap::Heatmap(
  plotDF, col = circlize::colorRamp2(c(-max(abs(plotDF), na.rm = TRUE), 0, 
                                       max(abs(plotDF), na.rm = TRUE)), 
                                     c("#284AA0", "white", "#BC4A4A")),
  show_heatmap_legend = TRUE, na_col = "grey90", border=T,
  border_gp = gpar(col = "darkgrey", lwd = 0.5), 
  rect_gp = gpar(col = "darkgrey", lwd = 0.5),
  column_names_gp = gpar(fontsize = 15),
  row_names_gp = gpar(fontsize = 15),
  row_names_max_width = unit(6.8, "cm"),
  column_title_gp = gpar(fontsize = 15),
  column_names_rot = 0, column_names_centered = T, 
  row_names_side = "left",
  heatmap_legend_param = list(
    title = "Effect size  ", direction = "horizontal",
    title_position = "leftcenter", title_gp = gpar(fontsize = 15), 
    labels_gp = gpar(fontsize = 15)), column_split = test_types , 
  cluster_columns = F, cluster_rows = F, 
  cell_fun = function(j, i, x, y, w, h, fill) {
    if (!is.na(cytotoxic_test$p_adjust[i,j])){
      if(cytotoxic_test$p_adjust[i,j] < 0.001) {
        grid.text("***", x, y-h*0.12)
        }else if(cytotoxic_test$p_adjust[i,j] < 0.01) {
          grid.text("**", x, y-h*0.12)
          }else if(cytotoxic_test$p_adjust[i,j] < 0.05) {
            grid.text("*", x, y-h*0.12)
            }
      }
    })

ComplexHeatmap::draw(cytotoxic_comparison,, heatmap_legend_side = "bottom")
```




