---
title: "Figure6"
author: "Cole Maguire"
date: "5/5/2023"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
# Most packages are loaded by "class_structure.R" (see below). Load any additional packages here.
suppressPackageStartupMessages(library(package = "knitr"))
suppressPackageStartupMessages(library(package = "lme4"))
suppressPackageStartupMessages(library(package = "nlme"))
suppressPackageStartupMessages(library(package = "gamm4"))
suppressPackageStartupMessages(library(package = "ordinal"))
suppressPackageStartupMessages(library(package = "qvalue"))
suppressPackageStartupMessages(library(package = "ggeffects"))
suppressPackageStartupMessages(library(package = "pvca"))
suppressPackageStartupMessages(library(package = "ggbeeswarm"))
suppressPackageStartupMessages(library(package = "tidyverse"))
#suppressPackageStartupMessages(library(package = "vegan"))
suppressPackageStartupMessages(library(package = "readxl"))
suppressPackageStartupMessages(library(package = "ggpubr"))
suppressPackageStartupMessages(library(package = "RColorBrewer"))
suppressPackageStartupMessages(library(package = "stringi"))
suppressPackageStartupMessages(library(package = "readxl"))
suppressPackageStartupMessages(library(package = "ggpubr"))
suppressPackageStartupMessages(library(package = "corrplot"))
suppressPackageStartupMessages(library(package = "ReactomePA"))

# set session options
options(show_col_types = FALSE)
VarCorr <- lme4::VarCorr
options(scipen=999)
set.seed(123)
```

```{r load code and data, warning=FALSE, message=FALSE}

##### Load other data files, if any
ISG_genes <- read_excel("/scratch/metagenomics/age_analysis/TLR_ISG_Genes.xlsx")
Reactome_DATA <- ReactomePA:::get_Reactome_DATA("human")
##### Set global variables
# Trajectory group colors
TrajGrpCol <- c("1" = "#639A21", "2" = "#39828C", "3" = "#6371AD", "4" = "#BD7D31", "5" = "#9C3418")

##### Output directory
graphing_dir = "../output/"
```

### Load codebase.R, load data matrices and set path to a local output directory
```{r load-codebase, results="hide", fig.show="hide", message=FALSE, warning=FALSE}
# # load codebase.R, nasal metagenomic data and clinical information
source("/scratch/metagenomics/age_analysis/data_analysis_template_codebase.R")

nasal_metagenomics_counts <- read.csv("/data/nasal-metagenomics/current/nasal-metagenomics-AllGenera-Counts_RPM.csv", row.names = 1)
nasal_metagenomics_counts <- nasal_metagenomics_counts[,!colnames(nasal_metagenomics_counts) %in% "X"]
nasal_metagenomics_rowfeature <- read.csv("/data/nasal-metagenomics/current/nasal-metagenomics-AllGenera-RowFeatures.csv",  skip = 1)
nasal_metagenomics_metadata <- read_csv("/data/nasal-metagenomics/current/nasal-metagenomics-Metadata.csv")
nasal_metagenomics_statistics <- read_csv("/data/nasal-metagenomics/current/nasal-metagenomics-Statistics.csv")
nasal_viral_load_counts <- read.csv("/data/nasal-viralload/current/nasal-viralload-Counts.csv")
clinical_data1 <- read_csv("/data/clinical/legacy/2021-11-11-frozen/2021-11-11-impacc-clin-sample-frozen.csv")
clinical_data2 <- read_csv("/data/clinical/legacy/2021-11-11-frozen/2021-11-11-impacc-clin-individ-frozen.csv")
clinical_data3 <- read_csv("/data/clinical/legacy/2021-11-11-frozen/2021-11-11-impacc-clin-event-frozen.csv")
clinical_data <- merge(clinical_data1, clinical_data2, by = "participant_id")
clinical_data <- merge(clinical_data, clinical_data3, by= c("event_id", "participant_id"))
clinical_data$discretized_admit_age_quantile <- cut(clinical_data$admit_age, breaks = c(17,46,54,62,70, 96), include.lowest = FALSE)
rm(clinical_data1, clinical_data2, clinical_data3)

load("/scratch/metagenomics/age_analysis/20221117_bulk_RNAseq_nasal_visit1_voom.RData")
```

```{r}

#### nasal_metagenomics_counts contains taxa read counts mapped to the genius level
print(paste0("Starting with ", ncol(nasal_metagenomics_counts), " taxa."))
nasal_metagenomics_counts <- nasal_metagenomics_counts[, colSums(nasal_metagenomics_counts) > 0]
nasal_metagenomics_counts <- nasal_metagenomics_counts[rowSums(nasal_metagenomics_counts) > 0, ]
print(paste0("After filtering Taxa with 0 counts, ", ncol(nasal_metagenomics_counts), " taxa remain."))
## Dropping 96 taxa that had no reads mapped

## Making sure to remove samples that failed QC, specified clinical events, patients without sc2 rpm, healthy controls, escalation visits and samples pass day 30
samples_remove <- nasal_metagenomics_metadata$sample_id[nasal_metagenomics_metadata$sample_status == "IMPACC sample assayed and failed QC" | is.na(nasal_metagenomics_metadata$participant_id)]
samples_remove <- c(samples_remove, clinical_data$sample_id[clinical_data$event_id %in% c('014-2038-1', '002-0040-1', '010-0024-6')])
samples_remove <- unique(c(samples_remove, nasal_metagenomics_metadata$sample_id[is.na(nasal_metagenomics_metadata$sc2_rpm)]))
samples_remove <- unique(c(samples_remove, clinical_data$sample_id[clinical_data$participant_type == "Healthy control (Emory)"]))
samples_remove <- unique(c(samples_remove, clinical_data$sample_id[is.na(clinical_data$participant_type)]))
samples_remove <- unique(c(samples_remove, clinical_data$sample_id[clinical_data$event_type %in% c("Escalation 1", "Escalation 2", "Control donor visit")]))
samples_remove <- unique(c(samples_remove, clinical_data$sample_id[clinical_data$event_date > 30]))
length(rownames(nasal_metagenomics_counts)[!rownames(nasal_metagenomics_counts) %in% samples_remove])

tmp.annot <- nasal_metagenomics_counts %>%
  as.data.frame() %>%
  rownames_to_column("sample_id") %>%
  filter(!sample_id %in% samples_remove) %>%
left_join(clinical_data, by = "sample_id") %>%
  filter(!event_type %in% c("Escalation 1", "Escalation 2")) %>%
  filter(event_date <= 30)
keep_samples <- tmp.annot$sample_id

taxa_selection <- nasal_metagenomics_counts %>%
  as.data.frame() %>%
  rownames_to_column("sample_id") %>%
  filter(sample_id %in% keep_samples) %>%
  pivot_longer(-sample_id) %>%
  left_join(clinical_data, by = "sample_id") %>%
  filter(!event_type %in% c("Escalation 1", "Escalation 2")) %>%
  filter(event_date <= 30) %>%
  group_by(discretized_admit_age_quantile, name) %>%
  dplyr::summarize(age_group_freq_detected = sum(value > 0) / n()) %>%
  pivot_wider(names_from = discretized_admit_age_quantile, values_from = age_group_freq_detected) %>%
  rowwise()%>%
  mutate(age_group_avg_freq = mean(c(`(17,46]`, `(46,54]`, `(54,62]`, `(62,70]`, `(70,96]`)),
         age_group_max_freq = max(c(`(17,46]`, `(46,54]`, `(54,62]`, `(62,70]`, `(70,96]`)))

selected_nasal_taxa_names <- log10(nasal_metagenomics_counts[,colnames(nasal_metagenomics_counts) %in% taxa_selection$name[taxa_selection$age_group_max_freq >= 0.3]] + 1)
write.csv(colnames(selected_nasal_taxa_names), paste0(graphing_dir, "selected_nasal_taxa.csv"))

selected_nasal_taxa <- nasal_metagenomics_counts[,colnames(nasal_metagenomics_counts) %in% colnames(selected_nasal_taxa_names)] / rowSums(nasal_metagenomics_counts[,colnames(nasal_metagenomics_counts) %in% colnames(selected_nasal_taxa_names)])
selected_nasal_taxa <- selected_nasal_taxa[!rownames(selected_nasal_taxa) %in% samples_remove,]

taxa_inputDF <- selected_nasal_taxa %>%
  rownames_to_column(var = "sample_id") %>%
  merge(y = dplyr::select(clinical_data, sample_id, event_date, participant_id, respiratory_status_day14, respiratory_status_day28,enrollment_site, trajectory_group, sex, admit_age, enrollment_site, discretized_admit_age_quantile),
        by = "sample_id") %>%
  pivot_longer(cols = -c("sample_id", "event_date", "participant_id",
                         "enrollment_site", "trajectory_group",
                         "respiratory_status_day14",
                         "respiratory_status_day28",
                         "sex", "admit_age", "discretized_admit_age_quantile")) %>%
  filter(!is.na(value) & !is.na(trajectory_group)) %>%
  mutate(discretized_admit_age_quantile = stri_replace_all_regex(discretized_admit_age_quantile,
                                  pattern=c('^.17', '^.46', '^.54', '^.62', '^.70'),
                                  replacement=c('[18', '[47', '[55', '[63', '[71'),
                                  vectorize=FALSE)) %>%
   mutate(
         enrollment_site = factor(enrollment_site),
         trajectory_group = ordered(factor(trajectory_group)),
         discretized_admit_age_quantile = ordered(factor(discretized_admit_age_quantile)),
         sex = factor(sex),
         name = factor(name),
         participant_id = factor(participant_id))

```

## Panel E
```{r main_e}
meta1_ready <-nasal_metagenomics_metadata %>%
  left_join(clinical_data %>%
              mutate(discretized_admit_age_quantile = stri_replace_all_regex(discretized_admit_age_quantile,
                                  pattern=c('^.17', '^.46', '^.54', '^.62', '^.70'),
                                  replacement=c('[18', '[47', '[55', '[63', '[71'),
                                  vectorize=FALSE)) %>%
              mutate(discretized_admit_age_quantile = ordered(discretized_admit_age_quantile)), by = c("sample_id", "participant_id")) 

data_cor_ready <- merge(as.data.frame(t(visit1.norm.expr[rownames(visit1.norm.expr) %in% ISG_genes$ensembl_gene_id,])), meta1_ready, by.x = 0, by.y = "event_id")


filtered_ISG <-ISG_genes$ensembl_gene_id[ISG_genes$gene_set == "ISG"]
filtered_ISG <- filtered_ISG[filtered_ISG %in% colnames(data_cor_ready)]

filtered_TLR <-ISG_genes$ensembl_gene_id[ISG_genes$gene_set == "TLR"]
filtered_TLR <- filtered_TLR[filtered_TLR %in% colnames(data_cor_ready)]
what <- data_cor_ready %>%
  mutate(IFN_Score = rowMeans(dplyr::select(data_cor_ready, filtered_ISG), na.rm = TRUE),
         TLR_Score = rowMeans(dplyr::select(data_cor_ready, filtered_TLR), na.rm = TRUE),
         sc2_rpm_log10 = log10(data_cor_ready$sc2_rpm + 0.1),
         total_bacterial_rpm_log10 = log10(data_cor_ready$total_bacterial_rpm + 0.1)) %>%
  dplyr::select(total_bacterial_rpm_log10, sc2_rpm_log10, IFN_Score, TLR_Score)

res <- cor(what, use = "everything")
colnames(res) <- c("Log10 Total Bacterial RPM", "Log10 SARS-CoV-2 RPM", "IFN Score", "TLR Score")
rownames(res) <- colnames(res)
panelE <- corrplot(res, col = rev(COL2('RdBu', 200)))
panelE
#ggsave(paste0(graphing_dir, "panelE.pdf"), device = "pdf", width = 3.7, height = 2)
```

## Panel F
```{r main_F, fig.width = 4.8, fig.height = 2.5}
panelF <- taxa_inputDF %>%
  filter(name == "X1847725") %>%
  left_join(left_join(nasal_metagenomics_metadata %>% dplyr::select(sample_id), clinical_data) %>% dplyr::select(sample_id, event_type)) %>%
  filter(event_type == "Visit 1") %>%
  ggplot(aes(x=discretized_admit_age_quantile, y = value,
             color = discretized_admit_age_quantile)) +
  geom_boxplot() +
  geom_quasirandom(size = 0.8) +
  theme_classic() +
  ylab("Lawsonella Log10 Abundance") +
  xlab("Age group") +
  theme(legend.position = "none") +
  theme(axis.text = element_text(size=12, color="black"))
panelF
#ggsave(paste0(graphing_dir, "panelF.pdf"), device = "pdf", width = 4.8, height = 2.5)

```


## Panel G
```{r main_G, fig.width = 6, fig.height = 2.5}

Lawsonella_TLR <- data_cor_ready %>%
  mutate(IFN_Score = rowMeans(dplyr::select(data_cor_ready, filtered_ISG), na.rm = TRUE),
         TLR_Score = rowMeans(dplyr::select(data_cor_ready, filtered_TLR), na.rm = TRUE),
         sc2_rpm_log10 = log10(data_cor_ready$sc2_rpm + 0.1),
         total_bacterial_rpm_log10 = log10(data_cor_ready$total_bacterial_rpm + 0.1)) %>%
  dplyr::select(sample_id, total_bacterial_rpm_log10, sc2_rpm_log10, IFN_Score, TLR_Score, discretized_admit_age_quantile) %>%
  left_join(selected_nasal_taxa %>% rownames_to_column("sample_id")) %>%
    dplyr::select(TLR_Score, X1847725, discretized_admit_age_quantile)

cor.out <- data.frame(matrix(nrow=5,ncol=3))
rownames(cor.out) <- levels(Lawsonella_TLR$discretized_admit_age_quantile)
colnames(cor.out) <- c("p.value", "estimate", "discretized_admit_age_quantile")
for(i in levels(Lawsonella_TLR$discretized_admit_age_quantile)){
  tmp.file <- Lawsonella_TLR[Lawsonella_TLR$discretized_admit_age_quantile == i,]
  ct <- cor.test(tmp.file$TLR_Score, tmp.file$X1847725)
  p <- ct$p.value
  est <- ct$estimate
  cor.out[i,] <- c(p, est, i)
}
cor.out$estimate <- as.numeric(cor.out$estimate)
cor.out$p.value <- as.numeric(cor.out$p.value)
cor.out$p.adj <- p.adjust(cor.out$p.value, method = "fdr")
cor.out$formatted <- paste0(cor.out$discretized_admit_age_quantile, ": ",
                            round(cor.out$estimate, 2), ", ",
                            signif(cor.out$p.adj, digits = 3))


panelG <- Lawsonella_TLR %>%
  left_join(cor.out %>% dplyr::select(discretized_admit_age_quantile, formatted)) %>%
  mutate(formatted = ordered(formatted)) %>%
  ggplot(aes(x=X1847725, y= TLR_Score, group = formatted,
             color = formatted,
             fill = formatted)) +
  geom_point(aes(color = formatted)) +
  theme_classic() +
  geom_smooth(formula = y ~ x, method = "lm") +
  xlab("log10 Lawsonella RPM") +
  ylab("TLR Score") +
  guides(fill=guide_legend(title=" "),
         color = guide_legend(title=" "))
panelG
#ggsave(paste0(graphing_dir, "panelG.pdf"), device = "pdf", height = 2.5, width = 6)
```


## Panel H

```{r main_H}
nasal_metagenomics_counts_bit <- nasal_metagenomics_counts %>%
  as.data.frame() %>%
  rownames_to_column("sample_id") %>%
  filter(sample_id %in% keep_samples) %>%
  column_to_rownames("sample_id")
## Greater than 0.1 RPM to count as detected
nasal_metagenomics_counts_bit[nasal_metagenomics_counts_bit>0.1] <- 1
nasal_metagenomics_counts_bit[nasal_metagenomics_counts_bit<1] <- 0
hit_no_hit_count_screen <- nasal_metagenomics_counts_bit %>%
  rownames_to_column("sample_id") %>%
  pivot_longer(-sample_id, names_to = "tax_id") %>%
  left_join(clinical_data, by = "sample_id") %>%
  left_join(nasal_metagenomics_rowfeature %>% mutate(tax_id = paste0("X", tax_id)), by = c("tax_id")) %>%
  filter(tax_id %in% c("X10294", "X10358")) %>% ## Selects Simplexvirus and CMV
  group_by(sample_id, discretized_admit_age_quantile, event_type, name) %>%
  dplyr::summarize(count = sum(value))


hit_no_hit_count_screen %>%
  filter(discretized_admit_age_quantile == "(17,46]") %>%
  filter(name == "Simplexvirus") %>%
  dplyr::rename(detected = count) %>%
  mutate(detected = gsub(1, "yes", gsub(0, "no", detected))) %>%
  group_by(event_type, detected) %>%
  dplyr::summarize(count = n()) %>%
  pivot_wider(names_from = detected, values_from = count, id_cols = event_type) %>%
  mutate(yes = ifelse(is.na(yes), 0, yes)) %>%
  mutate(percentage = (yes)/(sum(yes+no)) * 100) %>%
  mutate(label = paste0(yes, "/", yes+no)) %>%
  ggplot(aes(x=event_type, y=percentage, fill = event_type)) +
    geom_bar(stat = "identity", color = "black", width = 0.6) +
    scale_fill_manual(values = (brewer.pal(n = 6, name = "Reds"))) +
  theme_classic() +
  ylab("Percentage of positive samples") + xlab(" ") +
  geom_text(aes(label=label), vjust=-0.25) +
  ggtitle("Simplexvirus in [18,46]") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(limits = c(0, 40), expand = c(0, 0))
ggsave(paste0(graphing_dir, "panelH_1.pdf"), device = "pdf", height = 2.5, width = 4)

hit_no_hit_count_screen %>%
  filter(discretized_admit_age_quantile == "(70,96]") %>%
  filter(name == "Simplexvirus") %>%
  dplyr::rename(detected = count) %>%
  mutate(detected = gsub(1, "yes", gsub(0, "no", detected))) %>%
  group_by(event_type, detected) %>%
  dplyr::summarize(count = n()) %>%
  pivot_wider(names_from = detected, values_from = count, id_cols = event_type) %>%
  mutate(yes = ifelse(is.na(yes), 0, yes)) %>%
  mutate(percentage = (yes)/(sum(yes+no)) * 100) %>%
  mutate(label = paste0(yes, "/", yes+no)) %>%
  ggplot(aes(x=event_type, y=percentage, fill = event_type)) +
    geom_bar(stat = "identity", color = "black", width = 0.6) +
    scale_fill_manual(values = (brewer.pal(n = 6, name = "Reds"))) +
  theme_classic() +
  ylab("Percentage of positive samples") + xlab(" ") +
  geom_text(aes(label=label), vjust=-0.25) +
  ggtitle("Simplexvirus in [71,96]") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(limits = c(0, 40), expand = c(0, 0))
ggsave(paste0(graphing_dir, "panelH_2.pdf"), device = "pdf", height = 2.5, width = 4)

hit_no_hit_count_screen %>%
  filter(discretized_admit_age_quantile == "(70,96]") %>%
  filter(name == "Cytomegalovirus") %>%
  dplyr::rename(detected = count) %>%
  mutate(detected = gsub(1, "yes", gsub(0, "no", detected))) %>%
  group_by(event_type, detected) %>%
  dplyr::summarize(count = n()) %>%
  pivot_wider(names_from = detected, values_from = count, id_cols = event_type) %>%
  mutate(yes = ifelse(is.na(yes), 0, yes)) %>%
  mutate(percentage = (yes)/(sum(yes+no)) * 100) %>%
  mutate(label = paste0(yes, "/", yes+no)) %>%
  ggplot(aes(x=event_type, y=percentage, fill = event_type)) +
    geom_bar(stat = "identity", color = "black", width = 0.6) +
    scale_fill_manual(values = (brewer.pal(n = 6, name = "Blues"))) +
  theme_classic() +
  ylab("Percentage of positive samples") + xlab(" ") +
  geom_text(aes(label=label), vjust=-0.25) +
  ggtitle("Cytomegalovirus in [71,96]") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(limits = c(0,15), expand = c(0, 0))
ggsave(paste0(graphing_dir, "panelH_3.pdf"), device = "pdf", height = 2.5, width = 4)

hit_no_hit_count_screen %>%
  filter(discretized_admit_age_quantile == "(17,46]") %>%
  filter(name == "Cytomegalovirus") %>%
  dplyr::rename(detected = count) %>%
  mutate(detected = gsub(1, "yes", gsub(0, "no", detected))) %>%
  group_by(event_type, detected) %>%
  dplyr::summarize(count = n()) %>%
  pivot_wider(names_from = detected, values_from = count, id_cols = event_type) %>%
  mutate(yes = ifelse(is.na(yes), 0, yes)) %>%
  mutate(percentage = (yes)/(sum(yes+no)) * 100) %>%
  mutate(label = paste0(yes, "/", yes+no)) %>%
  ggplot(aes(x=event_type, y=percentage, fill = event_type)) +
    geom_bar(stat = "identity", color = "black", width = 0.6) +
    scale_fill_manual(values = (brewer.pal(n = 6, name = "Blues"))) +
  theme_classic() +
  ylab("Percentage of positive samples") + xlab(" ") +
  geom_text(aes(label=label), vjust=-0.25) +
  ggtitle("Cytomegalovirus in [18,46]") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(limits = c(0,15), expand = c(0, 0))
#ggsave(paste0(graphing_dir, "panelH_4.pdf"), device = "pdf", height = 2.5, width = 4)

```


```{r}
sessionInfo()

```

<!-- ## R version 4.0.2 (2020-06-22) -->
<!-- ## Platform: x86_64-pc-linux-gnu (64-bit) -->
<!-- ## Running under: Ubuntu 22.04.2 LTS -->
<!-- ##  -->
<!-- ## Matrix products: default -->
<!-- ## BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 -->
<!-- ## LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so -->
<!-- ##  -->
<!-- ## locale: -->
<!-- ##  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        -->
<!-- ##  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    -->
<!-- ##  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           -->
<!-- ## [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C    -->
<!-- ##  -->
<!-- ## attached base packages: -->
<!-- ## [1] parallel  stats4    stats     graphics  grDevices utils     datasets  -->
<!-- ## [8] methods   base      -->
<!-- ##  -->
<!-- ## other attached packages: -->
<!-- ##  [1] org.Hs.eg.db_3.12.0  AnnotationDbi_1.52.0 IRanges_2.24.1       -->
<!-- ##  [4] S4Vectors_0.28.1     Biobase_2.50.0       BiocGenerics_0.36.1  -->
<!-- ##  [7] ReactomePA_1.34.0    corrplot_0.92        stringi_1.7.8        -->
<!-- ## [10] RColorBrewer_1.1-2   ggpubr_0.4.0         readxl_1.3.1         -->
<!-- ## [13] forcats_0.5.1        stringr_1.4.1        dplyr_1.0.8          -->
<!-- ## [16] purrr_0.3.4          readr_2.1.2          tidyr_1.2.0          -->
<!-- ## [19] tibble_3.1.7         tidyverse_1.3.2      ggbeeswarm_0.6.0     -->
<!-- ## [22] ggplot2_3.3.5        pvca_0.1.0           ggeffects_1.1.1      -->
<!-- ## [25] qvalue_2.22.0        ordinal_2019.12-10   gamm4_0.2-6          -->
<!-- ## [28] mgcv_1.8-31          nlme_3.1-148         lme4_1.1-28          -->
<!-- ## [31] Matrix_1.4-1         knitr_1.37           -->
<!-- ##  -->
<!-- ## loaded via a namespace (and not attached): -->
<!-- ##   [1] shadowtext_0.1.1    backports_1.2.0     fastmatch_1.1-3     -->
<!-- ##   [4] systemfonts_1.0.4   plyr_1.8.6          igraph_1.4.2        -->
<!-- ##   [7] splines_4.0.2       BiocParallel_1.24.1 digest_0.6.29       -->
<!-- ##  [10] htmltools_0.5.3     GOSemSim_2.16.1     viridis_0.6.2       -->
<!-- ##  [13] GO.db_3.12.1        fansi_0.4.1         checkmate_2.0.0     -->
<!-- ##  [16] magrittr_2.0.3      memoise_2.0.1       googlesheets4_1.0.0 -->
<!-- ##  [19] tzdb_0.2.0          graphlayouts_0.8.0  modelr_0.1.8        -->
<!-- ##  [22] vroom_1.5.7         enrichplot_1.10.2   colorspace_2.0-3    -->
<!-- ##  [25] rappdirs_0.3.1      blob_1.2.2          rvest_1.0.2         -->
<!-- ##  [28] ggrepel_0.9.1       textshaping_0.2.1   haven_2.4.3         -->
<!-- ##  [31] xfun_0.30           crayon_1.5.0        jsonlite_1.8.0      -->
<!-- ##  [34] graph_1.68.0        scatterpie_0.1.7    glue_1.6.2          -->
<!-- ##  [37] polyclip_1.10-0     gtable_0.3.0        gargle_1.2.0        -->
<!-- ##  [40] graphite_1.36.0     car_3.0-12          abind_1.4-5         -->
<!-- ##  [43] scales_1.1.1        DOSE_3.16.0         DBI_1.1.2           -->
<!-- ##  [46] rstatix_0.7.0       Rcpp_1.0.8          viridisLite_0.4.0   -->
<!-- ##  [49] reactome.db_1.74.0  bit_4.0.4           httr_1.4.2          -->
<!-- ##  [52] fgsea_1.16.0        ellipsis_0.3.2      pkgconfig_2.0.3     -->
<!-- ##  [55] farver_2.1.0        sass_0.4.0          dbplyr_2.1.1        -->
<!-- ##  [58] utf8_1.1.4          labeling_0.4.2      tidyselect_1.1.2    -->
<!-- ##  [61] rlang_1.0.2         reshape2_1.4.4      munsell_0.5.0       -->
<!-- ##  [64] cellranger_1.1.0    tools_4.0.2         cachem_1.0.6        -->
<!-- ##  [67] cli_3.2.0           generics_0.1.2      RSQLite_2.2.10      -->
<!-- ##  [70] broom_0.7.12        evaluate_0.14       fastmap_1.1.0       -->
<!-- ##  [73] ragg_0.4.0          yaml_2.2.1          bit64_4.0.5         -->
<!-- ##  [76] fs_1.5.2            tidygraph_1.2.0     ggraph_2.0.5        -->
<!-- ##  [79] DO.db_2.9           xml2_1.3.3          compiler_4.0.2      -->
<!-- ##  [82] rstudioapi_0.13     beeswarm_0.4.0      ggsignif_0.6.3      -->
<!-- ##  [85] reprex_2.0.1        tweenr_1.0.2        bslib_0.3.1         -->
<!-- ##  [88] highr_0.8           lattice_0.20-41     nloptr_2.0.0        -->
<!-- ##  [91] vctrs_0.4.1         pillar_1.7.0        lifecycle_1.0.1     -->
<!-- ##  [94] jquerylib_0.1.4     ucminf_1.1-4        data.table_1.14.2   -->
<!-- ##  [97] cowplot_1.1.1       R6_2.5.0            gridExtra_2.3       -->
<!-- ## [100] vipor_0.4.5         boot_1.3-25         MASS_7.3-51.6       -->
<!-- ## [103] assertthat_0.2.1    withr_2.5.0         hms_1.1.1           -->
<!-- ## [106] ggfun_0.0.9         grid_4.0.2          minqa_1.2.4         -->
<!-- ## [109] rmarkdown_2.12      carData_3.0-5       googledrive_2.0.0   -->
<!-- ## [112] ggforce_0.3.3       numDeriv_2016.8-1.1 lubridate_1.8.0 -->