---
title: "ExtendedData2"
output: html_notebook
---

```{r load library}
library(ade4) #used in mcia
library(mogsa)
library(factoextra)
library(cluster)
library(nnet)
library(survival)
library(ordinal)
library(ggeffects)
library(openxlsx)
library(network)
library(GGally)
library(ggalt)
library(metafor)
library(cowplot)
library(survminer)
require(nlme) # directly provides p-values, unlike lme4
require(splines)
require(dplyr)
library(fgsea)
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
source("~/impacc/Analysis/molecular_subtyping/preliminary/helpers_LG202301.R")
source("~/impacc/Analysis/molecular_subtyping/code/ExtendedData2/src/ExtendedData2_helper.R")
date = "20230726"; inner_folds = 10
PACS_group = list(physical = c(2), cognitive = c(5), multiple = c(6))
path_impacc_analysis = "/scratch/data-integration/cleanedup/"
intermediate_results_outdir_DR = "/scratch/data-integration/molecular_subtyping/DimensionReduction/"
organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")
file_mcia = paste0(intermediate_results_outdir_DR,"MCIA_phase123_",date,".rds")
mcia_results = readRDS(file_mcia)

base_obj = readRDS(file ="/scratch/data-integration/cleanedup/mod1_interpretation_base.rds")
file_impacc_analysis = paste0(path_impacc_analysis,"impacc_analysis_record_innerfold", inner_folds,".rds")
impacc_analysis_record=readRDS(file = file_impacc_analysis)
data_path <- "/scratch/data-integration/pipelines/processedData/"
data_env0 <- readRDS(paste0(data_path, "data_env_ravi_20220513.RDS"))
```

# Load subtype assignment and clinical data
```{r load subtype assignment and clinical data}
nclust_tree_all = 6
subtype_hcl = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/subtype_hcl.rds")
clin_data_aligned = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/clin_data_aligned.rds")
clin_test = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig2/src/clin_test.rds")
clin_names = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig2/src/clin_names.rds")
clin_names[names(clin_names) == "comorb_hxtrans"] = "History of solid organ or\nbone marrow transplant"
```

# Complication names correspondence
```{r}
comp_names <- c("num_cardiac" = "Number of Cardiac Complications",
                "num_gastro" = "Number of Gastrointestinal Complications",
                "num_hema" = "Number of Hematologic Complications",
                "num_hepatic" = "Number of Hepatic Complications",
                "num_infectious" = "Number of Infectious Complications",
                "num_metabolic" = "Number of Metabolic/Endocrine Complications",
                "num_neuro" = "Number of Neurololgic/Psyschiatric Complications",
                "num_other" = "Number of Other Complications",
                "num_pulmo" = "Number of Pulmonary Complications",
                "num_renal" = "Number of Renal Complications",
                "if_cardiac" = "Existence of Cardiac Complications",
                "if_gastro" = "Existence of Gastrointestinal Complications",
                "if_hema" = "Existence of Hematologic Complications",
                "if_hepatic" = "Existence of Hepatic Complications",
                "if_infectious" = "Existence of Infectious Complications",
                "if_metabolic" = "Existence of Metabolic/Endocrine Complications",
                "if_neuro" = "Existence of Neurololgic/Psyschiatric Complications",
                "if_other" = "Existence of Other Complications",
                "if_pulmo" = "Existence of Pulmonary Complications",
                "if_renal" = "Existence of Renal Complications")
```


# Subtype effect on complications adjusted for prior comorbidities (ExtendedData 2A)
```{r subtype effect on complications, fig.height=8, fig.width=12}
clin_data_patient = clin_data_aligned[clin_data_aligned$event_type == "Visit 1",]
df_comp = clin_data_patient %>%
  dplyr::select(matches("^(comp)"))
sig_comp = colnames(clin_test$p_logit)
sig_comp = grep("^comp", sig_comp, value = TRUE)
df_comp = clin_data_patient[, sig_comp]

df_comorb = clin_data_patient %>%
  dplyr::select(matches("^(comorb)"))
sig_comorb = colnames(clin_test$p_logit)
sig_comorb = grep("^comorb", sig_comorb, value = TRUE)
df_comorb = clin_data_patient[, sig_comorb]
demo_data_adjust = clin_data_patient[, c("discretized_admit_age_quantile", 
                                         "sex")]
df_adjust = cbind(demo_data_adjust, df_comorb)

comp_demo_comorb_adjust = comp_comparison_adjust_pred(
  df_comp, df_adjust, subtype_hcl$label)
comp_demo_comorb_adjust$p_adj = apply(comp_demo_comorb_adjust$p_logit, 2,
                                      function(p) p.adjust(p, method = "BH"))
df_comp = data.frame(comp_demo_comorb_adjust$pred_mean_logit)
df_comp = df_comp %>%
  pivot_longer(cols = starts_with("comp_"),
               names_to = "comp",
               values_to = "mean")
df_comp$Subtype = rep(c("A", "B", "C", "E", "F"),
                      each = ncol(comp_demo_comorb_adjust$pred_mean_logit))

pval_comp = data.frame(
  comp = colnames(comp_demo_comorb_adjust$p_adj),
  pval_EFvsABC = comp_demo_comorb_adjust$p_adj["EF vs ABC",],
  pval_FvsE = comp_demo_comorb_adjust$p_adj["F vs E",],
  pval_AvsBC = comp_demo_comorb_adjust$p_adj["A vs BC",],
  pval_BvsAC = comp_demo_comorb_adjust$p_adj["B vs AC",],
  pval_CvsAB = comp_demo_comorb_adjust$p_adj["C vs AB",])

df_comp$category = ""
df_comp$category[df_comp$comp == "comp_stroke"] = "Neuro\nlogic"
df_comp$category[df_comp$comp == "comp_afib"|
                      df_comp$comp == "comp_ventricular_arr"|
                      df_comp$comp == "comp_cardarrest"|
                      df_comp$comp == "comp_nstemi"|
                      df_comp$comp == "comp_chf"] = "Cardiac"
df_comp$category[df_comp$comp == "comp_pneumonia"|
                   df_comp$comp == "comp_pneumomed"] = "Pulmonary"
df_comp$category[df_comp$comp == "comp_avthromb"|
                      df_comp$comp == "comp_bleed"|
                      df_comp$comp == "comp_anemia"] = "Hematologic"
df_comp$category[df_comp$comp == "comp_shock"] = "Other"
df_comp$category[df_comp$comp == "comp_bac"] = "Infectious"
df_comp$category[df_comp$comp == "comp_renal"] = "Renal"

df_comp = df_comp %>%
  arrange(Subtype, category, comp)
comp_max = df_comp %>%
  group_by(category, comp) %>%
  summarise(y_max = max(mean))
comp_max = left_join(comp_max, pval_comp, by = "comp")
comp_pval = data.frame(x = seq(1, length(sig_comp), by = 1),
                       y_EFvsABC = comp_max$y_max + 0.03,
                       val_EFvsABC = comp_max$pval_EFvsABC,
                       label_EFvsABC = format(comp_max$pval_EFvsABC, 
                                              scientific = TRUE, digits = 2),
                       y_AvsBC = comp_max$y_max + 0.07,
                       val_AvsBC = comp_max$pval_AvsBC,
                       label_AvsBC = format(comp_max$pval_AvsBC, 
                                            scientific = TRUE, digits = 2),
                       y_BvsAC = comp_max$y_max + 0.11,
                       val_BvsAC = comp_max$pval_BvsAC,
                       label_BvsAC = format(comp_max$pval_BvsAC, 
                                            scientific = TRUE, digits = 2),
                       y_CvsAB = comp_max$y_max + 0.15,
                       val_CvsAB = comp_max$pval_CvsAB,
                       label_CvsAB = format(comp_max$pval_CvsAB, 
                                            scientific = TRUE, digits = 2),
                       y_FvsE = comp_max$y_max + 0.19,
                       val_FvsE = comp_max$pval_FvsE,
                       label_FvsE = format(comp_max$pval_FvsE, 
                                           scientific = TRUE, digits = 2))

comp_pval = comp_pval %>% 
  mutate(sig_EFvsABC = ifelse(val_EFvsABC <= 0.001, "***",
                       ifelse(val_EFvsABC <= 0.01, "**",
                              ifelse(val_EFvsABC <= 0.05, " * ", ""))),
         segment_EFvsABC = sig_EFvsABC != "",
         sig_AvsBC = ifelse(val_AvsBC <= 0.001, "***",
                       ifelse(val_AvsBC <= 0.01, "**",
                              ifelse(val_AvsBC <= 0.05, " * ", ""))),
         segment_AvsBC = sig_AvsBC != "",
         sig_BvsAC = ifelse(val_BvsAC <= 0.001, "***",
                       ifelse(val_BvsAC <= 0.01, "**",
                              ifelse(val_BvsAC <= 0.05, " * ", ""))),
         segment_BvsAC = sig_BvsAC != "",
         sig_CvsAB = ifelse(val_CvsAB <= 0.001, "***",
                       ifelse(val_CvsAB <= 0.01, "**",
                              ifelse(val_CvsAB <= 0.05, " * ", ""))),
         segment_CvsAB = sig_CvsAB != "",
         sig_FvsE = ifelse(val_FvsE <= 0.001, "***",
                       ifelse(val_FvsE <= 0.01, "**",
                              ifelse(val_FvsE <= 0.05, " * ", ""))),
         segment_FvsE = sig_FvsE != "")

df_comp$comp = factor(df_comp$comp, levels = unique(df_comp$comp))
df_comp$Subtype = factor(df_comp$Subtype)

comp_cat = data.frame(x_raw = as.vector(table(df_comp$category))/
                        nlevels(df_comp$Subtype),
                      label = levels(as.factor(df_comp$category)))
comp_cat$x_cum = cumsum(comp_cat$x_raw)
comp_cat$x = (1+comp_cat$x_cum[1])/2
for (i in 2:length(comp_cat$x_cum)) {
  comp_cat$x[i] = (comp_cat$x_cum[i-1]+comp_cat$x_cum[i]+1)/2
}
comp_cat$x_left = c(0, head(comp_cat$x_cum, -1))
comp_cat$x_left = comp_cat$x_left+0.6
comp_cat$x_right = comp_cat$x_cum+0.4

ggplot(df_comp, aes(x = comp, y = mean)) +
  geom_col(aes(fill = Subtype), position = position_dodge(0.9), width = 0.6) +
  theme_classic() +
  scale_fill_manual(values = c("#20854EB2", "#0072B5B2", "#E18727B2",
                               "#EE4C97B2", "#BC3C29B2")) +
  theme(axis.title.x = element_text(size = 16, color = "black"),
        axis.title.y = element_text(size = 16, color = "black"),
        axis.text.x = element_text(angle = 45, hjust = 1, color = "black", size = 15),
        axis.text.y = element_text(size = 16, color = "black"),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        legend.key.size = unit(2, "lines"),
        axis.line.x = element_line(linewidth = 1),
        axis.line.y = element_line(linewidth = 1)) +
  geom_vline(xintercept = seq(1.5, length(sig_comp), by = 1), 
             linetype = "dotted", colour = "grey50") +
  scale_x_discrete(labels = clin_names) +
  labs(x = "Complication", y = "Mean Counterfactual Probability") +
  geom_text(data = comp_pval, aes(x = x, y = y_EFvsABC, label = sig_EFvsABC),
            position = position_dodge(0.9), hjust = 0.5, color = "grey40", size = 6) +
  geom_segment(data = filter(comp_pval, segment_EFvsABC), 
               aes(x = x-0.4, xend = x+0.4, y = y_EFvsABC-0.005, yend = y_EFvsABC-0.005), 
               color = "grey40", linewidth = 0.5) +
  geom_text(data = comp_pval, aes(x = x, y = y_AvsBC, label = sig_AvsBC),
            position = position_dodge(0.9), hjust = 1.1, color = "#20854EB2", size = 6) +
  geom_segment(data = filter(comp_pval, segment_AvsBC),
               aes(x = x-0.4, xend = x, y = y_AvsBC-0.005, yend = y_AvsBC-0.005),
               color = "#20854EB2", linewidth = 0.5) +
  geom_text(data = comp_pval, aes(x = x, y = y_BvsAC, label = sig_BvsAC),
            position = position_dodge(0.9), hjust = 1.1, color = "#0072B5B2", size = 6) +
  geom_segment(data = filter(comp_pval, segment_BvsAC),
               aes(x = x-0.4, xend = x, y = y_BvsAC-0.005, yend = y_BvsAC-0.005),
               color = "#0072B5B2", linewidth = 0.5) +
  geom_text(data = comp_pval, aes(x = x, y = y_CvsAB, label = sig_CvsAB),
            position = position_dodge(0.9), hjust = 1.1, color = "#E18727B2", size = 6) +
  geom_segment(data = filter(comp_pval, segment_CvsAB),
               aes(x = x-0.4, xend = x, y = y_CvsAB-0.005, yend = y_CvsAB-0.005),
               color = "#E18727B2", linewidth = 0.5) +
  geom_text(data = comp_pval, aes(x = x, y = y_FvsE, label = sig_FvsE),
            position = position_dodge(0.9), hjust = -0.28, color = "#BC3C29B2", size = 6) +
  geom_segment(data = filter(comp_pval, segment_FvsE),
               aes(x = x+0.1, xend = x+0.4, y = y_FvsE-0.005, yend = y_FvsE-0.005),
               color = "#BC3C29B2", linewidth = 0.5) +
  geom_text(data = comp_cat, aes(x = x, y = 1.08, label = label),
            position = position_dodge(0.9), hjust = 0.45, color = "black", size = 4.8) +
  geom_segment(data = comp_cat, aes(x = x_left, xend = x_right, y = 1.025, yend = 1.025), 
               color = "black", linewidth = 0.6) +
  coord_cartesian(ylim = c(0, 1), clip = "off") + 
  theme(plot.margin = margin(t = 25, unit = "pt"))
```

# Complication category
```{r}
clin_data_patient$num_cardiac = rowSums(clin_data_patient[c("comp_afib", 
                                "comp_ventricular_arr", "comp_endo", 
                                "comp_myocard", "comp_cardarrest", 
                                "comp_stemi", "comp_nstemi",
                                "comp_chf", "comp_aat")] == 1)
clin_data_patient$if_cardiac = ifelse(clin_data_patient$num_cardiac>0, 1, 0)
clin_data_patient$num_gastro = rowSums(clin_data_patient[c("comp_pancreas", 
                                "comp_gastroent")] == 1)
clin_data_patient$if_gastro = ifelse(clin_data_patient$num_gastro>0, 1, 0)
clin_data_patient$num_hema = rowSums(clin_data_patient[c("comp_avthromb", 
                                "comp_coag", "comp_bleed", "comp_anemia")] == 1)
clin_data_patient$if_hema = ifelse(clin_data_patient$num_hema>0, 1, 0)
clin_data_patient$num_hepatic = rowSums(clin_data_patient[c("comp_liver")] == 1)
clin_data_patient$if_hepatic = ifelse(clin_data_patient$num_hepatic>0, 1, 0)
clin_data_patient$num_infectious = rowSums(clin_data_patient[c("comp_bac",
                                "comp_othinf")] == 1)
clin_data_patient$if_infectious = ifelse(clin_data_patient$num_infectious>0, 1, 0)
clin_data_patient$num_metabolic = rowSums(clin_data_patient[c("comp_hypogly",
                                "comp_electrolyte", "comp_hypergly")] == 1)
clin_data_patient$if_metabolic = ifelse(clin_data_patient$num_metabolic>0, 1, 0)
clin_data_patient$num_neuro = rowSums(clin_data_patient[c("comp_seizure",
                                "comp_meningitis", "comp_stroke",
                                "comp_enceph", "comp_othneuro", "comp_psych",
                                "comp_aat")] == 1)
clin_data_patient$if_neuro = ifelse(clin_data_patient$num_neuro>0, 1, 0)
clin_data_patient$num_other = rowSums(clin_data_patient[c("comp_shock",
                                "comp_unddisease", "comp_mis")] == 1)
clin_data_patient$if_other = ifelse(clin_data_patient$num_other>0, 1, 0)
clin_data_patient$num_pulmo = rowSums(clin_data_patient[c("comp_pneumonia",
                                "comp_bronch", "comp_pneumo", "comp_pneumomed",
                                "comp_othpulm", "comp_pulmvas")] == 1)
clin_data_patient$if_pulmo = ifelse(clin_data_patient$num_pulmo>0, 1, 0)
clin_data_patient$num_renal = rowSums(clin_data_patient[c("comp_renal")] == 1)
clin_data_patient$if_renal = ifelse(clin_data_patient$num_renal>0, 1, 0)

comp_data_linear <- clin_data_patient %>%
  dplyr::select(matches("^num"))

sub_idx = which(subtype_hcl$label != "D")
comp_test_linear_group_comparison <- 
  test_clinical_linear_demo_group_comparison(
  subtype_hcl$label[sub_idx], 
  comp_data_linear[sub_idx,], 
  demo_data_adjust[sub_idx,])
comp_test_linear_group_comparison$p_adj <- apply(
  comp_test_linear_group_comparison$p_linear, 2,
  function(p) p.adjust(p, method = "BH"))

comp_test_linear_group_comparison_comorb <- 
  test_clinical_linear_demo_group_comparison(
  subtype_hcl$label[sub_idx], 
  comp_data_linear[sub_idx,], 
  df_adjust[sub_idx,])
comp_test_linear_group_comparison_comorb$p_adj <- 
  apply(comp_test_linear_group_comparison_comorb$p_linear, 2,
        function(p) p.adjust(p, method = "BH"))
comp_test_linear_group_comparison_comorb$p_comorb_adj <- 
  apply(comp_test_linear_group_comparison_comorb$p_comorb, 2,
        function(p) p.adjust(p, method = "BH"))
```

# Heatmap of complication category - vanilla vs comorbidty adjusted (ExtendedData 2B)
```{r, fig.height=8.5, fig.width=9.5}
heatmap_comp_category_subtype(
  comp_test_linear_group_comparison,
  comp_test_linear_group_comparison_comorb,
  comp_names)
```

# Heatmap of complication category - comorbidity (ExtendedData 2C)
```{r, fig.height=8.5, fig.width=8.5}
heatmap_comp_category_comorb(comp_test_linear_group_comparison_comorb, 
                             comp_names, clin_names,
                             adjust_p = TRUE)
```

