
---
title: "Serum auto-antibody against IFN's data analysis for core-assay manuscript"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

### Load libraries
```{r load-packages}
suppressPackageStartupMessages(library(package = "knitr"))
suppressPackageStartupMessages(library(package = "impute"))
suppressPackageStartupMessages(library(package = "igraph"))
suppressPackageStartupMessages(library(package = "ggnetwork"))
suppressPackageStartupMessages(library(package = "ordinal"))
suppressPackageStartupMessages(library(package = "qvalue"))
suppressPackageStartupMessages(library(package = "ggbeeswarm"))
suppressPackageStartupMessages(library(package = "ggeffects"))
suppressPackageStartupMessages(library(package = "pvca"))
suppressPackageStartupMessages(library(package = "GSA"))
suppressPackageStartupMessages(library(package = "lme4"))
suppressPackageStartupMessages(library(package = "nlme"))
suppressPackageStartupMessages(library(package = "tidyverse"))
suppressPackageStartupMessages(library(package = "gtsummary"))

# set session options
options(show_col_types = FALSE)
VarCorr <- lme4::VarCorr
```

### Load codebase.R, load data matrices and set path to your local output directory
```{r load-codebase, results="hide", fig.show="hide", message=FALSE, warning=FALSE}
# load codebase.R, serum-rbd-abtiters data and clinical information
# source("~/bitbucket/impacc/Analysis/data_analysis_template_codebase.R")
source("../../Codebase/codebase_v2.R")
data_env <- load_IMPACC_datasets(DATA_VERSION                = "2022-01-01", 
                                 KEEP_COVID19_POS            = TRUE, 
                                 FILTER_BY_CORE_ASSAY_COHORT = TRUE,
                                 ASSAY_NAME = "serum_autoantibody")
for (n in grep(pattern = "serum_autoantibody|clinical_data", 
               names(data_env), 
               value   = TRUE)) {
  assign(n, value = data_env[[n]])
}


# Setup the assay specific output directory
out_dir = "../output"



```


&nbsp;

&nbsp;

#### Combine clinical data and serum auto-antobody data

```{r Combine clinical data and serum auto-antobody data, echo=FALSE}

serum_autoantibody_metadata_select <- serum_autoantibody_metadata %>%
  rownames_to_column(var = "sample_id") %>%
  filter(sample_status == "IMPACC sample assayed and passed QC") %>%
  select(sample_id, 
#         block.IFNa = positive.for.blocking.anti.IFNa.,
#         block.IFNb = positive.for.blocking.anti.IFNb.,
#         block.IFNw = positive.for.blocking.anti.IFNw.,
         block.IFNabw = positive.for.blocking.autoantibodies.against.at.least.one.type.I.IFN..at.earliest.timepoint..) %>%
  replace_na(list(block.IFNa = "no", block.IFNb = "no", block.IFNw = "no"))


clinical_autoantibody_meta_data <- clinical_data %>%
  inner_join(serum_autoantibody_metadata_select, by = "sample_id") 

# First select 1 earliest sample for each donor based on event date
sample_per_partcipant <- clinical_autoantibody_meta_data %>%
  arrange(participant_id, event_date, event_type) %>%
  distinct(participant_id, .keep_all = TRUE) %>%
  select(sample_id, participant_id, enrollment_site, sex, race, ethnicity, discretized_admit_age_quantile, event_date, event_type, trajectory_group, 
         #block.IFNa, block.IFNb, block.IFNw, 
         block.IFNabw)

```

&nbsp;

&nbsp;

#### Get numbers and stats for Table 2

```{r Get numbers and stats for Table 2, echo=FALSE}

#table(sample_per_partcipant$sex)
#table(sample_per_partcipant$discretized_admit_age_quantile)
#table(sample_per_partcipant$trajectory_group)

table(sample_per_partcipant$sex, sample_per_partcipant$block.IFNabw)
table(sample_per_partcipant$discretized_admit_age_quantile, sample_per_partcipant$block.IFNabw)
table(sample_per_partcipant$trajectory_group, sample_per_partcipant$block.IFNabw)

sumTbl.IFNabw.block <- sample_per_partcipant %>%
  select(sex, discretized_admit_age_quantile, trajectory_group, block.IFNabw) %>% tbl_summary(by = block.IFNabw) %>% add_p()

TrjGrpByblock.IFNabw <- sample_per_partcipant %>%
  select(trajectory_group, block.IFNabw) %>% tbl_summary(by = trajectory_group) %>% add_p()

SexByblock.IFNabw <- sample_per_partcipant %>%
  select(sex, block.IFNabw) %>% tbl_summary(by = sex) %>% add_p()

AgeByblock.IFNabw <- sample_per_partcipant %>%
  select(discretized_admit_age_quantile, block.IFNabw) %>% tbl_summary(by = discretized_admit_age_quantile) %>% add_p()

```

### Session info
```{r, print-session-info}
sessionInfo()
```
<!--
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
 [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
 [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] parallel  grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gtsummary_1.5.2       doParallel_1.0.17     doRNG_1.8.2           rngtools_1.5.2       
 [5] missForest_1.4        itertools_0.1-3       iterators_1.0.14      foreach_1.5.2        
 [9] randomForest_4.6-10   ComplexHeatmap_2.11.1 corrr_0.4.3           gridExtra_2.3        
[13] rlang_1.0.1           RColorBrewer_1.1-2    cowplot_1.1.1         ggpubr_0.4.0         
[17] pals_1.7              forcats_0.5.1         stringr_1.4.0         dplyr_1.0.8          
[21] purrr_0.3.4           readr_2.1.2           tidyr_1.2.0           tibble_3.1.6         
[25] tidyverse_1.3.1       nlme_3.1-147          lme4_1.1-28           Matrix_1.2-18        
[29] GSA_1.03.2            pvca_0.1.0            ggeffects_1.1.1       ggbeeswarm_0.6.0     
[33] qvalue_2.22.0         ordinal_2019.12-10    ggnetwork_0.5.10      ggplot2_3.3.5        
[37] igraph_1.3.0          impute_1.64.0         knitr_1.37           

loaded via a namespace (and not attached):
 [1] minqa_1.2.4         colorspace_2.0-3    ggsignif_0.6.3      rjson_0.2.21       
 [5] ellipsis_0.3.2      circlize_0.4.14     GlobalOptions_0.1.2 fs_1.5.2           
 [9] dichromat_2.0-0     clue_0.3-60         rstudioapi_0.13     DT_0.15            
[13] fansi_1.0.2         lubridate_1.8.0     xml2_1.3.2          codetools_0.2-16   
[17] splines_4.0.2       jsonlite_1.7.3      nloptr_2.0.0        gt_0.4.0           
[21] broom_0.7.12        cluster_2.1.0       dbplyr_2.1.1        png_0.1-7          
[25] mapproj_1.2.8       compiler_4.0.2      httr_1.4.2          backports_1.4.1    
[29] assertthat_0.2.1    fastmap_1.1.0       cli_3.2.0           htmltools_0.5.2    
[33] tools_4.0.2         gtable_0.3.0        glue_1.6.1          reshape2_1.4.4     
[37] maps_3.4.0          Rcpp_1.0.8          carData_3.0-5       cellranger_1.1.0   
[41] vctrs_0.3.8         broom.helpers_1.6.0 xfun_0.29           rvest_1.0.2        
[45] lifecycle_1.0.1     rstatix_0.7.0       MASS_7.3-51.6       scales_1.1.1       
[49] hms_1.1.1           yaml_2.3.5          sass_0.4.0          stringi_1.7.6      
[53] ucminf_1.1-4        S4Vectors_0.28.1    checkmate_2.0.0     BiocGenerics_0.36.1
[57] boot_1.3-25         shape_1.4.6         commonmark_1.7      pkgconfig_2.0.3    
[61] matrixStats_0.61.0  evaluate_0.14       lattice_0.20-41     htmlwidgets_1.5.4  
[65] tidyselect_1.1.2    plyr_1.8.6          magrittr_2.0.2      R6_2.5.1           
[69] IRanges_2.24.1      generics_0.1.2      DBI_1.1.2           pillar_1.7.0       
[73] haven_2.4.3         withr_2.4.3         abind_1.4-5         modelr_0.1.8       
[77] crayon_1.5.0        car_3.0-12          utf8_1.2.2          tzdb_0.2.0         
[81] rmarkdown_2.11      GetoptLong_1.0.5    readxl_1.3.1        reprex_2.0.1       
[85] digest_0.6.29       numDeriv_2016.8-1.1 stats4_4.0.2        munsell_0.5.0      
[89] beeswarm_0.4.0      vipor_0.4.5
-->



