---
title: "prior factor comparison"
output: pdf_document
---

```{r load library}
require(openxlsx)
library(factoextra)
library(cluster)
require(nlme) # directly provides p-values, unlike lme4
require(splines)
require(dplyr)
library(fgsea)
library(knitr)
library(kableExtra)
library(tidyverse)
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
source(paste0(codebase_path,"/codebase_subtype.R"))

organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")

intermediate_results_outdir_DR = "/scratch/data-integration/molecular_subtyping/DimensionReduction/"
mcia_results = readRDS(paste0(intermediate_results_outdir_DR,"MCIA_phase123_20230726.rds"))

data_path <- "/scratch/data-integration/pipelines/processedData/"
data_env0 <- readRDS(paste0(data_path, "data_env_ravi_20220513.RDS"))

base_obj = readRDS(file ="/scratch/data-integration/cleanedup/mod1_interpretation_base.rds")
```

# Load preliminary results
```{r load subtype assignment and clinical data}
# load subtype assignment and clinical data
nclust_tree_all = 6
subtype_hcl = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/subtype_hcl.rds")
clin_data_aligned = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/clin_data_aligned.rds")
extended_data = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/extended_data.rds")
```

# Correlation between subtype factors and integration factors (Extended Data Fig4D)
```{r correlation between subtype factors and integration factors, fig.height=6, fig.width=7}
n_factor = 40
factor_subtype = as.data.frame(mcia_results$mcia_factors[, 1:n_factor])
rownames(factor_subtype) = rownames(organized_data$datasets$plasma_proteomics_targeted)

factor_train = base_obj$mcia.factors.train
rownames(factor_train) = rownames(base_obj$clin.train)
factor_test = base_obj$mcia.factors.test
rownames(factor_test) = rownames(base_obj$clin.test)
factor_integration = rbind(factor_train, factor_test)

shared_sample = intersect(rownames(factor_subtype), rownames(factor_integration))
shared_sample = sort(shared_sample)

factor_subtype = factor_subtype[shared_sample,]
factor_subtype = apply(factor_subtype, 2, function(z) qqnorm(z, plot.it = F)$x)
factor_subtype[,1] = -factor_subtype[,1]
factor_integration = factor_integration[shared_sample,]
factor_integration = apply(factor_integration, 2, function(z) qqnorm(z, plot.it = F)$x)

cor_mat = matrix(NA, nrow = n_factor, ncol = n_factor)
for (i in 1:n_factor) {
  for (j in 1:n_factor) {
    cor_mat[i, j] = cor(factor_subtype[,i], factor_integration[,j])
  }
}
cor_mat = abs(cor_mat)
rownames(cor_mat) = paste0("F", 1:40)
colnames(cor_mat) = paste0("F", 1:40)

df_cor = as.data.frame(cor_mat)
df_cor = df_cor %>%
  rownames_to_column(var = "factor_subtype") %>%
  pivot_longer(-factor_subtype, names_to = "factor_integration", 
               values_to = "correlation")
df_cor$factor_subtype = factor(df_cor$factor_subtype)
df_cor$factor_subtype = factor(df_cor$factor_subtype, 
                               levels = paste0("F", 1:40))
df_cor$factor_integration = factor(df_cor$factor_integration)
df_cor$factor_integration = factor(df_cor$factor_integration,
                                   levels = paste0("F", 1:40))

ggplot(df_cor, aes(x = factor_subtype, y = factor_integration, 
                   fill = correlation)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "#284AA0", mid = "white", high = "#BC4A4A", 
                       midpoint = 0, name = expression("Absolute\nCorrelation"),
                       limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  theme_minimal() +
  labs(x = "Factor (Molecular Subtyping)", y = "Factor (Integration)") +
  theme(axis.ticks = element_line(linewidth = 0.5),  
        axis.line.x = element_line(linewidth = 1),
        axis.line.y = element_line(linewidth = 1),
        axis.text.y = element_text(size = 9, color = "black"),
        axis.text.x = element_text(size = 9, color = "black", angle = 90,
                                   vjust = 0.5),
        legend.title = element_text(size = 15, margin = margin(b = 20)),
        legend.text = element_text(size = 15),
        legend.spacing.y = unit(20, "pt"),
        axis.title.x = element_text(color = "black", size = 15,
                                    margin = margin(t = 10)),
        axis.title.y = element_text(color = "black", size = 15,
                                    margin = margin(r = 10)))
```

# Correlation between Factor 1 (Extended Data Fig4C)
```{r correlation between Factor 1, fig.height=6, fig.width=6}
factor1_subtype = factor_subtype[,1]
factor1_integration = factor_integration[,1]
df_factor1 = data.frame(factor1_subtype, factor1_integration)
factor1_test = cor.test(factor1_subtype, factor1_integration)
factor1_cor = round(factor1_test$estimate, 2)
factor1_pval = factor1_test$p.value

ggplot(df_factor1, aes(x = factor1_subtype, y = factor1_integration)) +
  geom_point(alpha = 0.4, color = "grey40") +  # scatter points
  geom_smooth(method = "lm", se = TRUE, color = "#BC4A4A", size = 1) +
  annotate("text", 
           x = min(df_factor1$factor1_subtype, na.rm = TRUE), 
           y = max(df_factor1$factor1_integration, na.rm = TRUE), 
           label = paste0("correlation = ", factor1_cor, ", p-value < 2.2e-16"), 
           hjust = 0, vjust = 1, size = 5) +
  theme_minimal() +
  labs(x = "Factor (Molecular Subtyping)", y = "Factor (Integration)") +
  theme(axis.ticks = element_line(linewidth = 0.5),  
        axis.line.x = element_line(linewidth = 1),
        axis.line.y = element_line(linewidth = 1),
        axis.text.y = element_text(size = 15, color = "black"),
        axis.text.x = element_text(size = 15, color = "black"),
        legend.title = element_text(size = 15, margin = margin(b = 20)),
        legend.text = element_text(size = 15),
        legend.spacing.y = unit(20, "pt"),
        axis.title.x = element_text(color = "black", size = 15,
                                    margin = margin(t = 10)),
        axis.title.y = element_text(color = "black", size = 15,
                                    margin = margin(r = 10)))
```


