---
title: "S1"
output: html_document
---

```{r load library}
library(ade4) #used in mcia
library(mogsa)
library(factoextra)
library(cluster)
library(nnet)
library(survival)
library(ordinal)
library(ggeffects)
library(openxlsx)
library(network)
library(GGally)
library(ggalt)
library(metafor)
library(cowplot)
library(survminer)
require(nlme) # directly provides p-values, unlike lme4
require(splines)
require(dplyr)
library(fgsea)
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
source("~/impacc/Analysis/molecular_subtyping/preliminary/helpers_LG202301.R")
source("~/impacc/Analysis/molecular_subtyping/code/S1/src/S1_helper.R")
date = "20230726"; inner_folds = 10
PACS_group = list(physical = c(2), cognitive = c(5), multiple = c(6))
path_impacc_analysis = "/scratch/data-integration/cleanedup/"
intermediate_results_outdir_DR = "/scratch/data-integration/molecular_subtyping/DimensionReduction/"
organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")
file_mcia = paste0(intermediate_results_outdir_DR,"MCIA_phase123_",date,".rds")
mcia_results = readRDS(file_mcia)

base_obj = readRDS(file ="/scratch/data-integration/cleanedup/mod1_interpretation_base.rds")
file_impacc_analysis = paste0(path_impacc_analysis,"impacc_analysis_record_innerfold", inner_folds,".rds")
impacc_analysis_record=readRDS(file = file_impacc_analysis)
data_path <- "/scratch/data-integration/pipelines/processedData/"
data_env0 <- readRDS(paste0(data_path, "data_env_ravi_20220513.RDS"))

clin_data_all = organized_data$clinical_data[,setdiff(colnames(organized_data$clinical_data), c("sample_id","sample_type", "phase1_2","samples_collected","phase"))]
clin_data_all = unique(clin_data_all)
clin_data_aligned = data_frame(event_id=rownames(organized_data$datasets$plasma_proteomics_targeted))
clin_data_aligned <- clin_data_aligned %>% left_join(clin_data_all, by = c("event_id"))
ll = which(clin_data_aligned$event_type %in% paste0("Visit ",1:6))
clin_data_aligned =clin_data_aligned[ll,]
mcia_factors= mcia_results$mcia_factors[ll,]
clin_data_aligned$conv_cluster6[is.na(clin_data_aligned$conv_cluster6)] = 999
clin_data_aligned$conv_physical_deficit = ifelse(clin_data_aligned$conv_cluster6%in%PACS_group$physical,1,0)
clin_data_aligned$conv_cognitive_deficit = ifelse(clin_data_aligned$conv_cluster6%in%PACS_group$cognitive,1,0)
clin_data_aligned$conv_global_deficit = ifelse(clin_data_aligned$conv_cluster6%in%PACS_group$multiple,1,0)
```

# Clustering data preparation
```{r data preparation}
n_factor = 40
factor_scores = mcia_factors[,1:n_factor]
# normalize factor scores
factor_scores = apply(factor_scores, 2, function(z) qqnorm(z, plot.it = F)$x)
# update factors that explain more consistent variation across assays
aa = (apply(sqrt(mcia_results$mcia_factor_evaluation$ave_variance_explained[1:n_factor,]),
            1, sum))^2
factor_scores = t(apply(factor_scores, 1, function(z) z*sqrt(aa)))
# flip the sign of factor1
factor_scores[,1] = -factor_scores[,1]

visit_max = 6
extended_data = make_data_long(factor_scores, sample_meta = clin_data_aligned, 
                               visit_max = visit_max, mean_removal = F)
X = extended_data$X
# upweight samples with convalesent outcomes
ll0 = which(clin_data_aligned$conv_cluster6 != 999)
extended_data_conv = make_data_long(factor_scores[ll0,], 
                                    sample_meta = clin_data_aligned[ll0,], 
                                    visit_max = visit_max, mean_removal = F)

participant_ids = rownames(extended_data$X)
other_features = colnames(clin_data_aligned)[grepl("comorb",colnames(clin_data_aligned)) |grepl("ever",colnames(clin_data_aligned))|grepl("comp",colnames(clin_data_aligned))]
clin_vars <- c("participant_id", "conv_cluster3", "conv_cluster6", 
               "conv_cognitive_deficit", "conv_physical_deficit", 
               "conv_global_deficit", "ethnicity", other_features)
clin_mat_use = data.frame(unique(clin_data_aligned[, clin_vars]))
rownames(clin_mat_use) = clin_mat_use$participant_id
clin_mat_use = clin_mat_use[participant_ids,]
tmp1 = extended_data$sample_meta_participant_level
tmp1$participant_id = NULL
clin_mat_use = cbind(clin_mat_use, tmp1)

id_PASC = (clin_mat_use$conv_cluster6 != 999)
PASCs = rep(NA, nrow(clin_mat_use))
PASCs[id_PASC] = ifelse(
  clin_mat_use$conv_cluster6[id_PASC]%in%PACS_group$physical, "physical",
  ifelse(clin_mat_use$conv_cluster6[id_PASC]%in%PACS_group$cognitive, "cognitive",
         ifelse(clin_mat_use$conv_cluster6[id_PASC]%in%PACS_group$multiple, "multiple",
                "minimal")))
PASCs = factor(PASCs, c("minimal", "physical", "cognitive", "multiple"))
clin_data_pasc = data.frame("participant_id" = clin_mat_use$participant_id,
                            "PASC_group" = PASCs)
clin_data_aligned = left_join(clin_data_aligned, clin_data_pasc, 
                              by = "participant_id")
```

# Hierarchical clustering
```{r hierarchical clustering}
dist_mat_all <- calculate_distance_matrix(X, n_factor, visit_max = visit_max)
dist_mat_conv <- calculate_distance_matrix(extended_data_conv$X, n_factor, 
                                           visit_max = visit_max)
participant_id_conv = rownames(extended_data_conv$X)
# Clustering using all participants
hcl_all <- hclust(d = dist_mat_all, method = "ward.D2")
# Clustering using convalesent participants
hcl_conv <- hclust(d = dist_mat_conv, method = "ward.D2")

Kmin = 5; Kmax= 10
k.values <- Kmin:Kmax
sil_values <- c()
avg_sil <- function(dist_obj, cluster) {
  ss <- silhouette(cluster, dist_obj)
  mean(ss[, 3])
}
for (k in k.values) {
  cluster_cut <- cutree(hcl_all, k)
  sil_values[k - Kmin+1] <- avg_sil(dist_obj  = dist(x = X[,1:n_factor]), 
                                    cluster_cut)
}

nclust_tree_conv = nclust_tree_all = k.values[which.max(sil_values)]

subtype_hcl_all = cutree(hcl_all, k = nclust_tree_all)
subtype_hcl_conv =  cutree(hcl_conv, k = nclust_tree_conv)
subtype_hcl = data.frame(full = subtype_hcl_all)
subtype_hcl$conv = NA
rownames(subtype_hcl) = names(subtype_hcl_all)
subtype_hcl[names(subtype_hcl_conv),]$conv = subtype_hcl_conv
subtype_hcl$PASC = PASCs
subtype_hcl$TG = factor(clin_mat_use$trajectory_group)

# S8 S3 S4 S5 S7 S1 S6 S2
# rename: SD, SC1, SC2, SE, SF, SA, SB1, SB2
# merge: SD, SC, SC, SE, SF, SA, SB, SB
mapping_label <- c("1" = "A", "2" = "B", "3" = "C", "4" = "C", 
                   "5" = "E", "6" = "B", "7" = "F", "8" = "D")
subtype_hcl$label <- mapping_label[as.character(subtype_hcl$full)]
# table(subtype_hcl$label, subtype_hcl$full)
nclust_tree_all = 6
```

# Cluster Dendrogram
```{r, fig.height=6, fig.width=8.5}
cluster_dendrogram <- fviz_dend(hcl_all, k = 8, show_labels = FALSE,
                                k_colors = c("#FFDC91B2", "#E18727B2", 
                                             "#E18727B2", "#EE4C97B2",
                                             "#BC3C29B2", "#20854EB2", 
                                             "#0072B5B2", "#0072B5B2"),
                                rect = TRUE, lwd = 0.6) + 
  ggtitle(paste0("Targeted Cluster Dendrogram")) +
  theme(plot.title = element_text(size = 15),
        axis.title.y = element_text(size = 15, margin = margin(r = 10)),
        axis.title.x = element_text(size = 15),
        axis.text.y = element_text(size = 15, color = "black"),
        axis.text.x = element_blank())
cluster_annot <- data.frame(x = c(15, 70, 230, 420, 535, 710, 890, 1040),
                            y = rep(-2.6, 8),
                            label = c("D", "C1", "C2", "E", 
                                      "F", "A", "B1", "B2"),
                            color = rep("grey50", 8), size = rep(4.5, 8), 
                            fontface = rep("bold", 8))
cluster_dendrogram +
  lapply(seq_len(nrow(cluster_annot)), function(i) {
    annotate("text", x = cluster_annot$x[i], y = cluster_annot$y[i], 
             label = cluster_annot$label[i], color = cluster_annot$color[i],
             size = cluster_annot$size[i], 
             fontface = cluster_annot$fontface[i])})
```

# t-test at each split of cluster dendrogram
```{r t-test at each split of cluster dendrogram}
branch_1 = cutree(hcl_all, k=2)
branch_1 = ifelse(branch_1 == 1, "right", "left")
branch_1_left_id = names(branch_1[branch_1 == "left"])
branch_1_right_id = names(branch_1[branch_1 == "right"])
split_t1 = split_t_test(branch_1_left_id, branch_1_right_id, 
                        n_factor, visit_max)

branch_2 = cutree(hcl_all, k=3)
branch_2 = branch_2[names(branch_2) %in% branch_1_right_id]
branch_2 = ifelse(branch_2 == 1, "right", "left")
branch_2_left_id = names(branch_2[branch_2 == "left"])
branch_2_right_id = names(branch_2[branch_2 == "right"])
split_t2 = split_t_test(branch_2_left_id, branch_2_right_id, 
                        n_factor, visit_max)

branch_3 = cutree(hcl_all, k=4)
branch_3 = branch_3[names(branch_3) %in% branch_2_right_id]
branch_3 = ifelse(branch_3 == 2, "right", "left")
branch_3_left_id = names(branch_3[branch_3 == "left"])
branch_3_right_id = names(branch_3[branch_3 == "right"])
split_t3 = split_t_test(branch_3_left_id, branch_3_right_id, 
                        n_factor, visit_max)

branch_4 = cutree(hcl_all, k=5)
branch_4 = branch_4[names(branch_4) %in% branch_3_right_id]
branch_4 = ifelse(branch_4 == 2, "right", "left")
branch_4_left_id = names(branch_4[branch_4 == "left"])
branch_4_right_id = names(branch_4[branch_4 == "right"])
split_t4 = split_t_test(branch_4_left_id, branch_4_right_id, 
                        n_factor, visit_max)

branch_5 = cutree(hcl_all, k=6)
branch_5 = branch_5[names(branch_5) %in% branch_1_left_id]
branch_5 = ifelse(branch_5 == 3, "right", "left")
branch_5_left_id = names(branch_5[branch_5 == "left"])
branch_5_right_id = names(branch_5[branch_5 == "right"])
split_t5 = split_t_test(branch_5_left_id, branch_5_right_id, 
                        n_factor, visit_max)

branch_6 = cutree(hcl_all, k=7)
branch_6 = branch_6[names(branch_6) %in% branch_2_left_id]
branch_6 = ifelse(branch_6 == 6, "right", "left")
branch_6_left_id = names(branch_6[branch_6 == "left"])
branch_6_right_id = names(branch_6[branch_6 == "right"])
split_t6 = split_t_test(branch_6_left_id, branch_6_right_id, 
                        n_factor, visit_max)

branch_7 = cutree(hcl_all, k=8)
branch_7 = branch_7[names(branch_7) %in% branch_5_right_id]
branch_7 = ifelse(branch_7 == 4, "right", "left")
branch_7_left_id = names(branch_7[branch_7 == "left"])
branch_7_right_id = names(branch_7[branch_7 == "right"])
split_t7 = split_t_test(branch_7_left_id, branch_7_right_id, 
                        n_factor, visit_max)
```

# Factor trajectory at each split
```{r factor trajectory at each split}
colnames(factor_scores) <- paste0("Factor", 1:ncol(factor_scores))
assay_mat <- as.data.frame(factor_scores)
assay_mat$event_id <- clin_data_aligned$event_id
assay_mat <- cytof_mat_preprocess(cytof_mat = assay_mat,
                                  subtype_hcl = subtype_hcl,
                                  clin_data = clin_data_aligned)
# branch 1
branch_longit <- data.frame("branch" = branch_1,
                            "participant_id" = names(branch_1))
plotDF = left_join(assay_mat, branch_longit, by = "participant_id")
clin_colnames_select <- setdiff(colnames(plotDF), colnames(factor_scores))

branch1_traj <- helper_trajectory_data_smooth_spline(
  assay_mat = plotDF, clin_colnames_select = clin_colnames_select,
  endpoint = "branch", use_endpoint_levels = c("left", "right"),
  subgroup_cr = c("left" = "#9C3418", "right" = "#39828C"), max_date = 40,
  legend_name = "Branch", feature_select = TRUE,
  feature_with_ylab = "Factor1")

# branch 2
branch_longit <- data.frame("branch" = branch_2,
                            "participant_id" = names(branch_2))
plotDF = left_join(assay_mat, branch_longit, by = "participant_id")
clin_colnames_select <- setdiff(colnames(plotDF), colnames(factor_scores))

branch2_traj <- helper_trajectory_data_smooth_spline(
  assay_mat = plotDF, clin_colnames_select = clin_colnames_select,
  endpoint = "branch", use_endpoint_levels = c("left", "right"),
  subgroup_cr = c("left" = "#9C3418", "right" = "#39828C"), max_date = 40,
  legend_name = "Branch", feature_select = TRUE,
  feature_with_ylab = "Factor1")

# branch 3
branch_longit <- data.frame("branch" = branch_3,
                            "participant_id" = names(branch_3))
plotDF = left_join(assay_mat, branch_longit, by = "participant_id")
clin_colnames_select <- setdiff(colnames(plotDF), colnames(factor_scores))

branch3_traj <- helper_trajectory_data_smooth_spline(
  assay_mat = plotDF, clin_colnames_select = clin_colnames_select,
  endpoint = "branch", use_endpoint_levels = c("left", "right"),
  subgroup_cr = c("left" = "#9C3418", "right" = "#39828C"), max_date = 40,
  legend_name = "Branch", feature_select = TRUE,
  feature_with_ylab = "Factor1")

# branch 5
branch_longit <- data.frame("branch" = branch_5,
                            "participant_id" = names(branch_5))
plotDF = left_join(assay_mat, branch_longit, by = "participant_id")
clin_colnames_select <- setdiff(colnames(plotDF), colnames(factor_scores))

branch5_traj <- helper_trajectory_data_smooth_spline(
  assay_mat = plotDF, clin_colnames_select = clin_colnames_select,
  endpoint = "branch", use_endpoint_levels = c("left", "right"),
  subgroup_cr = c("left" = "#9C3418", "right" = "#39828C"), max_date = 40,
  legend_name = "Branch", feature_select = TRUE,
  feature_with_ylab = "Factor1")

# branch 6
branch_longit <- data.frame("branch" = branch_6,
                            "participant_id" = names(branch_6))
plotDF = left_join(assay_mat, branch_longit, by = "participant_id")
clin_colnames_select <- setdiff(colnames(plotDF), colnames(factor_scores))

branch6_traj <- helper_trajectory_data_smooth_spline(
  assay_mat = plotDF, clin_colnames_select = clin_colnames_select,
  endpoint = "branch", use_endpoint_levels = c("left", "right"),
  subgroup_cr = c("left" = "#9C3418", "right" = "#39828C"), max_date = 40,
  legend_name = "Branch", feature_select = TRUE)
```

# Top factor selection
```{r top factor selection}
idx_factor_hcl1 = as.numeric(gsub("Factor", "", 
                                  branch1_traj$particular_interest_features))
idx_factor_hcl1 = idx_factor_hcl1[apply(split_t1$p_adjust[idx_factor_hcl1,],
                                        1, min, na.rm=TRUE) < 1e-8]
idx_factor_hcl1
idx_factor_hcl2 = as.numeric(gsub("Factor", "", 
                                  branch2_traj$particular_interest_features))
idx_factor_hcl2 = idx_factor_hcl2[apply(split_t2$p_adjust[idx_factor_hcl2,], 
                                        1, min, na.rm=TRUE) < 1e-8]
idx_factor_hcl2
idx_factor_hcl3 = as.numeric(gsub("Factor", "", 
                                  branch3_traj$particular_interest_features))
idx_factor_hcl3 = idx_factor_hcl3[apply(split_t3$p_adjust[idx_factor_hcl3,], 
                                        1, min, na.rm=TRUE) < 1e-8]
idx_factor_hcl3
idx_factor_hcl5 = as.numeric(gsub("Factor", "", 
                                  branch5_traj$particular_interest_features))
idx_factor_hcl5 = idx_factor_hcl5[apply(split_t5$p_adjust[idx_factor_hcl5,], 
                                        1, min, na.rm=TRUE) < 1e-8]
idx_factor_hcl5
idx_factor_hcl6 = as.numeric(gsub("Factor", "", 
                                  branch6_traj$particular_interest_features))
idx_factor_hcl6 = idx_factor_hcl6[apply(split_t6$p_adjust[idx_factor_hcl6,], 
                                        1, min, na.rm=TRUE) < 1e-8]
idx_factor_hcl6

test_S2B = list()
test_S2B$split1 = branch1_traj$test_pval_list
test_S2B$split2 = branch2_traj$test_pval_list
test_S2B$split3 = branch3_traj$test_pval_list
test_S2B$split4 = branch5_traj$test_pval_list
test_S2B$split5 = branch6_traj$test_pval_list
```

# Pie chart of top factors
```{r pie chart of top factors, warning=FALSE}
idx_factor = unique(c(idx_factor_hcl1, idx_factor_hcl2, idx_factor_hcl3,
                      idx_factor_hcl5, idx_factor_hcl6))
pie_plot(split_t1, idx_factor = idx_factor)
pie_plot(split_t2, idx_factor = idx_factor)
pie_plot(split_t3, idx_factor = idx_factor)
pie_plot(split_t5, idx_factor = idx_factor)
pie_plot(split_t6, idx_factor = idx_factor)

test_S2A = list()
test_S2A$split1 = split_t1
test_S2A$split2 = split_t2
test_S2A$split3 = split_t3
test_S2A$split4 = split_t5
test_S2A$split5 = split_t6
```

# Factor trajectory - split 1
```{r factor trajectory - split 1, fig.height=6, fig.width=24, warning=FALSE}
# split 1 (original split 2)
ggarrange(plotlist = branch1_traj$test_fig_list[paste0("Factor", idx_factor_hcl1)], 
          nrow = 1, common.legend = T)
```

# Factor trajectory - split 2,3,4
```{r factor trajectory - split 2,3,4, fig.height=6, fig.width=12, warning=FALSE}
# split 2 (original split 2)
ggarrange(plotlist = branch2_traj$test_fig_list[paste0("Factor", idx_factor_hcl2)], 
          nrow = 1, common.legend = T)
# split 3 (original split 3)
ggarrange(plotlist = branch3_traj$test_fig_list[paste0("Factor", idx_factor_hcl3)], 
          nrow = 1, common.legend = T)
# split 4 (original split 5)
ggarrange(plotlist = branch5_traj$test_fig_list[paste0("Factor", idx_factor_hcl5)], 
          nrow = 1, common.legend = T)
```

# Factor trajectory - split 5
```{r factor trajectory - split 5, fig.height=6, fig.width=6, warning=FALSE}
# split 5 (original split 6)
ggarrange(plotlist = branch6_traj$test_fig_list[paste0("Factor", idx_factor_hcl6)], 
          nrow = 1, common.legend = T)
```



