---
title: "Fig3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(circlize)
library(nlme)
library(igraph)
library(ggraph)
```



```{r load code and data, warning=FALSE, message=FALSE}

##### Load code
source("../../../0.Codebase/class_structures.R", local=FALSE, chdir=TRUE)

##### Load data object
base_obj1 = readRDS("/scratch/data-integration/public_code_results/mod1_interpretation_base.rds")

##### Load other data files, if any
kegg_database = readRDS(file = "/scratch/data-integration/pipelines/Interpretation/remapped_databases/kegg0522.rds")
hallmark_database = readRDS( file = "/scratch/data-integration/pipelines/Interpretation/remapped_databases/hallmark0522.rds")

path_impacc_analysis = "/scratch/data-integration/cleanedup/"
inner_folds = 10
file_impacc_analysis = paste0(path_impacc_analysis,"impacc_analysis_record_innerfold", inner_folds,".rds")
impacc_analysis_record = readRDS(file_impacc_analysis)



##### Set global variables
# Trajectory group colors
TrajGrpCol <- c("1" = "#639A21", "2" = "#39828C", "3" = "#6371AD", "4" = "#BD7D31", "5" = "#9C3418")

# Omic names: 
# note: ppt, ppgd, so, pmg, nt and pbmc correspond to PPT, PPG, SPT, PMG, NGX and PGX, respectively, in the manuscript.
omics_used_DR = c(
  "ppt" = "plasma_proteomics_targeted",
  "ppgd" = "plasma_proteomics_global_dda",
  "so" = "serum_olink",
  "pmg" = "plasma_metabolomics_global",
  "nt" = "nasal_transcriptomics",
  "pbmc" = "pbmc_transcriptomics"
)
omic_short_names = names(omics_used_DR) %>% setNames(omics_used_DR)


##### Output directory
out_dir = "../output/"
dir.create(out_dir, showWarnings = F)
```


## Panels A & B
```{r panels Main A & B}

phase = "train"
factor = 1
TrajGrpCol = c("#639A21", "#39828C",  "#6371AD","#BD7D31", "#9C3418") %>% setNames(paste0("TG", 1:5))
base_obj = base_obj1

require(ggbeeswarm)
factors <- apply(base_obj[[paste0("mcia.factors.", phase)]],2,function(z) qqnorm(z,plot.it = F)$x) %>%
  as.data.frame()

boxplot = cbind.data.frame(factors, base_obj[[paste0("clin.", phase)]]) %>%
  filter(event_type == "Visit 1") %>% 
  mutate(trajectory_group = paste0("TG", trajectory_group), fac_score = .[,factor]) %>%
  ggplot(aes(x=trajectory_group, y= scale(fac_score), color = as.factor(trajectory_group))) +
  scale_color_manual(values = unname(TrajGrpCol)) +
  geom_boxplot() +
  geom_quasirandom() +
  theme_classic() +
  theme(legend.position = "none") +
  coord_cartesian(ylim = c(-3,3)) +
  ylab("Factor 1") +
  xlab("Clinical Trajectory Group")

fake_loop <- data.frame(matrix(nrow=40,ncol=20))
fake_loop[is.na(fake_loop)] <- 1
rownames(fake_loop) <- paste0("V", 1:40)
trajplot = cbind.data.frame(factors, base_obj[[paste0("clin.", phase)]]) %>%
  mutate(fac_score = .[,factor]) %>%
  pivot_longer(cols = !!paste0("V",factor)) %>%
  mutate(trajectory_group = ordered(factor(trajectory_group)),
         sex = factor(sex),
         discretized_admit_age_quantile = ordered(factor(discretized_admit_age_quantile)),
         participant_id = factor(participant_id),
         enrollment_site = factor(enrollment_site)) %>%
  plot_model(p_adjust = NA, modelType = "smoothSpline", model_loop = fake_loop,
             knot_lines = F, CI = T)

# Print the output in md
print(boxplot)
# Print pdf file
pdf(file.path(out_dir, "Fig3A.pdf"), width=6, height=6)
print(boxplot)
dev.off()

# Print the output in md
print(trajplot)
# Print pdf file
pdf(file.path(out_dir, "Fig3B.pdf"), width=10, height=5)
print(trajplot)
dev.off()

write.csv(boxplot$data %>% dplyr::select(V1, trajectory_group), paste0(out_dir, "Fig3_data_panelA.csv"))
write.csv(trajplot$data %>% dplyr::select(fac_score, trajectory_group, event_date, participant_id), paste0(out_dir, "Fig3_data_panelB.csv"))
```

## Panel C
```{r panel Main C}

# Combine all enrichment results which will be used for generating the enrichment dotplot and network.
streamline_enrichment_results(base_obj1, datasets=c("ppt","ppgd","so","pmg","nt","pbmc"), databases = c("kegg","hallmark","immglob", "subpathway"))

combine_enrichment_results(base_obj1, databases = c("kegg","hallmark","smpdb","immglob", "metabSub","isgs"))


path1_finalOrder <- c("Neutrophil extracellular trap formation",
"HALLMARK_INFLAMMATORY_RESPONSE",
"Complement and coagulation cascades",
"TNF signaling pathway",
"HALLMARK_IL6_JAK_STAT3_SIGNALING",
"Platelet activation",
"Tryptophan metabolism",
"Histidine metabolism",
"Phenylalanine metabolism",
"Th1 and Th2 cell differentiation",
"Th17 cell differentiation",
"T cell receptor signaling pathway",
"Antigen processing and presentation",
"Necroptosis",
"Apoptosis")
mod1_dot = plot_enrichment_dot_v2(base_obj1, select_pathways = path1_finalOrder, thr=0.1, test_type = "mhg", databases = c("kegg","hallmark","subpathway"), auto_ordering = F, plot_title = "Factor 1")


# Print the output in md
print(mod1_dot)
# Print pdf file
pdf(file.path(out_dir, "Fig3C.pdf"), width=7, height=10)
print(mod1_dot)
dev.off()

write.csv(mod1_dot$data, paste0(out_dir, "Fig3_data_panelC.csv"))
```

## Panel D
```{r panel Main D}
# Pathways to plot in the network
path_for_network=c("HALLMARK_INFLAMMATORY_RESPONSE","Apoptosis","Complement and coagulation cascades","Histidine metabolism",
        "HALLMARK_IL6_JAK_STAT3_SIGNALING",
        #"Intestinal immune network for IgA production",
        "Necroptosis","Neutrophil extracellular trap formation","Phenylalanine metabolism","Platelet activation","T cell receptor signaling pathway","Th1 and Th2 cell differentiation","Th17 cell differentiation","TNF signaling pathway","Tryptophan metabolism","Antigen processing and presentation")

# Features of the select pathways to include in the network
feat_for_network = c("CTSG","H2AC20","H2AC1","H2AC8","NCF1","NCF2","NCF4","FGA","FGB","FGG","C2","CFB","C1QC","CR1","ITGAM","SOCS3","STAT3","ACTB","ACTG1","MMP9","FAS","JAG1","IL15RA","CXCL8","CXCL10","CD4","CD3E","CD3G","CD8A","HLA-DPB1","HLA-DRA","HLA-DMB","CTSD","CTSB","PLA2G4A","PYGL","FTL","HLA-A","HLA-B","HLA-C","HLA-E","TNF","IL6","kynurenate","kynurenine","quinolinate","picolinate","anthranilate","formiminoglutamate","1-methyl-4-imidazoleacetate","hydantoin-5-propionate","phenylalanine","N-acetylphenylalanine","phenyllactate (PLA)")

# Make the plot.
fac1_network = term_feature_network(base_obj1, pathways = unique(path_for_network), title="Factor 1", min_path_count = 1, REDUCED_GRAPH = F, version2 = T, select_features = feat_for_network)
fac1_network
png(file.path(out_dir, "Fig3D.png"), width=8, height=7, units = "in", res=600)
fac1_network
dev.off()

write.csv(fac1_network$data, paste0(out_dir, "Fig3_data_panelD.csv"))
```

# Panels E & F
```{r panel Main E & F, fig.height=8, fig.width=8, message=FALSE, warning=FALSE}
# FIG3EF: identify early separators of TG4 and TG5
#extrafont::font_import(prompt = F)
#extrafont::loadfonts()

# Combine and form joint p-value with a different test
pos_list = base_obj1$MODmghRes$kegg_pos_impacc
neg_list = base_obj1$MODmghRes$kegg_neg_impacc
agg_keggMHG = enrichment_aggregation(pos_list=pos_list, neg_list = neg_list)
#agg_keggMHG$pval_mat[agg_keggMHG$pval_mat$joint_adj<0.1,]
pos_list = base_obj1$MODmghRes$subpathway_pos_impacc
neg_list = base_obj1$MODmghRes$subpathway_neg_impacc
agg_subMHG = enrichment_aggregation(pos_list=pos_list, neg_list = neg_list)
#agg_subMHG$pval_mat[agg_subMHG$pval_mat$joint_adj<0.1,]
pos_list = base_obj1$MODmghRes$hallmark_pos_impacc
neg_list = base_obj1$MODmghRes$hallmark_neg_impacc
agg_hallmarkMHG = enrichment_aggregation(pos_list=pos_list, neg_list = neg_list)
#agg_hallmarkMHG$pval_mat[agg_hallmarkMHG$pval_mat$joint_adj<0.1,]

# TG tests for all pathway acticity and high contributing cytokines
composite_mat_subsetting = function(composite_score_mat_list,selected_pathways){
  pathway_vec = c()
  omic_vec = c()
  composiste_mat = NULL
  for(d in 1:length(composite_score_mat_list)){
    tmp_X = composite_score_mat_list[[d]]
    intersect_pathways = intersect(selected_pathways,colnames(tmp_X ))
    if(length(intersect_pathways)>0){
      tmp_X = tmp_X[,intersect_pathways]
      pathway_vec=c(pathway_vec,intersect_pathways)
      omic_vec = c(omic_vec,rep(names(composite_score_mat_list)[d], length(intersect_pathways)))
      if(is.null(composiste_mat)){
        composiste_mat  = as.matrix(tmp_X)
      }else{
        composiste_mat  = cbind( composiste_mat,as.matrix(tmp_X))
      }
    }
  }
  return(list(composiste_mat =composiste_mat , omic_vec=omic_vec,
         pathway_vec = pathway_vec))
}

simple_pathwaytest_wrapper = function(composite_mat, base_obj1, phase = "others", adjust = F){
  if(phase == "train"){
    clin_dat = base_obj1$clin.train
  }else{
    clin_dat =base_obj1$clin.test
  }
  W =model.matrix(~as.character(clin_dat$trajectory_group)+clin_dat$event_type+clin_dat$discretized_admit_age_quantile+clin_dat$sex-1)
  id1 = (!is.na(composite_mat[,1]))&(apply(is.na(W),1,sum)==0)
  clin_mat = clin_dat[id1,,drop = F]
  composite_mat=composite_mat[id1,]
  fitted = linear_effects_simple(feature_mat=composite_mat, clin_mat=clin_mat,adjust = adjust)
  return(fitted)
}


selected_pathways = c("HALLMARK_INFLAMMATORY_RESPONSE",
                      "HALLMARK_IL6_JAK_STAT3_SIGNALING",
                      "Neutrophil extracellular trap formation",
                      "Platelet activation" ,"Complement and coagulation cascades","TNF signaling pathway",
                      "T cell receptor signaling pathway",
                      "Th17 cell differentiation",
                      "Th1 and Th2 cell differentiation",
                      "Antigen processing and presentation",
                      "Apoptosis", "Necroptosis","Tryptophan metabolism","Histidine metabolism", "Phenylalanine metabolism")

KEGG_POS_subset = composite_mat_subsetting(composite_score_mat_list = base_obj1$composite_features_train$KEGG_POS,
                         selected_pathways = selected_pathways)
KEGG_NEG_subset = composite_mat_subsetting(composite_score_mat_list = base_obj1$composite_features_train$KEGG_NEG,
                         selected_pathways = selected_pathways)
Hallmark_POS_subset = composite_mat_subsetting(composite_score_mat_list = base_obj1$composite_features_train$HALLMARK_POS,
                         selected_pathways = selected_pathways)
composite_mat = cbind(Hallmark_POS_subset$composiste_mat, KEGG_POS_subset$composiste_mat, KEGG_NEG_subset$composiste_mat)
omic_vec = c(Hallmark_POS_subset$omic_vec, KEGG_POS_subset$omic_vec, KEGG_NEG_subset$omic_vec)
pathway_vec = c(Hallmark_POS_subset$pathway_vec, KEGG_POS_subset$pathway_vec, KEGG_NEG_subset$pathway_vec)
sign_vec = c(rep(1,length(Hallmark_POS_subset$omic_vec)),
             rep(1, length(KEGG_POS_subset$omic_vec)),
             rep(-1, length(KEGG_NEG_subset$omic_vec)))
cytokine_mat = base_obj1$assays.train$serum_olink[,rownames(base_obj1$short_list_features$unsigned_mod$so)]
metabolite_mat = base_obj1$assays.train$plasma_metabolomics_global[,rownames(base_obj1$short_list_features$unsigned_mod$pmg)]
omic_uniq = names(base_obj1$omic_names)
pathway_test_DF = data.frame(matrix(NA, ncol = 7, nrow = length(pathway_vec)))
for(i in 1:length(omic_uniq)){
  omic_name0 = omic_uniq[i]
  ii = which(omic_vec==omic_name0)
  if(length(ii)>0){
    pathway_test_DF[ii,1]=omic_name0
    pathway_test_DF[ii,2]=pathway_vec[ii]
    pathway_test_DF[ii,3] = sign_vec[ii]
    composite_mat_sub = composite_mat[,ii] 
    tmp = simple_pathwaytest_wrapper(composite_mat = composite_mat_sub,
                                                              base_obj1 = base_obj1,
                                                              phase = "train", adjust = F)
    tmp1 = simple_pathwaytest_wrapper(composite_mat = composite_mat_sub,
                                                              base_obj1 = base_obj1,
                                                              phase = "train", adjust = T)
    pathway_test_DF[ii,4:6] =tmp
    pathway_test_DF[ii,7] =tmp1[,2]
  }

}

tmp = simple_pathwaytest_wrapper(composite_mat =cytokine_mat,
                                                              base_obj1 = base_obj1,
                                                              phase = "train", adjust = F)
tmp1 = simple_pathwaytest_wrapper(composite_mat =cytokine_mat,
                                                              base_obj1 = base_obj1,
                                                              phase = "train", adjust = T)
olink_individual_test = cbind(tmp, tmp1[,2])

tmp = simple_pathwaytest_wrapper(composite_mat =metabolite_mat,
                                                              base_obj1 = base_obj1,
                                                              phase = "train", adjust = F)
tmp1 = simple_pathwaytest_wrapper(composite_mat =metabolite_mat,
                                                              base_obj1 = base_obj1,
                                                              phase = "train", adjust = T)
metabolite_individual_test = cbind(tmp, tmp1[,2])

colnames( pathway_test_DF) = c("omic", "pathway", "sign", colnames(tmp), "mortality_time_adj")

sign_olink = ifelse(rownames(olink_individual_test)%in%rownames(base_obj1$short_list_features$pos_mod$so),1,-1)
olink_individual_test =cbind(sign_olink,olink_individual_test)
olink_individual_test = data.frame(olink_individual_test)
colnames(olink_individual_test) =colnames( pathway_test_DF)[-c(1:2)]


sign_metabolite = ifelse(rownames(metabolite_individual_test)%in%rownames(base_obj1$short_list_features$pos_mod$pmg),1,-1)
metabolite_individual_test =cbind(sign_metabolite,metabolite_individual_test)
metabolite_individual_test = data.frame(metabolite_individual_test)
colnames(metabolite_individual_test) =colnames( pathway_test_DF)[-c(1:2)]



thr = 0.05
#Factor 1 is high in TG5 and we consider only consistent pathway activity
idx_pathway1 = which(pathway_test_DF$sign*pathway_test_DF$mortality>abs(log(thr, base = 10)))
#stability: at least 2 out of 3 are consistently significant: mortality 4|5, slope4|5, time adjusted mortality 4|5
idx_pathway2=as.integer(rownames(pathway_selection(signed_log10_pathway = pathway_test_DF[,c(5,6,7)], thr =thr)))
# HALLMARK_INFLAMMATORY_RESPONSE is not significant in ppgd, therefore removing it from the final plot
idx_pathway3 = which(! (pathway_test_DF$omic == "ppgd" & pathway_test_DF$pathway == 
                    "HALLMARK_INFLAMMATORY_RESPONSE"))

idx_pathway = intersect(intersect(idx_pathway1, idx_pathway2), idx_pathway3)
#pathway_test_DF[idx_pathway,]

# Plot pathway test
plotDF = pathway_test_DF[idx_pathway,c(1,2,4:6)]
plotDF = tidyr::gather(plotDF, key = "test", value = "signed_pvalue_log10", -pathway, -omic)
#cap for visualization
plotDF$signed_pvalue_log10[plotDF$signed_pvalue_log10>4] = 4
plotDF$signed_pvalue_log10[plotDF$signed_pvalue_log10< -4] = -4
plotDF$pval = 10**(-abs(plotDF$signed_pvalue_log10))
z= plotDF$pval
#plotDF$stars = ifelse(z>0.1, "", ifelse(z>0.05,".",ifelse(z>0.01, "*", ifelse(z>0.001,"**",ifelse(z>0.0001,"***","****")))))
plotDF$stars = ifelse(z <= 0.001, "***", ifelse(z <= 0.01,"**",ifelse(z <= 0.05, "*", "")))

b <- c(-4,  0, 4)
library(RColorBrewer)
colors <- c(brewer.pal(7, "RdBu")[7], "white",brewer.pal(7, "RdBu")[1])
plotDF$test = factor(plotDF$test, c("mortality", "slope5|4", "ordinal"))
#p1 = ggplot(plotDF, aes(y=pathway, x=test, fill= signed_pvalue_log10)) + 
#  geom_tile()+ scale_fill_gradientn(colors = colors, breaks = b, labels = format(b), limits = c(-4,4))+theme(legend.position="top",legend.box="horizontal",axis.title.x=element_blank(), axis.title.y=element_blank(),)+geom_text(aes(label=stars), color="black", size=5)+facet_grid(omic~.,scales = "free",space = "free", switch="y")+scale_y_discrete(position = "left") + guides(fill = guide_colourbar(title.position="top", title.vjust = -20, barwidth=8))
plotDF_E = plotDF

plotDF2 = plotDF %>% dplyr::select(omic, pathway, test, signed_pvalue_log10) %>% pivot_wider(names_from = test, values_from = signed_pvalue_log10)
plotDF3 = plotDF %>% dplyr::select(omic, pathway, test, stars) %>% pivot_wider(names_from = test, values_from = stars)
col_fun = colorRamp2(c(0, max(plotDF$signed_pvalue_log10) ), c("white", pals::brewer.rdbu(11)[2]))
p1 = ComplexHeatmap::Heatmap(plotDF2[,c(2,4,5,3)] %>% column_to_rownames("pathway"), split = plotDF2$omic, 
                             cell_fun = function(j, i, x, y, w, h, col) { # add text to each grid
                                 grid.text(plotDF3[,c(4,5,3)][i, j], x, y)
                             },
                             col = col_fun,
                             cluster_rows = F, cluster_columns = F)
#FIG3EF = list()
#FIG3EF[["FIG3E"]] = p1
# Print the output in md
print(p1)
# Print pdf file
pdf(file.path(out_dir, "Fig3E.pdf"), width=10, height=5)
print(p1)
dev.off()


idx_olink1 = rownames(olink_individual_test)[which(olink_individual_test$sign*olink_individual_test$mortality>abs(log(thr, base = 10)))]
idx_olink2 =rownames(pathway_selection(signed_log10_pathway = olink_individual_test[,c(3:5)], thr =thr))
idx_olink = intersect(idx_olink1, idx_olink2)
#olink_individual_test[idx_olink,]


idx_metabolite1 = rownames(metabolite_individual_test)[which(metabolite_individual_test$sign*metabolite_individual_test$mortality>abs(log(thr, base = 10)))]
idx_metabolite2 =rownames(pathway_selection(signed_log10_pathway = metabolite_individual_test[,c(3:5)], thr =thr))
idx_metabolite = intersect(idx_metabolite1, idx_metabolite2)
#metabolite_individual_test[idx_metabolite,]
#olink_individual_test[idx_olink,]
shortlist_fnames = list(so = olink_individual_test[idx_olink,3,drop = F])
tmp_res1 = base_obj1$runMGH(short_list_coef =shortlist_fnames, 
                Term2GeneList = hallmark_database, 
                backround = "impacc")


shortlist_fnames = list(pmg = metabolite_individual_test[idx_metabolite,3,drop = F])
tmp_res2 = base_obj1$runMGH(short_list_coef =shortlist_fnames, 
                Term2GeneList = kegg_database, 
                backround = "impacc")
#head(tmp_res2$pmg, n =10)

##we did not find any additional pathways for both metabolite and olink, 50 metabolites are selected while only 6 olink features are selected

#show a heatmap of individual metabolites of all enriched pathways separate TG5|4 (together with TG5|4 filetered)
pathway_names = c("Tryptophan metabolism","Histidine metabolism","Phenylalanine metabolism")
IDs=base_obj1$MODmghRes$kegg_pos_impacc$pmg$ID
core_enrichment = strsplit(base_obj1$MODmghRes$kegg_pos_impacc$pmg$core_enrichment,"#")
metabolite_selected = c()
pathway_selected = c()
for(j in pathway_names){
  i = which(IDs==j)
  metabolite_selected=c(metabolite_selected,core_enrichment[[i]])
  pathway_selected = c( pathway_selected , rep(j, length(core_enrichment[[i]])))
}
pathway_selected = sapply(strsplit(pathway_selected," "),function(z) z[1])
plotDF =data.frame(pathway =pathway_selected, metabolite = metabolite_selected)
plotDF=cbind(plotDF,metabolite_individual_test[metabolite_selected,2:4]) 
plotDF = tidyr::gather(plotDF, key = "test", value = "signed_pvalue_log10", -pathway, -metabolite)
#cap for visualization
plotDF$signed_pvalue_log10[plotDF$signed_pvalue_log10>4] = 4
plotDF$signed_pvalue_log10[plotDF$signed_pvalue_log10< -4] = -4
plotDF$pval = 10**(-abs(plotDF$signed_pvalue_log10))
z= plotDF$pval
#plotDF$stars = ifelse(z>0.1, "", ifelse(z>0.05,".",ifelse(z>0.01, "*", ifelse(z>0.001,"**",ifelse(z>0.0001,"***","****")))))
plotDF$stars = ifelse(z <= 0.001, "***", ifelse(z <= 0.01,"**",ifelse(z <= 0.05, "*", "")))

plotDF$test = factor(plotDF$test, c("mortality", "slope5|4", "ordinal"))
plotDF$pathway = factor(plotDF$pathway, levels = c("Tryptophan","Phenylalanine","Histidine"))

#p2 = ggplot(plotDF, aes(y=metabolite, x=test, fill= signed_pvalue_log10)) + 
#  geom_tile()+ scale_fill_gradientn(colors = colors, breaks = b, labels = format(b), limits = c(-4,4))+theme(legend.position="none",legend.box="verticall",axis.title.x=element_blank(), axis.title.y=element_blank(),)+geom_text(aes(label=stars), color="black", size=5)+facet_grid(pathway~.,scales = "free",space = "free", switch="y")+scale_y_discrete(position = "left")
plotDF_F = plotDF

plotDF2 = plotDF %>% dplyr::select(pathway, metabolite, test, signed_pvalue_log10) %>% pivot_wider(names_from = test, values_from = signed_pvalue_log10)
plotDF3 = plotDF %>% dplyr::select(pathway, metabolite, test, stars) %>% pivot_wider(names_from = test, values_from = stars)
col_fun = colorRamp2(c(0, max(plotDF$signed_pvalue_log10) ), c("white", pals::brewer.rdbu(11)[2]))
p2 = ComplexHeatmap::Heatmap(plotDF2[,c(2,4,5,3)] %>% column_to_rownames("metabolite"), split = plotDF2$pathway, 
                        cell_fun = function(j, i, x, y, w, h, col) { # add text to each grid
                            grid.text(plotDF3[,c(4,5,3)][i, j], x, y)
                        },
                        col = col_fun,
                        cluster_rows = F, cluster_columns = F)


#FIG3EF[["FIG3F"]] = p2


# Print the output in md
print(p2)
# Print pdf file
pdf(file.path(out_dir, "Fig3F.pdf"), width=10, height=5)
print(p2)
dev.off()


#saveRDS(object = FIG3FG, file = "/scratch/data-integration/manuscriptFIGS/Factor1FIG3FG.rds")

write.csv(plotDF_E, paste0(out_dir, "Fig3_data_panelE.csv"))
write.csv(plotDF_F, paste0(out_dir, "Fig3_data_panelF.csv"))


```


## Panel G
```{r panel Main G, fig.height=8, fig.width=8, message=FALSE, warning=FALSE}
active_factor = "Factor1"
## This will generate for train only

## Right now requires the base_obj1 from the cleanedup folder be used
tmp.cytof <- as.data.frame(base_obj1$others$bld_cytof$train$bld_cytof_counts)
## Correct the typo in CyTOF
colnames(tmp.cytof)[grepl("Hematop", colnames(tmp.cytof))] <- "Hematopoetic progenitor Cell"
cytof_rowfeatures <- as.data.frame(base_obj1$others$bld_cytof$train$bld_cytof_rowfeature)
rownames(cytof_rowfeatures)[grepl("Hematop", rownames(cytof_rowfeatures))] <- "Hematopoetic progenitor Cell"
cytof_rowfeatures$`Broad Parent Population`[grepl("Hematop", cytof_rowfeatures$`Broad Parent Population`)] <- "Hematopoetic progenitor Cell"
colnames(cytof_rowfeatures) <- gsub("\\.", " ", colnames(cytof_rowfeatures))
tmp.cytof.parent <- base_obj1$others$bld_cytof$CyTOF_normalize(counts = tmp.cytof,
                                                               log1p = TRUE,
                                                               granulocytes = TRUE,
                                                               population = "parent",
                                                           rowfeature = cytof_rowfeatures)

## Generate Factor df
#factors <- rbind.data.frame(base_obj1$mcia.factors.train)
factors <- apply(base_obj1$mcia.factors.train,2,function(z) qqnorm(z,plot.it = F)$x) %>%
  as.data.frame() 
rownames(factors) <- rownames(base_obj1$clin.train)
colnames(factors) <- paste0("Factor", 1:40)

prep.data <- merge(factors, tmp.cytof.parent, by = 0)
tmp.long <- prep.data %>%
  mutate(cohort = ifelse(Row.names %in% base_obj1$clin.train$event_id, "train", "test")) %>%
  filter(cohort == "train") %>%
  pivot_longer(cols = `B Cell`:`Neutrophil`) %>%
  rename(event_id = Row.names) %>%
  left_join(rbind.data.frame(base_obj1$clin.train, base_obj1$clin.test) %>% dplyr::select(trajectory_group,enrollment_site, event_id, participant_id, sex, discretized_admit_age_quantile)) %>%
  filter(!is.na(value)) %>%
  mutate(trajectory_group = ordered(trajectory_group),
         sex = factor(sex),
         discretized_admit_age_quantile = ordered(discretized_admit_age_quantile),
         cohort = factor(cohort),
         participant_id = factor(participant_id),
         enrollment_site = factor(enrollment_site)) 
cor_res <- cor_loop(mat1 = as.data.frame(prep.data[,active_factor]),
                    mat2 = (prep.data[, colnames(prep.data) %in%
                                        colnames(tmp.cytof.parent)]))
cor_res <- cor_res[cor_res$Feature != "T Cell",] ## Remove somewhat unknown T Cells per advice from CyTOF team
cor_res <- cor_res[match(c("B Cell", "CD4 T Cell", "CD8 T Cell",
                           "gd T Cell", "NK Cell", "ILC",
                           "Hematopoetic progenitor Cell",
                           "Monocytes", "Neutrophil", "Eosinophil",
                           "Basophil", "Conventional DC",
                           "Plasmacytoid DC"), cor_res$Feature),]
out.p <- model_cell_pop(tmp.long, active_factor = active_factor)
cor_res <- cor_res %>% dplyr::select(-p.adj) %>%
  left_join(out.p %>% dplyr::select(-Factor)) %>%
  mutate(p.adj = p.adjust(as.numeric(p.model), "fdr")) %>%
  mutate(p.adj.star = ifelse(p.adj <= 0.001, "***",
                             ifelse(p.adj <= 0.01, "**", 
                                    ifelse(p.adj <= 0.05, "*", "")))) %>%
  mutate(p.adj.star = ifelse(is.na(p.adj), "", p.adj.star)) %>%
  mutate(coefficient_s = scale_tidy(coefficient))

##############################################################################
## Repeat for the child populations
tmp.cytof.child <- base_obj1$others$bld_cytof$CyTOF_normalize(counts = tmp.cytof,
                                                               log1p = TRUE,
                                                               granulocytes = TRUE,
                                                               population = "children",
                                                           rowfeature = cytof_rowfeatures)
prep.data <- merge(factors, tmp.cytof.child, by = 0)
cor_res2 <- cor_loop(mat1 = as.data.frame(prep.data[,active_factor,drop=FALSE]),
                     mat2 = (prep.data[colnames(prep.data) %in% colnames(tmp.cytof.child)]))
tmp.long <- prep.data %>%
  mutate(cohort = ifelse(Row.names %in% base_obj1$clin.train$event_id, "train", "test")) %>%
  filter(cohort == "train") %>%
  pivot_longer(cols = `B Cell (CD11c+ CXCR5-)`:`Neutrophil (CD16low)`) %>% 
  rename(event_id = Row.names) %>%
  left_join(rbind.data.frame(base_obj1$clin.train, base_obj1$clin.test) %>%
        dplyr::select(trajectory_group,enrollment_site, event_id, participant_id, sex, discretized_admit_age_quantile)) %>%
  filter(!is.na(value)) %>%
  mutate(trajectory_group = ordered(trajectory_group),
         sex = factor(sex),
         discretized_admit_age_quantile = ordered(discretized_admit_age_quantile),
         cohort = factor(cohort),
         participant_id = factor(participant_id),
         enrollment_site = factor(enrollment_site)) 
out.p <- model_cell_pop(tmp.long, active_factor = active_factor)
cor_res2 <- cor_res2 %>% dplyr::select(-p.adj) %>%
  left_join(out.p %>% dplyr::select(-Factor)) %>%
  mutate(p.adj = p.adjust(as.numeric(p.model), "fdr")) %>%
  mutate(p.adj.star = ifelse(p.adj <= 0.001, "***",
                             ifelse(p.adj <= 0.01, "**", 
                                    ifelse(p.adj <= 0.05, "*", "")))) %>%
  mutate(p.adj.star = ifelse(is.na(p.adj), "", p.adj.star)) %>%
  mutate(coefficient_s = scale_tidy(coefficient))
##############################################################################
## Make main df for heatmap
heatdf <- cor_res2 %>%
  left_join(cytof_rowfeatures %>% rownames_to_column("Feature")) %>%
  mutate(p.adj = ifelse(p.adj <= 0.001, "***", ifelse(p.adj <= 0.01, "**", 
                               ifelse(p.adj <= 0.05, "*", "")))) %>%
  mutate(p.adj = ifelse(is.na(p.adj), "", p.adj)) %>%
  arrange(`Broad Parent Population`) %>%
  left_join(cor_res %>% mutate(Feature = ifelse(Feature == "CD4 T Cell", "CD4+ T Cell",
                                                ifelse(Feature == "CD8 T Cell", "CD8+ T Cell", Feature))), by = c("Broad Parent Population" = "Feature")) %>%
  filter(!grepl("Undefined", Feature)) %>%
  mutate(p.adj.y = ifelse(p.adj.y <= 0.001, "***", ifelse(p.adj.y <= 0.01, "**", 
                                 ifelse(p.adj.y <= 0.05, "*", ""))))  %>%
  mutate(`Broad Parent Population` = gsub("Plasmacytoid ", "p", gsub("Conventional ", "c", gsub("Hematopoetic progenitor Cell", "HPC", `Broad Parent Population`))))

## Reorder the factor so I can get the relevant populations next to one another in the circle
heatdf <- heatdf %>%
  mutate(`Broad Parent Population` = factor(`Broad Parent Population`, levels = c("B Cell", "CD4+ T Cell", "CD8+ T Cell", "gd T Cell", "NK Cell", "ILC", "HPC", "Monocytes", "pDC", "cDC", "Neutrophil", "Eosinophil", "Basophil"))) %>%
  arrange(`Broad Parent Population`)

## Declaring the track height, this is global setting that applies to all tracks
circos.par("track.height" = 0.05)
## Define color palette for the rings
col_fun = colorRamp2(c(-3, 0, 3), c("blue", "white", "red"))
## This line technically isn't necessary, but there is a bug that sometimes necessitate you run it at the beginning of your session
## (You also need to run this to clear the plotting window if you want to rerender or start the plot again)
circos.clear()
pdf(file.path(out_dir, "Fig3G.pdf"), width=8, height=6)
## Generate simplified dataframe ensuring variable are proper data types
heat_circle <- heatdf %>%
  mutate(Feature = ifelse(Feature == "CD4+ Treg (naive)", "Treg Naive", Feature)) %>%
  mutate(Feature = gsub(".*\\(", "", gsub(")", "", Feature))) %>%
  mutate(Feature = ifelse(`Broad Parent Population` %in% c("CD8+ T Cell",
                                                         "B Cell"),
                          ifelse(`Broad Parent Population` %in% c("B Cell"),
                                 paste0(Feature, " B"), paste0("T8 ", Feature)), Feature)) %>%
  column_to_rownames("Feature") %>%
  dplyr::select(coefficient_s.x, p.adj.x) %>%
  mutate(coefficient_s.x = as.numeric(coefficient_s.x)) %>%
  as.data.frame() 
## Define splitting vector which is used for grouping child populations by their parents
split <- factor(heatdf$`Broad Parent Population`)
circos.heatmap(heat_circle %>% dplyr::select(coefficient_s.x), col = col_fun, cluster = F, split = split, #show.sector.labels =T,
               rownames.side = "outside", bg.border = "black", #cell.border = "black",
               rownames.cex = 0.6, #cell.lwd = 0.2, 
               track.height = 0.1)

## Again generate a simplified dataframe for plotting, but for the parent populations this time
heatdf_p <- heatdf %>%
  dplyr::select(coefficient_s.y, p.adj.y)
heatdf_p_stars <- heatdf %>%
  distinct(`Broad Parent Population`,p.adj.y) %>%
  dplyr::select(p.adj.y)

split_parent <- factor(heatdf_p$coefficient_s.y)
circos.heatmap(heatdf_p %>% dplyr::select(coefficient_s.y),
               cluster = F, col = col_fun, split = split_parent,
               bg.border = "black", track.height = 0.1)

## Annotate significance of parent populations
##    (Sadly I can't find a way to automate the child populations as well if
##     a split/group exists between the rings, ie I manually annotate)
circos.track(ylim = c(0, 1), track.index = 3, panel.fun = function(x, y) {
  circos.text(CELL_META$xcenter, CELL_META$cell.ylim[2] + convert_y(0, "mm"), 
              paste0(heatdf_p_stars$p.adj.y[CELL_META$sector.numeric.index]),
              facing = "clockwise", cex = 0.5,
              adj = c(1.5,0.5), niceFacing = TRUE)
}, bg.border = NA)

## Annotate parent population text labels inside the ring
circos.track(ylim = c(0, 1), track.index = 3, panel.fun = function(x, y) {
  circos.text(CELL_META$xcenter, CELL_META$cell.ylim[2] + convert_y(-13, "mm"), 
              paste0(levels(split)[CELL_META$sector.numeric.index]),
              facing = "bending.outside", cex = 0.5,
              adj = c( 0.5, 1), niceFacing = TRUE)
}, bg.border = NA)

## Add a legend to the top right of the figure
lgd = Legend(title = "Rho", col_fun = col_fun)
draw(lgd, x = unit(0.95, "npc"), y = unit(0.85, "npc"), just = c("right", "top"))
dev.off()

write.csv(heatdf %>% dplyr::select(Factor.x, Feature, coefficient_s.x, p.adj.x,
                                   `Broad Parent Population`, coefficient_s.y, p.adj.y), paste0(out_dir, "Fig3_data_panelG.csv"))
```


