---
title: "Fig1"
output: pdf_document
---

```{r load library}
library(ade4) #used in mcia
library(mogsa)
library(factoextra)
library(cluster)
library(nnet)
library(survival)
library(ordinal)
library(ggeffects)
library(openxlsx)
library(network)
library(GGally)
library(ggalt)
library(metafor)
library(cowplot)
library(survminer)
require(nlme) # directly provides p-values, unlike lme4
require(splines)
require(dplyr)
library(fgsea)
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
source(paste0(codebase_path,"/codebase_subtype.R"))

organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")

intermediate_results_outdir_DR = "/scratch/data-integration/molecular_subtyping/DimensionReduction/"
mcia_results = readRDS(paste0(intermediate_results_outdir_DR,"MCIA_phase123_20230726.rds"))

data_path <- "/scratch/data-integration/pipelines/processedData/"
data_env0 <- readRDS(paste0(data_path, "data_env_ravi_20220513.RDS"))

PACS_group = list(physical = c(2), cognitive = c(5), multiple = c(6))
clin_data_all = organized_data$clinical_data[,setdiff(colnames(organized_data$clinical_data), c("sample_id","sample_type", "phase1_2","samples_collected","phase"))]
clin_data_all = unique(clin_data_all)
clin_data_aligned = data_frame(event_id=rownames(organized_data$datasets$plasma_proteomics_targeted))
clin_data_aligned <- clin_data_aligned %>% left_join(clin_data_all, by = c("event_id"))
ll = which(clin_data_aligned$event_type %in% paste0("Visit ",1:6))
clin_data_aligned =clin_data_aligned[ll,]
mcia_factors= mcia_results$mcia_factors[ll,]
clin_data_aligned$conv_cluster6[is.na(clin_data_aligned$conv_cluster6)] = 999
clin_data_aligned$conv_physical_deficit = ifelse(clin_data_aligned$conv_cluster6%in%PACS_group$physical,1,0)
clin_data_aligned$conv_cognitive_deficit = ifelse(clin_data_aligned$conv_cluster6%in%PACS_group$cognitive,1,0)
clin_data_aligned$conv_global_deficit = ifelse(clin_data_aligned$conv_cluster6%in%PACS_group$multiple,1,0)
```

# Clustering data preparation
```{r data preparation}
n_factor = 40
factor_scores = mcia_factors[,1:n_factor]
# normalize factor scores
factor_scores = apply(factor_scores, 2, function(z) qqnorm(z, plot.it = F)$x)
# update factors that explain more consistent variation across assays
aa = (apply(sqrt(mcia_results$mcia_factor_evaluation$ave_variance_explained[1:n_factor,]),
            1, sum))^2
factor_scores = t(apply(factor_scores, 1, function(z) z*sqrt(aa)))
# flip the sign of factor1
factor_scores[,1] = -factor_scores[,1]

visit_max = 6
extended_data = make_data_long(factor_scores, sample_meta = clin_data_aligned, 
                               visit_max = visit_max, mean_removal = F)
X = extended_data$X
# upweight samples with convalesent outcomes
ll0 = which(clin_data_aligned$conv_cluster6 != 999)
extended_data_conv = make_data_long(factor_scores[ll0,], 
                                    sample_meta = clin_data_aligned[ll0,], 
                                    visit_max = visit_max, mean_removal = F)

participant_ids = rownames(extended_data$X)
other_features = colnames(clin_data_aligned)[grepl("comorb",colnames(clin_data_aligned)) |grepl("ever",colnames(clin_data_aligned))|grepl("comp",colnames(clin_data_aligned))]
clin_vars <- c("participant_id", "conv_cluster3", "conv_cluster6", 
               "conv_cognitive_deficit", "conv_physical_deficit", 
               "conv_global_deficit", "ethnicity", other_features)
clin_mat_use = data.frame(unique(clin_data_aligned[, clin_vars]))
rownames(clin_mat_use) = clin_mat_use$participant_id
clin_mat_use = clin_mat_use[participant_ids,]
tmp1 = extended_data$sample_meta_participant_level
tmp1$participant_id = NULL
clin_mat_use = cbind(clin_mat_use, tmp1)

id_PASC = (clin_mat_use$conv_cluster6 != 999)
PASCs = rep(NA, nrow(clin_mat_use))
PASCs[id_PASC] = ifelse(
  clin_mat_use$conv_cluster6[id_PASC]%in%PACS_group$physical, "physical",
  ifelse(clin_mat_use$conv_cluster6[id_PASC]%in%PACS_group$cognitive, "cognitive",
         ifelse(clin_mat_use$conv_cluster6[id_PASC]%in%PACS_group$multiple, "multiple",
                "minimal")))
PASCs = factor(PASCs, c("minimal", "physical", "cognitive", "multiple"))
clin_data_pasc = data.frame("participant_id" = clin_mat_use$participant_id,
                            "PASC_group" = PASCs)
clin_data_aligned = left_join(clin_data_aligned, clin_data_pasc, 
                              by = "participant_id")
```

# Hierarchical clustering
```{r hierarchical clustering}
dist_mat_all <- calculate_distance_matrix(X, n_factor, visit_max = visit_max)
dist_mat_conv <- calculate_distance_matrix(extended_data_conv$X, n_factor, 
                                           visit_max = visit_max)
participant_id_conv = rownames(extended_data_conv$X)
# Clustering using all participants
hcl_all <- hclust(d = dist_mat_all, method = "ward.D2")
# Clustering using convalesent participants
hcl_conv <- hclust(d = dist_mat_conv, method = "ward.D2")

Kmin = 5; Kmax= 10
k.values <- Kmin:Kmax
sil_values <- c()
avg_sil <- function(dist_obj, cluster) {
  ss <- silhouette(cluster, dist_obj)
  mean(ss[, 3])
}
for (k in k.values) {
  cluster_cut <- cutree(hcl_all, k)
  sil_values[k - Kmin+1] <- avg_sil(dist_obj  = dist(x = X[,1:n_factor]), 
                                    cluster_cut)
}

nclust_tree_conv = nclust_tree_all = k.values[which.max(sil_values)]

subtype_hcl_all = cutree(hcl_all, k = nclust_tree_all)
subtype_hcl_conv =  cutree(hcl_conv, k = nclust_tree_conv)
subtype_hcl = data.frame(full = subtype_hcl_all)
subtype_hcl$conv = NA
rownames(subtype_hcl) = names(subtype_hcl_all)
subtype_hcl[names(subtype_hcl_conv),]$conv = subtype_hcl_conv
subtype_hcl$PASC = PASCs
subtype_hcl$TG = factor(clin_mat_use$trajectory_group)

# S8 S3 S4 S5 S7 S1 S6 S2
# rename: SD, SC1, SC2, SE, SF, SA, SB1, SB2
# merge: SD, SC, SC, SE, SF, SA, SB, SB
mapping_label <- c("1" = "A", "2" = "B", "3" = "C", "4" = "C", 
                   "5" = "E", "6" = "B", "7" = "F", "8" = "D")
subtype_hcl$label <- mapping_label[as.character(subtype_hcl$full)]
# table(subtype_hcl$label, subtype_hcl$full)
nclust_tree_all = 6
```

# Network plot - 6 clusters (Figure 1D)
```{r network plot, fig.height=6, fig.width=9}
net_hcl <- as.matrix(dist_mat_all)
net_hcl <- network(net_hcl, directed=FALSE)
net_subtype <- as.factor(subtype_hcl$label)
levels(net_subtype) <- paste("Subtype", LETTERS[1:nclust_tree_all])
net_hcl %v% "Subtype" <- as.character(net_subtype)

network_plot <- ggnet2(net_hcl, node.size = 1, node.color = "Subtype", 
                       node.alpha = 0.5,
  palette = c("Subtype A" = "#20854EB2", "Subtype B" = "#0072B5B2",
              "Subtype C" = "#E18727B2", "Subtype D" = "#FFDC91B2",
              "Subtype E" = "#EE4C97B2", "Subtype F" = "#BC3C29B2"),
  edge.size = 0.1, edge.color = c("color", "white"),
  edge.alpha = 0.6, legend.size = 12, mode = "mds",
  layout.par = list(var="user", dist="none", vm=dist_mat_all, exp=0.1))

network_plot_data <- ggplot_build(network_plot)$data[[2]]
major_points <- network_plot_data %>%
    group_by(group) %>%
    mutate(centroid_x = mean(x), 
           centroid_y = mean(y),
           distance = sqrt((x - centroid_x)^2 + (y - centroid_y)^2)) %>%
    arrange(group, distance) %>%
    group_by(group) %>%
    slice_head(prop = 0.6)

network_plot +
  geom_encircle(data = major_points[major_points$group == 1, ], 
                aes(x = x, y = y, group = group), 
                color = "#20854EB2", fill = "#20854EB2",
                size = 1.5, linetype = "dashed", alpha = 0.5) +
  geom_text(aes(x = major_points$centroid_x[major_points$group == 1][1]+0.1, 
                y = major_points$centroid_y[major_points$group == 1][1]+0.1), 
            label = "A", color = "grey20", size = 8) +
  geom_encircle(data = major_points[major_points$group == 2, ], 
                aes(x = x, y = y, group = group), 
                color = "#0072B5B2", fill = "#0072B5B2",
                size = 1.5, linetype = "dashed", alpha = 0.5) +
   geom_text(aes(x = major_points$centroid_x[major_points$group == 2][1]-0.1, 
                 y = major_points$centroid_y[major_points$group == 2][1]+0.1), 
             label = "B", color = "grey40", size = 8) +
  geom_encircle(data = major_points[major_points$group == 3, ], 
                aes(x = x, y = y, group = group), 
                color = "#E18727B2", fill = "#E18727B2",
                size = 1.5, linetype = "dashed", alpha = 0.5) +
   geom_text(aes(x = major_points$centroid_x[major_points$group == 3][1]-0.1, 
                 y = major_points$centroid_y[major_points$group == 3][1]), 
             label = "C", color = "grey40", size = 8) +
  geom_encircle(data = major_points[major_points$group == 4, ], 
                aes(x = x, y = y, group = group), 
                color = "#FFDC91B2", fill = "#FFDC91B2",
                size = 1.5, linetype = "dashed", alpha = 0.5) +
   geom_text(aes(x = major_points$centroid_x[major_points$group == 4][1], 
                 y = major_points$centroid_y[major_points$group == 4][1]), 
             label = "D", color = "grey40", size = 8) +
  geom_encircle(data = major_points[major_points$group == 5, ], 
                aes(x = x, y = y, group = group), 
                color = "#EE4C97B2", fill = "#EE4C97B2",
                size = 1.5, linetype = "dashed", alpha = 0.5) +
   geom_text(aes(x = major_points$centroid_x[major_points$group == 5][1]+0.1, 
                 y = major_points$centroid_y[major_points$group == 5][1]), 
             label = "E", color = "grey40", size = 8) +
  geom_encircle(data = major_points[major_points$group == 6, ], 
                aes(x = x, y = y, group = group), 
                color = "#BC3C29B2", fill = "#BC3C29B2",
                size = 1.5, linetype = "dashed", alpha = 0.5) +
   geom_text(aes(x = major_points$centroid_x[major_points$group == 6][1], 
                 y = major_points$centroid_y[major_points$group == 6][1]-0.1), 
             label = "F", color = "grey40", size = 8) +
  guides(color = guide_legend(keywidth = 1.5, keyheight = 1.5)) +
  theme(legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        legend.key.size = unit(1.5, "lines"))
```

# Barplot colored by TG - 6 clusters (Figure 1E right)
```{r barplot colored by TG, fig.height=6, fig.width=8}
df_summary <- data.frame(Subtype = factor(subtype_hcl$label),
                         PASC =subtype_hcl$PASC,
                         TG = subtype_hcl$TG)

df_summary2 <- df_summary %>%
  dplyr::group_by(Subtype, TG) %>%
  dplyr::summarise(Count = n(), .groups = "drop")
total_counts2 <- df_summary2 %>%
  group_by(Subtype) %>%
  summarise(Total = sum(Count))
df_summary2 <- df_summary2 %>%
  dplyr::group_by(Subtype) %>% 
  mutate(percent = Count/sum(Count)*100)

df_summary2$Subtype <- factor(df_summary2$Subtype, 
                              levels = rev(levels(df_summary2$Subtype)))

ggplot(df_summary2, aes(y = Subtype, x = percent, fill = TG)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
    geom_text(data = total_counts2,
              aes(y = Subtype, x = -6, label = sprintf(" %d", Total)),
            position = position_dodge(width = 0.9),
            inherit.aes = FALSE, size = 7)+
  labs(y = "Subtype",
       x = "Percent") +
  theme(axis.title.x = element_text(size = 15),
        axis.title.y = element_blank(),
        axis.text.x = element_text(color = "black", size = 15),
        axis.text.y = element_blank(),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.key.size = unit(2, "lines"),
        plot.margin = margin(b = 55, t = 5)) +
  scale_fill_manual(values = c("1" = "#639A21", "2" = "#39828C", 
                               "3" = "#6371AD", "4" = "#BD7D31", 
                               "5" = "#9C3418"))
```

# Test hierarchical clustering with TG (Figure 1E left)
```{r test hierarchical clustering with TG, fig.height=6, fig.width=2}
full_clust_test = list(); full_clust_test[["TG"]] = list()
clin_data_patient = clin_data_aligned[clin_data_aligned$event_type == "Visit 1", ]
demo_data_adjust = clin_data_patient[, c("discretized_admit_age_quantile", "sex")]

df_global = cbind(subtype = subtype_hcl$label, 
                  response = subtype_hcl$TG, demo_data_adjust)
m1 = clm(response ~ subtype + discretized_admit_age_quantile + sex, 
         data = df_global)
m0 = clm(response ~ discretized_admit_age_quantile + sex, 
         data = df_global)
LRT_stat = 2*(as.numeric(logLik(m1))-as.numeric(logLik(m0)))
df_drop = attr(logLik(m1), "df") - attr(logLik(m0), "df")
pval_global = pchisq(LRT_stat, df = df_drop, lower.tail = FALSE)
pval_global

full_clust_test[["TG"]][["ordinal_demo"]] = test_ordinal_demo(
  subtype = subtype_hcl$label,
  response = subtype_hcl$TG,
  demo_data = demo_data_adjust)

test_Fig1E = cbind(total_counts2$Total,
                   full_clust_test[["TG"]][["ordinal_demo"]]$est_ordinal,
                   full_clust_test[["TG"]][["ordinal_demo"]]$p_ordinal)
rownames(test_Fig1E) = paste0("Subtype ", LETTERS[1:nclust_tree_all])
colnames(test_Fig1E) = c("Count", "Estimate", "p-value")

heatmap_ordinal(full_clust_test[["TG"]][["ordinal_demo"]])
```

# Survival curve for acute infection (Figure 1F left)
```{r survival curve for acute infection, fig.height=6, fig.width=6}
logrank_pvals_mat = list()

# adjust for demographics
clin_data_patient <- clin_data_aligned[clin_data_aligned$event_type == "Visit 1",]
demo_data_adjust <- clin_data_patient[, c("discretized_admit_age_quantile", "sex")]

sample_meta_participant = extended_data$sample_meta_participant_level
sample_meta_participant$death_date[sample_meta_participant$death_date<0] = 999
censoring_date_death = 28
death_surv = cbind(sample_meta_participant$death_date,
                   sample_meta_participant$death_date)
death_surv[death_surv[,2]>censoring_date_death,2] = censoring_date_death+1
death_surv[,1] = ifelse(death_surv[,2]<=censoring_date_death,1,0)
death_surv = data.frame(death_surv)
colnames(death_surv) = c("state", "time")
surv_object = Surv(time = death_surv$time, event = death_surv$state)
data_surv = data.frame(subtype = factor(subtype_hcl$label))

fit1 = survfit(surv_object ~ subtype, data = data_surv)
coef_cox1 = coxph_coef(surv_object, subtype_hcl$label, demo_data_adjust)

test_Fig1F = cbind(fit1$n, 
                   coef_cox1[, 1],
                   coef_cox1[, 3],
                   coef_cox1[, 5])
rownames(test_Fig1F) = paste0("Subtype ", LETTERS[1:nclust_tree_all])
colnames(test_Fig1F) = c("Count", "Coef", "se(Coef)", "p-value")

logrank_pvals_mat[["acute"]] = pairwise_survival_comparisons(
  surv_object = surv_object, subtype=subtype_hcl$label)

acute_surv <- ggsurvplot(fit1, data_surv, title = "", 
                         xlab = "Days after Admission",
                         ylab = "Probability of Survival", 
                         size = 1.2,
                         conf.int = TRUE,
                         conf.int.alpha = 0.1,
                         font.x = c(12, "black"),
                         font.y = c(12, "black"),
                         axes.offset = F,
                         palette = c("#20854EB2", "#0072B5B2", "#E18727B2",
                                     "#FFDC91B2", "#EE4C97B2", "#BC3C29B2"),
                         legend.labs = paste("Subtype", 
                                             LETTERS[1:nclust_tree_all]),
                         legend.title = "Subtype",
                         xlim = c(0, 31), ylim = c(0, 1.05),
                         font.main = c(12, "black"),
                         font.tickslab = c(12, "black"),
                         risk.table = TRUE, tables.height = 0.5, 
                         tables.theme = theme_cleantable())

acute_surv$plot +
  ggtitle("Survival Curve for Acute Infection") +
  theme(panel.grid.major = element_blank(),
       panel.grid.minor = element_blank(),
       panel.border = element_blank(),
       axis.line.x = element_line(linewidth = 1),
       axis.line.y = element_line(linewidth = 1),
       axis.ticks = element_line(linewidth = 1),
       axis.text.x = element_text(color = "black", size = 15),  
       axis.text.y = element_text(color = "black", size = 15, 
                                  margin = margin(l = 12, r = 2)),  
       axis.title = element_text(color = "black", size = 15),
       axis.ticks.length = unit(0.15, "cm"),
       legend.position = "top",
       axis.title.x = element_text(color = "black", size = 15),
       axis.title.y = element_text(color = "black", size = 15),
       plot.title = element_text(size = 15, hjust = 0.5))
```

# Forest plot for acute mortality (Figure 1F right)
```{r forest plot for acute mortality, fig.height=6, fig.width=8}
forest(coef_cox1[, 1], sei = coef_cox1[, 3], refline = 0, xlim = c(-8.5,7), 
       ilab = fit1$n, pch = 20, ilab.xpos = -4.2, 
       slab = paste("Subtype", LETTERS[1:nclust_tree_all]), shade = "zebra",
       header = c("Subtype", "log(Hazard Ratio) [95% CI]"), xlab = "", cex = 1.4)
text(0, 9, "log(Hazard Ratio) for Acute Mortality", font = 2, cex = 1.4)
text(-4.2, 8, "No. of Participant", font = 2, cex = 1.4)
```

