---
title: "factor stratified by TG"
output: pdf_document
---

```{r load library}
require(openxlsx)
library(factoextra)
library(cluster)
require(nlme) # directly provides p-values, unlike lme4
require(splines)
require(dplyr)
library(fgsea)
library(knitr)
library(kableExtra)
library(tidyverse)
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
source(paste0(codebase_path,"/codebase_subtype.R"))

organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")

intermediate_results_outdir_DR = "/scratch/data-integration/molecular_subtyping/DimensionReduction/"
mcia_results = readRDS(paste0(intermediate_results_outdir_DR,"MCIA_phase123_20230726.rds"))

data_path <- "/scratch/data-integration/pipelines/processedData/"
data_env0 <- readRDS(paste0(data_path, "data_env_ravi_20220513.RDS"))
```

# Load preliminary results
```{r load subtype assignment and clinical data}
# load subtype assignment and clinical data
nclust_tree_all = 6
subtype_hcl = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/subtype_hcl.rds")
clin_data_aligned = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/clin_data_aligned.rds")
extended_data = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/extended_data.rds")
```

# Subtype A-C within TG1
```{r Subtype A-C within TG1, fig.height=6, fig.width=24, warning=FALSE}
mod_ids = c(1, 2, 3, 10)
negation = c(-1, 1, 1, 1)
# negate factors
mcia_factors = t(t(mcia_results$mcia_factors[,mod_ids]) * negation)
mcia_factors=apply(mcia_factors,2, function(z) qqnorm(z, plot.it = F)$x)
mcia_factors = data.frame(mcia_factors,row.names = rownames(organized_data$datasets$plasma_proteomics_targeted))
mcia_factors = mcia_factors[clin_data_aligned$event_id,]
colnames(mcia_factors) = paste0("Factor", mod_ids)

assay_mat = mcia_factors
assay_mat$event_id = rownames(assay_mat)
assay_mat = cytof_mat_preprocess(cytof_mat = assay_mat, 
                                 subtype_hcl = subtype_hcl,
                                 clin_data = clin_data_aligned)
clin_colnames_select = setdiff(colnames(assay_mat), colnames(mcia_factors))

assay_mat = assay_mat[assay_mat$TG == 1 & assay_mat$label %in% c("A", "B", "C"), ]
table(assay_mat$TG, assay_mat$label)

factor_trajectory_analysis_results = helper_trajectory_data_smooth_spline(
  assay_mat = assay_mat, clin_colnames_select = clin_colnames_select,
  endpoint = "label", use_endpoint_levels = c("A", "B", "C"),
  max_date = 40, feature_with_ylab = c("Factor1"), text_position = 2)

ggarrange(plotlist = factor_trajectory_analysis_results$test_fig_list, 
          nrow = 1, common.legend = T, legend = "bottom")
```

# Subtype A-C within TG2
```{r Subtype A-C within TG2, fig.height=6, fig.width=24, warning=FALSE}
mod_ids = c(1, 2, 3, 10)
negation = c(-1, 1, 1, 1)
# negate factors
mcia_factors = t(t(mcia_results$mcia_factors[,mod_ids]) * negation)
mcia_factors=apply(mcia_factors,2, function(z) qqnorm(z, plot.it = F)$x)
mcia_factors = data.frame(mcia_factors,row.names = rownames(organized_data$datasets$plasma_proteomics_targeted))
mcia_factors = mcia_factors[clin_data_aligned$event_id,]
colnames(mcia_factors) = paste0("Factor", mod_ids)

assay_mat = mcia_factors
assay_mat$event_id = rownames(assay_mat)
assay_mat = cytof_mat_preprocess(cytof_mat = assay_mat, 
                                 subtype_hcl = subtype_hcl,
                                 clin_data = clin_data_aligned)
clin_colnames_select = setdiff(colnames(assay_mat), colnames(mcia_factors))

assay_mat = assay_mat[assay_mat$TG == 2 & assay_mat$label %in% c("A", "B", "C"), ]
table(assay_mat$TG, assay_mat$label)

factor_trajectory_analysis_results = helper_trajectory_data_smooth_spline(
  assay_mat = assay_mat, clin_colnames_select = clin_colnames_select,
  endpoint = "label", use_endpoint_levels = c("A", "B", "C"),
  max_date = 40, feature_with_ylab = c("Factor1"), text_position = 2)

ggarrange(plotlist = factor_trajectory_analysis_results$test_fig_list, 
          nrow = 1, common.legend = T, legend = "bottom")
```

# Subtype A-C within TG3
```{r Subtype A-C within TG3, fig.height=6, fig.width=24, warning=FALSE}
mod_ids = c(1, 2, 3, 10)
negation = c(-1, 1, 1, 1)
# negate factors
mcia_factors = t(t(mcia_results$mcia_factors[,mod_ids]) * negation)
mcia_factors=apply(mcia_factors,2, function(z) qqnorm(z, plot.it = F)$x)
mcia_factors = data.frame(mcia_factors,row.names = rownames(organized_data$datasets$plasma_proteomics_targeted))
mcia_factors = mcia_factors[clin_data_aligned$event_id,]
colnames(mcia_factors) = paste0("Factor", mod_ids)

assay_mat = mcia_factors
assay_mat$event_id = rownames(assay_mat)
assay_mat = cytof_mat_preprocess(cytof_mat = assay_mat, 
                                 subtype_hcl = subtype_hcl,
                                 clin_data = clin_data_aligned)
clin_colnames_select = setdiff(colnames(assay_mat), colnames(mcia_factors))

assay_mat = assay_mat[assay_mat$TG == 3 & assay_mat$label %in% c("A", "B", "C"), ]
table(assay_mat$TG, assay_mat$label)

factor_trajectory_analysis_results = helper_trajectory_data_smooth_spline(
  assay_mat = assay_mat, clin_colnames_select = clin_colnames_select,
  endpoint = "label", use_endpoint_levels = c("A", "B", "C"),
  max_date = 40, feature_with_ylab = c("Factor1"), text_position = 2)

ggarrange(plotlist = factor_trajectory_analysis_results$test_fig_list, 
          nrow = 1, common.legend = T, legend = "bottom")
```

# Subtype A & E & F within TG4
```{r Subtype E-F within TG4, fig.height=6, fig.width=24, warning=FALSE}
mod_ids = c(1, 2, 3, 10)
negation = c(-1, 1, 1, 1)
# negate factors
mcia_factors = t(t(mcia_results$mcia_factors[,mod_ids]) * negation)
mcia_factors=apply(mcia_factors,2, function(z) qqnorm(z, plot.it = F)$x)
mcia_factors = data.frame(mcia_factors,row.names = rownames(organized_data$datasets$plasma_proteomics_targeted))
mcia_factors = mcia_factors[clin_data_aligned$event_id,]
colnames(mcia_factors) = paste0("Factor", mod_ids)

assay_mat = mcia_factors
assay_mat$event_id = rownames(assay_mat)
assay_mat = cytof_mat_preprocess(cytof_mat = assay_mat, 
                                 subtype_hcl = subtype_hcl,
                                 clin_data = clin_data_aligned)
clin_colnames_select = setdiff(colnames(assay_mat), colnames(mcia_factors))

assay_mat = assay_mat[assay_mat$TG == 4 & assay_mat$label %in% c("A", "E", "F"), ]
table(assay_mat$TG, assay_mat$label)

factor_trajectory_analysis_results = helper_trajectory_data_smooth_spline(
  assay_mat = assay_mat, clin_colnames_select = clin_colnames_select,
  endpoint = "label", use_endpoint_levels = c("A", "E", "F"),
  max_date = 40, feature_with_ylab = c("Factor1"), text_position = 2)

ggarrange(plotlist = factor_trajectory_analysis_results$test_fig_list, 
          nrow = 1, common.legend = T, legend = "bottom")
```

# Subtype A & E & F within TG5
```{r Subtype E-F within TG5, fig.height=6, fig.width=24, warning=FALSE}
mod_ids = c(1, 2, 3, 10)
negation = c(-1, 1, 1, 1)
# negate factors
mcia_factors = t(t(mcia_results$mcia_factors[,mod_ids]) * negation)
mcia_factors=apply(mcia_factors,2, function(z) qqnorm(z, plot.it = F)$x)
mcia_factors = data.frame(mcia_factors,row.names = rownames(organized_data$datasets$plasma_proteomics_targeted))
mcia_factors = mcia_factors[clin_data_aligned$event_id,]
colnames(mcia_factors) = paste0("Factor", mod_ids)

assay_mat = mcia_factors
assay_mat$event_id = rownames(assay_mat)
assay_mat = cytof_mat_preprocess(cytof_mat = assay_mat, 
                                 subtype_hcl = subtype_hcl,
                                 clin_data = clin_data_aligned)
clin_colnames_select = setdiff(colnames(assay_mat), colnames(mcia_factors))

assay_mat = assay_mat[assay_mat$TG == 5 & assay_mat$label %in% c("E", "F"), ]
table(assay_mat$TG, assay_mat$label)

factor_trajectory_analysis_results = helper_trajectory_data_smooth_spline(
  assay_mat = assay_mat, clin_colnames_select = clin_colnames_select,
  endpoint = "label", use_endpoint_levels = c("E", "F"),
  max_date = 40, feature_with_ylab = c("Factor1"), text_position = 2,
  demo_adjust_plot = FALSE)

ggarrange(plotlist = factor_trajectory_analysis_results$test_fig_list, 
          nrow = 1, common.legend = T, legend = "bottom")
```


