---
title: "Fig6"
output: html_document
---

```{r load library}
library(ade4) #used in mcia
library(mogsa)
library(factoextra)
library(cluster)
library(nnet)
library(survival)
library(ordinal)
library(ggeffects)
library(openxlsx)
library(network)
library(GGally)
library(ggalt)
library(metafor)
library(cowplot)
library(survminer)
require(nlme) # directly provides p-values, unlike lme4
require(splines)
require(dplyr)
library(fgsea)
codebase_path = "~/impacc/Analysis/molecular_subtyping/codebase"
source(paste0(codebase_path,"/data_analysis_template_codebase.R"))
source(paste0(codebase_path,"/codebase_basic.R"))
source(paste0(codebase_path,"/codebase_prediction.R"))
source(paste0(codebase_path,"/codebase_interpretation.R"))
source(paste0(codebase_path,"/class_structures.R"))
source(paste0(codebase_path,"/codebase_mod.R"))
source(paste0(codebase_path,"/codebase_subtype.R"))

organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")

intermediate_results_outdir_DR = "/scratch/data-integration/molecular_subtyping/DimensionReduction/"
mcia_results = readRDS(paste0(intermediate_results_outdir_DR,"MCIA_phase123_20230726.rds"))

data_path <- "/scratch/data-integration/pipelines/processedData/"
data_env0 <- readRDS(paste0(data_path, "data_env_ravi_20220513.RDS"))
```

# Load subtype assignment and clinical data
```{r load subtype assignment and clinical data}
nclust_tree_all = 6
subtype_hcl = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/subtype_hcl.rds")
clin_data_aligned = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/clin_data_aligned.rds")
extended_data = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/extended_data.rds")
```

# Barplot colored by PASC - 5 subtypes (Figure 6A right)
```{r barplot colored by PASC, fig.height=6, fig.width=8}
df_summary <- data.frame(Subtype = factor(subtype_hcl$label),
                         PASC =subtype_hcl$PASC,
                         TG = subtype_hcl$TG)

df_summary1 <- df_summary %>%
  dplyr::group_by(Subtype, PASC) %>%
  dplyr::summarise(Count = n(), .groups = "drop")
df_summary1 <- df_summary1[!is.na(df_summary1$PASC),]
total_counts1 <- df_summary1 %>%
  group_by(Subtype) %>%
  summarise(Total = sum(Count))
df_summary1 <- df_summary1 %>%
  dplyr::group_by(Subtype) %>%
  mutate(percent = Count/sum(Count)*100)

df_summary1 <- df_summary1[df_summary1$Subtype != "D", ]
total_counts1 <- total_counts1[total_counts1$Subtype != "D", ]
df_summary1$Subtype <- factor(as.character(df_summary1$Subtype))
df_summary1$PASC <- factor(df_summary1$PASC, labels = c("Minimal", "Physical", 
                                                        "Cognitive", "Multiple"))
df_summary1$Subtype <- factor(df_summary1$Subtype, 
                              levels = rev(levels(df_summary1$Subtype)))

ggplot(df_summary1, aes(y = Subtype, x = percent, fill = PASC)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  geom_text(data = total_counts1,
            aes(y = Subtype, x = -6, label = sprintf(" %d", Total)),
            position = position_dodge(width = 0.9),
            inherit.aes = FALSE, size = 7)+
  labs(y = "Subtype", x = "Percent") +
  theme(axis.title.x = element_text(size = 15),
        axis.title.y = element_blank(),
        axis.text.x = element_text(color = "black", size = 15),
        axis.text.y = element_blank(),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.key.size = unit(2, "lines"),
        plot.margin = margin(b = 55, t = 5)) +
  scale_fill_manual(values = c("Minimal" = "#999999", "Physical" = "#58B5EA", 
                               "Cognitive" = "#EAAE2A", "Multiple" = "#FF1820"))
```

# Test hierarchical clustering with PASC (Figure 6A middle)
```{r test hierarchical clustering with PASC, fig.height=6, fig.width=5}
id = which(!is.na(subtype_hcl$PASC) & subtype_hcl$label != "D")
full_clust_test= list(); full_clust_test[["PASC"]] = list()
ww = ifelse(subtype_hcl$PASC[id] == "minimal", 0, 1)
clin_data_patient = clin_data_aligned[clin_data_aligned$event_type == "Visit 1", ]
demo_data_adjust = clin_data_patient[, c("discretized_admit_age_quantile", "sex")]

full_clust_test[["PASC"]][["fisher"]] = test_clinical_fisher_exact(
  subtype = subtype_hcl$label[id],
  response = subtype_hcl$PASC[id],
  response_binary = ww, seed = 123)

heatmap_fisher(full_clust_test[["PASC"]][["fisher"]])
```

# Test hierarchical clustering with PASC - global (Figure 6A left)
```{r test hierarchical clustering with PASC - global, fig.height=6, fig.width=2}
heatmap_fisher_global(full_clust_test[["PASC"]][["fisher"]])
```

# Forest plot for post-acute mortality (Figure 6B)
```{r forest plot for post-acute mortality, fig.height=6, fig.width=9, warning=FALSE}
logrank_pvals_mat = list()

# adjust for demographics
clin_data_patient <- clin_data_aligned[clin_data_aligned$event_type == "Visit 1",]
demo_data_adjust <- clin_data_patient[, c("discretized_admit_age_quantile", "sex")]

sample_meta_participant = extended_data$sample_meta_participant_level
sample_meta_participant$death_date[sample_meta_participant$death_date<0] = 999
censoring_date_death = 200
death_surv = cbind(sample_meta_participant$death_date,
                   sample_meta_participant$death_date)
death_surv[death_surv[,2]>censoring_date_death,2] = censoring_date_death+1
death_surv[,1] = ifelse(death_surv[,2]<=censoring_date_death,1,0)
death_surv = data.frame(death_surv)
colnames(death_surv) = c("state", "time")

id_post_acute <- which(death_surv$time > 28 & subtype_hcl$label != "D")
post_acute_death_surv <- death_surv[id_post_acute, ]
surv_object <- Surv(time = post_acute_death_surv$time, 
                    event = post_acute_death_surv$state)
data_surv = data.frame(subtype = factor(subtype_hcl$label)[id_post_acute])
fit2 <- survfit(surv_object ~ subtype, data = data_surv)
coef_cox2 <- coxph_coef(surv_object, subtype_hcl$label[id_post_acute], 
                        demo_data_adjust[id_post_acute, ])

logrank_pvals_mat[["post_acute"]] = pairwise_survival_comparisons(
  surv_object=surv_object, subtype=subtype_hcl$label[id_post_acute])

forest(coef_cox2[, 1], sei = coef_cox2[, 3], refline = 0, xlim  =c(-8.5,7), 
       ilab = fit2$n, pch = 20, ilab.xpos = -5.2, 
       slab=c("Subtype A", "Subtype B", "Subtype C", "Subtype E", "Subtype F"), 
       shade = "zebra", at = c(-4,-2,0,2,3), 
       header = c("Subtype", "log(Hazard Ratio) [95% CI]"), 
       xlab = "", cex = 1.4)
text(0, 8, "log(Hazard Ratio) for Post-Acute Mortality", font=2, cex=1.4)
text(-4.5, 7, "No. of Participant", font=2, cex=1.4)
```



