---
title: "Figure4"
format: html
editor: visual
---

## Figure 4: Serum OLINK Analysis

## Boot up Key Data

```{r}
library(tidyverse)
library(data.table)
library(viridis)
library(scales)
library(ggeffects)
comb_data <- read_csv("/scratch/metagenomics/viral_reactivation/full_comb_data.csv") %>% select(-1) %>%
  select(-starts_with("Human betaherpesvirus 6"),
         -starts_with("Human gammaherpesvirus 8"),
         -starts_with("Human betaherpesvirus 7"),
         -starts_with("Respiratory syncytial virus"),
         -starts_with("Human immunodeficiency virus 1"),
         -starts_with("SARS-CoV-2.pbmc"),
         -starts_with("Enterovirus.pbmc"),
         -starts_with("Enterovirus.ea"),
         -starts_with("Anelloviridae.ea"),
         -starts_with("Anelloviridae.nasal"),
         -ends_with(".ea")) %>%
  dplyr::rename("Betacoronavirus.nasal" = "SARS-CoV-2.nasal")
data_env <- readRDS("/scratch/metagenomics/viral_reactivation/2024-02-02_obj.RDS")
clinical_data <- data_env$clinical_data

out_dir <- "../output/"

```

## Gamm modeling function

```{r}
library(nlme)

gamm_modeling <- function(counts, viral_load_control, binary = TRUE, event_date_cutoff){
  ## Requires a data_env be made and in the environment
  ## using the load_IMPACC_dataset function from the codebase
  model.out <- data.frame()
  plot_list <- list()
  residual_list <- list()
  
  old_comb_data <- read_csv("/scratch/metagenomics/viral_reactivation/old_full_comb_data.csv") %>% select(-1) %>%
  select(-starts_with("Human betaherpesvirus 6"),
         -starts_with("Human gammaherpesvirus 8"),
         -starts_with("Human betaherpesvirus 7"),
         -starts_with("Respiratory syncytial virus"),
         -starts_with("Human immunodeficiency virus 1"),
         -starts_with("SARS-CoV-2.pbmc"),
         -starts_with("Enterovirus.pbmc"),
         -starts_with("Enterovirus.ea"),
         -starts_with("Anelloviridae.ea"),
         -starts_with("Anelloviridae.nasal"),
         -ends_with(".ea")) %>%
  dplyr::rename("Betacoronavirus.nasal" = "SARS-CoV-2.nasal")
  
  max_part <- old_comb_data %>%
    pivot_longer(cols = -event_id) %>%
    left_join(data_env$clinical_data %>%
                distinct(event_id, participant_id, event_date)) %>%
    filter(event_date >= 0) %>%
    filter(event_date <= event_date_cutoff) %>%
    group_by(participant_id, name) %>%
    filter(name != "Betacoronavirus.nasal") %>%
    dplyr::summarize(value = max(value, na.rm = TRUE)) %>%
    filter(value != -Inf) %>%
    distinct() %>%
    pivot_wider(names_from = name, values_from = value) %>%
    ungroup() %>%
    dplyr::select(-starts_with("Betacoronavirus"))
  max_part <- max_part[complete.cases(max_part),]
  ctl_part <- max_part$participant_id[rowSums(max_part[,c(-1)]) == 0]
  
  max_part <- comb_data %>%
    pivot_longer(cols = -event_id) %>%
    left_join(data_env$clinical_data %>%
                distinct(event_id, participant_id, event_date)) %>%
    filter(event_date >= 0) %>%
    filter(event_date <= event_date_cutoff) %>%
    group_by(participant_id, name) %>%
    filter(name != "Betacoronavirus.nasal") %>%
    dplyr::summarize(value = max(value, na.rm = TRUE)) %>%
    filter(value != -Inf) %>%
    distinct() %>%
    pivot_wider(names_from = name, values_from = value) %>%
    ungroup() %>%
    dplyr::select(-starts_with("Betacoronavirus"))
  
  ## Filter for participants that we have both a nasal and pbmc sample for
  ## Really not that big of deal because we control for nasal viral load
  max_part <- max_part[complete.cases(max_part),]
  
  ## This is to standardize the control cohort to the prior version
  ## that did not yet exclude 3B plate 4 for HSV1
  
  
  for(active_vir in colnames(max_part)[-1]){
    print(paste0("Starting ", match(active_vir, colnames(max_part)[-1]), " out of ", length(colnames(max_part)[-1])))
    
    tmp.data <- counts %>%
      rownames_to_column("sample_id") %>%
      inner_join(data_env$clinical_data %>% dplyr::select(sample_id, event_id,
                                                          participant_id,
                                                          respiratory_status,
                                                          trajectory_group,
                                                          event_type,
                                                          event_date,
                                                          enrollment_site,
                                                          discretized_admit_age_quantile,
                                                          sex)) %>%
      inner_join(max_part %>% dplyr::select(participant_id, .data[[active_vir]]), by = "participant_id") %>%
      inner_join(comb_data %>%
                   dplyr::select(event_id, Betacoronavirus.nasal), by = "event_id") %>%
      relocate(sample_id, event_id, event_type, event_date,
               participant_id,
               respiratory_status, trajectory_group, enrollment_site,
               sex,discretized_admit_age_quantile, all_of(active_vir), Betacoronavirus.nasal) %>%
      filter(!is.na(.data[[active_vir]])) %>%
      mutate(sex = as.factor(sex),
             participant_id = as.factor(participant_id),
             event_date = as.numeric(event_date),
             enrollment_site = as.factor(enrollment_site),
             trajectory_group = ordered(as.factor(trajectory_group)),
             respiratory_status = ordered(as.factor(respiratory_status)),
             discretized_admit_age_quantile = ordered(as.factor(discretized_admit_age_quantile))) %>%
     filter(.data[[active_vir]] > 0 | participant_id %in% ctl_part)
    
    if(viral_load_control){
      tmp.data <- tmp.data %>%
        filter(!is.na(Betacoronavirus.nasal)) %>%
        mutate(Betacoronavirus.nasal = log2(Betacoronavirus.nasal + 1))
    }
    
    if(binary){
      ## Convert to a binary approach
      tmp.data[[active_vir]] <- ordered(as.factor(ifelse(tmp.data[[active_vir]] > 0, 1, 0)))
    } else {
      tmp.data[[active_vir]] <- log2(tmp.data[[active_vir]] +1)
    }
    
    
    ## Prepare colnames for formala/modeling
    colnames(tmp.data) <- gsub(" ", "_",
                               gsub("-", "_",
                                    gsub("\\(", "_",sub("\\)", "_",  colnames(tmp.data)))))
    cleaned_vir <- gsub(" ", "_",
                        gsub("-", "_",
                             gsub("\\(", "_",sub("\\)", "_", active_vir))))
    
   
    for(active_feature in colnames(tmp.data)[13:ncol(tmp.data)]){
      
      ## GAMM Modeling ####################
      ## Formula construction
      active_formula <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') + s(event_date, bs = 'cr', by = ", cleaned_vir, ")+s(event_date, bs = 'cr', by = trajectory_group)+", cleaned_vir, "+sex+trajectory_group+discretized_admit_age_quantile"))
      
      if(viral_load_control){
        active_formula <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') + s(event_date, bs = 'cr', by = ", cleaned_vir, ")+s(event_date, bs = 'cr', by = trajectory_group)+", cleaned_vir, "+sex+trajectory_group+discretized_admit_age_quantile+Betacoronavirus.nasal"))
      }
      
      tmp.data.tmp <- tmp.data %>%
        dplyr::select(event_date, enrollment_site, participant_id,
                      trajectory_group, sex, discretized_admit_age_quantile,
                      any_of(active_feature), any_of(cleaned_vir),
                      Betacoronavirus.nasal )
      tmp.data.tmp <- tmp.data.tmp[complete.cases(tmp.data.tmp),]
      
      
      tmp.data.tmp <- tmp.data.tmp %>%
        filter(event_date >= 0) %>%
        filter(event_date <= event_date_cutoff) %>%
        as.data.frame() %>%
        distinct()
    
      fit <- try(gamm4::gamm4(active_formula, random = ~(1|enrollment_site/participant_id), data = as.data.frame(tmp.data.tmp)))
      
      if(class(fit) == "try-error"){
        next
      }
      a1 =anova(fit$gam)
      ## Think about what to do here
      aa1 = sum(a1$s.table[-c(1), 3]*a1$s.table[-c(1), 2])
      aa2 = sum(a1$s.table[-c(1), 2])
      slopep=pchisq(aa1,aa2, lower.tail = F)
      slopep = a1[["s.pv"]][2]
      interceptp =a1$pTerms.pv[1]
      
      virus_n <- length(unique(tmp.data.tmp$participant_id[tmp.data.tmp[[cleaned_vir]] > 0]))
      control_n <- length(unique(tmp.data.tmp$participant_id[tmp.data.tmp[[cleaned_vir]] == 0]))

      model.out <- rbind.data.frame(model.out, c(active_vir, active_feature, slopep, unname(interceptp),
                                 sum(fit$gam$coefficients[grepl(paste0(":", cleaned_vir), names(fit$gam$coefficients))]),
                                 mean(fit$gam$coefficients[grepl(paste0(":", cleaned_vir), names(fit$gam$coefficients))]),
                                 fit$gam$coefficients[2], virus_n, control_n))
      
      if(slopep <= 0.025 | interceptp <= 0.025){
        pred <- ggpredict(fit, c("event_date", cleaned_vir), type = "fixed",
                          ci.lvl = 0.95)
        colnames(pred) <- gsub("x", "event_date", gsub("group", "virus", colnames(pred)))
        
        pred <- pred %>%
          mutate(virus = as.character(virus)) %>%
          left_join(tmp.data.tmp %>%
                      dplyr::rename("virus" = 8) %>%
                      mutate(virus = as.character(virus)) %>%
                      group_by(virus) %>%
                      dplyr::summarize(max = max(event_date)), by = "virus") %>%
          filter(event_date <= max)
        
        p1 <-pred %>%
          ggplot(mapping = aes(x = event_date, y = predicted)) +
          geom_line(mapping = aes(group = virus, y = predicted, x=event_date,
                                  color = virus), size = 0.8) +
          geom_ribbon(aes(x=event_date, ymin = conf.low, ymax = conf.high, fill = virus),
                      alpha = 0.3) +
          
          theme_classic(base_size  = 18) +
          scale_color_manual(values = c("lightgray", "#BF5700"))+
          scale_fill_manual(values = c("lightgray", "#BF5700")) +
          ylab(active_feature) +
          xlab("Days from Hospitalization") +
          ggtitle(paste0(active_vir, "\nShape = ",signif(slopep, digits = 3), "\nAverage = ", signif(interceptp, digits = 3)))
        
        plot_list <- c(plot_list, list(p1))
        names(plot_list)[length(plot_list)] <- paste0(active_feature,"___", active_vir)
        
      }
      
      if(active_vir == colnames(max_part)[2]){
        
        ## This next section is to calculate the residuals for a model WITHOUT
        ## Viral reactivation as a feature. For this reason, it only needs to be
        ## ran once, which we do during the first loop. (PS This is for the boxplot component of Figure 4)
        
        tmp.data2 <- counts %>%
          rownames_to_column("sample_id") %>%
          inner_join(data_env$clinical_data %>% dplyr::select(sample_id, event_id,
                                                              participant_id,
                                                              respiratory_status,
                                                              trajectory_group,
                                                              event_type,
                                                              event_date,
                                                              enrollment_site,
                                                              discretized_admit_age_quantile,
                                                              sex)) %>%
          inner_join(max_part %>% dplyr::select(participant_id), by = "participant_id") %>%
          inner_join(comb_data %>%
                       dplyr::select(event_id, Betacoronavirus.nasal), by = "event_id") %>%
          relocate(sample_id, event_id, event_type, event_date,
                   participant_id,
                   respiratory_status, trajectory_group, enrollment_site,
                   sex,discretized_admit_age_quantile, Betacoronavirus.nasal) %>%
          mutate(sex = as.factor(sex),
                 participant_id = as.factor(participant_id),
                 event_date = as.numeric(event_date),
                 enrollment_site = as.factor(enrollment_site),
                 trajectory_group = ordered(as.factor(trajectory_group)),
                 respiratory_status = ordered(as.factor(respiratory_status)),
                 discretized_admit_age_quantile = ordered(as.factor(discretized_admit_age_quantile)))
        
        tmp.data.tmp2 <- tmp.data2 %>%
        dplyr::select(event_date, enrollment_site, participant_id,
                      trajectory_group, sex, discretized_admit_age_quantile,
                      any_of(active_feature),
                      Betacoronavirus.nasal )
        tmp.data.tmp2 <- tmp.data.tmp2[complete.cases(tmp.data.tmp2),]
        tmp.data.tmp2 <- tmp.data.tmp2 %>%
          filter(event_date >= 0) %>%
          filter(event_date <= event_date_cutoff) %>%
          as.data.frame() %>%
          distinct()
        
        ## Construct model without viral reactivation and show residuals
        active_formula2 <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') +s(event_date, bs = 'cr', by = trajectory_group) + sex+trajectory_group+discretized_admit_age_quantile"))
        if(viral_load_control){
          active_formula2 <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') +s(event_date, bs = 'cr', by = trajectory_group) + sex+trajectory_group+discretized_admit_age_quantile+Betacoronavirus.nasal"))
        }
        fit2 <- try(gamm4::gamm4(active_formula2, random = ~(1|enrollment_site/participant_id), data = as.data.frame(tmp.data.tmp2)))
        
        residuals_df <- cbind.data.frame(fit2$gam$model, as.data.frame(fit2$gam$residuals)) %>%
          left_join(max_part, by = "participant_id")
        residual_list <- c(residual_list, list(residuals_df))
        names(residual_list)[length(residual_list)] <- paste0(active_feature)
      }
    }
    
  }
  return(c(list(model.out), list(plot_list), list(residual_list), list(ctl_part)))
}
```

```{r}
#| eval: false
## This only needs to be run once, and is very slow.
library(gamm4)
library(ggeffects)
counts <- data_env$serum_olink_counts

test <- gamm_modeling(counts, viral_load_control = TRUE, binary = TRUE,
                      event_date_cutoff = 40)
results <- as.data.frame(test[[1]])
colnames(results) <- c("virus_compartment", "feature", "shape", "average", "summed_virus_smooth_coefficients", "average_virus_smooth_coefficients", "average_coefficient", "virus_n", "control_n")

results2 <- results %>%
  group_by(virus_compartment) %>%
  mutate(shape.adj = p.adjust(shape, "fdr"), average.adj = p.adjust(average, "fdr"))
write.csv(results2, paste0(out_dir, "Supplemental_Data_3_part1.csv"))
saveRDS(test, paste0(out_dir, "Supplemental_Data_3.RDS"))
```

## Figure 4A

```{r, fig.width = 4.5, fig.height = 8}
library(ComplexHeatmap)
library(tidyverse)
library(circlize)
library(tidyverse)
col_fun = colorRamp2(breaks = c(-5, 0, 5), c("darkblue", "white", "darkred"))

so <- read.csv(paste0(out_dir, "Supplemental_Data_3_part1.csv"))
remove <- c("Human betaherpesvirus 5 (CMV).nasal", "Enterovirus.nasal")

heat_df <- plyr::rbind.fill(so %>% mutate(omic = "serum olink")) %>%
  filter(!virus_compartment %in% remove) %>%
  pivot_longer(cols = c(shape.adj, average.adj)) %>%
  mutate(value = as.numeric(value),
         average_coefficient = as.numeric(average_coefficient),
         summed_virus_smooth_coefficients = as.numeric(summed_virus_smooth_coefficients)) %>%
  mutate(value = ifelse(value == 0, 2e-16, value)) %>%
  mutate(log10p = ifelse(name == "shape.adj", -log10(value) * (summed_virus_smooth_coefficients/abs(summed_virus_smooth_coefficients)),
                         -log10(value) * (average_coefficient/abs(average_coefficient)))) %>%
  filter(round(value, 3) <= 0.01)


heat_df2 <- heat_df %>%
  group_by(virus_compartment, feature, omic) %>%
  slice_max(abs(log10p)) %>%
  distinct() %>%
  pivot_wider(names_from = c(virus_compartment), values_from = log10p,
              id_cols = c(omic, feature))

heat_df3 <- as.data.frame(heat_df2[,-1:-2])
rownames(heat_df3) <- heat_df2$feature
heat_df3 <- heat_df3[,order(colnames(heat_df3))]
heat_df3 <- heat_df3[,c(1,3,5,4,2)]
colnames(heat_df3) <- gsub("\\)", "", gsub(".*\\(", "", colnames(heat_df3)))
heat_df3[is.na(heat_df3)] <- 0

pdf(paste0(out_dir, "Figure4A.pdf"), height = 8, width = 4.5)
Heatmap(heat_df3, border = TRUE, cluster_column_slices = F,
        col = col_fun, show_row_dend = F, show_column_dend = F,column_title = "Virus",
        column_split = factor(gsub("_.*", "", colnames(heat_df3)),
                    levels = c("Anelloviridae.pbmc",
                               "CMV.pbmc", "EBV.pbmc", "EBV.nasal",
                               "HSV1.nasal", "HSV2.nasal")),
        cluster_rows = T,
        column_names_rot = 45, column_names_side = "top",column_title_side = "bottom",
        name = "Signed\n-log10 transformed\nadjusted p.values", cluster_columns = FALSE)
dev.off()

write.csv(heat_df3, paste0(out_dir, "source_data_Figure4A.csv"))
```

## Figure 4B-G

```{r, width = 25, height =3 }

modeling_results <- readRDS(paste0(out_dir, "Supplemental_Data_3.RDS"))

traj_plot <- function(feature, viruses, results_obj, colors, log_residuals = F,
                      variable_width = 0.6, base_size = 12, better_name){
  library(ggpubr)
  if(missing(better_name)){
    feature_name <- feature
  } else {
    feature_name <- better_name
  }
  plot_list <- list()
  for(active_virus in viruses){
      plots <- results_obj[[2]][[paste0(feature, "___", active_virus)]]
      plots$data <- plots$data %>%
        mutate(virus = ifelse(virus == 0, "Control",
                              gsub("\\)", "", gsub(".*\\(", "", active_virus))))
      plots <- plots + scale_color_manual(values = colors, name = "Group")+
        scale_fill_manual(values = colors, name = "Group") +
          theme_classic(base_size  = base_size) +
        ggtitle(" ") +
          ylab(paste0("Normalized ", feature_name)) +
          theme(legend.position = "none",
                axis.text = element_text(color = "black"),
                axis.ticks = element_line(color = "black"))
      plot_list <- c(plot_list, list(plots))
  }
  
  gg2 <- as.data.frame(results_obj[[3]][[feature]]) %>%
    dplyr::rename("residuals" = 16) %>%
    pivot_longer(cols = 17:24) %>%
    mutate(value = ifelse(value > 0, 1, 0)) %>%
    group_by(participant_id, name, value) %>%
    distinct(participant_id, name, value, residuals) %>%
    slice_max(abs(residuals)) %>%
    mutate(name = ifelse(participant_id %in%results_obj[[4]], "Control", name)) %>%
    filter(value!=0|name=="Control") %>%
    mutate(name = gsub("\\)", "", gsub(".*\\(", "", name))) %>%
    filter(name %in% c("Control", gsub("\\)", "", gsub(".*\\(", "", viruses)))) %>%
    distinct() %>%
    mutate(name = fct_relevel(name, "Control")) %>%
    ggplot(aes(x=name, y=abs(residuals), color = name)) +
    #geom_violin(draw_quantiles = T) +
    geom_boxplot(outlier.shape = NA, alpha = 1, width = 0.8) +
    ggbeeswarm::geom_quasirandom(size = 0.01, alpha = 0.3) +
    theme_classic(base_size  = base_size) +
    ggtitle(feature_name) +
    scale_color_manual(values = colors) +
    theme(axis.text.x = element_blank(),
          legend.position = "none",
          axis.text = element_text(color = "black"),
            axis.ticks = element_line(color = "black"),
          axis.text.y = element_text(color = "black")) +
    ylab("Largest Magnitude Residual") +
    xlab(" ")
  if(log_residuals){
    gg2 <- gg2 + scale_y_continuous(trans='log10', labels = label_comma())
  }
      return(ggarrange(plotlist = c(list(gg2), plot_list), widths = c(variable_width,rep(1, length(plot_list))),
                       nrow = 1, align = "hv"))
}

viral_colors <- c("Control"="#757575", "EBV.pbmc"="#BF5700", "EBV.nasal"="#008080",
                  "CMV.pbmc"="#005F86", "Anelloviridae.pbmc" = "#86005F",
                  "HSV1.nasal" = "#1b820d", "HSV2.nasal" = "#cba90a")


ggb <- traj_plot("CXCL10", c("Human betaherpesvirus 5 (CMV).pbmc",
                      "Human gammaherpesvirus 4 (EBV).pbmc",
                     "Human alphaherpesvirus 1 (HSV1).nasal"),
          modeling_results, viral_colors, base_size = 14, log_residuals = T)
ggb
ggsave(paste0(out_dir, "Figure4B.pdf"), width = 12.32142, height = 3)

ggc <- traj_plot("CXCL11", c("Human betaherpesvirus 5 (CMV).pbmc",
                      "Human gammaherpesvirus 4 (EBV).pbmc",
                     "Human alphaherpesvirus 1 (HSV1).nasal",
                     "Anelloviridae.pbmc"), modeling_results, viral_colors,
          base_size = 14, log_residuals = T)
ggc
ggsave(paste0(out_dir, "Figure4C.pdf"), width = 15, height = 3)

ggd <- traj_plot("IL18", c("Human betaherpesvirus 5 (CMV).pbmc",
                     "Human alphaherpesvirus 1 (HSV1).nasal",
                     "Anelloviridae.pbmc"), modeling_results, viral_colors,
          base_size = 14, log_residuals = T)
ggd
ggsave(paste0(out_dir, "Figure4D.pdf"), width = 12.32142, height = 3)

gge <- traj_plot("IL6", c("Human gammaherpesvirus 4 (EBV).pbmc"), modeling_results,
          viral_colors, base_size = 14, log_residuals = T)
gge
ggsave(paste0(out_dir, "Figure4E.pdf"), width = 4.285714, height = 3)

ggf <- traj_plot("IL10", c("Human gammaherpesvirus 4 (EBV).pbmc", "Human betaherpesvirus 5 (CMV).pbmc"),
          modeling_results, viral_colors, base_size = 14, log_residuals = T)
ggf
ggsave(paste0(out_dir, "Figure4F.pdf"), width = 6.964285, height = 3)

ggg <- traj_plot("IFNG", c("Human betaherpesvirus 5 (CMV).pbmc"), modeling_results,
          viral_colors, base_size = 14, log_residuals = T)
ggg
ggsave(paste0(out_dir, "Figure4G.pdf"), width = 4.285714, height = 3)

```

# Supplemental Figure 8

```{r}

traj_plot <- function(feature, viruses, results_obj, colors, log_residuals = F,
                      variable_width = 0.6, base_size = 12, better_name){
  library(ggpubr)
  if(missing(better_name)){
    feature_name <- feature
  } else {
    feature_name <- better_name
  }
  plot_list <- list()
  for(active_virus in viruses){
      plots <- results_obj[[2]][[paste0(feature, "___", active_virus)]]
      plots$data <- plots$data %>%
        mutate(virus = ifelse(virus == 0, "Control",
                              gsub("\\)", "", gsub(".*\\(", "", active_virus))))
      plots <- plots + scale_color_manual(values = colors, name = "Group")+
        scale_fill_manual(values = colors, name = "Group") +
          theme_classic(base_size  = base_size) +
        ggtitle(" ") +
          ylab(paste0("Normalized ", feature_name)) +
          theme(legend.position = "none",
                axis.text = element_text(color = "black"),
                axis.ticks = element_line(color = "black"))
      plot_list <- c(plot_list, list(plots))
  }
  
  gg2 <- as.data.frame(results_obj[[3]][[feature]]) %>%
    dplyr::rename("residuals" = 16) %>%
    pivot_longer(cols = 17:24) %>%
    mutate(value = ifelse(value > 0, 1, 0)) %>%
    group_by(participant_id, name, value) %>%
    distinct(participant_id, name, value, residuals) %>%
    slice_max(abs(residuals)) %>%
    mutate(name = ifelse(participant_id %in%results_obj[[4]], "Control", name)) %>%
    filter(value!=0|name=="Control") %>%
    mutate(name = gsub("\\)", "", gsub(".*\\(", "", name))) %>%
    filter(name %in% c("Control", gsub("\\)", "", gsub(".*\\(", "", viruses)))) %>%
    distinct() %>%
    mutate(name = fct_relevel(name, "Control")) %>%
    ggplot(aes(x=name, y=abs(residuals), color = name)) +
    #geom_violin(draw_quantiles = T) +
    geom_boxplot(outlier.shape = NA, alpha = 1, width = 0.8) +
    ggbeeswarm::geom_quasirandom(size = 0.01, alpha = 0.3) +
    theme_classic(base_size  = base_size) +
    ggtitle(feature_name) +
    scale_color_manual(values = colors) +
    theme(axis.text.x = element_blank(),
          legend.position = "none",
          axis.text = element_text(color = "black"),
            axis.ticks = element_line(color = "black"),
          axis.text.y = element_text(color = "black")) +
    ylab("Largest Magnitude\nResidual") +
    xlab(" ")
  if(log_residuals){
    gg2 <- gg2 + scale_y_continuous(trans='log10', labels = label_comma())
  }
      return(ggarrange(plotlist = c(list(gg2), plot_list), widths = c(variable_width,rep(1, length(plot_list))),
                       nrow = 1, align = "hv"))
}


viral_colors <- c("Control"="#757575", "EBV.pbmc"="#BF5700", "EBV.nasal"="#008080",
                  "CMV.pbmc"="#005F86", "Anelloviridae.pbmc" = "#86005F",
                  "HSV1.nasal" = "#1b820d", "HSV2.nasal" = "#cba90a")
ggout <- list()
heat_df <- heat_df %>%
  filter(virus_compartment != "Human gammaherpesvirus 4 (EBV).nasal")
for(i in unique(heat_df$feature)){
  active_viruses <- unique(heat_df$virus_compartment[heat_df$feature == i])
  active_viruses <- active_viruses[active_viruses != "Human gammaherpesvirus 4 (EBV).nasal"]
  ggtmp <- traj_plot(i, active_viruses, modeling_results, viral_colors, variable_width = 1, base_size = 9)
  ggout <- c(ggout, list(ggtmp))
  names(ggout)[length(ggout)] <- paste0(i, '_', length(active_viruses))
}

```

```{r, fig.width = 18, fig.height = 15}
## Arranging these is the NP-Hard problem
max_row_length <- 6
ggout <- ggout[!grepl("^IL6|^IL10|^CXCL10|^CXCL11|^IL18",names(ggout))]
for(i in names(ggout)){
  value <- as.numeric(gsub(".*_", "", i))
  if(i==names(ggout)[1]){
    bins <- list(i) } else {
      for(j in length(bins)){
         current_bin_length <- sum(as.numeric(gsub(".*_", "", bins[[j]]))) 
         if((current_bin_length + value) > max_row_length){
           bins <- c(bins, list(i))
         } else {
           bins[[j]] <- c(bins[[j]], i)
         }
      }
    }
}
ggempty <- ggplot() + theme_void()
ggout2 <- list()
counter <- 1
LETTERS_long <- c(LETTERS, "AA", "AB", "AC")
for(k in 1:length(bins)){
  tmp_plots <- ggout[bins[[k]]]
  true_length <- length(tmp_plots)
  if(sum(as.numeric(gsub(".*_", "", bins[[k]]))) < 6){
    tmp_plots <- c(tmp_plots, list(ggempty))
    names(tmp_plots)[length(tmp_plots)] <- paste0("Empty_", max_row_length - sum(as.numeric(gsub(".*_", "", bins[[k]]))))
  }
  values_final <- as.numeric(gsub(".*_", "", names(tmp_plots)))
  ggout2 <- c(ggout2, list(ggarrange(plotlist = tmp_plots, nrow = 1, label.y = 1,
                                     labels = LETTERS_long[counter:(counter+true_length-1)],
                                     widths = values_final + 0.5)))
  counter <- counter + true_length
}

ggarrange(plotlist = ggout2, ncol = 1, nrow = length(ggout2), heights = rep(1, length(ggout2)))
ggsave(paste0(out_dir, "FigureS8.pdf"), width = 21, height = 13)
```

### TGFB Additional Plots

##### Days from Symptom Onset Version

```{r}
counts <- as.data.frame(data_env$serum_olink_counts)[, 10, drop = FALSE]
event_date_cutoff = 40
viral_load_control = TRUE
binary = TRUE
model.out <- data.frame()
  plot_list <- list()
  residual_list <- list()
  max_part <- comb_data %>%
    pivot_longer(cols = -event_id) %>%
    left_join(data_env$clinical_data %>%
                distinct(event_id, participant_id, event_date)) %>%
    filter(event_date >= 0) %>%
    filter(event_date <= event_date_cutoff) %>%
    group_by(participant_id, name) %>%
    filter(name != "Betacoronavirus.nasal") %>%
    dplyr::summarize(value = max(value, na.rm = TRUE)) %>%
    filter(value != -Inf) %>%
    distinct() %>%
    pivot_wider(names_from = name, values_from = value) %>%
    ungroup() %>%
    dplyr::select(-starts_with("Betacoronavirus"))
  
  ## Filter for participants that we have both a nasal and pbmc sample for
  ## Really not that big of deal because we control for nasal viral load
  max_part <- max_part[complete.cases(max_part),]
  ctl_part <- max_part$participant_id[rowSums(max_part[,c(-1)]) == 0]
  
  for(active_vir in colnames(max_part)[9]){
    print(paste0("Starting ", match(active_vir, colnames(max_part)[-1]), " out of ", length(colnames(max_part)[-1])))
    
    tmp.data <- counts %>%
      rownames_to_column("sample_id") %>%
      inner_join(data_env$clinical_data %>% dplyr::select(sample_id, event_id,
                                                          participant_id,
                                                          respiratory_status,
                                                          trajectory_group,
                                                          event_type,
                                                          event_date,
                                                          enrollment_site,
                                                          discretized_admit_age_quantile, symptom_date,
                                                          sex)) %>%
        mutate(event_date = event_date - symptom_date) %>% dplyr::select(-symptom_date) %>%
      inner_join(max_part %>% dplyr::select(participant_id, .data[[active_vir]]), by = "participant_id") %>%
      inner_join(comb_data %>%
                   dplyr::select(event_id, Betacoronavirus.nasal), by = "event_id") %>%
      relocate(sample_id, event_id, event_type, event_date,
               participant_id,
               respiratory_status, trajectory_group, enrollment_site,
               sex,discretized_admit_age_quantile, all_of(active_vir), Betacoronavirus.nasal) %>%
      filter(!is.na(.data[[active_vir]])) %>%
      mutate(sex = as.factor(sex),
             participant_id = as.factor(participant_id),
             event_date = as.numeric(event_date),
             enrollment_site = as.factor(enrollment_site),
             trajectory_group = ordered(as.factor(trajectory_group)),
             respiratory_status = ordered(as.factor(respiratory_status)),
             discretized_admit_age_quantile = ordered(as.factor(discretized_admit_age_quantile))) %>%
     filter(.data[[active_vir]] > 0 | participant_id %in% ctl_part)
    
    if(viral_load_control){
      tmp.data <- tmp.data %>%
        filter(!is.na(Betacoronavirus.nasal)) %>%
        mutate(Betacoronavirus.nasal = log2(Betacoronavirus.nasal + 1))
    }
    
    if(binary){
      ## Convert to a binary approach
      tmp.data[[active_vir]] <- ordered(as.factor(ifelse(tmp.data[[active_vir]] > 0, 1, 0)))
    } else {
      tmp.data[[active_vir]] <- log2(tmp.data[[active_vir]] +1)
    }
    
    
    ## Prepare colnames for formala/modeling
    colnames(tmp.data) <- gsub(" ", "_",
                               gsub("-", "_",
                                    gsub("\\(", "_",sub("\\)", "_",  colnames(tmp.data)))))
    cleaned_vir <- gsub(" ", "_",
                        gsub("-", "_",
                             gsub("\\(", "_",sub("\\)", "_", active_vir))))
    
   
    for(active_feature in colnames(tmp.data)[13:ncol(tmp.data)]){
      
      ## GAMM Modeling ####################
      ## Formula construction
      active_formula <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') + s(event_date, bs = 'cr', by = ", cleaned_vir, ")+s(event_date, bs = 'cr', by = trajectory_group)+", cleaned_vir, "+sex+trajectory_group+discretized_admit_age_quantile"))
      
      if(viral_load_control){
        active_formula <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') + s(event_date, bs = 'cr', by = ", cleaned_vir, ")+s(event_date, bs = 'cr', by = trajectory_group)+", cleaned_vir, "+sex+trajectory_group+discretized_admit_age_quantile+Betacoronavirus.nasal"))
      }
      
      tmp.data.tmp <- tmp.data %>%
        dplyr::select(event_date, enrollment_site, participant_id,
                      trajectory_group, sex, discretized_admit_age_quantile,
                      any_of(active_feature), any_of(cleaned_vir),
                      Betacoronavirus.nasal )
      tmp.data.tmp <- tmp.data.tmp[complete.cases(tmp.data.tmp),]
      
      
      tmp.data.tmp <- tmp.data.tmp %>%
        filter(event_date >= 0) %>%
        filter(event_date <= event_date_cutoff) %>%
        as.data.frame() %>%
        distinct()
    
      fit <- try(gamm4::gamm4(active_formula, random = ~(1|enrollment_site/participant_id), data = as.data.frame(tmp.data.tmp)))
      
      if(class(fit) == "try-error"){
        next
      }
      a1 =anova(fit$gam)
      ## Think about what to do here
      aa1 = sum(a1$s.table[-c(1), 3]*a1$s.table[-c(1), 2])
      aa2 = sum(a1$s.table[-c(1), 2])
      slopep=pchisq(aa1,aa2, lower.tail = F)
      slopep = a1[["s.pv"]][2]
      interceptp =a1$pTerms.pv[1]
      
      virus_n <- length(unique(tmp.data.tmp$participant_id[tmp.data.tmp[[cleaned_vir]] > 0]))
      control_n <- length(unique(tmp.data.tmp$participant_id[tmp.data.tmp[[cleaned_vir]] == 0]))

      model.out <- rbind.data.frame(model.out, c(active_vir, active_feature, slopep, unname(interceptp),
                                 sum(fit$gam$coefficients[grepl(paste0(":", cleaned_vir), names(fit$gam$coefficients))]),
                                 mean(fit$gam$coefficients[grepl(paste0(":", cleaned_vir), names(fit$gam$coefficients))]),
                                 fit$gam$coefficients[2], virus_n, control_n))
      
      if(slopep <= 1 | interceptp <= 1){
        pred <- ggpredict(fit, c("event_date", cleaned_vir), type = "fixed",
                          ci.lvl = 0.95)
        colnames(pred) <- gsub("x", "event_date", gsub("group", "virus", colnames(pred)))
        
        pred <- pred %>%
          mutate(virus = as.character(virus)) %>%
          left_join(tmp.data.tmp %>%
                      dplyr::rename("virus" = 8) %>%
                      mutate(virus = as.character(virus)) %>%
                      group_by(virus) %>%
                      dplyr::summarize(max = max(event_date)), by = "virus") %>%
          filter(event_date <= max)
        
        p1 <-pred %>%
          ggplot(mapping = aes(x = event_date, y = predicted)) +
          geom_line(mapping = aes(group = virus, y = predicted, x=event_date,
                                  color = virus), size = 0.8) +
          geom_ribbon(aes(x=event_date, ymin = conf.low, ymax = conf.high, fill = virus),
                      alpha = 0.3) +
          
          theme_classic(base_size  = 18) +
          scale_color_manual(values = c("lightgray", "#BF5700"))+
          scale_fill_manual(values = c("lightgray", "#BF5700")) +
          ylab(active_feature) +
          xlab("Days from Hospitalization") +
          ggtitle(paste0(active_vir, "\nShape = ",signif(slopep, digits = 3), "\nAverage = ", signif(interceptp, digits = 3)))
        
        plot_list <- c(plot_list, list(p1))
        names(plot_list)[length(plot_list)] <- paste0(active_feature,"___", active_vir)
        
      }
      
      if(active_vir == colnames(max_part)[2]){
        
        ## This next section is to calculate the residuals for a model WITHOUT
        ## Viral reactivation as a feature. For this reason, it only needs to be
        ## ran once, which we do during the first loop. (PS This is for the boxplot component of Figure 4)
        
        tmp.data2 <- counts %>%
          rownames_to_column("sample_id") %>%
          inner_join(data_env$clinical_data %>% dplyr::select(sample_id, event_id,
                                                              participant_id,
                                                              respiratory_status,
                                                              trajectory_group,
                                                              event_type,
                                                              event_date,
                                                              enrollment_site,
                                                              discretized_admit_age_quantile,
                                                              sex)) %>%
          inner_join(max_part %>% dplyr::select(participant_id), by = "participant_id") %>%
          inner_join(comb_data %>%
                       dplyr::select(event_id, Betacoronavirus.nasal), by = "event_id") %>%
          relocate(sample_id, event_id, event_type, event_date,
                   participant_id,
                   respiratory_status, trajectory_group, enrollment_site,
                   sex,discretized_admit_age_quantile, Betacoronavirus.nasal) %>%
          mutate(sex = as.factor(sex),
                 participant_id = as.factor(participant_id),
                 event_date = as.numeric(event_date),
                 enrollment_site = as.factor(enrollment_site),
                 trajectory_group = ordered(as.factor(trajectory_group)),
                 respiratory_status = ordered(as.factor(respiratory_status)),
                 discretized_admit_age_quantile = ordered(as.factor(discretized_admit_age_quantile)))
        
        tmp.data.tmp2 <- tmp.data2 %>%
        dplyr::select(event_date, enrollment_site, participant_id,
                      trajectory_group, sex, discretized_admit_age_quantile,
                      any_of(active_feature),
                      Betacoronavirus.nasal )
        tmp.data.tmp2 <- tmp.data.tmp2[complete.cases(tmp.data.tmp2),]
        tmp.data.tmp2 <- tmp.data.tmp2 %>%
          filter(event_date >= 0) %>%
          filter(event_date <= event_date_cutoff) %>%
          as.data.frame() %>%
          distinct()
        
        ## Construct model without viral reactivation and show residuals
        active_formula2 <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') +s(event_date, bs = 'cr', by = trajectory_group) + sex+trajectory_group+discretized_admit_age_quantile"))
        if(viral_load_control){
          active_formula2 <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') +s(event_date, bs = 'cr', by = trajectory_group) + sex+trajectory_group+discretized_admit_age_quantile+Betacoronavirus.nasal"))
        }
        fit2 <- try(gamm4::gamm4(active_formula2, random = ~(1|enrollment_site/participant_id), data = as.data.frame(tmp.data.tmp2)))
        
        residuals_df <- cbind.data.frame(fit2$gam$model, as.data.frame(fit2$gam$residuals)) %>%
          left_join(max_part, by = "participant_id")
        residual_list <- c(residual_list, list(residuals_df))
        names(residual_list)[length(residual_list)] <- paste0(active_feature)
      }
    }
    
  }
plot(p1 + xlab("Days from Symptom Onset"))
ggsave(paste0(out_dir, "FigureS8_TGF_DFSO.pdf"), width = 6, height = 4)

```

##### Days from Hospitalization

```{r}



event_date_cutoff = 40
viral_load_control = TRUE
binary = TRUE
model.out <- data.frame()
  plot_list <- list()
  residual_list <- list()
  max_part <- comb_data %>%
    pivot_longer(cols = -event_id) %>%
    left_join(data_env$clinical_data %>%
                distinct(event_id, participant_id, event_date)) %>%
    filter(event_date >= 0) %>%
    filter(event_date <= event_date_cutoff) %>%
    group_by(participant_id, name) %>%
    filter(name != "Betacoronavirus.nasal") %>%
    dplyr::summarize(value = max(value, na.rm = TRUE)) %>%
    filter(value != -Inf) %>%
    distinct() %>%
    pivot_wider(names_from = name, values_from = value) %>%
    ungroup() %>%
    dplyr::select(-starts_with("Betacoronavirus"))
  
  ## Filter for participants that we have both a nasal and pbmc sample for
  ## Really not that big of deal because we control for nasal viral load
  max_part <- max_part[complete.cases(max_part),]
  ctl_part <- max_part$participant_id[rowSums(max_part[,c(-1)]) == 0]
  
  for(active_vir in colnames(max_part)[9]){
    print(paste0("Starting ", match(active_vir, colnames(max_part)[-1]), " out of ", length(colnames(max_part)[-1])))
    
    tmp.data <- counts %>%
      rownames_to_column("sample_id") %>%
      inner_join(data_env$clinical_data %>% dplyr::select(sample_id, event_id,
                                                          participant_id,
                                                          respiratory_status,
                                                          trajectory_group,
                                                          event_type,
                                                          event_date,
                                                          enrollment_site,
                                                          discretized_admit_age_quantile, symptom_date,
                                                          sex)) %>%
      dplyr::select(-symptom_date) %>%
      inner_join(max_part %>% dplyr::select(participant_id, .data[[active_vir]]), by = "participant_id") %>%
      inner_join(comb_data %>%
                   dplyr::select(event_id, Betacoronavirus.nasal), by = "event_id") %>%
      relocate(sample_id, event_id, event_type, event_date,
               participant_id,
               respiratory_status, trajectory_group, enrollment_site,
               sex,discretized_admit_age_quantile, all_of(active_vir), Betacoronavirus.nasal) %>%
      filter(!is.na(.data[[active_vir]])) %>%
      mutate(sex = as.factor(sex),
             participant_id = as.factor(participant_id),
             event_date = as.numeric(event_date),
             enrollment_site = as.factor(enrollment_site),
             trajectory_group = ordered(as.factor(trajectory_group)),
             respiratory_status = ordered(as.factor(respiratory_status)),
             discretized_admit_age_quantile = ordered(as.factor(discretized_admit_age_quantile))) %>%
     filter(.data[[active_vir]] > 0 | participant_id %in% ctl_part)
    
    if(viral_load_control){
      tmp.data <- tmp.data %>%
        filter(!is.na(Betacoronavirus.nasal)) %>%
        mutate(Betacoronavirus.nasal = log2(Betacoronavirus.nasal + 1))
    }
    
    if(binary){
      ## Convert to a binary approach
      tmp.data[[active_vir]] <- ordered(as.factor(ifelse(tmp.data[[active_vir]] > 0, 1, 0)))
    } else {
      tmp.data[[active_vir]] <- log2(tmp.data[[active_vir]] +1)
    }
    
    
    ## Prepare colnames for formala/modeling
    colnames(tmp.data) <- gsub(" ", "_",
                               gsub("-", "_",
                                    gsub("\\(", "_",sub("\\)", "_",  colnames(tmp.data)))))
    cleaned_vir <- gsub(" ", "_",
                        gsub("-", "_",
                             gsub("\\(", "_",sub("\\)", "_", active_vir))))
    
   
    for(active_feature in colnames(tmp.data)[13:ncol(tmp.data)]){
      
      ## GAMM Modeling ####################
      ## Formula construction
      active_formula <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') + s(event_date, bs = 'cr', by = ", cleaned_vir, ")+s(event_date, bs = 'cr', by = trajectory_group)+", cleaned_vir, "+sex+trajectory_group+discretized_admit_age_quantile"))
      
      if(viral_load_control){
        active_formula <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') + s(event_date, bs = 'cr', by = ", cleaned_vir, ")+s(event_date, bs = 'cr', by = trajectory_group)+", cleaned_vir, "+sex+trajectory_group+discretized_admit_age_quantile+Betacoronavirus.nasal"))
      }
      
      tmp.data.tmp <- tmp.data %>%
        dplyr::select(event_date, enrollment_site, participant_id,
                      trajectory_group, sex, discretized_admit_age_quantile,
                      any_of(active_feature), any_of(cleaned_vir),
                      Betacoronavirus.nasal )
      tmp.data.tmp <- tmp.data.tmp[complete.cases(tmp.data.tmp),]
      
      
      tmp.data.tmp <- tmp.data.tmp %>%
        filter(event_date >= 0) %>%
        filter(event_date <= event_date_cutoff) %>%
        as.data.frame() %>%
        distinct()
    
      fit <- try(gamm4::gamm4(active_formula, random = ~(1|enrollment_site/participant_id), data = as.data.frame(tmp.data.tmp)))
      
      if(class(fit) == "try-error"){
        next
      }
      a1 =anova(fit$gam)
      ## Think about what to do here
      aa1 = sum(a1$s.table[-c(1), 3]*a1$s.table[-c(1), 2])
      aa2 = sum(a1$s.table[-c(1), 2])
      slopep=pchisq(aa1,aa2, lower.tail = F)
      slopep = a1[["s.pv"]][2]
      interceptp =a1$pTerms.pv[1]
      
      virus_n <- length(unique(tmp.data.tmp$participant_id[tmp.data.tmp[[cleaned_vir]] > 0]))
      control_n <- length(unique(tmp.data.tmp$participant_id[tmp.data.tmp[[cleaned_vir]] == 0]))

      model.out <- rbind.data.frame(model.out, c(active_vir, active_feature, slopep, unname(interceptp),
                                 sum(fit$gam$coefficients[grepl(paste0(":", cleaned_vir), names(fit$gam$coefficients))]),
                                 mean(fit$gam$coefficients[grepl(paste0(":", cleaned_vir), names(fit$gam$coefficients))]),
                                 fit$gam$coefficients[2], virus_n, control_n))
      
      if(slopep <= 1 | interceptp <= 1){
        pred <- ggpredict(fit, c("event_date", cleaned_vir), type = "fixed",
                          ci.lvl = 0.95)
        colnames(pred) <- gsub("x", "event_date", gsub("group", "virus", colnames(pred)))
        
        pred <- pred %>%
          mutate(virus = as.character(virus)) %>%
          left_join(tmp.data.tmp %>%
                      dplyr::rename("virus" = 8) %>%
                      mutate(virus = as.character(virus)) %>%
                      group_by(virus) %>%
                      dplyr::summarize(max = max(event_date)), by = "virus") %>%
          filter(event_date <= max)
        
        p1 <-pred %>%
          ggplot(mapping = aes(x = event_date, y = predicted)) +
          geom_line(mapping = aes(group = virus, y = predicted, x=event_date,
                                  color = virus), size = 0.8) +
          geom_ribbon(aes(x=event_date, ymin = conf.low, ymax = conf.high, fill = virus),
                      alpha = 0.3) +
          
          theme_classic(base_size  = 18) +
          scale_color_manual(values = c("lightgray", "#BF5700"))+
          scale_fill_manual(values = c("lightgray", "#BF5700")) +
          ylab(active_feature) +
          xlab("Days from Hospitalization") +
          ggtitle(paste0(active_vir, "\nShape = ",signif(slopep, digits = 3), "\nAverage = ", signif(interceptp, digits = 3)))
        
        plot_list <- c(plot_list, list(p1))
        names(plot_list)[length(plot_list)] <- paste0(active_feature,"___", active_vir)
        
      }
      
      if(active_vir == colnames(max_part)[2]){
        
        ## This next section is to calculate the residuals for a model WITHOUT
        ## Viral reactivation as a feature. For this reason, it only needs to be
        ## ran once, which we do during the first loop. (PS This is for the boxplot component of Figure 4)
        
        tmp.data2 <- counts %>%
          rownames_to_column("sample_id") %>%
          inner_join(data_env$clinical_data %>% dplyr::select(sample_id, event_id,
                                                              participant_id,
                                                              respiratory_status,
                                                              trajectory_group,
                                                              event_type,
                                                              event_date,
                                                              enrollment_site,
                                                              discretized_admit_age_quantile,
                                                              sex)) %>%
          inner_join(max_part %>% dplyr::select(participant_id), by = "participant_id") %>%
          inner_join(comb_data %>%
                       dplyr::select(event_id, Betacoronavirus.nasal), by = "event_id") %>%
          relocate(sample_id, event_id, event_type, event_date,
                   participant_id,
                   respiratory_status, trajectory_group, enrollment_site,
                   sex,discretized_admit_age_quantile, Betacoronavirus.nasal) %>%
          mutate(sex = as.factor(sex),
                 participant_id = as.factor(participant_id),
                 event_date = as.numeric(event_date),
                 enrollment_site = as.factor(enrollment_site),
                 trajectory_group = ordered(as.factor(trajectory_group)),
                 respiratory_status = ordered(as.factor(respiratory_status)),
                 discretized_admit_age_quantile = ordered(as.factor(discretized_admit_age_quantile)))
        
        tmp.data.tmp2 <- tmp.data2 %>%
        dplyr::select(event_date, enrollment_site, participant_id,
                      trajectory_group, sex, discretized_admit_age_quantile,
                      any_of(active_feature),
                      Betacoronavirus.nasal )
        tmp.data.tmp2 <- tmp.data.tmp2[complete.cases(tmp.data.tmp2),]
        tmp.data.tmp2 <- tmp.data.tmp2 %>%
          filter(event_date >= 0) %>%
          filter(event_date <= event_date_cutoff) %>%
          as.data.frame() %>%
          distinct()
        
        ## Construct model without viral reactivation and show residuals
        active_formula2 <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') +s(event_date, bs = 'cr', by = trajectory_group) + sex+trajectory_group+discretized_admit_age_quantile"))
        if(viral_load_control){
          active_formula2 <- formula(paste0(active_feature, "~s(event_date, bs = 'cr') +s(event_date, bs = 'cr', by = trajectory_group) + sex+trajectory_group+discretized_admit_age_quantile+Betacoronavirus.nasal"))
        }
        fit2 <- try(gamm4::gamm4(active_formula2, random = ~(1|enrollment_site/participant_id), data = as.data.frame(tmp.data.tmp2)))
        
        residuals_df <- cbind.data.frame(fit2$gam$model, as.data.frame(fit2$gam$residuals)) %>%
          left_join(max_part, by = "participant_id")
        residual_list <- c(residual_list, list(residuals_df))
        names(residual_list)[length(residual_list)] <- paste0(active_feature)
      }
    }
    
  }
plot(p1 + xlab("Days from Hospitalization"))
ggsave(paste0(out_dir, "FigureS8_TGF_DSH.pdf"), width = 6, height = 4)
```

## Session Info

```{r}
sessionInfo()
```
