---
title: "Sepsis"
output: pdf_document
---
```{r}
library(readxl)
library(GGally)
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
```

# COMBAT cytokine
```{r}
external_data_path = "/scratch/data-integration/molecular_subtyping/Revisions/External_Datasets/COMBAT/so"
factor_external = read.csv(paste0(external_data_path, 
                                  "/COMBAT_so_projections.csv"))
data_external = read.csv(paste0(external_data_path, 
                                  "/combat_so_normalized_data.csv"))
metadata_external = read_excel(paste0(external_data_path,
                                  "/COMBAT_Luminex_metadata.xlsx"))
metadata_external = metadata_external[,-1]
feature_external = colnames(data_external)[-1]
participant_id_external = data_external$X
rownames(data_external) = data_external$X
data_external = data_external[,-1]

organized_data = readRDS("/scratch/data-integration/molecular_subtyping/Data Preprocessing/phases123_combined_jeremy_072023.rds")
extended_data = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/extended_data.rds")
subtype_labels = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/subtype_hcl.rds")
clin_data_used = readRDS("~/impacc/Analysis/molecular_subtyping/code/Fig1/src/clin_data_aligned.rds")


common_feature = intersect(feature_external,
                           colnames(organized_data$datasets$serum_olink))
cat("Total feature: ", ncol(organized_data$datasets$serum_olink), "\n")
cat("Common feature: ", length(common_feature))
```

# Sepsis vs healthy
```{r, warning=FALSE}
df_external = data_external[, common_feature]
df_prob = data.frame(COMBAT_Luminex_sample_ID = rownames(data_external))
df_prob = inner_join(df_prob, metadata_external, by = "COMBAT_Luminex_sample_ID")
df_prob = df_prob %>% mutate(TimeSinceOnset = as.numeric(TimeSinceOnset)) %>%
  mutate(TimeSinceOnset = ifelse(Source %in% c("HV", "Flu"), 0, TimeSinceOnset)) %>%
  group_by(COMBAT_ID) %>% 
  filter(TimeSinceOnset <= 20) %>% slice_min(TimeSinceOnset) %>%
  mutate(Outcome = ifelse(Outcome == "NA" | Source %in% c("HV", "Flu"), Source, 
                          as.character(Outcome)))
df_prob = df_prob[df_prob$Outcome != 6,] # not hospitalized
df_prob$severity = df_prob$Outcome
df_prob$severity[df_prob$severity == "1"] = "ECMO or Mortality"
df_prob$severity[df_prob$severity == "2"] = "ECMO or Mortality"
df_prob$severity[df_prob$severity == "3"] = "Non-invasive Ventilation / High-Oxygen"
df_prob$severity[df_prob$severity == "4"] = "Oxygen Support"
df_prob$severity[df_prob$severity == "5"] = "No Support"
df_prob$severity[df_prob$severity == "HV"] = "Healthy"

df_sepsis = df_prob[df_prob$severity %in% c("Sepsis", "Healthy"), ]
df_external = df_external[df_sepsis$COMBAT_Luminex_sample_ID, , drop = FALSE]
res_sepsis <- matrix(NA, nrow = length(common_feature), ncol = 3)
rownames(res_sepsis) <- common_feature
colnames(res_sepsis) <- c("stats", "effect_size", "pval")
for (i in 1:length(common_feature)) {
  test_res <- tryCatch({
      t.test(df_external[df_sepsis$severity == "Sepsis", i],
             df_external[df_sepsis$severity == "Healthy", i])},
      error = function(e) NULL)
  if (!is.null(test_res)) {
    n1 <- length(df_external[df_sepsis$severity == "Sepsis", i])
    n2 <- length(df_external[df_sepsis$severity == "Healthy", i])
    n_effect <- n1*n2/(n1+n2)
    res_sepsis[i, "stats"] <- test_res$statistic
    res_sepsis[i, "effect_size"] <- test_res$statistic / sqrt(n_effect)
    res_sepsis[i, "pval"] <- test_res$p.value
  }
}
res_sepsis = na.omit(res_sepsis)
res_sepsis = as.data.frame(res_sepsis)
res_sepsis$adj_pval = p.adjust(res_sepsis$pval, method = "BH")
```

# Within subtype (EF vs ABC)
```{r}
df_original = organized_data$datasets$serum_olink
v1_event_id = clin_data_used$event_id[clin_data_used$event_type == "Visit 1"]
df_original = df_original[v1_event_id, common_feature]
rownames(df_original) = sub("-[^-]+$", "", rownames(df_original))
df_original = df_original[order(rownames(df_original)), ]
df_subtype = subtype_labels[rownames(df_original),]

res_subtype <- matrix(NA, nrow = length(common_feature), ncol = 3)
rownames(res_subtype) <- common_feature
colnames(res_subtype) <- c("stats", "effect_size", "pval")
for (i in 1:length(common_feature)) {
  test_res <- tryCatch({
      t.test(df_original[df_subtype$label == "E" |
                           df_subtype$label == "F", i],
             df_original[df_subtype$label == "A" |
                           df_subtype$label == "B" |
                           df_subtype$label == "C", i])},
      error = function(e) NULL)
  if (!is.null(test_res)) {
    n1 <- length(df_original[df_subtype$label == "E" |
                           df_subtype$label == "F", i])
    n2 <- length(df_original[df_subtype$label == "A" |
                           df_subtype$label == "B" |
                           df_subtype$label == "C", i])
    n_effect <- n1*n2/(n1+n2)
    res_subtype[i, "stats"] <- test_res$statistic
    res_subtype[i, "effect_size"] <- test_res$statistic / sqrt(n_effect)
    res_subtype[i, "pval"] <- test_res$p.value
  }
}
res_subtype = na.omit(res_subtype)
res_subtype = as.data.frame(res_subtype)
res_subtype$adj_pval = p.adjust(res_subtype$pval, method = "BH")
```

# Effect size plot (EF vs ABC)
```{r, fig.height=5, fig.width=5}
common_id = union(rownames(res_sepsis), rownames(res_subtype))
# common_id = intersect(rownames(res_sepsis), rownames(res_subtype))
df_plot = data.frame(
  sample_id = common_id,
  res_sepsis = res_sepsis[common_id, "effect_size"],
  res_subtype = res_subtype[common_id, "effect_size"])

ggplot(df_plot, aes(x = res_subtype, y = res_sepsis, label = sample_id)) +
  geom_point(color = "steelblue", alpha = 0.7) +
  geom_text(vjust = -0.6, size = 4) +
  geom_vline(xintercept = 0, color = "black") +
  geom_hline(yintercept = 0, color = "black") +
  labs(
    x = "Effect Size (EF vs. ABC)",
    y = "Effect Size (Sepsis vs. Healthy)",
    title = "COMBAT Cytokines") +
  theme_minimal() +
  theme(axis.ticks = element_blank(),
          axis.text = element_text(size = 15, color = "black"),
          axis.title = element_text(size = 15, color = "black"))
```

# Within subtype (C vs A)
```{r}
df_original = organized_data$datasets$serum_olink
v1_event_id = clin_data_used$event_id[clin_data_used$event_type == "Visit 1"]
df_original = df_original[v1_event_id, common_feature]
rownames(df_original) = sub("-[^-]+$", "", rownames(df_original))
df_original = df_original[order(rownames(df_original)), ]
df_subtype = subtype_labels[rownames(df_original),]

res_subtype <- matrix(NA, nrow = length(common_feature), ncol = 3)
rownames(res_subtype) <- common_feature
colnames(res_subtype) <- c("stats", "effect_size", "pval")
for (i in 1:length(common_feature)) {
  test_res <- tryCatch({
      t.test(df_original[df_subtype$label == "C", i],
             df_original[df_subtype$label == "A", i])},
      error = function(e) NULL)
  if (!is.null(test_res)) {
    n1 <- length(df_original[df_subtype$label == "C", i])
    n2 <- length(df_original[df_subtype$label == "A", i])
    n_effect <- n1*n2/(n1+n2)
    res_subtype[i, "stats"] <- test_res$statistic
    res_subtype[i, "effect_size"] <- test_res$statistic / sqrt(n_effect)
    res_subtype[i, "pval"] <- test_res$p.value
  }
}
res_subtype = na.omit(res_subtype)
res_subtype = as.data.frame(res_subtype)
res_subtype$adj_pval = p.adjust(res_subtype$pval, method = "BH")
```

# Effect size plot (C vs A)
```{r, fig.height=5, fig.width=5}
common_id = union(rownames(res_sepsis), rownames(res_subtype))
# common_id = intersect(rownames(res_sepsis), rownames(res_subtype))
df_plot = data.frame(
  sample_id = common_id,
  res_sepsis = res_sepsis[common_id, "effect_size"],
  res_subtype = res_subtype[common_id, "effect_size"])

ggplot(df_plot, aes(x = res_subtype, y = res_sepsis, label = sample_id)) +
  geom_point(color = "steelblue", alpha = 0.7) +
  geom_text(vjust = -0.6, size = 4) +
  geom_vline(xintercept = 0, color = "black") +
  geom_hline(yintercept = 0, color = "black") +
  labs(
    x = "Effect Size (C vs. A)",
    y = "Effect Size (Sepsis vs. Healthy)",
    title = "COMBAT Cytokines") +
  theme_minimal() +
  theme(axis.ticks = element_blank(),
          axis.text = element_text(size = 15, color = "black"),
          axis.title = element_text(size = 15, color = "black"))
```

# Within subtype (F vs E)
```{r, warning=FALSE}
df_original = organized_data$datasets$serum_olink
v1_event_id = clin_data_used$event_id[clin_data_used$event_type == "Visit 1"]
df_original = df_original[v1_event_id, common_feature]
rownames(df_original) = sub("-[^-]+$", "", rownames(df_original))
df_original = df_original[order(rownames(df_original)), ]
df_subtype = subtype_labels[rownames(df_original),]

res_subtype <- matrix(NA, nrow = length(common_feature), ncol = 3)
rownames(res_subtype) <- common_feature
colnames(res_subtype) <- c("stats", "effect_size", "pval")
for (i in 1:length(common_feature)) {
  test_res <- tryCatch({
      t.test(df_original[df_subtype$label == "F", i],
             df_original[df_subtype$label == "E", i])},
      error = function(e) NULL)
  if (!is.null(test_res)) {
    n1 <- length(df_original[df_subtype$label == "F", i])
    n2 <- length(df_original[df_subtype$label == "E", i])
    n_effect <- n1*n2/(n1+n2)
    res_subtype[i, "stats"] <- test_res$statistic
    res_subtype[i, "effect_size"] <- test_res$statistic / sqrt(n_effect)
    res_subtype[i, "pval"] <- test_res$p.value
  }
}
res_subtype = na.omit(res_subtype)
res_subtype = as.data.frame(res_subtype)
res_subtype$adj_pval = p.adjust(res_subtype$pval, method = "BH")
```

# Effect size plot (F vs E)
```{r, fig.height=5, fig.width=5}
common_id = union(rownames(res_sepsis), rownames(res_subtype))
# common_id = intersect(rownames(res_sepsis), rownames(res_subtype))
df_plot = data.frame(
  sample_id = common_id,
  res_sepsis = res_sepsis[common_id, "effect_size"],
  res_subtype = res_subtype[common_id, "effect_size"])

ggplot(df_plot, aes(x = res_subtype, y = res_sepsis, label = sample_id)) +
  geom_point(color = "steelblue", alpha = 0.7) +
  geom_text(vjust = -0.6, size = 4) +
  geom_vline(xintercept = 0, color = "black") +
  geom_hline(yintercept = 0, color = "black") +
  labs(
    x = "Effect Size (F vs. E)",
    y = "Effect Size (Sepsis vs. Healthy)",
    title = "COMBAT Cytokines") +
  theme_minimal() +
  theme(axis.ticks = element_blank(),
          axis.text = element_text(size = 15, color = "black"),
          axis.title = element_text(size = 15, color = "black"))
```





