---
title: "IMPACC_figure_S5"
output: html_document
date: "2026-05-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(DT)
library(e1071)
library(openxlsx)
library(stringr)
library(dplyr)
library(plyr)
source("~/Bitbucket/impacc-full-cohort/Analysis/IMPACC_data_analysis_codebase.R")
load("/scratch/metabolomics/plasma-metabolomics-global/scripts/deep_dive_met/deep_dive_data.Rdata")
```


```{r}
Metabolomics_counts_conv = Metabolomics_counts_conv[clinical_data$sample_id,]
plasma_metabolomics_global_rowfeature = Metabolomics_rowfeature
```
```{r}
subpathway_info <- plasma_metabolomics_global_rowfeature[colnames(Metabolomics_counts_conv), ]
chem_to_subpath <- setNames(subpathway_info$SUB_PATHWAY, subpathway_info$CHEMICAL_NAME)

plasma_metabolomics_global_counts_tmp <- Metabolomics_counts_conv[clinical_data$sample_id, ]
plasma_metabolomics_global_rowfeature_tmp <- plasma_metabolomics_global_rowfeature[colnames(plasma_metabolomics_global_counts_tmp), ]
colnames(plasma_metabolomics_global_counts_tmp) <- plasma_metabolomics_global_rowfeature_tmp$CHEMICAL_NAME

counts_df <- as.data.frame(plasma_metabolomics_global_counts_tmp)
counts_df$sample_id <- rownames(counts_df)

counts_long <- counts_df %>%
  pivot_longer(cols = -sample_id, names_to = "CHEMICAL_NAME", values_to = "value") %>%
  mutate(SUB_PATHWAY = chem_to_subpath[CHEMICAL_NAME]) %>%
  filter(!is.na(SUB_PATHWAY) & SUB_PATHWAY != "" & !is.na(value)) %>%
  group_by(sample_id, SUB_PATHWAY) %>%
  dplyr::summarise(value = mean(value, na.rm = TRUE), .groups = "drop")

counts_subpath_wide <- counts_long %>%
  pivot_wider(names_from = SUB_PATHWAY, values_from = value) %>%
  column_to_rownames("sample_id")

data_use_subpath <- counts_subpath_wide %>%
  rownames_to_column(var = "sample_id") %>%
  merge(y = dplyr::select(clinical_data,
                           sample_id,
                           event_date,
                           trajectory_group,
                           enrollment_site,
                           discretized_admit_age_quantile,
                           sex,
                           bmi,
                           participant_id, event_location, conv_cluster4, event_type, Type),
        by = "sample_id") %>%
  filter(!is.na(trajectory_group)) %>%
  filter(duplicated(participant_id) | duplicated(participant_id, fromLast = TRUE)) %>%
  mutate_if(is.character, as.factor) %>%
  mutate(trajectory_group = factor(trajectory_group)) %>%
  pivot_longer(cols = -c("sample_id", "event_date", "participant_id",
                         "enrollment_site", "trajectory_group",
                         "discretized_admit_age_quantile", "sex", "bmi",
                         "event_location", "conv_cluster4", "event_type", "Type")) %>%
  mutate(discretized_admit_age_quantile = factor(discretized_admit_age_quantile)) %>%
  filter(!is.na(value))

data_use_subpath$conv_cluster4 <- as.factor(data_use_subpath$conv_cluster4)
data_use_subpath$OUTCOME <- data_use_subpath$conv_cluster4
source("/scratch/metabolomics/plasma-metabolomics-global/scripts/conv/codebase.R")
# Run the smooth spline model loop on subpathways
smooth_spline_model_loop_subpath <- model_loop(data_use_subpath,
                                               modelType = "smoothSpline",
                                               endpoint  = "OUTCOME")

# Summarize results
sum(smooth_spline_model_loop_subpath$adjp.slope <= 0.05)
sum(smooth_spline_model_loop_subpath$adjp.intercept <= 0.05)
sum(smooth_spline_model_loop_subpath$adjp.slope <= 0.05 & smooth_spline_model_loop_subpath$adjp.intercept <= 0.05)

a_subpath <- subset(smooth_spline_model_loop_subpath,
                    smooth_spline_model_loop_subpath$adjp.slope <= 0.05 &
                    smooth_spline_model_loop_subpath$adjp.intercept <= 0.05)

# Optional save
# save(smooth_spline_model_loop_subpath,
#      file = "/scratch/metabolomics/plasma-metabolomics-global/scripts/deep_dive_met/smooth_spline_model_loop_subpath.Rdata")
```
```{r}
cc1_2 = subset(smooth_spline_model_loop_subpath, smooth_spline_model_loop_subpath$p.slope.adj_1v2 <= 0.05 & smooth_spline_model_loop_subpath$p.intercept.adj_1v2 <= 0.05)
cc1_5 = subset(smooth_spline_model_loop_subpath, smooth_spline_model_loop_subpath$p.slope.adj_1v5 <= 0.05 & smooth_spline_model_loop_subpath$p.intercept.adj_1v5 <= 0.05)
cc1_6 = subset(smooth_spline_model_loop_subpath, smooth_spline_model_loop_subpath$p.slope.adj_1v6 <= 0.05 & smooth_spline_model_loop_subpath$p.intercept.adj_1v6 <= 0.05)
```

```{r}
cc1_2_or = subset(smooth_spline_model_loop_subpath, smooth_spline_model_loop_subpath$p.slope.adj_1v2 <= 0.05 | smooth_spline_model_loop_subpath$p.intercept.adj_1v2 <= 0.05)
cc1_5_or = subset(smooth_spline_model_loop_subpath, smooth_spline_model_loop_subpath$p.slope.adj_1v5 <= 0.05 | smooth_spline_model_loop_subpath$p.intercept.adj_1v5 <= 0.05)
cc1_6_or = subset(smooth_spline_model_loop_subpath, smooth_spline_model_loop_subpath$p.slope.adj_1v6 <= 0.05 | smooth_spline_model_loop_subpath$p.intercept.adj_1v6 <= 0.05)
cc1_2_or$met = rownames(cc1_2_or)
cc1_5_or$met = rownames(cc1_5_or)
cc1_6_or$met = rownames(cc1_6_or)

cc1_2_or =cc1_2_or[,c("met","p.intercept.adj_1v2")]
cc1_2_or$p.intercept.adj_1v2 = -log10(cc1_2_or$p.intercept.adj_1v2)
cc1_5_or =cc1_5_or[,c("met","p.intercept.adj_1v5")]
cc1_5_or$p.intercept.adj_1v5 = -log10(cc1_5_or$p.intercept.adj_1v5)
cc1_6_or =cc1_6_or[,c("met","p.intercept.adj_1v6")]
cc1_6_or$p.intercept.adj_1v6 = -log10(cc1_6_or$p.intercept.adj_1v6)
```

```{r}
met_names <- c("Tryptophan Metabolism","Medium Chain Fatty Acid","Urea cycle; Arginine and Proline Metabolism","Plasmalogen","Androgenic Steroids","Long Chain Polyunsaturated Fatty Acid (n3 and n6)","Long Chain Monounsaturated Fatty Acid","Long Chain Saturated Fatty Acid","Fatty Acid, Dicarboxylate","Tyrosine Metabolism","Phosphatidylcholine (PC)","Fatty Acid Metabolism (Acyl Carnitine, Hydroxy)","Fatty Acid Metabolism (Acyl Carnitine, Medium Chain)","Fatty Acid Metabolism (Acyl Carnitine, Long Chain Saturated)", "Fatty Acid Metabolism (Acyl Carnitine, Monounsaturated)")

# Get predicted lines for all metabolites
pred_all <- lapply(met_names, function(met) {
  exampleDF <- data_use_subpath %>%
    filter(name %in% met) %>%
    mutate(conv_cluster4 = ordered(as.factor(as.character(conv_cluster4)),
                                   levels = c("1", "2", "5", "6")))
  
  plotExample <- plot_model(exampleDF,
                            model_loop     = smooth_spline_model_loop_subpath,
                            modelType      = "smoothSpline",
                            p_adjust       = NA,
                            endpoint       = "conv_cluster4",
                            signif_markers = FALSE,
                            remove_NS      = TRUE,
                            bar_height     = 6.5)
  
  as.data.frame(get("pred", plotExample$plot_env)) %>%
    mutate(conv_cluster4 = paste0(conv_cluster4),
           name = met)
}) %>% bind_rows()

# Recode clusters to labels
pred_all <- pred_all %>%
  mutate(conv_cluster4 = recode(conv_cluster4,
                                "1" = "MIN",
                                "2" = "PHY",
                                "5" = "COG",
                                "6" = "MLT"),
         conv_cluster4 = factor(conv_cluster4, levels = c("MIN", "PHY", "COG", "MLT")))

sig_lookup <- lapply(met_names, function(met) {
  wrapped_name <- str_wrap(met, width = 25) %>% str_replace_all("\n", "<br>")
  data.frame(
    name = met,
    facet_label = paste0(
      wrapped_name, "<br>",
      "<span style='color:#58B5EA'>PHY: ", ifelse(met %in% cc1_2_or$met, "*", "ns"), "</span>  ",
      "<span style='color:#EAAE2A'>COG: ", ifelse(met %in% cc1_5_or$met, "*", "ns"), "</span>  ",
      "<span style='color:#FF1820'>MLT: ", ifelse(met %in% cc1_6_or$met, "*", "ns"), "</span>","</b>"
    ),
    stringsAsFactors = FALSE
  )
}) %>% bind_rows()

# ── 2. Merge into pred_all ────────────────────────────────────────────────
pred_all_new <- pred_all %>%
  left_join(sig_lookup, by = "name")

# ── 3. Plot ───────────────────────────────────────────────────────────────
long <- pred_all_new %>%
  ggplot(aes(x = event_date, y = predicted, colour = conv_cluster4)) +
  geom_line(size = 1.5) +
  facet_wrap(~ facet_label, ncol = 5, nrow = 3,
             scales   = "free_y",
             labeller = label_wrap_gen(width = 30)) +
  labs(y = "Predicted", x = "Days from admission") +
  scale_color_manual(
    name   = "Long COVID",
    values = c("MIN" = "#999999",
               "PHY" = "#58B5EA",
               "COG" = "#EAAE2A",
               "MLT" = "#FF1820")
  ) +
  coord_cartesian(xlim = c(0, max(data_use_subpath$event_date))) +
  theme_classic() +
  theme(
    legend.position  = "right",
    panel.grid.minor = element_blank(),
    axis.title       = element_text(size = 15),
    legend.title     = element_text(size = 15),
    strip.text       = element_markdown(size = 11),
    axis.text        = element_text(size = 15)
  )

long


```

```{r}
sig_lookup <- lapply(met_names, function(met) {
   wrapped_name <- str_wrap(met, width = 25) %>% str_replace_all("\n", "<br>")
  data.frame(
    name = met,
    facet_label = paste0(
      met, "<br>",
      "<span style='color:#58B5EA'>PHY: ", ifelse(met %in% cc1_2_or$met, "*", "ns"), "</span>  ",
      "<span style='color:#EAAE2A'>COG: ", ifelse(met %in% cc1_5_or$met, "*", "ns"), "</span>  ",
      "<span style='color:#FF1820'>MLT: ", ifelse(met %in% cc1_6_or$met, "*", "ns"), "</span>","</b>"
    ),
    stringsAsFactors = FALSE
  )
}) %>% bind_rows()

# ── 2. Merge into pred_all ────────────────────────────────────────────────
pred_all_new <- pred_all %>%
  left_join(sig_lookup, by = "name")

# ── 3. Plot ───────────────────────────────────────────────────────────────
long <- pred_all_new %>%
  ggplot(aes(x = event_date, y = predicted, colour = conv_cluster4)) +
  geom_line(size = 1.5) +
  facet_wrap(~ facet_label, ncol = 3, nrow = 4,
             scales   = "free_y",
             labeller = label_wrap_gen(width = 30)) +
  labs(y = "Predicted", x = "Days from admission") +
  scale_color_manual(
    name   = "Long COVID",
    values = c("MIN" = "#999999",
               "PHY" = "#58B5EA",
               "COG" = "#EAAE2A",
               "MLT" = "#FF1820")
  ) +
  coord_cartesian(xlim = c(0, max(data_use_conv$event_date))) +
  theme_classic() +
  theme(
    legend.position  = "right",
    panel.grid.minor = element_blank(),
    axis.title       = element_text(size = 15),
    legend.title     = element_text(size = 15),
    strip.text       = element_markdown(size = 11),
    axis.text        = element_text(size = 15)
  )

long
```

