---
title: "FigS1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages}
# Most packages are loaded by "class_structure.R" (see below). Load any additional packages here.
library(boot)
```


```{r load code and data, warning=FALSE, message=FALSE}
# setwd("~/impacc_bitbucket_submission/Analysis/data-integration/scripts/public-code/4.figures_and_tables/FigS1/src")

##### Load code
source("../../../0.Codebase/class_structures.R", local=FALSE, chdir=TRUE)
# source("~/impacc_bitbucket_submission/Analysis/data-integration/scripts/public-code/0.Codebase/class_structures.R", local=FALSE, chdir=TRUE)

##### Load data object
# MODIFY THIS
base_obj1 = readRDS(file ="/scratch/data-integration/public_code_results/flipped_impacc_analysis_record_innerfold10.rds") # e.g., ../../3.data_object_preparation/output/mod1_interpretation_base.rds
#base_obj1 = readRDS(file ="") # e.g., ../../3.data_object_preparation/output/mod1_interpretation_base.rds
train.data = readRDS("/scratch/data-integration/pipelines/processedData/mofa_imputed_train_jeremy_20220517.RDS")
test.data = readRDS("/scratch/data-integration/pipelines/processedData/mofa_imputed_test_jeremy_20220517.RDS")



##### Load other data files, if any
fig.s1b.results <- readRDS(file = "../../Fig2/src/Fig2_files/Fig2B_model_eval_results.rds")
fig.s1c.results <- readRDS(file = "FigS1_files/FigS1C_results.rds")

fig.s1e.mcia.multiomics <- readRDS(file = "FigS1_files/FigS1E_MCIA_multi_omics.rds")
fig.s1e.concat.singleomics <- readRDS(file = "FigS1_files/FigS1E_single_omic_cv_predictions.rds")
fig.s1e.results <- readRDS(file = "FigS1_files/FigS1E_results.rds")
fig.s1g.tg2.tg3 <- readRDS(file = "FigS1_files/FigS1G_tg2_vs_tg3.rds")
fig.s1g.results <- readRDS(file = "FigS1_files/FigS1G_results.rds")
fig.s1h.mcia.singleomics <- readRDS(file = "FigS1_files/FigS1H_MCIA_single_omics.rds")
fig.s1h.results <- readRDS(file = "FigS1_files/FigS1H_results.rds")
fig.s1i.concat.literature <- readRDS(file = "FigS1_files/FigS1I_concatenated_literature_sigs.rds")
fig.s1i.results <- readRDS(file = "FigS1_files/FigS1I_results.rds")
fig.s1j.results <- readRDS(file = "FigS1_files/FigS1J_results.rds")
fig.s1k.results <- readRDS(file = "FigS1_files/FigS1K_results.rds")

##### Set global variables
model_cols <- c(
  clin = "#4E8098",
  mcia = "#BA3F1D",
  ensemble = "#B88AC9",
  mcia.lab = "#BA3F1D"
)
names(model_cols)[4] <- "MCIA (Multi-omics)"

dataset_cols <- RColorBrewer::brewer.pal(n = 6, name = "Greys")
dataset_cols_abbrev <- dataset_cols
datasets <- c("Plasma: Targeted Proteomics",
              "Plasma: Global Proteomics (DDA)",
              "Serum: OLINK",
              "Plasma: Global Metabolomics",
              "Nasal: Transcriptomics",
              "PBMC: Transcriptomics")
names(dataset_cols) <- datasets[1:6]
names(dataset_cols_abbrev) <- c("PPT", "PPG", "SPT", "PMG", "NGX", "PGX")
dataset_cols["All Omics Concat."] <- "#218B9A"
dataset_cols["MCIA Modules 1-7"] <- "#64BB56"

severity_cols <- c(
  mild = "#ffba08",
  moderate = "#e85d04",
  severe = "#d00000",
  death = "#370617"
)

tg_colors <- c(
  '#639A21',
  '#6371AD',
  '#BD7D31',
  '#9C3418'
)
names(tg_colors) <- c("TG1", "TG2/TG3", "TG4", "TG5")

# Omic names: 
# note: ppt, ppgd, so, pmg, nt and pbmc correspond to PPT, PPG, SPT, PMG, NGX and PGX, respectively, in the manuscript.
omics_used_DR = c(
  "ppt" = "plasma_proteomics_targeted",
  "ppgd" = "plasma_proteomics_global_dda",
  "so" = "serum_olink",
  "pmg" = "plasma_metabolomics_global",
  "nt" = "nasal_transcriptomics",
  "pbmc" = "pbmc_transcriptomics"
)
omic_short_names = names(omics_used_DR) %>% setNames(omics_used_DR)


##### Output directory
out_dir = "../output/"
dir.create(out_dir, showWarnings = F)
```

```{r functions}
get_ROC = function(probs, Y, simplify = TRUE){
  p.res <- pROC::roc(predictor = probs, response = Y, ci = TRUE, boot.n=100, ci.alpha=0.9, stratified=FALSE)
  if(!simplify){
    return(data.frame(
      tpr = p.res$sensitivities,
      fpr = p.res$specificities,
      auc = rep(p.res$auc, length(p.res$sensitivities)),
      sd = rep(p.res$ci[2] - p.res$ci[1], length(p.res$sensitivities))
    ))
  } else {
    return(data.frame(
      auc = p.res$auc,
      sd = p.res$ci[2] - p.res$ci[1]
    ))
  }
}
get_PR = function(probs, Y){
  library(PRROC)
  pr <- pr.curve(scores.class0 = probs, weights.class0 = Y, curve = TRUE)
  return(pr)
}
get_multiclass_ROC <- function(probs, classes, Y){
  all.res <- data.frame()
  for(j in 1:ncol(probs)){
    # get class:
    cur.class <- classes[j]
    A.probs <- probs[,j]
    # convert Y:
    A.true <- sapply(Y, function(i){if(i == j){return("A")}else{return("B")}})
    tmp.res <- get_ROC(probs = A.probs, Y = A.true, simplify = FALSE)
    tmp.res$class <- cur.class
    all.res <- rbind(all.res, tmp.res)
  }
  return(all.res)
}
get_multiclass_PR <- function(probs, classes, Y){
  all.res <- list()
  for(j in 1:ncol(probs)){
    # get class:
    cur.class <- classes[j]
    A.probs <- probs[,j]
    # convert Y:
    A.true <- sapply(Y, function(i){if(i == j){return(0)}else{return(1)}})
    tmp.res <- get_PR(probs = A.probs, Y = A.true)
    all.res[[cur.class]] <- tmp.res
  }
  return(all.res)
}

get_boostrap_res <- function(model, x, y, type = "corr"){
  df <- data.frame(
    x = x,
    y = y
  )
  #define dataset
  
  if(type == "corr"){
    boot.res <- boot(df, 
                   statistic = function(data, i) {
                       o <- cor(data[i, "x"], data[i, "y"], method = "spearman", use = "pairwise.complete")
                     return(o)
                   },
                   R = 1000)
    res <- data.frame(
      model = model,
      corr = boot.res$t0,
      sd = sd(boot.res$t)
    )
  } else {
    o <- get_ROC(probs = df$y, Y = df$x, simplify = TRUE)
    res <- data.frame(
      model = model,
      corr = o$auc,
      sd = o$sd
    )
  }
  
  return(res)
}

get_cv_res <- function(model, x, y, fold.ids, type = "corr"){

  df <- data.frame(
    x = x,
    y = y
  )
  
  
  # initial:
  if(type == "corr"){
    initial.cor <- cor(df$x, df$y, method = "spearman", use = "pairwise.complete")
  } else if(type == "auc"){
    initial.auc <- get_ROC(probs = df$y, Y = df$x)$auc
  }
  
  # bootstrap:
  R = 1000
  if(type == "corr"){
    cors <- c()
    for(i in 1:R){
      folds <- sort(sample(1:max(fold.ids), size = 50, replace = TRUE))
      df.tmp <- data.frame()
      for(f in folds){
        df.tmp <- rbind(df.tmp, df[which(fold.ids == f),])
      }
      cor.tmp <- cor(df.tmp$x, df.tmp$y, method = "spearman", use = "pairwise.complete")
      cors <- c(cors, cor.tmp)
    }  
  } else if(type == "auc"){
    aucs <- c()
    for(i in 1:R){
      folds <- sort(sample(1:max(fold.ids), size = 50, replace = TRUE))
      df.tmp <- data.frame()
      for(f in folds){
        df.tmp <- rbind(df.tmp, df[which(fold.ids == f),])
        rownames(df.tmp) <- NULL
      }
      auc.tmp <- get_ROC(probs = df.tmp$y, Y = df.tmp$x)$auc
      aucs <- c(aucs, auc.tmp)
    }
  }
  
  
  if(type == "corr"){
    res <- data.frame(
      model = model,
      value = initial.cor,
      sd = sd(cors, na.rm = TRUE)
    )
  } else if(type == "auc"){
    res <- data.frame(
      model = model,
      value = initial.auc,
      sd = sd(aucs, na.rm = TRUE)
    )
  }
  
  return(res)
}

get_P4v5 <- function(probs){
  return(probs[,3]/(probs[,3] + probs[,4]))
}
```


```{r panel S1A plotting}
coef_mat_mcia = base_obj1$coef_extract_composite(
  model = base_obj1$model_mcia$model_full,
  method =  "MCIA")

coef_mat_clin = base_obj1$coef_extract_composite(
  model = base_obj1$model_clin$model_full,
  method =  "CLIN")

coef_mat_mcia$Feature <- c(
  rep(paste0("Factor ", 1:7), 2)
)

coef_mat_clin$Feature <- rep(c(
  "Sex",
  "BMI",
  # Comorbidities:
  paste0("Comorb: ", c(
  "Hypertension",
  "Diabetes",
  "Pulmonary Disease",
  "Asthma",
  "Chronic Cardiac Disease",
  "Chronic Kidney Disease",
  "Malignant Neoplasm",
  "Chronic Neurological Disorder",
  "Liver Disease",
  "Organ/BM Transplant",
  "HIV",
  "Smoking/Vaping",
  "Drugs/Alcohol Abuse/Cannibis",
  "Total Count",
  "Total Count (categorical)")),
  # Baseline:
  paste0("Baseline: ", c(
  "Chest Image Radiography",
  "Lymphocyte",
  "Platelet",
  "ALT",
  "Creatinine",
  "CRP",
  "D-dimer",
  "Troponin")),
  # Race
  paste0("Race: ", c(
    "American Indian/Alaska Native",
    "Asian",
    "Black/African American",
    "Multiple",
    "Native Hawaiian/Pacific Islander",
    "Other/Declined",
    "White")),
  # Ethnicity
  paste0("Ethnicity: ", c(
    "Hispanic/Latino",
    "Not Hispanic/Latino"
  )),
  # Race
  paste0("Age: ", c(
    "36-51",
    "52-66",
    "67-81",
    "82-96"
  ))
), 2)


coef_mat = rbind(coef_mat_mcia, coef_mat_clin)
# set to NA if below thresh
coef.thresh <- .1
coef_mat$coef[abs(coef_mat$coef) < coef.thresh] <- NA

# factor:
coef_mat$Feature <- factor(coef_mat$Feature, levels = unique(c(
  paste0("Factor ", 1:7),
  "Sex",
  "BMI",
  coef_mat_clin$Feature[grepl("Age", coef_mat_clin$Feature)],
  sort(coef_mat_clin$Feature)
)))

sup.fig.s1a <- ggplot(coef_mat) +
  geom_tile(aes(x = Feature, y = model), fill = "white", color = "grey50", size = .1) +
  geom_point(aes(x = Feature, y = model, fill = coef, size = abs(coef)), shape = 21) +
  #geom_segment(x = 0.5, xend = .5 + length(unique(coef_mat$Feature)), y = 1.5, yend = 1.5, size = .1)
  scale_fill_gradient2(low = "darkblue", high = "darkred", na.value = "white") +
  scale_size_continuous(range = c(2, 7)) +
  scale_y_discrete(labels = c("Mortality", "Severity")) +
  #scale_x_discrete(labels = paste0("Module ", 1:7)) +
  coord_equal() +
  guides(size = "none") +
  theme_bw() +
  xlab(NULL) +
  ylab(NULL) +
  labs(fill = "Coef.") +
  theme(axis.text.x = element_text(angle = 270, hjust = 0, vjust = .5),
        panel.grid = element_blank(),
        panel.background = element_blank(), panel.border = element_blank())

# save plot:
ggsave(filename = "../output/FigS1A.pdf", plot = sup.fig.s1a, width = 12, height = 3)
```


```{r panel S1B plotting}
# Load result file (NOTE: Uses object generated in Fig2 script)
total.df.filt.main <- fig.s1b.results$metrics
comparison.bars <- fig.s1b.results$bars
all.pvals.melt.main <- fig.s1b.results$pvals

sup.fig.s1b <- ggplot(dplyr::filter(total.df.filt.main, test == "Train")) +
  geom_bar(aes(x = model, y = value, fill = model), color = "black", stat = "identity") +
  geom_errorbar((aes(x = model, ymin = value - sd, ymax = value + sd)), width = .5) +
  geom_segment(data = comparison.bars, aes(x = x, y = y, xend = xend, yend = yend), size = .5, color = "grey50") +
  geom_text(data = all.pvals.melt.main, aes(x = xpos, y = ypos, label = asterisk)) +
  geom_hline(yintercept = 0, color = "black", size = .5) +
  theme_bw() +
  ylab(NULL) +
  xlab(NULL) +
  theme(axis.text.x = element_text(angle = 315, hjust = 0, vjust = .5),
        plot.title = element_text(hjust = .5, size = 12),
        panel.grid.major.x = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank()) +
  guides(fill = "none") +
  scale_fill_manual(values = model_cols) +
  scale_x_discrete(labels = c("MCIA", "Clinical", "Ensemble")) +
  scale_y_continuous(limits = c(0, 1.1), breaks = seq(0, 1, by = .2), minor_breaks = NULL) +
  facet_grid(rows = vars(factor(test, levels = c("Train", "Test"))), cols = vars(factor(task, levels = c("TG1/23/45 vs. P(TG45)\nSpearman Corr.",
                                                                  "TG123/45 vs. P(TG45)\nAUROC",
                                                                  "TG4/5 vs. P(TG5)\nAUROC"
                                                                  ))))

# save plot:
ggsave(filename = "../output/FigS1B.pdf", plot = sup.fig.s1b, width = 4, height = 3)
```


```{r panel S1C preparation, eval = FALSE}
# Set seed
set.seed(123)

# 1 v 23 v 4 v 5
trad_probs <- data.frame(
  mcia = 1 - base_obj1$test_prediction_list$mcia_prob[,1],
  clin = 1 - base_obj1$test_prediction_list$clin_prob[,1],
  ensemble_mcia_clin = 1 - base_obj1$test_prediction_list$ENSEMBL.mcia.clin[,1],
  TGgrp = dplyr::filter(base_obj1$clin.test, event_type == "Visit 1")$trajectory_group,
  TGgrp.merge = sapply(dplyr::filter(base_obj1$clin.test, event_type == "Visit 1")$trajectory_group, function(tg){
    if(tg == 1){
      return(1)
    } else if(tg %in% 2:3){
      return(2)
    } else if(tg == 4){
      return(3)
    } else {
      return(4)
    }
}),
  baseline_resp = dplyr::filter(base_obj1$clin.test, event_type == "Visit 1")$resp_status_v1
)

# PR:
mcia.te.full <- get_multiclass_PR(base_obj1$test_prediction_list$mcia_prob, c("TG1", "TG2/TG3", "TG4", "TG5"), trad_probs$TGgrp.merge)
clin.te.full <- get_multiclass_PR(base_obj1$test_prediction_list$clin_prob[complete.cases(base_obj1$test_prediction_list$clin_prob),], c("TG1", "TG2/TG3", "TG4", "TG5"), trad_probs$TGgrp.merge[complete.cases(base_obj1$test_prediction_list$clin_prob)])
ensemble.te.full <- get_multiclass_PR(base_obj1$test_prediction_list$ENSEMBL.mcia.clin[complete.cases(base_obj1$test_prediction_list$ENSEMBL.mcia.clin),], c("TG1", "TG2/TG3", "TG4", "TG5"), trad_probs$TGgrp.merge[complete.cases(base_obj1$test_prediction_list$ENSEMBL.mcia.clin)])

# AUROC:
mcia.te.full <- get_multiclass_ROC(base_obj1$test_prediction_list$mcia_prob, c("TG1", "TG2/TG3", "TG4", "TG5"), trad_probs$TGgrp.merge)
mcia.te.full$model <- "mcia"
clin.te.full <- get_multiclass_ROC(base_obj1$test_prediction_list$clin_prob, c("TG1", "TG2/TG3", "TG4", "TG5"), trad_probs$TGgrp.merge)
clin.te.full$model <- "clin"
ensemble.te.full <- get_multiclass_ROC(base_obj1$test_prediction_list$ENSEMBL.mcia.clin, c("TG1", "TG2/TG3", "TG4", "TG5"), trad_probs$TGgrp.merge)
ensemble.te.full$model <- "ensemble"

all.res <- rbind(mcia.te.full,
                 clin.te.full,
                 ensemble.te.full)
all.res <- all.res[nrow(all.res):1,]

# Save:
#saveRDS(all.res, "FigS1_files/FigS1C_results.rds")
```

```{r panel S1C plotting}
all.res <- fig.s1c.results

sup.fig.s1c <- ggplot(all.res) +
  geom_abline(slope = 1, linetype = "dashed", color = "grey10", size = .2) +
  geom_line(aes(x = 1-fpr, y = tpr, color = model)) +
  scale_color_manual(values = model_cols) +
  facet_wrap(vars(class), nrow = 2) +
  xlab("FPR") +
  ylab("TPR") +
  ggtitle("Multi-class AUROC") +
  theme_bw() +
  theme(plot.title = element_text(hjust = .5)) +
  labs(color = "Model")

# save plot:
ggsave(filename = "../output/FigS1C.pdf", plot = sup.fig.s1c, width = 4, height = 4)

# Table (to plot:)
sup.fig.s1c.table <- dplyr::distinct(all.res, auc, sd, class, model)
write.csv(sup.fig.s1c.table, "../output/FigS1Ctable.csv")
```


```{r panel S1D plotting}
prob.list <- list(
  mcia = base_obj1$test_prediction_list$mcia_prob,
  clin = base_obj1$test_prediction_list$clin_prob,
  ensemble = base_obj1$test_prediction_list$ENSEMBL.mcia.clin
)

df.all <- data.frame()
df.background.all <- data.frame()
for(model in names(prob.list)){
  probs <- prob.list[[model]]
  prob_glob <- probs[,3] + probs[,4]
  prob_45 <- probs[,4]/(prob_glob)
  tg <- dplyr::filter(base_obj1$clin.test, event_type == "Visit 1")$trajectory_group
  eps = 1e-2
  df <- data.frame(
    prob_glob = prob_glob,
    log_prob_glob = qqnorm(log((prob_glob + eps)/(1-prob_glob + eps)),plot.it=F)$x,
    prob_45 = prob_45,
    log_prob_45 = qqnorm(log((prob_45 + eps)/(1-prob_45 + eps)),plot.it=F)$x,
    tg = c("TG1", "TG2/TG3", "TG2/TG3", "TG4", "TG5")[tg],
    model = model
  )
  df.all <- rbind(df.all, df)
  df.background <- df
  colnames(df.background)[1:5] <- paste0(colnames(df.background)[1:5], "_background")
  # global: 80% of TG4/5 are to the right
  df.tmp <- dplyr::arrange(df.background, -log_prob_glob_background)
  ranked.tgs <- df.tmp$tg
  tot <- sum(ranked.tgs %in% c("TG4", "TG5"))
  thresh <- as.integer(.8 * tot)
  df.background$glob_line <- df.tmp$log_prob_glob_background[which(ranked.tgs %in% c("TG4", "TG5"))[thresh]]
  # 4/5: 80% of TG5 are above
  df.tmp <- dplyr::arrange(df.background, -log_prob_45_background)
  ranked.tgs <- df.tmp$tg
  tot <- sum(ranked.tgs == "TG5")
  thresh <- as.integer(.8 * tot)
  df.background$sev_line <- df.tmp$log_prob_45_background[which(ranked.tgs == "TG5")[thresh]]
  df.background.all <- rbind(df.background.all, df.background)
}

bg_col <- "grey50"

sup.fig.s1d <- ggplot() +
  # background
  geom_hline(yintercept = unique(dplyr::filter(df.background.all, model == "mcia")$sev_line), linetype = "dashed") +
  geom_vline(xintercept = unique(dplyr::filter(df.background.all, model == "mcia")$glob_line), linetype = "dashed") +
  stat_ellipse(data = dplyr::filter(df.background.all, model == "mcia"), aes(x = log_prob_glob_background, y = log_prob_45_background, group = tg_background), color = bg_col) +
  geom_point(data = dplyr::filter(df.background.all, model == "mcia"), aes(x = log_prob_glob_background, y = log_prob_45_background), shape = 21, color = bg_col) +
  # only color each facet:
  stat_ellipse(data = dplyr::filter(df.all, model == "mcia"), aes(x = log_prob_glob, y = log_prob_45, group = tg, fill = tg), geom = "polygon", alpha = .5) +
  geom_point(data = dplyr::filter(df.all, model == "mcia"), aes(x = log_prob_glob, y = log_prob_45, fill = tg), shape = 21) +
  scale_fill_manual(values = tg_colors) +
  #facet_grid(cols = vars(tg), rows = vars(model)) +
  facet_wrap(vars(tg), nrow = 2) + 
  xlab("Severity") +
  ylab("Mortality") +
  labs(fill = "Trajectory Group") +
  theme_bw()

# save plot:
ggsave(filename = "../output/FigS1D.pdf", plot = sup.fig.s1d, width = 4, height = 4)
```


```{r panel S1E preparation, eval = FALSE}
# Set seed
set.seed(123)

# load model prediction results:
obj <- fig.s1e.mcia.multiomics
supp.obj <- fig.s1e.concat.singleomics
ordinal_probs <- obj$ordinal_probs
TG45_probs <- obj$TG45_probs

# add data:
ordinal_probs$dataset1 <- 1 - supp.obj[[1]]$nested_cv_probs[,1]
ordinal_probs$dataset2 <- 1 - supp.obj[[2]]$nested_cv_probs[,1]
ordinal_probs$dataset3 <- 1 - supp.obj[[3]]$nested_cv_probs[,1]
ordinal_probs$dataset4 <- 1 - supp.obj[[4]]$nested_cv_probs[,1]
ordinal_probs$dataset5 <- 1 - supp.obj[[5]]$nested_cv_probs[,1]
ordinal_probs$dataset6 <- 1 - supp.obj[[6]]$nested_cv_probs[,1]
ordinal_probs$dataset7 <- 1 - supp.obj[[7]]$nested_cv_probs[,1]
ordinal_probs$dataset8 <- 1 - supp.obj[[8]]$nested_cv_probs[,1]

TG45_probs$dataset1 <- supp.obj[[1]]$nested_cv_probs[,3] / (supp.obj[[1]]$nested_cv_probs[,3] + supp.obj[[1]]$nested_cv_probs[,4])
TG45_probs$dataset2 <- supp.obj[[2]]$nested_cv_probs[,3] / (supp.obj[[2]]$nested_cv_probs[,3] + supp.obj[[2]]$nested_cv_probs[,4])
TG45_probs$dataset3 <- supp.obj[[3]]$nested_cv_probs[,3] / (supp.obj[[3]]$nested_cv_probs[,3] + supp.obj[[3]]$nested_cv_probs[,4])
TG45_probs$dataset4 <- supp.obj[[4]]$nested_cv_probs[,3] / (supp.obj[[4]]$nested_cv_probs[,3] + supp.obj[[4]]$nested_cv_probs[,4])
TG45_probs$dataset5 <- supp.obj[[5]]$nested_cv_probs[,3] / (supp.obj[[5]]$nested_cv_probs[,3] + supp.obj[[5]]$nested_cv_probs[,4])
TG45_probs$dataset6 <- supp.obj[[6]]$nested_cv_probs[,3] / (supp.obj[[6]]$nested_cv_probs[,3] + supp.obj[[6]]$nested_cv_probs[,4])
TG45_probs$dataset7 <- supp.obj[[7]]$nested_cv_probs[,3] / (supp.obj[[7]]$nested_cv_probs[,3] + supp.obj[[7]]$nested_cv_probs[,4])
TG45_probs$dataset8 <- supp.obj[[8]]$nested_cv_probs[,3] / (supp.obj[[8]]$nested_cv_probs[,3] + supp.obj[[8]]$nested_cv_probs[,4])

TG123_45probs <- ordinal_probs
TG123_45probs$TGgrp.merge[TG123_45probs$TGgrp.merge == 1] <- 2
TG123_45probs$TGgrp.merge <- TG123_45probs$TGgrp.merge - 1

# First plot: spearman correlation of true TGgrp (1 vs 2/3 vs 4/5) vs. 1-P(TG1)
x <- ordinal_probs$TGgrp.merge
y <- ordinal_probs$mcia
cv.folds <- obj$nest_cv_foldid
mcia.cors <- get_cv_res("mcia", x, y, fold.ids = cv.folds)

y <- ordinal_probs$clin
clin.cors <- get_cv_res("clin", x, y, fold.ids = cv.folds)

y <- ordinal_probs$ensemble_mcia_clin
emc.cors <- get_cv_res("ensemble_mcia_clin", x, y, fold.ids = cv.folds)

ordinal.cors <- list(
  mcia = mcia.cors,
  clin = clin.cors,
  ensemble_mcia_clin = emc.cors
)
datasets <- c("Plasma: Targeted Proteomics",
              "Plasma: Global Proteomics (DDA)",
              "Serum: OLINK",
              "Plasma: Global Metabolomics",
              "Nasal: Transcriptomics",
              "PBMC: Transcriptomics",
              "All Omics Concat.",
              "MCIA Modules 1-7")
datasets <- c("PPT", "PPG", "SPT", "PMG", "NGX", "PGX", "All Omics Concat.", "MCIA Modules 1-7")
for(d in 1:8){
  y <- ordinal_probs[[paste0("dataset", d)]]
  dataset.cors <- get_cv_res(datasets[d], x, y, fold.ids = cv.folds)
  ordinal.cors[[paste0("dataset", d)]] <- dataset.cors
}

# 123 vs 45
x <- TG123_45probs$TGgrp
y <- TG123_45probs$mcia
mcia.cors <- get_cv_res("mcia", x, y, cv.folds, type = "auc")

y <- TG123_45probs$clin
clin.cors <- get_cv_res("clin", x, y, cv.folds, type = "auc")

y <- TG123_45probs$ensemble_mcia_clin
emc.cors <- get_cv_res("ensemble_mcia_clin", x, y, cv.folds, type = "auc")

onetwothree_fourfive.cors <- list(
  mcia = mcia.cors,
  clin = clin.cors,
  ensemble_mcia_clin = emc.cors
)
for(d in 1:8){
  y <- TG123_45probs[[paste0("dataset", d)]]
  dataset.cors <- get_cv_res(datasets[d], x, y, fold.ids = cv.folds, type = "auc")
  onetwothree_fourfive.cors[[paste0("dataset", d)]] <- dataset.cors
}

# TG4 vs 5:
# Subset to only use TG4/5:
TG45_probs <- dplyr::filter(TG45_probs, TGgrp >= 4)
cv.folds.45 <- cv.folds[which(obj$TG45_probs$TGgrp >= 4)]

x <- TG45_probs$TGgrp
y <- TG45_probs$mcia
mcia.cors <- get_cv_res("mcia", x, y, cv.folds.45, type = "auc")

y <- TG45_probs$clin
clin.cors <- get_cv_res("clin", x, y, cv.folds.45, type = "auc")

y <- TG45_probs$ensemble_mcia_clin
emc.cors <- get_cv_res("ensemble_mcia_clin", x, y, cv.folds.45, type = "auc")

four.vs.five.cors <- list(
  mcia = mcia.cors,
  clin = clin.cors,
  ensemble_mcia_clin = emc.cors
)
for(d in 1:8){
  y <- TG45_probs[[paste0("dataset", d)]]
  dataset.cors <- get_cv_res(datasets[d], x, y, fold.ids = cv.folds.45, type = "auc")
  four.vs.five.cors[[paste0("dataset", d)]] <- dataset.cors
}

# plot:
cor.list <- ordinal.cors
df <- do.call("rbind", cor.list)
df$task <- "TG(1/23/45) vs. P(TG45)\nSpearman Correlation"
ord.df <- df
cor.list <- onetwothree_fourfive.cors
df <- do.call("rbind", cor.list)
df$task <- "TG(123/45) vs. P(TG45)\nAUROC"
bin.df <- df
cor.list <- four.vs.five.cors
df <- do.call("rbind", cor.list)
df$task <- "TG(4/5) vs. P(TG5)\nAUROC"
sev.df <- df

total.df <- rbind(ord.df, bin.df, sev.df)

all_colors <- c(model_cols, dataset_cols)
rel.models <- c("All Assays (MCIA)", "All Assays (Concat.)", "All Assays (Multinom.)", datasets[1:6])

total.df$xpos <- unname(unlist(sapply(total.df$model, function(m){
  if(m == "mcia") return(1);
  if(m == datasets[1]) return(2.2);
  if(m == datasets[2]) return(3.2);
  if(m == datasets[3]) return(4.2);
  if(m == datasets[4]) return(5.2);
  if(m == datasets[5]) return(6.2);
  if(m == datasets[6]) return(7.2);
  if(m == datasets[7]) return(8.4);
  if(m == datasets[8]) return(9.4);
  return(0)
})))
total.df$model[which(total.df$model == "mcia")] <- "All Assays (MCIA)"
total.df$model[which(total.df$model == "MCIA Modules 1-7")] <- "All Assays (Multinom.)"
total.df$model[which(total.df$model == "All Omics Concat.")] <- "All Assays (Concat.)"
total.df <- dplyr::filter(total.df, model != "MCIA Modules 1-7")
total.df$model <- factor(total.df$model, levels = unique(total.df$model))
total.df <- dplyr::filter(total.df, task != "TG(123/45) vs. P(TG45)\nAUROC")

#Facets:
total.df$task[which(total.df$task == "TG(1/23/45) vs. P(TG45)\nSpearman Correlation")] <- "Severity Task\n(TG1vsTG2/3vsTG4/5)"
total.df$task[which(total.df$task == "TG(4/5) vs. P(TG5)\nAUROC")] <- "Mortality Task\n(TG4vsTG5)"

# Save:
#saveRDS(total.df, "FigS1_files/FigS1E_results.rds")
```

```{r panel S1E plotting}
total.df <- fig.s1e.results

mcia.mo.col <- c("#BA3F1D")
names(mcia.mo.col) <- c("All Assays (MCIA)")
all.assay.col <- c("#BAAC1D")
names(all.assay.col) <- c("All Assays (Concat.)")
concat.assay.col <- c("#9F886E")
names(concat.assay.col) <- c("All Assays (Multinom.)")

sup.fig.s1e <- ggplot() +
  geom_bar(data = dplyr::filter(total.df, model %in% rel.models), aes(x = xpos, y = value, fill = model), color = "black", size = .3, stat = "identity") +
  geom_errorbar(data = dplyr::filter(total.df, model %in% rel.models), aes(x = xpos, ymin = value - sd, ymax = value + sd), width = .5) +
  geom_hline(data = dplyr::filter(total.df, model == "All Assays (MCIA)"), aes(yintercept = value), size = .5, linetype = "dashed", color = "grey20") +
  facet_wrap(vars(factor(task, levels = c("Severity Task\n(TG1vsTG2/3vsTG4/5)", "Mortality Task\n(TG4vsTG5)")))) +
  theme_bw() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), plot.title = element_text(hjust = .5)) +
  scale_fill_manual(
    values = c(mcia.mo.col, dataset_cols_abbrev, all.assay.col, concat.assay.col)) +
  ylab(NULL) +
  xlab(NULL) +
  labs(fill = "Model") +
  ggtitle("Multi-omics vs. Single-omics using Concatenation")

# save plot:
ggsave(filename = "../output/FigS1E.pdf", plot = sup.fig.s1e, width = 4, height = 3)
```


```{r panel S1F plotting}
df <- data.frame(
  deviance.loss = base_obj1$deviance_loss_vec_cv,
  modules = 2:(length(base_obj1$deviance_loss_vec_cv) + 1)
)

sup.fig.s1f <- ggplot(df) +
  geom_line(aes(x = modules, y = deviance.loss)) +
  geom_point(aes(x = modules, y = deviance.loss)) +
  geom_hline(yintercept = dplyr::filter(df, modules == 7)$deviance.loss, linetype = "dashed") +
  theme_bw() +
  ylab("Deviance Loss") +
  xlab("Number of Multi-omics Factors")

# save plot:
ggsave(filename = "../output/FigS1F.pdf", plot = sup.fig.s1f, width = 4, height = 4)
```


```{r panel S1G preparation, eval = FALSE}
obj <- fig.s1e.mcia.multiomics
supp.obj <- fig.s1g.tg2.tg3
ordinal_probs <- obj$ordinal_probs
TG45_probs <- obj$TG45_probs
x <- supp.obj[[1]]$TGgrp
y <- supp.obj[[1]]$nested_cv_probs[,1]
cv.folds <- supp.obj[[1]]$foldids
mcia.cors <- get_cv_res("mcia", x, y, fold.ids = cv.folds)
mcia.cv.full <- get_multiclass_ROC(supp.obj[[1]]$nested_cv_probs, c("TG2", "TG3"), supp.obj[[1]]$TGgrp + 1)
mcia.cv.full$model <- "mcia"

all.res <- mcia.cv.full

all.res <- all.res[nrow(all.res):1,]

# Save:
#saveRDS(all.res, "FigS1_files/FigS1G_results.rds")
```

```{r panel S1G plotting}
all.res <- fig.s1g.results

sup.fig.s1g <- ggplot(dplyr::filter(all.res, class == "TG2")) +
  geom_abline(slope = 1, linetype = "dashed", color = "grey10", size = .2) +
  geom_line(aes(x = 1-fpr, y = tpr, color = model)) +
  scale_color_manual(values = "black") +
  xlab("FPR") +
  ylab("TPR") +
  ggtitle("TG2 vs. TG3 (AUROC = 0.558)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = .5)) +
  guides(color = "none")

# save plot:
ggsave(filename = "../output/FigS1G.pdf", plot = sup.fig.s1g, width = 4, height = 4)
```


```{r panel S1H preparation, eval = FALSE}
# Set seed:
set.seed(123)

obj <- fig.s1e.mcia.multiomics
supp.obj <- fig.s1h.mcia.singleomics
ordinal_probs <- obj$ordinal_probs
TG45_probs <- obj$TG45_probs

# add data:
ordinal_probs$dataset1 <- 1 - supp.obj[[1]]$nested_cv_probs[,1]
ordinal_probs$dataset2 <- 1 - supp.obj[[2]]$nested_cv_probs[,1]
ordinal_probs$dataset3 <- 1 - supp.obj[[3]]$nested_cv_probs[,1]
ordinal_probs$dataset4 <- 1 - supp.obj[[4]]$nested_cv_probs[,1]
ordinal_probs$dataset5 <- 1 - supp.obj[[5]]$nested_cv_probs[,1]
ordinal_probs$dataset6 <- 1 - supp.obj[[6]]$nested_cv_probs[,1]

TG45_probs$dataset1 <- supp.obj[[1]]$nested_cv_probs[,3] / (supp.obj[[1]]$nested_cv_probs[,3] + supp.obj[[1]]$nested_cv_probs[,4])
TG45_probs$dataset2 <- supp.obj[[2]]$nested_cv_probs[,3] / (supp.obj[[2]]$nested_cv_probs[,3] + supp.obj[[2]]$nested_cv_probs[,4])
TG45_probs$dataset3 <- supp.obj[[3]]$nested_cv_probs[,3] / (supp.obj[[3]]$nested_cv_probs[,3] + supp.obj[[3]]$nested_cv_probs[,4])
TG45_probs$dataset4 <- supp.obj[[4]]$nested_cv_probs[,3] / (supp.obj[[4]]$nested_cv_probs[,3] + supp.obj[[4]]$nested_cv_probs[,4])
TG45_probs$dataset5 <- supp.obj[[5]]$nested_cv_probs[,3] / (supp.obj[[5]]$nested_cv_probs[,3] + supp.obj[[5]]$nested_cv_probs[,4])
TG45_probs$dataset6 <- supp.obj[[6]]$nested_cv_probs[,3] / (supp.obj[[6]]$nested_cv_probs[,3] + supp.obj[[6]]$nested_cv_probs[,4])

TG123_45probs <- ordinal_probs
TG123_45probs$TGgrp.merge[TG123_45probs$TGgrp.merge == 1] <- 2
TG123_45probs$TGgrp.merge <- TG123_45probs$TGgrp.merge - 1

# First plot: spearman correlation of true TGgrp (1 vs 2/3 vs 4/5) vs. 1-P(TG1)
x <- ordinal_probs$TGgrp.merge
y <- ordinal_probs$mcia
cv.folds <- obj$nest_cv_foldid
mcia.cors <- get_cv_res("mcia", x, y, fold.ids = cv.folds)

y <- ordinal_probs$clin
clin.cors <- get_cv_res("clin", x, y, fold.ids = cv.folds)

y <- ordinal_probs$ensemble_mcia_clin
emc.cors <- get_cv_res("ensemble_mcia_clin", x, y, fold.ids = cv.folds)

ordinal.cors <- list(
  mcia = mcia.cors,
  clin = clin.cors,
  ensemble_mcia_clin = emc.cors
)
datasets <- c("Plasma: Targeted Proteomics",
              "Plasma: Global Proteomics (DDA)",
              "Serum: OLINK",
              "Plasma: Global Metabolomics",
              "Nasal: Transcriptomics",
              "PBMC: Transcriptomics",
              "All Omics Concat.",
              "MCIA Modules 1-7")
datasets <- c("PPT", "PPG", "SPT", "PMG", "NGX", "PGX", "All Omics Concat.", "MCIA Modules 1-7")
for(d in 1:6){
  y <- ordinal_probs[[paste0("dataset", d)]]
  dataset.cors <- get_cv_res(datasets[d], x, y, fold.ids = cv.folds)
  ordinal.cors[[paste0("dataset", d)]] <- dataset.cors
}

# 123 vs 45
x <- TG123_45probs$TGgrp
y <- TG123_45probs$mcia
mcia.cors <- get_cv_res("mcia", x, y, cv.folds, type = "auc")

y <- TG123_45probs$clin
clin.cors <- get_cv_res("clin", x, y, cv.folds, type = "auc")

y <- TG123_45probs$ensemble_mcia_clin
emc.cors <- get_cv_res("ensemble_mcia_clin", x, y, cv.folds, type = "auc")

onetwothree_fourfive.cors <- list(
  mcia = mcia.cors,
  clin = clin.cors,
  ensemble_mcia_clin = emc.cors
)
for(d in 1:6){
  y <- TG123_45probs[[paste0("dataset", d)]]
  dataset.cors <- get_cv_res(datasets[d], x, y, fold.ids = cv.folds, type = "auc")
  onetwothree_fourfive.cors[[paste0("dataset", d)]] <- dataset.cors
}

# TG4 vs 5:
# Subset to only use TG4/5:
TG45_probs <- dplyr::filter(TG45_probs, TGgrp >= 4)
cv.folds.45 <- cv.folds[which(obj$TG45_probs$TGgrp >= 4)]

x <- TG45_probs$TGgrp
y <- TG45_probs$mcia
mcia.cors <- get_cv_res("mcia", x, y, cv.folds.45, type = "auc")

y <- TG45_probs$clin
clin.cors <- get_cv_res("clin", x, y, cv.folds.45, type = "auc")

y <- TG45_probs$ensemble_mcia_clin
emc.cors <- get_cv_res("ensemble_mcia_clin", x, y, cv.folds.45, type = "auc")

four.vs.five.cors <- list(
  mcia = mcia.cors,
  clin = clin.cors,
  ensemble_mcia_clin = emc.cors
)
for(d in 1:6){
  y <- TG45_probs[[paste0("dataset", d)]]
  dataset.cors <- get_cv_res(datasets[d], x, y, fold.ids = cv.folds.45, type = "auc")
  four.vs.five.cors[[paste0("dataset", d)]] <- dataset.cors
}

# plot:
cor.list <- ordinal.cors
df <- do.call("rbind", cor.list)
df$task <- "TG(1/23/45) vs. P(TG45)\nSpearman Correlation"
ord.df <- df
cor.list <- onetwothree_fourfive.cors
df <- do.call("rbind", cor.list)
df$task <- "TG(123/45) vs. P(TG45)\nAUROC"
bin.df <- df
cor.list <- four.vs.five.cors
df <- do.call("rbind", cor.list)
df$task <- "TG(4/5) vs. P(TG5)\nAUROC"
sev.df <- df

total.df <- rbind(ord.df, bin.df, sev.df)


rel.models <- c("All Assays (MCIA)", datasets)

total.df$xpos <- unname(unlist(sapply(total.df$model, function(m){
  if(m == "mcia") return(1);
  if(m == datasets[1]) return(2.2);
  if(m == datasets[2]) return(3.2);
  if(m == datasets[3]) return(4.2);
  if(m == datasets[4]) return(5.2);
  if(m == datasets[5]) return(6.2);
  if(m == datasets[6]) return(7.2);
  return(0)
})))
total.df$model[which(total.df$model == "mcia")] <- "All Assays (MCIA)"
mcia.mo.col <- "#BA3F1D"
names(mcia.mo.col) <- "All Assays (MCIA)"
total.df$model <- factor(total.df$model, levels = unique(total.df$model))
total.df <- dplyr::filter(total.df, task != "TG(123/45) vs. P(TG45)\nAUROC")
#Facets:
total.df$task[which(total.df$task == "TG(1/23/45) vs. P(TG45)\nSpearman Correlation")] <- "Severity Task\n(TG1vsTG2/3vsTG4/5)"
total.df$task[which(total.df$task == "TG(4/5) vs. P(TG5)\nAUROC")] <- "Mortality Task\n(TG4vsTG5)"

# Save
#saveRDS(total.df, "FigS1_files/FigS1H_results.rds")
```

```{r panel S1H plotting}
total.df <- fig.s1h.results
all_colors <- c(model_cols, dataset_cols)

sup.fig.s1h <- ggplot() +
  geom_bar(data = dplyr::filter(total.df, model %in% rel.models), aes(x = xpos, y = value, fill = model), color = "black", size = .3, stat = "identity") +
  geom_errorbar(data = dplyr::filter(total.df, model %in% rel.models), aes(x = xpos, ymin = value - sd, ymax = value + sd), width = .5) +
  geom_hline(data = dplyr::filter(total.df, model == "All Assays (MCIA)"), aes(yintercept = value), size = .5, linetype = "dashed", color = "grey20") +
  facet_wrap(vars(factor(task, levels = c("Severity Task\n(TG1vsTG2/3vsTG4/5)", "Mortality Task\n(TG4vsTG5)")))) +
  theme_bw() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), plot.title = element_text(hjust = .5)) +
  scale_fill_manual(
    values = c(mcia.mo.col, dataset_cols_abbrev)) +
  ylab(NULL) +
  xlab(NULL) +
  labs(fill = "Model") +
  ggtitle("Multi-omics vs. Single-omics using MCIA")

# save plot:
ggsave(filename = "../output/FigS1H.pdf", plot = sup.fig.s1h, width = 4, height = 3)
```


```{r panel S1I preparation, eval = FALSE}
# Set seed
set.seed(123)

obj <- fig.s1e.mcia.multiomics
supp.obj <- fig.s1i.concat.literature
ordinal_probs <- obj$ordinal_probs
TG45_probs <- obj$TG45_probs

# add data:
ordinal_probs$Gisby <- 1 - supp.obj[[1]]$nested_cv_probs[,1]
ordinal_probs$Ling <- 1 - supp.obj[[2]]$nested_cv_probs[,1]
ordinal_probs$Patterson <- 1 - supp.obj[[3]]$nested_cv_probs[,1]


TG45_probs$Gisby <- supp.obj[[1]]$nested_cv_probs[,3] / (supp.obj[[1]]$nested_cv_probs[,3] + supp.obj[[1]]$nested_cv_probs[,4])
TG45_probs$Ling <- supp.obj[[2]]$nested_cv_probs[,3] / (supp.obj[[2]]$nested_cv_probs[,3] + supp.obj[[2]]$nested_cv_probs[,4])
TG45_probs$Patterson <- supp.obj[[3]]$nested_cv_probs[,3] / (supp.obj[[3]]$nested_cv_probs[,3] + supp.obj[[3]]$nested_cv_probs[,4])

TG123_45probs <- ordinal_probs
TG123_45probs$TGgrp.merge[TG123_45probs$TGgrp.merge == 1] <- 2
TG123_45probs$TGgrp.merge <- TG123_45probs$TGgrp.merge - 1

# First plot: spearman correlation of true TGgrp (1 vs 2/3 vs 4/5) vs. 1-P(TG1)
x <- ordinal_probs$TGgrp.merge
y <- ordinal_probs$mcia
cv.folds <- obj$nest_cv_foldid
mcia.cors <- get_cv_res("mcia", x, y, fold.ids = cv.folds)

y <- ordinal_probs$clin
clin.cors <- get_cv_res("clin", x, y, fold.ids = cv.folds)

y <- ordinal_probs$ensemble_mcia_clin
emc.cors <- get_cv_res("ensemble_mcia_clin", x, y, fold.ids = cv.folds)

ordinal.cors <- list(
  mcia = mcia.cors,
  clin = clin.cors,
  ensemble_mcia_clin = emc.cors
)
datasets <- c("Gisby", "Ling", "Patterson")
for(d in datasets){
  y <- ordinal_probs[[d]]
  dataset.cors <- get_cv_res(d, x, y, fold.ids = cv.folds)
  ordinal.cors[[d]] <- dataset.cors
}

# 123 vs 45
x <- TG123_45probs$TGgrp
y <- TG123_45probs$mcia
mcia.cors <- get_cv_res("mcia", x, y, cv.folds, type = "auc")

y <- TG123_45probs$clin
clin.cors <- get_cv_res("clin", x, y, cv.folds, type = "auc")

y <- TG123_45probs$ensemble_mcia_clin
emc.cors <- get_cv_res("ensemble_mcia_clin", x, y, cv.folds, type = "auc")

onetwothree_fourfive.cors <- list(
  mcia = mcia.cors,
  clin = clin.cors,
  ensemble_mcia_clin = emc.cors
)
for(d in datasets){
  y <- TG123_45probs[[d]]
  dataset.cors <- get_cv_res(d, x, y, fold.ids = cv.folds, type = "auc")
  onetwothree_fourfive.cors[[d]] <- dataset.cors
}

# TG4 vs 5:
# Subset to only use TG4/5:
TG45_probs <- dplyr::filter(TG45_probs, TGgrp >= 4)
cv.folds.45 <- cv.folds[which(obj$TG45_probs$TGgrp >= 4)]

x <- TG45_probs$TGgrp
y <- TG45_probs$mcia
mcia.cors <- get_cv_res("mcia", x, y, cv.folds.45, type = "auc")

y <- TG45_probs$clin
clin.cors <- get_cv_res("clin", x, y, cv.folds.45, type = "auc")

y <- TG45_probs$ensemble_mcia_clin
emc.cors <- get_cv_res("ensemble_mcia_clin", x, y, cv.folds.45, type = "auc")

four.vs.five.cors <- list(
  mcia = mcia.cors,
  clin = clin.cors,
  ensemble_mcia_clin = emc.cors
)
for(d in datasets){
  y <- TG45_probs[[d]]
  dataset.cors <- get_cv_res(d, x, y, fold.ids = cv.folds.45, type = "auc")
  four.vs.five.cors[[d]] <- dataset.cors
}

# plot:
cor.list <- ordinal.cors
df <- do.call("rbind", cor.list)
df$task <- "TG(1/23/45) vs. P(TG45)\nSpearman Correlation"
ord.df <- df
cor.list <- onetwothree_fourfive.cors
df <- do.call("rbind", cor.list)
df$task <- "TG(123/45) vs. P(TG45)\nAUROC"
bin.df <- df
cor.list <- four.vs.five.cors
df <- do.call("rbind", cor.list)
df$task <- "TG(4/5) vs. P(TG5)\nAUROC"
sev.df <- df

total.df <- rbind(ord.df, bin.df, sev.df)

total.df$xpos <- unname(unlist(sapply(total.df$model, function(m){
  if(m == "mcia") return(1);
  if(m == datasets[1]) return(2.2);
  if(m == datasets[2]) return(3.2);
  if(m == datasets[3]) return(4.2);
  return(0)
})))
total.df$model[which(total.df$model == "mcia")] <- "All Assays (MCIA)"
total.df$model <- factor(total.df$model, levels = unique(total.df$model))
total.df <- dplyr::filter(total.df, task != "TG(123/45) vs. P(TG45)\nAUROC")
#Facets:
total.df$task[which(total.df$task == "TG(1/23/45) vs. P(TG45)\nSpearman Correlation")] <- "Severity Task\n(TG1vsTG2/3vsTG4/5)"
total.df$task[which(total.df$task == "TG(4/5) vs. P(TG5)\nAUROC")] <- "Mortality Task\n(TG4vsTG5)"

# Save:
#saveRDS(total.df, "FigS1_files/FigS1I_results.rds")
```

```{r panel S1I plotting}
total.df <- fig.s1i.results

lit_cols <- c(
  Gisby = "#7966B3",
  Ling = "#2A5475",
  Patterson = "#604E0A",
  mcia = "#BA3F1D"
)
names(lit_cols)[4] <- "All Assays (MCIA)"

all_colors <- c(model_cols, lit_cols)
rel.models <- c("All Assays (MCIA)", datasets)

sup.fig.s1i <- ggplot() +
  geom_bar(data = dplyr::filter(total.df, model %in% rel.models), aes(x = xpos, y = value, fill = model), color = "black", size = .3, stat = "identity") +
  geom_errorbar(data = dplyr::filter(total.df, model %in% rel.models), aes(x = xpos, ymin = value - sd, ymax = value + sd), width = .5) +
  geom_hline(data = dplyr::filter(total.df, model == "All Assays (MCIA)"), aes(yintercept = value), size = .5, linetype = "dashed", color = "grey20") +
  facet_wrap(vars(factor(task, levels = c("Severity Task\n(TG1vsTG2/3vsTG4/5)", "Mortality Task\n(TG4vsTG5)")))) +
  theme_bw() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), plot.title = element_text(hjust = .5)) +
  scale_fill_manual(
    values = all_colors[rel.models]) +
  ylab(NULL) +
  xlab(NULL) +
  labs(fill = "Model") +
  ggtitle("MCIA Factors vs. Literature")


# save plot:
ggsave(filename = "../output/FigS1I.pdf", plot = sup.fig.s1i, width = 4, height = 3)
```


```{r panel S1J preparation, eval = FALSE}
### MOFA Imputation Testing:

# Train:
clin.train <- base_obj1$clin.train
clin.df <- clin.train
data.df <- train.data
event_ids <- clin.df$event_id
res.list <- list()
for(i in 1:6){
  df <- data.df$datasets[[i]]
  res.list[[i]] <- apply(df, 1, function(row){return(!any(is.na(row)))})
}
res <- do.call("cbind", res.list)
visits_per_event_id.tr <- rowSums(res)

# Test:
clin.test <- base_obj1$clin.test
clin.df <- clin.test
data.df <- test.data
event_ids <- clin.df$event_id
res.list <- list()
for(i in 1:6){
  df <- data.df$datasets[[i]]
  res.list[[i]] <- apply(df, 1, function(row){return(!any(is.na(row)))})
}
res <- do.call("cbind", res.list)
visits_per_event_id.te <- rowSums(res)

# Calculate frequencies of missing data:
tmp.tr <- as.data.frame(table(visits_per_event_id.tr))
colnames(tmp.tr) <- c("visits_per_event_id", "Freq")
tmp.tr$train_test <- "Train"
tmp.tr$visits <- "All"
tmp.te <- as.data.frame(table(visits_per_event_id.te))
colnames(tmp.te) <- c("visits_per_event_id", "Freq")
tmp.te$train_test <- "Test"
tmp.te$visits <- "All"
# only for Visit 1:
tmp.tr.v1 <- as.data.frame(table(visits_per_event_id.tr[grepl("-1$", names(visits_per_event_id.tr))]))
colnames(tmp.tr.v1) <- c("visits_per_event_id", "Freq")
tmp.tr.v1$train_test <- "Train"
tmp.tr.v1$visits <- "Baseline"
tmp.te.v1 <- as.data.frame(table(visits_per_event_id.te[grepl("-1$", names(visits_per_event_id.te))]))
colnames(tmp.te.v1) <- c("visits_per_event_id", "Freq")
tmp.te.v1$train_test <- "Test"
tmp.te.v1$visits <- "Baseline"
tmp <- rbind(tmp.tr, tmp.te, tmp.tr.v1, tmp.te.v1)

# Save:
#saveRDS(tmp, "FigS1_files/FigS1J_results.rds")
```

```{r panel S1J plotting}
tmp <- fig.s1j.results

sup.fig.s1j <- ggplot(tmp) +
  geom_bar(aes(x = factor(visits_per_event_id), y = Freq, fill = visits_per_event_id), stat = "identity", color = "black") +
  scale_fill_brewer(palette = "Greys") +
  theme_bw() +
  ylab("Number of Samples") +
  xlab("Number of Complete Assays") +
  guides(fill = "none") +
  facet_grid(rows = vars(factor(train_test, levels = c("Train", "Test"))), cols = vars(factor(visits, levels = c("Baseline", "All"))))

# save plot:
ggsave(filename = "../output/FigS1J.pdf", plot = sup.fig.s1j, width = 4, height = 4)
```


```{r panel S1K preparation, eval = FALSE}
obj <- fig.s1e.mcia.multiomics
ordinal_probs <- obj$ordinal_probs
TG45_probs <- obj$TG45_probs
num.visits <- visits_per_event_id.tr[grepl("-1$", names(visits_per_event_id.tr))]

# add data:
TG123_45probs <- ordinal_probs
TG123_45probs$TGgrp.merge[TG123_45probs$TGgrp.merge == 1] <- 2
TG123_45probs$TGgrp.merge <- TG123_45probs$TGgrp.merge - 1

# First plot: spearman correlation of true TGgrp (1 vs 2/3 vs 4/5) vs. 1-P(TG1)
cv.res <- list()

for(i in 1:6){
  idx <- which(num.visits == i)
  x <- ordinal_probs$TGgrp.merge[idx]
  y <- ordinal_probs$mcia[idx]
  cv.folds <- obj$nest_cv_foldid[idx]
  cv.res[[i]] <- get_cv_res("mcia", x, y, fold.ids = cv.folds)
}

df <- do.call("rbind", cv.res)
df$NumberOfVisits <- 1:6
df$train_test <- "Train"
df.tr <- df

# make ordinal_probs:
ordinal_probs <- data.frame(
  mcia = 1 - base_obj1$test_prediction_list$mcia_prob[,1],
  clin = 1 - base_obj1$test_prediction_list$clin_prob[,1],
  ensemble_mcia_clin = 1 - base_obj1$test_prediction_list$ENSEMBL.mcia.clin[,1],
  TGgrp = dplyr::filter(base_obj1$clin.test, event_type == "Visit 1")$trajectory_group,
  TGgrp.merge = sapply(dplyr::filter(base_obj1$clin.test, event_type == "Visit 1")$trajectory_group, function(tg){if(tg%in%4:5){return(3)};if(tg%in%2:3){return(2)};return(1)}),
  baseline_resp = dplyr::filter(base_obj1$clin.test, event_type == "Visit 1")$resp_status_v1
)

TG45_probs <- data.frame(
  mcia = get_P4v5(base_obj1$test_prediction_list$mcia_prob),
  clin = get_P4v5(base_obj1$test_prediction_list$clin_prob),
  ensemble_mcia_clin = get_P4v5(base_obj1$test_prediction_list$ENSEMBL.mcia.clin),
  TGgrp = dplyr::filter(base_obj1$clin.test, event_type == "Visit 1")$trajectory_group,
  TGgrp.merge = sapply(dplyr::filter(base_obj1$clin.test, event_type == "Visit 1")$trajectory_group, function(tg){if(tg%in%4:5){return(3)};if(tg%in%2:3){return(2)};return(1)}),
  baseline_resp = dplyr::filter(base_obj1$clin.test, event_type == "Visit 1")$resp_status_v1
)

TG45_probs <- dplyr::filter(TG45_probs, TGgrp %in% 4:5)
TG45_probs$TGgrp.merge <- TG45_probs$TGgrp - 3

# First plot: spearman correlation of true TGgrp (1 vs 2/3 vs 4/5) vs. 1-P(TG1)
test.res <- list()

for(i in 1:6){
  idx <- which(num.visits == i)
  x <- ordinal_probs$TGgrp.merge[idx]
  y <- ordinal_probs$mcia[idx]
  test.res[[i]] <- get_boostrap_res("mcia", x, y)
}

df <- do.call("rbind", test.res)
df$NumberOfVisits <- 1:6
df$train_test <- "Test"
df.te <- df

colnames(df.tr) <- colnames(df.te) <- c("model", "value", "sd", "NumberOfVisits", "train_test")

df <- dplyr::filter(rbind(df.tr, df.te), NumberOfVisits >= 4)

# Save:
#saveRDS(df, "FigS1_files/FigS1K_results.rds")
```

```{r panel S1K plotting}
df <- fig.s1k.results

sup.fig.s1k <- ggplot(df) +
  geom_bar(aes(x = factor(NumberOfVisits), y = value, fill = factor(NumberOfVisits)), stat = "identity", color = "black") +
  geom_errorbar(aes(x = factor(NumberOfVisits), ymin = value - sd, ymax = value + sd), width = .5) +
  scale_fill_brewer(palette = "Greys") +
  theme_bw() +
  ylab("Spearman Correlation") +
  xlab("Number of Complete Assays") +
  guides(fill = "none") +
  facet_grid(rows = vars(factor(train_test, levels = c("Train", "Test"))))

# save plot:
ggsave(filename = "../output/FigS1K.pdf", plot = sup.fig.s1k, width = 2.5, height = 4)
```

